packages/firebase_auth/CHANGELOG.md, packages/firebase_auth/README.md, packages/firebase_auth/pubspec.yaml
Fix Register a user example code snippet in README.md
Fix README.md code snippet for user creation example
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTI …
=> [firebase_auth] Fix README.md snippet

.opensource/project.json
I just copied the one from flutter/plugins and changed the `content` key to point at README.md*
N/A
- [ x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [ x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x ] All existing and new tests are passing.
- [x ] I updated/added relevant documentation (doc comments with `///`).
- [ x] The analyzer (`flutter analyze`) does not …
=> Create firebaseopensource.com configuration

packages/cloud_firestore/pubspec.yaml
#87 was missing a pubspec.yaml change
Was not caught in CI due to https://github.com/flutter/flutter/issues/13897
=> [cloud_firestore] Update pubspec.yaml

packages/cloud_functions/CHANGELOG.md, packages/cloud_functions/android/src/main/java/io/flutter/plugins/firebase/cloudfunctions/CloudFunctionsPlugin.java, packages/cloud_functions/pubspec.yaml
The package name doesn't match the directory structure.
https://github.com/flutter/flutter/issues/42661
=> Cloud function package name

packages/firebase_core/CHANGELOG.md, packages/firebase_core/pubspec.yaml
Bump firebase_core version number.
=> [firebase_core] bump core version to 0.4.1+4

packages/firebase_core/firebase_core/CHANGELOG.md, packages/firebase_core/firebase_core/lib/firebase_core.dart, packages/firebase_core/firebase_core/lib/src/firebase_app.dart, packages/firebase_core/firebase_core/pubspec.yaml
We will crash on web if we call `Platform.isIos`. This prevents us from crashing on the web.
=> [firebase_core] Check `kIsWeb` in `firebase_core`

packages/firebase_auth/firebase_auth_web/CHANGELOG.md, packages/firebase_auth/firebase_auth_web/LICENSE, packages/firebase_auth/firebase_auth_web/README.md, packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart, packages/firebase_auth/firebase_auth_web/pubspec.yaml, packages/firebase_auth/firebase_auth_web/test/firebase_auth_web_test.dart
Adds `firebase_auth_web`, the web implementation of `package:firebase_auth`.
Fixes https://github.com/flutter/flutter/issues/45288
=> [firebase_auth_web] Add initial implementation

README.md
FlutterFire now has web support for some SDKs so I've updated the README.
=> Update README to mention web support

packages/firebase_crashlytics/CHANGELOG.md, packages/firebase_crashlytics/lib/src/firebase_crashlytics.dart, packages/firebase_crashlytics/pubspec.yaml
The english was a bit confusing. …
=> [firebase_crashlytics] Updated the documentation language.

packages/firebase_auth/firebase_auth/test/firebase_auth_test.dart, packages/firebase_auth/firebase_auth_web/CHANGELOG.md, packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart, packages/firebase_auth/firebase_auth_web/pubspec.yaml, packages/firebase_auth/firebase_auth_web/test/firebase_auth_web_test.dart
While trying firebase_auth_web with signInAnonymously I've found an un-serialization error.
creationTime and lastSignInTime are RFC1123 formatted and `dart:core`'s DateTime.parse is unable to parse it.
I used HttpDate.parse which is able to parse RFC1123 in a correct DateTime.  
None. Maybe I should open it for future reference? …
=> [firebase_auth_web] creationTime and lastSignInTime are not parsable by DateTime.parse

script/incremental_build.sh
This should have been landed as part of the previous flutter_tools PR.
=> [none] Whitelist custom analysis_options

analysis_options.yaml, pubspec.yaml
This will prevent CI from unexpectedly breaking when the pedantic
package is updated to check for new lints.
Mirror of flutter/plugins#2354
=> [none] Lock pedantic package version

packages/firebase_messaging/CHANGELOG.md, packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m, packages/firebase_messaging/pubspec.yaml
Without this the plugin does not compile internally. I am not sure how it is building upstream.
=> Add UserNotifications header

packages/firebase_crashlytics/example/lib/main.dart
Fix [CI issue](https://cirrus-ci.com/task/6047934658904064) when analyzing the Crashlytics example app.
=> [CI] fix analyze error on crashlytics example

packages/firebase_core/firebase_core/CHANGELOG.md, packages/firebase_core/firebase_core/example/web/index.html, packages/firebase_core/firebase_core/pubspec.yaml
Endorses `firebase_core_web` as the default web implementation of `firebase_core`.
=> [firebase_core] Endorse web implementation

packages/firebase_auth/firebase_auth/CHANGELOG.md, packages/firebase_auth/firebase_auth/example/README.md, packages/firebase_auth/firebase_auth/example/web/index.html, packages/firebase_auth/firebase_auth/pubspec.yaml
Endorses `firebase_auth_web` as the default web implementation of `firebase_auth`.
=> [firebase_auth] Endorse web implementation

packages/firebase_messaging/CHANGELOG.md, packages/firebase_messaging/README.md, packages/firebase_messaging/pubspec.yaml
This addresses https://github.com/FirebaseExtended/flutterfire/pull/1564#issuecomment-566156718.  
Additionally, it fixes the code blocks in that section by specifying languages and fixing the indentation.
* https://github.com/FirebaseExtended/flutterfire/issues/1651
=> [firebase_messaging] Update README

packages/firebase_crashlytics/CHANGELOG.md, packages/firebase_crashlytics/example/lib/main.dart, packages/firebase_crashlytics/example/test_driver/crashlytics.dart, packages/firebase_crashlytics/pubspec.yaml
Updates the example with the missing "recordError". (#1663)
#1663
=> [firebase_crashlytics] Updates the example with the missing "recordError". (#1663)

packages/firebase_auth/firebase_auth/CHANGELOG.md, packages/firebase_auth/firebase_auth/README.md, packages/firebase_auth/firebase_auth/pubspec.yaml, packages/firebase_auth/firebase_auth_web/CHANGELOG.md, packages/firebase_auth/firebase_auth_web/README.md, packages/firebase_auth/firebase_auth_web/pubspec.yaml, packages/firebase_core/firebase_core/CHANGELOG.md, packages/firebase_core/firebase_core/README.md, packages/firebase_core/firebase_core/example/web/index.html, packages/firebase_core/firebase_core/pubspec.yaml, packages/firebase_core/firebase_core_web/CHANGELOG.md, packages/firebase_core/firebase_core_web/README.md, packages/firebase_core/firebase_core_web/pubspec.yaml
The old documentation referred the time when people had to manually depend on _web implementation of plugins.
This PR changes that, and documents the current state of the art on how to integrate firebase plugins with the web.
* https://github.com/FirebaseExtended/flutterfire/issues/1635
* https://github.com/FirebaseExtended/flutterfire/issues/1746
* Maybe others... …
=> [firebase_core, firebase_auth] Update web integration docs

.github/move.yml
Configure the [GitHub move app](https://github.com/apps/move) so issues can be moved from the Flutter repo (or elsewhere) to this repo.
Preferences (except aliases) copied from [flutter/flutter](https://github.com/flutter/flutter/blob/master/.github/move.yml).
=> Configure GitHub move app

packages/cloud_firestore/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/cloud_firestore/ios/Classes/FLTCloudFirestorePlugin.m, packages/cloud_firestore/cloud_firestore/pubspec.yaml
Previously, it was always `true` even though set to `false`.
- Several related issues like this: #90
---
> - [ ] My PR includes unit or integration tests for *all* …
=> [cloud_firestore] Fix broken __NSCFBoolean conversion always resulting in TRUE (iOS only)

.gitignore
Similar to https://github.com/flutter/plugins/pull/2476. Examples need the .xcworkspace in order to run.
=> [all] Remove ignore for workspaces

packages/firebase_ml_vision/CHANGELOG.md, packages/firebase_ml_vision/example/lib/material_barcode_scanner.dart, packages/firebase_ml_vision/pubspec.yaml
Fixes lint error causing tests to be red.
=> [firebase_ml_vision] Replace deprecated text theme fields in example app

packages/cloud_functions/cloud_functions/CHANGELOG.md, packages/cloud_functions/cloud_functions/darwin/Classes/CloudFunctionsPlugin.m, packages/cloud_functions/cloud_functions/pubspec.yaml
Unfortunately the integration test [did not catch this](https://cirrus-ci.com/task/5539174048595968).
=> [cloud_functions] Use correct method channel

packages/firebase_auth/firebase_auth/CHANGELOG.md, packages/firebase_auth/firebase_auth/pubspec.yaml, packages/firebase_auth/firebase_auth/test/firebase_auth_test.dart
Updates the platform interface in `firebase_auth`
* Partially addresses #2064
* Fixes #1939
=> [firebase_auth] Update platform interface version to 1.1.7

packages/cloud_firestore/cloud_firestore_platform_interface/test/method_channel_cloud_firestore_test.dart, packages/cloud_firestore/cloud_firestore_web/CHANGELOG.md, packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart, packages/cloud_firestore/cloud_firestore_web/pubspec.yaml, packages/cloud_firestore/cloud_firestore_web/test/query_web_test.dart
This change ensures that the package:firestore Query objects are created with properly encoded values when done so from the start/end (pagination) methods.
This also adds some Timestamps to the unit tests to verify the behavior of Timestamp -> DateTime.
_(There are some integration tests in cloud_firestore that cover this behavior further.)_
Fixes https://github.com/FirebaseExtended/flutterfire/issues/2153 …
=> [cloud_firestore_web] Ensure Query pagination methods encode values.

packages/firebase_admob/CHANGELOG.md, packages/firebase_admob/ios/Classes/FLTMobileAd.m, packages/firebase_admob/ios/Classes/FLTRequestFactory.m, packages/firebase_admob/ios/Classes/FLTRewardedVideoAdWrapper.h, packages/firebase_admob/ios/Classes/FLTRewardedVideoAdWrapper.m, packages/firebase_admob/pubspec.yaml, packages/firebase_admob/test/firebase_admob_e2e.dart
=> [firebase_admob] Use instance variables when loading ads

packages/firebase_database/example/lib/main.dart
Matching some functionality from the Firestore sample
* Added trash icon to each line item
* Trash icon removes the related item from RTDB
Change was added so we don't need to manually clear the project database as often, as having thousands of items causes the Flutter sample app to slow when pulling all of them.
This change does not affect the plugin, and only adds functionality to the sample. All original functionality still exists.
```
I/Choreographer(27246): Skipped 64 frames!  The application may be doing too much work on its main thread.
I/flutter (27246): Child added: {Hello: world! 2554}
```
No related issue logged.
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review …
=> [RTDB] [Sample App] Added a delete option to items in the RTDB sample

packages/firebase_messaging/pubspec.yaml
Missing release commit from #1774 🙈 
N/A
=> chore(firebase_messaging): v6.0.15

packages/firebase_analytics/firebase_analytics/CHANGELOG.md, packages/firebase_analytics/firebase_analytics/lib/firebase_analytics.dart, packages/firebase_analytics/firebase_analytics/pubspec.yaml
Use the platform interface introduced in https://github.com/FirebaseExtended/flutterfire/pull/1529.
https://github.com/flutter/flutter/issues/45289
=> [firebase_analytics] Wire the platform interface.

packages/firebase_auth/firebase_auth/README.md
When I started with FirebaseAuth I was puzzled how I access possible error code because exceptions get easily swallowed in an async function.
I added a paragraph to the readme and to the code comments to make it easier for people just starting with Firebase and Flutter
- [ x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [ x] I updated/added relevant documentation (doc comments with `///`).
- [ x] The title of the PR starts with the …
=> [FirebasAuth] added that Errors are thrown via a PlatformException

packages/firebase_messaging/CHANGELOG.md, packages/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
[flutter-messaging] Fix for push notifications disappearing after app launch for iOS.
https://github.com/FirebaseExtended/flutterfire/issues/114
=> [flutter-messaging] fix notifications disappearing after app launch

packages/firebase_messaging/README.md
Anyone who just need firebase messaging then following the guide only and haven't experience with it, they will found an error which is at function myBackgroundMessageHandler, and they don't know what is the problem, i had got this problem twice at different project, so i don't want anyone who just follow the basic guide got an exact same error because of forgotten async word.
No related issue …
=> docs(messaging): update readme

CONTRIBUTING.md
I edited CONTRIBUTING.md because of the example dir path was wrong.
- `packages/cloud_firestore/example` is not exists. 
- changed to `packages/cloud_firestore/cloud_firestore/example`
no exists.
[CLA]: …
=> docs(cloud_firestore): fix example dir path in CONTRIBUTING.md

docs/overview.mdx, website/docusaurus.config.js, website/src/pages/index.tsx, website/src/theme/MDXComponents/index.tsx
Adds logo to header & overview docs
=> docs: add logo to overview

packages/cloud_firestore/cloud_firestore/analysis_options.yaml, packages/cloud_firestore/cloud_firestore/example/lib/main.dart, packages/cloud_firestore/cloud_firestore/example/run-tests-web, packages/cloud_firestore/cloud_firestore/example/test_driver/document_change_e2e.dart, packages/cloud_firestore/cloud_firestore/example/test_driver/document_reference_e2e.dart, packages/cloud_firestore/cloud_firestore/example/test_driver/instance_e2e.dart, packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart, packages/cloud_firestore/cloud_firestore/lib/src/collection_reference.dart, packages/cloud_firestore/cloud_firestore/lib/src/document_change.dart, packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart, packages/cloud_firestore/cloud_firestore/lib/src/document_snapshot.dart, packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart, packages/cloud_firestore/cloud_firestore/lib/src/query.dart, packages/cloud_firestore/cloud_firestore/lib/src/query_snapshot.dart, packages/cloud_firestore/cloud_firestore/lib/src/write_batch.dart
Removes an outstanding `analysis_options` file and fixes any highlighted warnings.
=> chore(cloud_firestore): remove analysis_options and fix warnings

docs/auth/overview.mdx, docs/sidebars.js, packages/firebase_auth/firebase_auth/CHANGELOG.md, packages/firebase_auth/firebase_auth/android/build.gradle, packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java, packages/firebase_auth/firebase_auth/darwin/Classes/FLTFirebaseAuthPlugin.m, packages/firebase_auth/firebase_auth/example/android/build.gradle, packages/firebase_auth/firebase_auth/example/lib/main.dart, packages/firebase_auth/firebase_auth/example/test_driver/firebase_auth_e2e.dart, packages/firebase_auth/firebase_auth/ios/firebase_auth.podspec, packages/firebase_auth/firebase_auth/macos/firebase_auth.podspec, packages/firebase_auth/firebase_auth/pubspec.yaml, packages/firebase_auth/firebase_auth_web/CHANGELOG.md, packages/firebase_auth/firebase_auth_web/pubspec.yaml
Migration of current (this is not the reworked version of auth) `firebase_auth` package to depend on new `firebase_core` as per #2582.
* Depend on `firebase_core` pre-release versions and migrate plugin to use `firebase_core` native SDK versioning features;
* Firebase iOS SDK versions are now locked to use the same version defined in `firebase_core`.
* Firebase Android SDK versions are now using the Firebase Bill of Materials (BoM) to specify individual SDK versions. BoM version is also sourced from `firebase_core`.
* Allow iOS & MacOS plugins to be imported as modules.
N/A …
=> chore(firebase_auth): migrate to depend on new `firebase_core` plugin

packages/firebase_auth/firebase_auth/darwin/Classes/FLTFirebaseAuthPlugin.m
On iOS, a FIRAuthErrorCodeTooManyRequests exception is currently reported as a generic verifyPhoneNumberError error, but on Android this is reported as 'quotaExceeded'.
To allow consistent handling of this error on both platforms, the iOS plugin now maps both FIRAuthErrorCodeQuotaExceeded and FIRAuthErrorCodeTooManyRequests to the ‘quotaExceeded’ error code to match the behaviour of the Android plugin.
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes …
=> [firebase-auth] handles FIRAuthErrorCodeTooManyRequests on iOS

.github/workflows/firebase_auth.yaml, .github/workflows/firebase_core.yaml, .github/workflows/firebase_database.yaml, .github/workflows/firebase_firestore.yaml, .github/workflows/firebase_performance.yaml, .github/workflows/firebase_storage.yaml, .github/workflows/scripts/drive-example.sh, README.md, website/plugins.js
Updates all workflows to use new CI scripts (which should also improve stability of testing).
N/A
- [] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [] I updated/added relevant documentation (doc comments with `///`). …
=> tests: update CI workflows to use new scripts

docs/core/usage.mdx, docs/firestore/usage.mdx
Fixes a couple of incorrect examples (API changed). …
=> docs(cloud_firestore): update usage examples

packages/firebase_ml_custom/example/README.md, packages/firebase_ml_custom/example/lib/main.dart, packages/firebase_ml_custom/example/test_driver/firebase_model_manager.dart
Added better instructions for example app users on how to upload their custom model to the Firebase console.
=> [firebase_ml_custom] Added information about the model in the example app

packages/firebase_ml_custom/example/README.md, packages/firebase_ml_custom/example/android/app/google-services.json, packages/firebase_ml_custom/example/ios/Runner.xcodeproj/project.pbxproj, packages/firebase_ml_custom/example/ios/Runner/GoogleService-Info.plist, packages/firebase_ml_custom/example/lib/main.dart, packages/firebase_ml_custom/ios/firebase_ml_custom.podspec
These changes are aimed to reduce the time taken by developer to familiarize themselves with plugin and specifically the example app.
Summary of changes:
- Comments and try-catch throughout example app main file
- Wifi connection is now required on both platforms for consistency
- Reminder to check internet connection on the loading screen
- A list of common issues and solutions in the example app README
- Example app package name and bundle id are specified in the app's README and adjusted in google services files
=> [firebase_ml_custom] Final adjustments before the initial release

docs/migration-guide.mdx, docs/sidebars.js
Adds a migration guide page along with the sidebar.
=> docs: add migration guide

README.md, packages/firebase_ml_custom/CHANGELOG.md, packages/firebase_ml_custom/pubspec.yaml
- Added new firebase_ml_custom plugin to the main README file
- Removed untrue information about firebase_ml_vision plugin from the main README file
- Increased firebase_ml_custom description
- Provided a better description of firebase_ml_custom initial release …
=> [firebase_ml_custom] Improved descriptions of the plugin and the initial commit

packages/firebase_auth/firebase_auth/CHANGELOG.md, packages/firebase_auth/firebase_auth/pubspec.yaml
Bump `firebase_auth_web` dependency in `firebase_auth` plugin.
=> Bump firebase_auth_web dependency version

packages/firebase_auth/firebase_auth_platform_interface/lib/src/id_token_result.dart, packages/firebase_auth/firebase_auth_platform_interface/test/id_token_result_test.dart, packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_tests/method_channel_user_test.dart
MFA is currently not supported. Removing a field as it'd never return a value.
=> refactor: remove signInSecondFactor

docs/auth/error-handling.mdx, docs/auth/overview.mdx, docs/auth/phone.mdx, docs/auth/social.mdx, docs/auth/usage.mdx, docs/firestore/usage.mdx, docs/installation/android.mdx, docs/installation/ios.mdx, docs/migration-guide.mdx
Fixes typos, removed images links, added additional steps to migration guide. …
=> docs: update docs

packages/cloud_firestore/cloud_firestore/README.md
This pr fixes minor grammar issues with the cloud_firestore package README …
=> docs: fixed typos

docs/migration-guide.mdx
Changed from "how" to "now".
None.
=> docs: fixed a typo in migration-guide.mdx

packages/firebase_dynamic_links/ios/firebase_dynamic_links.podspec
Fix build breakage by adding required variables to firebase_dynamic_links podspec file.
=> fix(dynamic_links): podspec

docs/migration-guide.mdx
=> docs: update android migration steps

docs/auth/usage.mdx
Changed from "provide" to "provider".
None.
=> docs(auth): fixed typo

packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java, packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java, packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreTransactionHandler.java, packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java, packages/firebase_auth/firebase_auth/example/test_driver/user_e2e.dart
=> fix(android): suppress warnings

docs/auth/error-handling.mdx, docs/auth/phone.mdx, docs/auth/social.mdx, docs/auth/usage.mdx, docs/core/usage.mdx, docs/firestore/usage.mdx, docs/migration-guide.mdx, packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/google_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/test/providers_tests/google_auth_test.dart
Doc fixes & google auth provider assert …
=> fix: documentation changes and google auth provider assert

packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java, packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPluginException.java
=> fix(auth,android): unknown error codes

website/src/pages/index.tsx
https://github.com/FirebaseExtended/flutterfire/tree/next/packages seems old, so I think https://github.com/FirebaseExtended/flutterfire/tree/master/packages is appropriate
=> Update GitHub link of https://firebase.flutter.dev

packages/firebase_in_app_messaging/ios/firebase_in_app_messaging.podspec
=> fix(fiam): podspec missing variable

docs/auth/usage.mdx, docs/firestore/usage.mdx
=> docs: updated file path

packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart, packages/cloud_firestore/cloud_firestore/lib/src/document_snapshot.dart, packages/cloud_firestore/cloud_firestore/lib/src/query.dart
This fixes 2 issues:
1. Values passed to the `where` filter were not being encoded, therefore a `DocumentReference` was reaching the codec when in fact it should have been a `DocumentReferencePlatform`.
2. When adding a test to verify (1), I discovered `DocumentSnapshot.get` values were not being decoded.
Fixes #3237 …
=> fix(cloud_firestore): encode "where" query values

docs/auth/social.mdx
Update to social auth docs including Twitter and GitHub
=> docs: social auth docs fixes

packages/firebase_auth/firebase_auth/lib/src/user.dart
=> fix(auth): add missing auth deprecations

packages/cloud_firestore/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/cloud_firestore/pubspec.yaml, packages/cloud_firestore/cloud_firestore_platform_interface/CHANGELOG.md, packages/cloud_firestore/cloud_firestore_platform_interface/pubspec.yaml, packages/cloud_firestore/cloud_firestore_web/CHANGELOG.md, packages/cloud_firestore/cloud_firestore_web/pubspec.yaml, packages/firebase_auth/firebase_auth/CHANGELOG.md, packages/firebase_auth/firebase_auth/pubspec.yaml, packages/firebase_auth/firebase_auth_platform_interface/CHANGELOG.md, packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml, packages/firebase_auth/firebase_auth_web/CHANGELOG.md, packages/firebase_auth/firebase_auth_web/pubspec.yaml, packages/firebase_dynamic_links/CHANGELOG.md, packages/firebase_dynamic_links/pubspec.yaml, packages/firebase_in_app_messaging/CHANGELOG.md, packages/firebase_in_app_messaging/pubspec.yaml
=> chore: release 20-08-2020

README.md
To quickly visualize the _pub points_ of each package, adding badges next to the current ones.
This will help identifying what packages need attention to improve _pub points_ and generally give confidence to users of the package quality.
Adding only 2 to get feedback (hence the Draft PR). If the decision is to go on with adding these badges, I'd complete the list.
Note that it's possible to get badges for _likes_ and _popularity_ too, for example:
The _sentry_ package:
[![likes](https://badges.bar/sentry/likes)](https://pub.dev/packages/sentry/score)
[![popularity](https://badges.bar/sentry/popularity)](https://pub.dev/packages/sentry/score)
[![pub points](https://badges.bar/sentry/pub%20points)](https://pub.dev/packages/sentry/score) 
/cc @Salakar @helenaford 
Before you create this PR …
=> docs: add badges for Pub Points from pub.dev 

docs/firestore/usage.mdx
Added the missing `catch` for error handling
None.
- [] I updated CHANGELOG.md to add a description of the change.
=> docs: added the missing catch for error handling

docs/auth/error-handling.mdx
Mention non-specific method exception codes in the documentation.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/3273
=> docs: mention non-specific method exception codes

packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
Fixes web users not propagating to streams.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/3291
=> fix(firebase_auth): send userPlatform on changes

docs/overview.mdx
The docs for initialization of a `FutureBuilder` currently suggest to create a new Future during each build, which is incorrect and causes rebuilding of the Widget tree. These docs changes ensure only a single Future is used and not rebuilt each time.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/3292 …
=> docs: update initialization docs

docs/overview.mdx
Improved instructions for installation on iOS
=> docs: add note about Firestore iOS build times

docs/installation/android.mdx, docs/installation/ios.mdx, docs/installation/macos.mdx, docs/installation/web.mdx
=> docs: update Firebase configuration naming

docs/firestore/usage.mdx
#before
Map<String, dynamic> data = snapshot.data();
#after
Map<String, dynamic> data = snapshot.data.data(); …
=> [docs] snapshot calls data

docs/overview.mdx
ERROR: This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: MyApp._initialization
Sample code shows error as _initialisation isn't marker as final.
=> docs: update overview example

packages/firebase_auth/firebase_auth/lib/src/user.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_user.dart, packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web_user.dart
Supports https://firebase.google.com/docs/reference/js/firebase.User#linkwithphonenumber on web.
NA
=> feat(firebase_auth): add support for linkWithPhoneNumber

.github/workflows/firebase_analytics.yaml, .github/workflows/firebase_core.yaml, .github/workflows/firebase_crashlytics.yaml, .github/workflows/firebase_database.yaml, .github/workflows/firebase_firestore.yaml, .github/workflows/firebase_storage.yaml, packages/cloud_firestore/cloud_firestore/example/test_driver/cloud_firestore_e2e.dart
- Re-enable Firestore Emulator for Web tests (found to function correctly on macOS runners).
- Use the `default` android emulator image instead of `googleapis` image for certain plugins that don't require Google Play Services, based on: https://firebase.google.com/docs/android/android-play-services
Does your PR require plugin users to manually …
=> tests(*): ci tweaks

docs/firestore/usage.mdx
Added a reference to FieldValue.increment() as the original docs do.
=> docs(cloud_firestore): added a reference to FieldValue.increment()

docs/overview.mdx
In the Android Firebase SDK version override, `project.ext` has been changed to `rootProject.ext`. `project.ext` does not produce the override described in the docs.
Note: a different solution would be to add the `project.ext` block to `android/build.gradle` instead of `android/app/build.gradle`.
Fixes FirebaseExtended/flutterfire#3554
Fixes FirebaseExtended/flutterfire#3564
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.m …
=> docs(core): fixed Firebase SDK version override in build.gradle

docs/versions.js
=> docs: bump web sdk to 7.20.0

docs/migration-guide.mdx
=> docs: update migration-guide

docs/firestore/usage.mdx
I am updating the reference to document to be doc
https://github.com/FirebaseExtended/flutterfire/issues/3714
=> docs: updating document to proper doc reference

docs/firestore/usage.mdx
Replaced deprecated reference for "document" with "doc" in the file docs/firestore/usage.mdx
FirebaseExtended/flutterfire#3714
=> docs: fixed a typo error in documentation

packages/firebase_ml_vision/README.md
I fixed the documentation of firebase_ml_vision.
=> docs: fix typo in the documentation of firebase_ml_vision

packages/cloud_firestore/cloud_firestore_web/CHANGELOG.md, packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
In this PR, I have updated the dependency of `cloud_firestore_platform_interface` in `cloud_firestore_web`. As `cloud_firestore` depends on version `2.1.0` and `cloud_firestore_web` depends on `<2.1.0` so it gave error while `pub get`. So here is a update to it dependency.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/3712 and https://github.com/flutter/flutter/issues/67026 …
=> fix(cloud_firestore_web): fix dependency in pubspec.yaml

packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
In my previous [PR](https://github.com/FirebaseExtended/flutterfire/pull/3713), I mistakenly updated the wrong platform interface dependency (apologies for that), this PR fixes that and also the initial [issue](https://github.com/FirebaseExtended/flutterfire/issues/3712).
[pub …
=> fix: dependency issue in pubspec.yaml

docs/auth/phone.mdx
Added named argument labels for PhoneAuthProvider.credential() constructor.
>before
PhoneAuthCredential phoneAuthCredential = PhoneAuthProvider.credential(verificationId, smsCode);
>after
PhoneAuthCredential phoneAuthCredential = PhoneAuthProvider.credential(verificationId: verificationId, smsCode: smsCode);
Before you …
=> docs(auth): added named argument labels.

CONTRIBUTING.md
Small URL fix for contributing file
=> Contributing file: Fix outdated url

docs/storage/usage.mdx, packages/firebase_auth/firebase_auth/README.md, packages/firebase_crashlytics/firebase_crashlytics/README.md, packages/firebase_storage/firebase_storage/README.md
Updates to README for storage, crashlytics and auth.
=> docs: README updates

docs/versions.js
I have updated the library to make the implementation in iOS easier by eliminating a configuration in the AppDelegate.swift …
=> docs: updated flutter_facebook_auth version

docs/storage/usage.mdx
Fix `TaskState` typo in docs
Fixes #3783 
=> docs(firebase_storage): fix TaskState typo in docs

packages/cloud_firestore/cloud_firestore/example/ios/Podfile, packages/cloud_firestore/cloud_firestore/ios/cloud_firestore.podspec, packages/cloud_firestore/cloud_firestore/macos/cloud_firestore.podspec, packages/cloud_functions/cloud_functions/ios/cloud_functions.podspec, packages/cloud_functions/cloud_functions/macos/cloud_functions.podspec, packages/firebase_admob/ios/firebase_admob.podspec, packages/firebase_analytics/firebase_analytics/ios/firebase_analytics.podspec, packages/firebase_auth/firebase_auth/ios/firebase_auth.podspec, packages/firebase_auth/firebase_auth/macos/firebase_auth.podspec, packages/firebase_core/firebase_core/android/gradle.properties, packages/firebase_core/firebase_core/ios/firebase_core.podspec, packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb, packages/firebase_core/firebase_core/macos/firebase_core.podspec, packages/firebase_crashlytics/firebase_crashlytics/ios/firebase_crashlytics.podspec, packages/firebase_crashlytics/firebase_crashlytics/macos/firebase_crashlytics.podspec, packages/firebase_database/ios/firebase_database.podspec, packages/firebase_database/macos/firebase_database.podspec, packages/firebase_dynamic_links/ios/firebase_dynamic_links.podspec, packages/firebase_in_app_messaging/ios/firebase_in_app_messaging.podspec, packages/firebase_messaging/ios/firebase_messaging.podspec, packages/firebase_performance/example/android/app/build.gradle, packages/firebase_performance/ios/firebase_performance.podspec, packages/firebase_remote_config/ios/firebase_remote_config.podspec, packages/firebase_remote_config/macos/firebase_remote_config.podspec, packages/firebase_storage/firebase_storage/ios/firebase_storage.podspec, packages/firebase_storage/firebase_storage/macos/firebase_storage.podspec
=> feat: update native Firebase SDK dependencies for Android & iOS

docs/auth/usage.mdx
Flutter port of the 'sending' and 'link verification' process of this page https://firebase.google.com/docs/auth/android/email-link-auth
None
[CLA]: …
=> docs(firebase_auth): add steps for Email Link Authentication

docs/auth/usage.mdx
Working on a project with cloud_firestore: ^0.14.0+2 as I learn my way around firebase, I noticed that the current documentation causes an error, because the current sdk for flutter uses object notations.
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes …
=> docs(auth): update to credential to use object notation

docs/auth/usage.mdx
Fix typos in #3889
Fixes #3889
=> docs(firebase_auth): fix broken links

packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
=> fix(messaging,ios): crash when senderId null (fixes #4024)

docs/messaging/notifications.mdx, docs/messaging/usage.mdx
=> docs: add warnings about APNs not working on simulators

packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java, packages/firebase_messaging/firebase_messaging/example/lib/main.dart, packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m, packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/method_channel/method_channel_messaging.dart, packages/firebase_messaging/firebase_messaging_platform_interface/test/method_channel_tests/method_channel_messaging_test.dart
=> refactor(messaging): use invokeMapMethod instead of invokeMethod

packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundExecutor.java
Unable to reproduce the issue myself, but this has been tested in #4032 and confirmed as fixing the issue.
Fixes #4032 
[CLA]: …
=> fix(messaging): potential crash (fixes #4032)

packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingUtils.java
=> fix(messaging,android): java String arrays should be converted to a List (fixes #4072)

docs/messaging/usage.mdx
Update the incorrect function name
Update documentation with correct function name.
None
=> docs(messaging): update incorrect function name

docs/auth/usage.mdx
[auth/doc] Updated Email verification doc to include link based verification and handling link directly in app via Firebase Dynamic Links.
The email verification using firebase auth is link based, the existing documentation referred to the code based flow.
I have added documentation to handle the link directly in app using Firebase dynamic links. 
References taken from Firebase's official documentation. …
=> docs(auth): updated Email verification documentation

docs/versions.js
I'm the creator of `flutter_facebook_auth` I've been updated the plugin version to ^1.0.0
I'm the creator of `flutter_facebook_auth` I've been updated the plugin version to ^1.0.0 …
=> docs: updated flutter_facebook_auth to ^1.0.0

packages/firebase_auth/firebase_auth/example/lib/signin_page.dart
ActionCodeSettings changed in current (2.0.1) auth in action_code_settings.dart, so changed example to fit
=> fix(auth,example): updated email link signin to use latest format for ActionCodeSettings

.github/workflows/scripts/install-flutter.sh, .github/workflows/scripts/install-tools.sh
=> ci: use new GH actions path adding mechanism

packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m, packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_message.dart, packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_notification.dart
This pull request fixes the toMap method of RemoteMessage for firebase push images.
When sending a test push via firebase with an image the message looks like this:
```
{
data =  {
"fcm_options" = {
image = "https://www.kostenlos.de/app/uploads/2020/11/slider_orange.jpg";
};
};
messageId = 1605769654017551;
sentTime = 1605769654;
}
```
The problem is, that `fcm_options` within `data` is a map and the `toMap` method currently needs data as a `Map<String, String>`. When changing it to `Map<String, dynamic>` it works.
* https://github.com/FirebaseExtended/flutterfire/issues/4097#issuecomment-729827418 …
=> fix(firebase_messaging): various data types issues in remote message 

docs/firestore/usage.mdx
=> docs(firestore): fix typo

packages/cloud_firestore/cloud_firestore/example/android/app/gradle/wrapper/gradle-wrapper.properties, packages/cloud_firestore/cloud_firestore/example/android/gradle/wrapper/gradle-wrapper.properties, packages/cloud_functions/cloud_functions/example/android/app/gradle/wrapper/gradle-wrapper.properties, packages/cloud_functions/cloud_functions/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_admob/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_admob/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_analytics/firebase_analytics/example/android/app/gradle/wrapper/gradle-wrapper.properties, packages/firebase_analytics/firebase_analytics/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_auth/firebase_auth/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_auth/firebase_auth/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_core/firebase_core/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_crashlytics/firebase_crashlytics/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_database/example/android/app/gradle/wrapper/gradle-wrapper.properties, packages/firebase_database/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_dynamic_links/example/android/app/gradle/wrapper/gradle-wrapper.properties, packages/firebase_dynamic_links/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_in_app_messaging/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_messaging/firebase_messaging/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_ml_custom/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_ml_custom/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_ml_vision/example/android/app/gradle/wrapper/gradle-wrapper.properties, packages/firebase_ml_vision/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_performance/example/android/app/gradle/wrapper/gradle-wrapper.properties, packages/firebase_performance/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_remote_config/example/android/app/gradle/wrapper/gradle-wrapper.properties, packages/firebase_storage/firebase_storage/example/android/app/gradle/wrapper/gradle-wrapper.properties, packages/firebase_storage/firebase_storage/example/android/gradle/wrapper/gradle-wrapper.properties
=> chore(examples): bump gradle wrapper to 5.6.4

CONTRIBUTING.md
=> docs(contributor guide): Comment out TODOs

docs/storage/usage.mdx
=> docs(firebase_storage): Fix mismatched progress calculator

packages/firebase_storage/firebase_storage_web/lib/src/firebase_storage_web.dart, packages/firebase_storage/firebase_storage_web/lib/src/interop/firebase_interop.dart, packages/firebase_storage/firebase_storage_web/lib/src/interop/storage.dart, packages/firebase_storage/firebase_storage_web/lib/src/interop/storage_interop.dart, packages/firebase_storage/firebase_storage_web/lib/src/reference_web.dart, packages/firebase_storage/firebase_storage_web/lib/src/task_snapshot_web.dart, packages/firebase_storage/firebase_storage_web/lib/src/task_web.dart, packages/firebase_storage/firebase_storage_web/lib/src/utils/errors.dart, packages/firebase_storage/firebase_storage_web/lib/src/utils/list.dart, packages/firebase_storage/firebase_storage_web/lib/src/utils/metadata.dart, packages/firebase_storage/firebase_storage_web/lib/src/utils/task.dart, packages/firebase_storage/firebase_storage_web/pubspec.yaml
Migrates the interop code on top of `firebase_storage_web`.
=> feat(firebase_storage_web): migrate firebase interop into library

packages/firebase_auth/firebase_auth/lib/src/user.dart
I just fixed two typos in method documentation: "will be refresh" should be "will be refresh**ed**".
=> docs: Fixed two typos in method documentation

packages/cloud_functions/cloud_functions_web/lib/interop/functions.dart
=> fix: issue when specifying a functions region #4226

CONTRIBUTING.md
Mention likely install sources to find clang-format
It is required to run the `melos format` command which is recommended in the file
None logged
This is docs only, so much of the checklist does not apply
=> docs(CONTRIBUTING): note that clang-format is needed

melos.yaml
=> chore: rework melos scripts

docs/messaging/usage.mdx
web firebase_messaging usage documentation updates.
none.
=> docs(messaging): usage tweaks

docs/auth/usage.mdx
When you sign-out of an anonymous auth account, the account details are wiped from the device/browser and can't be reclaimed.
Context: https://stackoverflow.com/q/65158467 …
=> docs(auth): clarify anonymous auth

packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
Issues discovered in #4331 by @mikehardy. …
=> fix(messaging): some iOS methods could result in an `no implementation found` error

docs/messaging/server-integration.mdx
Corrected codes for working well.
-
=> docs(firebase_messaging): Correct codes on the document for firebase messaging

packages/firebase_core/firebase_core/lib/src/firebase.dart, packages/firebase_core/firebase_core/test/firebase_core_test.dart, packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_exception.dart, packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart, packages/firebase_core/firebase_core_platform_interface/lib/src/method_channel/method_channel_firebase.dart, packages/firebase_core/firebase_core_platform_interface/lib/src/method_channel/method_channel_firebase_app.dart, packages/firebase_core/firebase_core_platform_interface/lib/src/platform_interface/platform_interface_firebase.dart, packages/firebase_core/firebase_core_platform_interface/lib/src/platform_interface/platform_interface_firebase_plugin.dart, packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart, packages/firebase_core/firebase_core_web/lib/src/interop/core_interop.dart, packages/firebase_core/firebase_core_web/lib/src/interop/utils/es6_interop.dart, packages/firebase_core/firebase_core_web/lib/src/interop/utils/func.dart, packages/firebase_core/firebase_core_web/lib/src/interop/utils/js_interop.dart, packages/firebase_core/firebase_core_web/lib/src/interop/utils/utils.dart
Adds null safety hints to the core packages.
Note; this does not allow null safety, it's a precursor to a larger migration
[CLA]: …
=> chore(firebase_core): null safety hints

docs/firestore/usage.mdx
`FlatButton` is obsolete so we should use `TextButton`.
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/C …
=> docs: removed `FlatButton` in favour of `TextButton`

packages/firebase_crashlytics/firebase_crashlytics/example/test_driver/firebase_crashlytics_e2e.dart, packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart, packages/firebase_crashlytics/firebase_crashlytics/test/firebase_crashlytics_test.dart, packages/firebase_crashlytics/firebase_crashlytics/test/mock.dart, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/lib/src/method_channel/method_channel_crashlytics.dart, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/lib/src/method_channel/utils/exception.dart, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/lib/src/platform_interface/platform_interface_crashlytics.dart, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/test/method_channel_tests/method_channel_crashlytics_test.dart, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/test/method_channel_tests/utils_tests/exception_test.dart, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/test/mock.dart, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/test/platform_interface_tests/platform_interface_crashlytics_test.dart
Ensures that exceptions are bubbled up to the users error handler when debugging on VSCode.
Also adds hints to crashlytics packages for null safety
[CLA]: …
=> fix(firebase_crashlytics): bubble exceptions

docs/auth/usage.mdx
Fixes Docusaurus local building issues with links not being generated correctly.
=> chore: relative documentation links

packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart
=> refactor(firebase_crashlytics)!: remove deprecated APIs

packages/cloud_firestore/cloud_firestore/example/pubspec.yaml, packages/firebase_analytics/firebase_analytics/example/pubspec.yaml, packages/firebase_dynamic_links/example/pubspec.yaml, packages/firebase_messaging/firebase_messaging/example/pubspec.yaml, packages/firebase_messaging/firebase_messaging/pubspec.yaml, packages/firebase_ml_vision/example/pubspec.yaml
This adds missing SDK constraints on some example packages, that would otherwise cause `pub get` to fail with:
```
pubspec.yaml has no lower-bound SDK constraint.                         
You should edit pubspec.yaml to contain an SDK constraint:              
environment:                                                            
sdk: '>=2.10.0 <3.0.0'                                                
See https://dart.dev/go/sdk-constraint                                  
Running "flutter pub get" in example...                                 
pub get failed (65; See https://dart.dev/go/sdk-constraint)
```
https://github.com/invertase/melos/issues/50, which is likely how we arrived at this situation as `melos` swallows the error …
=> fix: Add missing sdk version constraints inside pubspec.yaml

packages/firebase_messaging/firebase_messaging_web/lib/src/interop/messaging.dart
=> fix(messaging,web): null check notification jsObject

packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
This check ensures that firebase_auth only handles remoteNotifications when firebase_messaging is not present, when firebase_messaging is present, it will send auth messages to firebase_auth.
Fixes #4097
Fixes #4412
Fixes #4388
- [-] The analyzer (`flutter analyze`) does not report any problems on my PR.
-flutter analyze
warning • The include file package:pedantic/analysis_options.1.8.0.yaml in
/Users/diego/Documents/flutterfire/analysis_options.yaml cannot be found • analysis_options.yaml:1:11 •
include_file_not_found
warning • The include file …
=> fix(auth,messaging): package compatibility

packages/firebase_core/firebase_core/CHANGELOG.md, packages/firebase_core/firebase_core/pubspec.yaml, packages/firebase_core/firebase_core_platform_interface/CHANGELOG.md, packages/firebase_core/firebase_core_platform_interface/pubspec.yaml, packages/firebase_core/firebase_core_web/CHANGELOG.md, packages/firebase_core/firebase_core_web/pubspec.yaml
update versions/changelogs of firebase_core packages
=> chore: update versions/changelogs of firebase_core packages

packages/firebase_core/firebase_core_web/CHANGELOG.md
=> chore: update incorrect version used in the changelog of firebase_core_web

packages/firebase_core/firebase_core/lib/firebase_core.dart, packages/firebase_core/firebase_core/lib/src/firebase_app.dart, packages/firebase_core/firebase_core/pubspec.yaml, packages/firebase_core/firebase_core_platform_interface/lib/firebase_core_platform_interface.dart, packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_exception.dart, packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart, packages/firebase_core/firebase_core_platform_interface/lib/src/platform_interface/platform_interface_firebase_app.dart
Flutter now includes hash functions, so quiver is no-longer needed
=> refactor: remove quiver from firebase_core

packages/firebase_core/firebase_core/pubspec.yaml
remove dependency_overrides in firebase_chore
=> chore: remove dependency_overrides in firebase_chore

packages/firebase_core/firebase_core/lib/firebase_core.dart
1eae3e263e487d4c06df035ea413e6cc2946b2a6 was merged too fast and introduced a compilation error. This fixes it
=> chore: fix invalid import

.github/workflows/all_plugins.yaml, .github/workflows/scripts/build-example.sh, .github/workflows/scripts/install-tools.sh, CONTRIBUTING.md, melos.yaml, packages/cloud_functions/cloud_functions_web/test/cloud_functions_web_test.dart, packages/firebase_storage/firebase_storage/example/lib/save_as/save_as.dart, packages/firebase_storage/firebase_storage/example/lib/save_as/save_as_interface.dart
Adds a `flutter test` job for Web testing. Additionally has various CI tweaks post merging of core nnbd changes.
N/A
[CLA]: …
=> ci: various tweaks/fixes

packages/firebase_auth/firebase_auth/CHANGELOG.md, packages/firebase_auth/firebase_auth/pubspec.yaml, packages/firebase_auth/firebase_auth_platform_interface/CHANGELOG.md, packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml, packages/firebase_auth/firebase_auth_web/CHANGELOG.md, packages/firebase_auth/firebase_auth_web/pubspec.yaml
Let's release the NNBD version of firebase_auth!
=> chore: Add changelogs for firebase_auth

packages/cloud_functions/cloud_functions/pubspec.yaml, packages/cloud_functions/cloud_functions_platform_interface/pubspec.yaml, packages/cloud_functions/cloud_functions_web/pubspec.yaml, packages/firebase_auth/firebase_auth/pubspec.yaml, packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml, packages/firebase_auth/firebase_auth_web/pubspec.yaml, packages/firebase_core/firebase_core/CHANGELOG.md, packages/firebase_core/firebase_core/pubspec.yaml, packages/firebase_core/firebase_core_web/pubspec.yaml
=> feat: bump firebase_core to v0.8.0-nullsafety.1

packages/firebase_auth/firebase_auth/pubspec.yaml, packages/firebase_auth/firebase_auth_platform_interface/CHANGELOG.md, packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml, packages/firebase_auth/firebase_auth_web/CHANGELOG.md, packages/firebase_auth/firebase_auth_web/pubspec.yaml
bump firebase_core for firebase_auth
=> release NNBD firebase_auth

.github/workflows/scripts/install-tools.sh
=> chore: no melos version install

packages/firebase_messaging/firebase_messaging/example/lib/main.dart
Changed the typo in the example code. Initalize -> Initialize
- [x ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x ] All existing and new tests are passing.
- [x ] I updated/added relevant documentation (doc comments with `///`).
- [x ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x ] I read and followed the [Flutter Style Guide].
- [x ] I signed the [CLA].
- [x ] …
=> docs: fix typo

docs/overview.mdx
=> docs: add missing semicolon to example

packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart, packages/cloud_firestore/cloud_firestore/example/test_driver/write_batch_e2e.dart, packages/cloud_firestore/cloud_firestore/example/web/index.html, packages/cloud_firestore/cloud_firestore_web/lib/src/collection_reference_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/document_reference_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/interop/utils/utils.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/transaction_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/write_batch_web.dart, packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
=> fix(firestore,web): nnbd issues on web

packages/cloud_firestore/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/cloud_firestore/example/pubspec.yaml, packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart, packages/cloud_firestore/cloud_firestore/example/test_driver/write_batch_e2e.dart, packages/cloud_firestore/cloud_firestore/example/web/index.html, packages/cloud_firestore/cloud_firestore/pubspec.yaml, packages/cloud_firestore/cloud_firestore_platform_interface/CHANGELOG.md, packages/cloud_firestore/cloud_firestore_platform_interface/pubspec.yaml, packages/cloud_firestore/cloud_firestore_web/CHANGELOG.md, packages/cloud_firestore/cloud_firestore_web/lib/src/collection_reference_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/document_reference_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/interop/utils/utils.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/transaction_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/write_batch_web.dart, packages/cloud_firestore/cloud_firestore_web/pubspec.yaml, packages/firebase_messaging/firebase_messaging/CHANGELOG.md, packages/firebase_messaging/firebase_messaging/example/analysis_options.yaml, packages/firebase_messaging/firebase_messaging/example/pubspec.yaml, packages/firebase_messaging/firebase_messaging/pubspec.yaml, packages/firebase_messaging/firebase_messaging_platform_interface/CHANGELOG.md, packages/firebase_messaging/firebase_messaging_platform_interface/pubspec.yaml, packages/firebase_messaging/firebase_messaging_web/CHANGELOG.md, packages/firebase_messaging/firebase_messaging_web/pubspec.yaml
=> chore(release): publish new nullsafety packages

website/plugins.js
I noticed that on README file we have support for web ticked, but not on https://firebase.flutter.dev
https://github.com/FirebaseExtended/flutterfire/pull/4206 …
=> docs: update Cloud Messaging support for web

.github/workflows/firebase_admob.yaml, melos.yaml
Internal ticket: [FLUTTERFIRE-38](https://yt.invertase.io/youtrack/issue/FLUTTERFIRE-38) …
=> chore: temporarily exclude admob from CI & Melos workspace

docs/firestore/usage.mdx
"snapshot.data.documents" have been renamed to "snapshot.data.docs". …
=> docs: fix incorrect usage of snapshot.docs

packages/cloud_firestore/cloud_firestore/example/pubspec.yaml, packages/cloud_functions/cloud_functions/example/pubspec.yaml, packages/firebase_analytics/firebase_analytics/example/pubspec.yaml, packages/firebase_analytics/firebase_analytics/pubspec.yaml, packages/firebase_analytics/firebase_analytics_platform_interface/pubspec.yaml, packages/firebase_analytics/firebase_analytics_web/pubspec.yaml, packages/firebase_crashlytics/firebase_crashlytics/example/pubspec.yaml, packages/firebase_database/example/pubspec.yaml, packages/firebase_database/pubspec.yaml, packages/firebase_dynamic_links/example/pubspec.yaml, packages/firebase_dynamic_links/pubspec.yaml, packages/firebase_in_app_messaging/pubspec.yaml, packages/firebase_messaging/firebase_messaging/example/pubspec.yaml, packages/firebase_ml_vision/example/pubspec.yaml, packages/firebase_ml_vision/pubspec.yaml, packages/firebase_performance/pubspec.yaml, packages/firebase_remote_config/firebase_remote_config/example/pubspec.yaml, packages/firebase_remote_config/firebase_remote_config/pubspec.yaml, packages/firebase_remote_config/firebase_remote_config_platform_interface/pubspec.yaml
=> chore: remove upperbound flutter sdk constraint

docs/auth/social.mdx
Caution developers about Facebook provider issue.
fixes https://github.com/FirebaseExtended/flutterfire/issues/4612
[CLA]: …
=> docs: email verified behaviour when using the Facebook provider

docs/analytics/overview.mdx, docs/auth/overview.mdx, docs/core/usage.mdx, docs/crashlytics/overview.mdx, docs/database/overview.mdx, docs/firestore/overview.mdx, docs/functions/overview.mdx, docs/messaging/overview.mdx, docs/null-safety.mdx, docs/overview.mdx, docs/performance/overview.mdx, docs/remote-config/overview.mdx, docs/storage/overview.mdx, website/api.js, website/package.json, website/yarn.lock
NNBD migration documentation for each package.
[Internal ticket](https://yt.invertase.io/youtrack/issue/FLUTTERFIRE-34)
[CLA]: …
=> refactor: NNBD docs migration

packages/firebase_admob/README.md
Include deprecation plan and migration guide in README.
Readme in markdown: https://github.com/bparrishMines/flutterfire/blob/deprecation/packages/firebase_admob/README.md …
=> docs: include deprecation plan and migration guide for firebase_admob to google_mobile_ads

packages/firebase_admob/CHANGELOG.md, packages/firebase_admob/README.md, packages/firebase_admob/pubspec.yaml
Bump version of AdMob plugin so it can be published. This will allow the deprecation instructions to be displayed on pub.
=> Deprecate admob

packages/firebase_analytics/firebase_analytics_web/pubspec.yaml
This upgrades `firebase` to fix version conflicts on `http_parser` between `firebase` and some of our packages
fixes #5202 
[CLA]: …
=> fix: upgrade `firebase` in firebase_analytics_web

docs/crashlytics/overview.mdx
I have fixed a typo in Firebase Crashlytics docs
fixes #5291 
=> docs: fix typo in crashlytics docs

docs/installation/android.mdx
This reflects the usage on the [android docs](https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic)
This will ensure a smooth and quick review process. Updating …
=> fix: Added `android:` to `usesCleartextTraffic` in docs

docs/null-safety.mdx
remove notice about null safety is beta
=> docs: update null-safety.mdx

packages/cloud_firestore/cloud_firestore/example/ios/Runner.xcodeproj/project.pbxproj, packages/firebase_admob/example/ios/Runner.xcodeproj/project.pbxproj, packages/firebase_analytics/firebase_analytics/example/ios/Runner.xcodeproj/project.pbxproj, packages/firebase_database/example/ios/Runner.xcodeproj/project.pbxproj, packages/firebase_dynamic_links/example/ios/Runner.xcodeproj/project.pbxproj, packages/firebase_dynamic_links/test/firebase_dynamic_links_test.dart, packages/firebase_performance/example/ios/Runner.xcodeproj/project.pbxproj, packages/firebase_remote_config/firebase_remote_config/example/ios/Runner.xcodeproj/project.pbxproj, packages/firebase_storage/firebase_storage/example/ios/Runner.xcodeproj/project.pbxproj
=> fix: remove incorrect ARCHS in ios examples

CODEOWNERS
Since the code owners for all the packages are the same, specifying each package is not required.
=> chore(repository): Simplify CODEOWNERS

docs/installation/web.mdx, docs/migration-guide.mdx, docs/null-safety.mdx, docs/overview.mdx
Docs tweaks to keep them up-to-date.
None.
=> docs: wording tweaks around plugin stability

docs/firestore/usage.mdx
Fix print statement text in removing data code snippet
=> docs(auth): reword print message in code snippet

packages/firebase_in_app_messaging/README.md
Fix code snippets for using firebase_in_app_messaging plugin.
No
=> fix: [firebase_in_app_messaging] README code snippets

packages/firebase_ml_vision/example/lib/camera_preview_scanner.dart, packages/firebase_ml_vision/example/lib/material_barcode_scanner.dart
Audio is not used for this demo, just request one additional,
unnecessary permission.
Only changes the example app
None
[CLA]: …
=> fix: Disable audio for camera controller in example app.

website/plugins.js, website/src/pages/index.tsx
revert documentation link to deprecated admob. 
none.
=> docs: discontinued admob

packages/firebase_ml_vision/example/lib/material_barcode_scanner.dart, packages/firebase_ml_vision/example/pubspec.yaml
Needs a small change in barcode scanner, as interface of takePicture
method change. Might help with some error reports.
#5501
#1518
#5117
=> docs: Upgrading to camera plugin 0.8.1

.github/workflows/cancel.yaml, .github/workflows/firebase_admob.yaml
=> chore: Update cancel.yaml workflow to cancel all workflows.

.github/workflows/all_plugins.yaml, .github/workflows/firebase_admob.yaml, .github/workflows/firebase_analytics.yaml, .github/workflows/firebase_auth.yaml, .github/workflows/firebase_core.yaml, .github/workflows/firebase_crashlytics.yaml, .github/workflows/firebase_database.yaml, .github/workflows/firebase_firestore.yaml, .github/workflows/firebase_functions.yaml, .github/workflows/firebase_messaging.yaml, .github/workflows/firebase_performance.yaml, .github/workflows/firebase_remote_config.yaml, .github/workflows/firebase_storage.yaml
=> chore: Skip CI when editing only markdown files

docs/sidebars.js
Adds examples to https://firebase.flutter.dev
fixes https://github.com/FirebaseExtended/flutterfire/issues/3818
=> docs: Add github examples to the firebase docs

packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart
Further clarification on `auth.userChanges` API.
fixes #3461
=> docs(firestore): userChanges clarification

docs/crashlytics/usage.mdx
Update Crashlytics documentation example.
fixes #3623
=> docs(crashlytics): update example

packages/cloud_firestore/cloud_firestore/example/pubspec.yaml, packages/cloud_functions/cloud_functions/example/pubspec.yaml, packages/firebase_auth/firebase_auth/example/pubspec.yaml, packages/firebase_crashlytics/firebase_crashlytics/example/pubspec.yaml, packages/firebase_messaging/firebase_messaging/example/pubspec.yaml, packages/firebase_storage/firebase_storage/example/pubspec.yaml
=> chore: update drive dependency

.github/workflows/firebase_auth.yaml, .github/workflows/firebase_firestore.yaml, .github/workflows/firebase_functions.yaml, .github/workflows/scripts/drive-example.sh, packages/cloud_firestore/cloud_firestore/example/test_driver/cloud_firestore_e2e.dart
=> ci(web): switch back to ubuntu CI runners for testing with Firebase emulator suite

packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/document_reference_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/internals.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/transaction_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/write_batch_web.dart, packages/firebase_core/firebase_core/lib/src/internals.dart, packages/firebase_messaging/firebase_messaging_web/lib/firebase_messaging_web.dart, packages/firebase_messaging/firebase_messaging_web/lib/src/internals.dart, packages/firebase_messaging/firebase_messaging_web/lib/src/utils.dart, packages/firebase_storage/firebase_storage_web/lib/src/firebase_storage_web.dart, packages/firebase_storage/firebase_storage_web/lib/src/reference_web.dart, packages/firebase_storage/firebase_storage_web/lib/src/task_web.dart, packages/firebase_storage/firebase_storage_web/lib/src/utils/errors.dart
Share guards/getFirebaseException between all packages
=> refactor: Share guard functions accross plugins

packages/firebase_auth/firebase_auth_platform_interface/lib/src/action_code_info.dart, packages/firebase_ml_vision/lib/src/document_text_recognizer.dart, packages/firebase_ml_vision/lib/src/image_labeler.dart, packages/firebase_ml_vision/lib/src/text_recognizer.dart
CI format check is currently failing.
none.
=> refactor: fix formatting

packages/firebase_auth/firebase_auth_platform_interface/lib/src/user_info.dart
`UserInfo.uid` is nullable.
fixes #5218
=> fix(auth): uid can be null

.github/workflows/all_plugins.yaml, .github/workflows/docs.yaml, .github/workflows/firebase_admob.yaml, .github/workflows/firebase_analytics.yaml, .github/workflows/firebase_auth.yaml, .github/workflows/firebase_core.yaml, .github/workflows/firebase_crashlytics.yaml, .github/workflows/firebase_database.yaml, .github/workflows/firebase_firestore.yaml, .github/workflows/firebase_functions.yaml, .github/workflows/firebase_messaging.yaml, .github/workflows/firebase_performance.yaml, .github/workflows/firebase_remote_config.yaml, .github/workflows/firebase_storage.yaml, packages/firebase_auth/firebase_auth/example/lib/signin_page.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/action_code_info.dart, packages/firebase_ml_vision/lib/src/document_text_recognizer.dart, packages/firebase_ml_vision/lib/src/image_labeler.dart, packages/firebase_ml_vision/lib/src/text_recognizer.dart, packages/firebase_remote_config/firebase_remote_config/example/test_driver/firebase_remote_config_e2e.dart, packages/firebase_remote_config/firebase_remote_config/example/test_driver/firebase_remote_config_e2e_test.dart
=> ci: workflow changes

docs/firestore/usage.mdx
Calling `snapshot.data.data()` on a non-existing `DocumentSnapshot` leads to:
> The method '[]' was called on null.
I see this error pop up a lot on Stack Overflow, so this behavior is not obvious to developers. 
Explicitly including a `exists` check in this code sample should lead to move devs doing the right thing. …
=> docs(firestore): handle non-existent document

packages/firebase_auth/firebase_auth/ios/Classes/Public/FLTFirebaseAuthPlugin.h
The header file should import all header files needed to parse itself.
=> fix(firebase_auth,ios): Import all necessary headers from the header file.

packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
As discovered on #5939 and the fix confirmed working on the same PR.
- N/A
=> fix(auth,web): fixed an issue where Web could not connect to the Firebase Auth emulator

packages/firebase_core/firebase_core/android/gradle.properties
fixes #4935
Bump firebase BOM to 26.8.0. On current version no network errors are not reported correctly.
=> feat(android,*): upgrade Firebase Android SDK to 26.8.0

docs/firestore/usage.mdx, packages/cloud_firestore/cloud_firestore/example/analysis_options.yaml, packages/cloud_firestore/cloud_firestore/example/lib/main.dart, packages/cloud_firestore/cloud_firestore/example/lib/movie.dart, packages/cloud_firestore/cloud_firestore/example/test_driver/collection_reference_e2e.dart, packages/cloud_firestore/cloud_firestore/example/test_driver/document_reference_e2e.dart, packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart, packages/cloud_firestore/cloud_firestore/lib/cloud_firestore.dart, packages/cloud_firestore/cloud_firestore/lib/src/collection_reference.dart, packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart, packages/cloud_firestore/cloud_firestore/lib/src/document_snapshot.dart, packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart, packages/cloud_firestore/cloud_firestore/lib/src/query.dart, packages/cloud_firestore/cloud_firestore/lib/src/query_document_snapshot.dart, packages/cloud_firestore/cloud_firestore/lib/src/query_snapshot.dart, packages/cloud_firestore/cloud_firestore/lib/src/transaction.dart, packages/cloud_firestore/cloud_firestore/lib/src/write_batch.dart, packages/cloud_firestore/cloud_firestore/test/collection_reference_test.dart, packages/cloud_firestore/cloud_firestore/test/document_reference_test.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
`withConverter` transforms a reference to manipulate a custom object instead
of a `Map<String, dynamic>`.
This makes both read and write operations type-safe.
```dart
final usersRef = FirebaseFirestore
.instance
.collection('users')
.withConverter<User>(
fromFirestore: (snapshot, _) => User.fromJson(snapshot.data()!),
toFirestore: (user, _) => user.toJson(),
);
Future<void> main() async {
// Writes now take a User as parameter instead of a Map
await usersRef.add(User(name: 'John'));
// Reads now return a User instead of a Map
final User user = await usersRef.doc('123').get().then((s) => s.data());
}
``` …
=> feat: Add withConverter function to CollectionReference, DocumentReference and Query

packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart
When using firebase auth package - phone authentication with ios device, the error occurs below.
```
Unhandled Exception: type 'Null' is not a subtype of type 'int'
#0      MethodChannelFirebaseAuth.verifyPhoneNumber.
```
So I changed below
```dart
// method_channel_firebase_auth.dart
else if (name == 'Auth#phoneCodeSent') {
final String verificationId = arguments['verificationId'];
final int forceResendingToken = arguments['forceResendingToken'];
```
to
```dart
// method_channel_firebase_auth.dart
else if (name == 'Auth#phoneCodeSent') {
final String verificationId = arguments['verificationId'];
final int? forceResendingToken = arguments['forceResendingToken'];
```
This PR solves the type error that ios devices could not sign in with phone.
Before you create this PR confirm that it meets …
=> fix(firebase_auth): authentication forceResendingToken int can be null on iOS

packages/cloud_firestore/cloud_firestore/lib/src/document_snapshot.dart, packages/cloud_firestore/cloud_firestore/lib/src/query.dart, packages/cloud_firestore/cloud_firestore/test/document_snapshot_test.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_document_snapshot.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/set_options.dart, packages/cloud_firestore/cloud_firestore_platform_interface/test/set_options_test.dart
These are leftover from the null-safety migration
=> feat!: convert FieldPath parameters from dynamic to Object

.github/ISSUE_TEMPLATE/---bug-report.md
To improve the bug reporting & triaging process.
=> chore: update issue template to suggest providing example project

docs/analytics/overview.mdx, docs/database/overview.mdx, docs/performance/overview.mdx, docs/remote-config/overview.mdx, website/plugins.js, website/src/pages/index.tsx
=> docs: add package stable/beta quality indicators

CONTRIBUTING.md
update how to publish documentation.
none.
=> docs: update contributing docs for publishing

packages/cloud_firestore/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/cloud_firestore/pubspec.yaml, packages/cloud_firestore/cloud_firestore_platform_interface/CHANGELOG.md, packages/cloud_firestore/cloud_firestore_platform_interface/pubspec.yaml, packages/cloud_firestore/cloud_firestore_web/CHANGELOG.md, packages/cloud_firestore/cloud_firestore_web/pubspec.yaml, packages/cloud_functions/cloud_functions/CHANGELOG.md, packages/cloud_functions/cloud_functions/pubspec.yaml, packages/firebase_analytics/firebase_analytics/CHANGELOG.md, packages/firebase_analytics/firebase_analytics/pubspec.yaml, packages/firebase_auth/firebase_auth/CHANGELOG.md, packages/firebase_auth/firebase_auth/pubspec.yaml, packages/firebase_auth/firebase_auth_platform_interface/CHANGELOG.md, packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml, packages/firebase_auth/firebase_auth_web/CHANGELOG.md, packages/firebase_auth/firebase_auth_web/pubspec.yaml
- cloud_firestore@2.0.0
- cloud_firestore_platform_interface@5.0.0
- cloud_firestore_web@2.0.0
- cloud_functions@1.0.6
- firebase_analytics@8.0.3
- firebase_auth@1.1.3
- firebase_auth_platform_interface@4.2.1
- firebase_auth_web@1.1.1 …
=> chore(release): publish packages

packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/source.dart
=> docs(cloud_firestore): update Source.cache doc

packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
=> docs(firebase_auth): Update the documentation of sendPasswordResetEmail

docs/overview.mdx
=> docs: update the "initializing flutterfire" snippet

docs/crashlytics/usage.mdx
=> docs: improve the documentation about using runZoneGuarded for crashlytics

packages/cloud_firestore/cloud_firestore_platform_interface/pubspec.yaml, packages/cloud_firestore/cloud_firestore_web/pubspec.yaml, packages/cloud_functions/cloud_functions_platform_interface/pubspec.yaml, packages/cloud_functions/cloud_functions_web/pubspec.yaml, packages/firebase_admob/pubspec.yaml, packages/firebase_analytics/firebase_analytics_platform_interface/pubspec.yaml, packages/firebase_analytics/firebase_analytics_web/pubspec.yaml, packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml, packages/firebase_auth/firebase_auth_web/pubspec.yaml, packages/firebase_core/firebase_core_platform_interface/pubspec.yaml, packages/firebase_core/firebase_core_web/pubspec.yaml, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/pubspec.yaml, packages/firebase_dynamic_links/pubspec.yaml, packages/firebase_in_app_messaging/pubspec.yaml, packages/firebase_messaging/firebase_messaging_platform_interface/pubspec.yaml, packages/firebase_messaging/firebase_messaging_web/pubspec.yaml, packages/firebase_ml_custom/pubspec.yaml, packages/firebase_ml_vision/pubspec.yaml, packages/firebase_remote_config/firebase_remote_config_platform_interface/pubspec.yaml, packages/firebase_storage/firebase_storage_platform_interface/pubspec.yaml, packages/firebase_storage/firebase_storage_web/pubspec.yaml
=> docs: Add missing homepage/repository links

README.md
=> docs: fix readme incorrectly saying analytics supports macos

packages/firebase_ml_vision/README.md
ML Kit Vision APIs in Firebase are completely going away in the next iOS and Android SDK releases. This PR adds a discontinued blurb in the readme. I've already marked the package on pub.dev as discontinued; https://pub.dev/packages/firebase_ml_vision  …
=> docs(ml_vision): add discontinuation message and list alternatives

packages/cloud_firestore/cloud_firestore/CHANGELOG.md
=> docs: add QueryDocumentSnapshot to the list of classes that received a breaking change

packages/firebase_analytics/firebase_analytics/example/lib/main.dart, packages/firebase_analytics/firebase_analytics/example/lib/tabs_page.dart
fixes https://github.com/FirebaseExtended/flutterfire/issues/6095
=> docs: migrate firebase_analytics/example to null safety

packages/firebase_messaging/firebase_messaging/example/test_driver/instance_e2e.dart, packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart, packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/method_channel/method_channel_messaging.dart, packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/platform_interface/platform_interface_messaging.dart, packages/firebase_messaging/firebase_messaging_web/lib/firebase_messaging_web.dart
exposes isSupported API primarily for web applications when running on unsupported browsers like Safari.
Closes https://github.com/FirebaseExtended/flutterfire/issues/4584 …
=> feat(messaging): implement isSupported for web

all_lint_rules.yaml, analysis_options.yaml, packages/firebase_core/analysis_options.yaml, packages/firebase_core/firebase_core/lib/src/internals.dart, packages/firebase_core/firebase_core/lib/src/interop_shimmer.dart, packages/firebase_core/firebase_core_platform_interface/lib/src/platform_interface/platform_interface_firebase_plugin.dart, packages/firebase_core/firebase_core_platform_interface/test/method_channel_tests/method_channel_firebase_core_test.dart, packages/firebase_core/firebase_core_web/lib/src/interop/utils/js_interop.dart, packages/firebase_core/firebase_core_web/test/firebase_core_web_test.dart, packages/firebase_database/firebase_database/test/firebase_database_test.dart, packages/firebase_ml_vision/example/lib/detector_painters.dart, packages/firebase_ml_vision/example/lib/picture_scanner.dart, packages/firebase_storage/firebase_storage/example/lib/main.dart, packages/firebase_storage/firebase_storage/example/test_driver/instance_e2e.dart, packages/firebase_storage/firebase_storage_platform_interface/test/method_channel_tests/method_channel_firebase_storage_test.dart, packages/firebase_storage/firebase_storage_platform_interface/test/method_channel_tests/method_channel_list_result_test.dart, packages/firebase_storage/firebase_storage_platform_interface/test/mock.dart, packages/firebase_storage/firebase_storage_web/lib/src/interop/storage.dart, packages/firebase_storage/firebase_storage_web/lib/src/interop/storage_interop.dart, packages/firebase_storage/firebase_storage_web/test/metadata_cache_test.dart
=> chore: Enable more lints

docs/versions.js, packages/cloud_firestore/cloud_firestore/example/web/index.html, packages/cloud_functions/cloud_functions/example/web/index.html, packages/firebase_analytics/firebase_analytics/example/web/index.html, packages/firebase_auth/firebase_auth/example/test_driver/instance_e2e.dart, packages/firebase_auth/firebase_auth/example/test_driver/user_e2e.dart, packages/firebase_auth/firebase_auth/example/web/index.html, packages/firebase_core/firebase_core/android/gradle.properties, packages/firebase_core/firebase_core/example/web/index.html, packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb, packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart, packages/firebase_messaging/firebase_messaging/example/web/firebase-messaging-sw.js, packages/firebase_messaging/firebase_messaging/example/web/index.html, packages/firebase_storage/firebase_storage/example/web/index.html
=> feat: upgrade Firebase SDKs

docs/firestore/usage.mdx
=> docs: fix incorrect snippet

docs/functions/usage.mdx
cloud functions example with region.
closes https://github.com/FirebaseExtended/flutterfire/issues/5942
=> docs(functions): region config example

packages/firebase_auth/firebase_auth_platform_interface/lib/src/action_code_info.dart, packages/firebase_ml_vision/lib/src/document_text_recognizer.dart, packages/firebase_ml_vision/lib/src/image_labeler.dart, packages/firebase_ml_vision/lib/src/text_recognizer.dart
Reformat files, since dartfmt appears to have recently changed on stable
=> chore: fix format errors

docs/app-check/usage.mdx
Add missing `.instance`.
[activate method](https://pub.dev/documentation/firebase_app_check/latest/firebase_app_check/FirebaseAppCheck/activate.html) isn't static method.
None. …
=> docs(app_check): Add missing `.instance`

packages/firebase_database/firebase_database/example/pubspec.yaml, packages/firebase_database/firebase_database/example/test_driver/firebase_database_e2e.dart, packages/firebase_database/firebase_database/lib/src/database_reference.dart, packages/firebase_database/firebase_database/lib/src/event.dart
=> fix(firebase_database): Fix a null exception when using `runTransaction` with Maps.

website/plugins.js
add `ml_custom` to overview in docs under "Beta Plugins".
none
=> docs(ml_custom): reinstate ml_custom as beta

CONTRIBUTING.md
document how to use melos to graduate packages.
none.
=> docs: document melos graduate packages

docs/auth/usage.mdx
Fixing spelling mistake.
This PR is to correct a spelling mistake. The text currently contains 'archived', but in the context of the sentence it is supposed to be 'achieved'. …
=> docs: fix spelling mistake 

docs/auth/usage.mdx
Some of the codes were not passing the static analysis because of null safety. I fixed them along other little modifications. 
- [] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [] All existing and new tests are passing.
- [] I updated/added relevant documentation (doc comments with `///`).
- [] The analyzer (`melos run analyze`) does not report any problems on my PR. …
=> docs: fixed some Dart null safety issues. 

.github/workflows/all_plugins.yaml, .github/workflows/docs.yaml, .github/workflows/firebase_admob.yaml, .github/workflows/firebase_analytics.yaml, .github/workflows/firebase_app_check.yaml, .github/workflows/firebase_auth.yaml, .github/workflows/firebase_core.yaml, .github/workflows/firebase_crashlytics.yaml, .github/workflows/firebase_database.yaml, .github/workflows/firebase_dynamic_links.yaml, .github/workflows/firebase_firestore.yaml, .github/workflows/firebase_functions.yaml, .github/workflows/firebase_messaging.yaml, .github/workflows/firebase_ml_custom.yaml, .github/workflows/firebase_performance.yaml, .github/workflows/firebase_remote_config.yaml, .github/workflows/firebase_storage.yaml, .github/workflows/website.yaml
Update GitHub workflow "usings" to latest
=> ci: update github action versions to latest

docs/firestore/usage.mdx
Update Firestore docs for null safety.
closes #6286.
=> docs(firestore): null safe changes & corrections

docs/auth/usage.mdx
Further clarification on what to expect should a user be deleted or disabled via the Firebase console or admin sdk.
closes #4950
[CLA]: …
=> docs(auth): further clarification on auth events

docs/migration-guide.mdx
Update migration guide for auth.
closes https://github.com/FirebaseExtended/flutterfire/issues/5345
=> docs(auth): update migration guide breaking change

docs/messaging/usage.mdx, packages/firebase_messaging/firebase_messaging/example/web/firebase-messaging-sw.js, packages/firebase_messaging/firebase_messaging/example/web/index.html
Update messaging web docs example in line with latest stable flutter version `index.html`. direct users to example for setup.
closes https://github.com/FirebaseExtended/flutterfire/issues/6372 …
=> docs(messaging): update web example in line with flutter 2.2.0 generated `index.html`

packages/firebase_ml_custom/README.md
=> docs(ml_custom): removing extra `)` in sample

packages/firebase_ml_custom/README.md
=> docs(ml_custom): fix typo in README.md

docs/versions.js
bump google services version on docs.
closes https://github.com/FirebaseExtended/flutterfire/issues/6414
=> docs(android): bump google-services version

packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart
Looks like someone pressed backspace by accident.
=> fix(cloud_firestore): DocumentReference @sealed annotation

packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart, packages/cloud_firestore/cloud_firestore/lib/src/query.dart
The docs were just wrong from what I can tell.
=> fix(cloud_firestore): withConverter examples in docs

packages/cloud_firestore/cloud_firestore/android/build.gradle, packages/cloud_functions/cloud_functions/android/build.gradle, packages/firebase_analytics/firebase_analytics/android/build.gradle, packages/firebase_auth/firebase_auth/android/build.gradle, packages/firebase_core/firebase_core/android/build.gradle, packages/firebase_crashlytics/firebase_crashlytics/android/build.gradle, packages/firebase_database/firebase_database/android/build.gradle, packages/firebase_dynamic_links/android/build.gradle, packages/firebase_in_app_messaging/android/build.gradle, packages/firebase_messaging/firebase_messaging/android/build.gradle, packages/firebase_ml_custom/android/build.gradle, packages/firebase_ml_vision/android/build.gradle, packages/firebase_performance/android/build.gradle, packages/firebase_remote_config/firebase_remote_config/android/build.gradle, packages/firebase_storage/firebase_storage/android/build.gradle
remove deprecated jcenter repository from android build.
none.
=> chore(android): rm deprecated jcenter repository

docs/app-check/overview.mdx
Fixes #6413
Hey @nt4f04uNd! How does this look?
Let me know if this needs any changes!
Thanks
=> fix: App check installation doc mistake

docs/auth/phone.mdx
According to the plugin, resendToken is an optional parameter but It's omitted in the doc.
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not …
=> docs(auth): add optional codeSent callback parameter

docs/storage/usage.mdx
update documentation on handling CORS when downloading from storage bucket via web.
closes https://github.com/FirebaseExtended/flutterfire/issues/6172 …
=> docs(storage): web CORS documentation

docs/messaging/usage.mdx
=> docs(messaging): Improve Docs For FCM subscribeToTopic

packages/cloud_firestore/cloud_firestore/example/lib/main.dart, packages/cloud_firestore/cloud_firestore/example/test_driver/cloud_firestore_e2e.dart, packages/cloud_firestore/cloud_firestore/lib/cloud_firestore.dart, packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_firestore.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/settings.dart, packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
A couple of things to note:
1. For native platforms, `useEmulator` updates the settings in app code initially. This allows users to call `useFirestoreEmulator()` and also to set `FirebaseFirestore.settings = settings`. The settings properties are  merged together and sent over to the native platform on the first method invocation to the native platform. This is necessary as settings can only be set once.
2. Web is slightly different, `settings` & `useEmulator` can be set/called independently. We can use the `useEmulator` API on the SDK without having to set `sslEnabled` to `false` unlike android.
related to https://github.com/FirebaseExtended/flutterfire/issues/5224 …
=> feat(firestore): useFirestoreEmulator(host, port) API for firestore

docs/crashlytics/usage.mdx
=> docs(crashlytics): update example from docs

packages/firebase_auth/firebase_auth/example/lib/signin_page.dart
Update auth example to demonstrate how to authenticate via phone on the web.
closes https://github.com/FirebaseExtended/flutterfire/issues/5666
[CLA]: …
=> chore(auth, web): verifyPhoneNumber() example

packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_user.dart
Catch native web error and recast as a `FirebaseAuthException`.
closes https://github.com/FirebaseExtended/flutterfire/issues/5519
[CLA]: …
=> chore(auth, web): catch native error verifyBeforeUpdateEmail()

packages/cloud_functions/cloud_functions/example/lib/main.dart, packages/cloud_functions/cloud_functions/example/test_driver/cloud_functions_e2e.dart, packages/cloud_functions/cloud_functions/lib/src/firebase_functions.dart, packages/cloud_functions/cloud_functions/test/firebase_functions_test.dart, packages/firebase_auth/firebase_auth/example/lib/main.dart, packages/firebase_auth/firebase_auth/example/test_driver/firebase_auth_e2e.dart, packages/firebase_auth/firebase_auth/example/test_driver/test_utils.dart, packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart, packages/firebase_auth/firebase_auth/test/firebase_auth_test.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_tests/method_channel_firebase_auth_test.dart, packages/firebase_auth/firebase_auth_platform_interface/test/platform_interface_tests/platform_interface_auth_test.dart, packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart, packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart, packages/firebase_storage/firebase_storage/example/test_driver/firebase_storage_e2e.dart, packages/firebase_storage/firebase_storage/lib/src/firebase_storage.dart, packages/firebase_storage/firebase_storage/test/firebase_storage_test.dart, packages/firebase_storage/firebase_storage/test/mock.dart, packages/firebase_storage/firebase_storage_platform_interface/lib/src/method_channel/method_channel_firebase_storage.dart, packages/firebase_storage/firebase_storage_platform_interface/lib/src/platform_interface/platform_interface_firebase_storage.dart, packages/firebase_storage/firebase_storage_platform_interface/test/platform_interface_tests/platform_interface_firebase_storage_test.dart, packages/firebase_storage/firebase_storage_web/lib/src/firebase_storage_web.dart, packages/firebase_storage/firebase_storage_web/lib/src/interop/storage.dart
This reverts commit de7dd7e5bed4b05dde6432323b8e01362e9edeea.
Does your PR require plugin …
=> Revert "feat(*)!: use<product>Emulator(host, port) API update (#6439)"

docs/auth/usage.mdx, docs/firestore/usage.mdx, docs/functions/usage.mdx, docs/storage/usage.mdx
Update useEmulator() api documentation for storage, auth, firestore and functions packages.
closes https://github.com/FirebaseExtended/flutterfire/issues/6532 …
=> docs: use<product>Emulator() api

packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart
In the sample snippet, there's no variable `johnRef`, it should rather be `modelRef`.
=> fix: Fixed variable name

packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
bump `firebase-ios-sdk`.
none.
=> feat: bump Firebase iOS SDK version to 8.3.0

packages/firebase_database/firebase_database/example/lib/main.dart
Show how to use `increment()` function for RTDB
closes https://github.com/FirebaseExtended/flutterfire/issues/3711
=> docs(database): update database example with increment()

packages/firebase_crashlytics/firebase_crashlytics/ios/Classes/FLTFirebaseCrashlyticsPlugin.m
Fixes https://github.com/FirebaseExtended/flutterfire/issues/6623
=> fix(crashlytics, ios): issue where build would fail with missing header

docs/firestore/usage.mdx
There is no description of the merge in the documentation.
Now it is)
=> fix: Update usage.mdx

docs/database/overview.mdx
Since firebase_database plugin is stable and null-safety, I deleted caution messages of beta and not migrating null-safety.
[CLA]: …
=> fix: Update overview.mdx

docs/overview.mdx
Update overview.mdx, Firebase SDK version from 8.0.0 to 8.3.0
=> docs: Update overview.mdx, Firebase SDK version from 8.0.0 to 8.3.0

docs/firestore/usage.mdx
fix [docs/firestore/usage]:  Fixed a broken link.
[The current link was pointing to a link that doesn't exist. This fix will replace that link with the correct one.]
*The link in the existing documentation was pointing to a page that doesn't exist. This change will replace the broken [link](https://firebase.flutter.dev/docs/firestore/usage/usage#batch-write) with the correct [link](https://firebase.flutter.dev/docs/firestore/usage/#batch-write).*
*None*
[issue …
=> docs(firestore):  Fixed  broken batch write link.

docs/messaging/notifications.mdx
=> docs(messaging): notification tweak

docs/messaging/notifications.mdx
This PR modifies the documentation to use a better practice which is to centralize message handling in one place.
None.
=> docs(firebase_messaging): simplify notifications example

docs/firestore/usage.mdx
Null safety fix in Cloud Firestore usage docs (Section: Realtime Changes).
=> docs(firestore): null safe corrections

docs/firestore/usage.mdx
=> docs(firestore): formatting

docs/remote-config/overview.mdx, website/plugins.js
revert back to beta plugin.
none.
=> docs(remote_config): revert back to beta package

docs/versions.js
See also: https://github.com/FirebaseExtended/flutterfire/pull/6683#pullrequestreview-714843776
=> docs: updated the `flutter_facebook_auth` recommended version

packages/firebase_database/firebase_database/example/test_driver/firebase_database_e2e.dart, packages/firebase_database/firebase_database/lib/src/event.dart, packages/firebase_database/firebase_database/lib/src/query.dart
=> Revert "format: run formatter"

docs/auth/social.mdx
The code sample for Facebook Auth is outdated. I updated this according to the new version.
=> docs: Updated the code sample for Facebook Auth.

packages/cloud_firestore/cloud_firestore_web/lib/src/document_reference_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/field_value_factory_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/interop/utils/utils.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/transaction_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/utils/codec_utility.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/utils/decode_utility.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/utils/encode_utility.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/write_batch_web.dart
Separated the encoding and decoding because I wanted to import classes from different files with name clashes. The relevant fix is [here](https://github.com/FirebaseExtended/flutterfire/pull/6728/files#diff-ad2e8b21ea951364151827b99cea0ce04dbf437c8f696f418e9b6d6bf916970dR33) which allows for checking if the value is a `GeoPoint` class.  
fixes https://github.com/FirebaseExtended/flutterfire/issues/3865 …
=> fix(firestore, web): blob was being parsed as geopoint.

packages/cloud_firestore/cloud_firestore/lib/src/query.dart, packages/cloud_firestore/cloud_firestore/test/query_test.dart
Fix where filter query assertion.
fixes #6548
=> fix(firestore): improve query filter assertions

packages/firebase_database/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/MethodCallHandlerImpl.java, packages/firebase_database/firebase_database/example/test_driver/firebase_database_e2e.dart, packages/firebase_database/firebase_database/ios/Classes/FLTFirebaseDatabasePlugin.m, packages/firebase_database/firebase_database/lib/src/firebase_database.dart
Allow diagnostic logging for debugging purposes.
closes https://github.com/FirebaseExtended/flutterfire/issues/6458
[CLA]: …
=> feat(database): allow diagnostic logging for android/ios

packages/firebase_dynamic_links/README.md
=> docs(dynamic_links): fix readme example

packages/firebase_auth/firebase_auth/example/pubspec.yaml, packages/firebase_crashlytics/firebase_crashlytics/example/pubspec.yaml, packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart, packages/firebase_ml_vision/example/lib/material_barcode_scanner.dart, packages/firebase_ml_vision/example/pubspec.yaml, packages/firebase_ml_vision/example/test_driver/firebase_ml_vision.dart, packages/firebase_performance/firebase_performance/example/pubspec.yaml, packages/firebase_storage/firebase_storage/example/pubspec.yaml, packages/firebase_storage/firebase_storage_platform_interface/lib/src/method_channel/method_channel_firebase_storage.dart
Fixed various warnings that appears on the Flutter master channel
=> chore: fix various warnings

packages/firebase_remote_config/firebase_remote_config/ios/Classes/FLTFirebaseRemoteConfigUtils.m
Propagates the underlying error up to flutter
None
=> fix(remote_config): propagate error message

packages/firebase_app_check/firebase_app_check/CHANGELOG.md
As you can see in the screenshot is the change log a little bit buggy. I think this is because version `0.0.1` is using another markdown headline level as the other versions.
... …
=> docs(firebase_app_check): using for version `0.0.1` the same markdown headline level as the other versions have in the changelog

packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundService.java, packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/JobIntentService.java
Switched out android's `JobIntentService` for custom implementation as used by [OneSignal](https://github.com/OneSignal/OneSignal-Android-SDK/blob/main/OneSignalSDK/onesignal/src/main/java/com/onesignal/JobIntentService.java).
fixes https://github.com/FirebaseExtended/flutterfire/issues/4718 …
=> fix(messaging, android): allow messages when device is in idle mode

packages/firebase_storage/firebase_storage/example/test_driver/instance_e2e.dart, packages/firebase_storage/firebase_storage/lib/src/utils.dart, packages/firebase_storage/firebase_storage/test/utils_test.dart
In line with Firebase Storage http logic on `firebase-js-sdk`.
fixes https://github.com/FirebaseExtended/flutterfire/issues/6773
[CLA]: …
=> fix(storage): accept google storage bucket urls

docs/auth/usage.mdx
I think "Open link in app" in "Verifying a users email" section's example code is something wrong.
Isn't it the latest example code? …
=> docs(auth): update "ActionCodeSettings" example code

packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
Reverts FirebaseExtended/flutterfire#6838
From additional testing, fixes the duplication issue but causes another issue where apple throttle willPresentNotification with the presence of mutableContent in the payload
I will be pursuing other solutions as the duplicate notification bug causes a big issue in apps
=> fix(messaging, iOS): revert onMessage event handler commit which causes another bug

packages/firebase_database/firebase_database/example/test_driver/firebase_database_e2e.dart, packages/firebase_database/firebase_database/example/test_driver/query_e2e.dart
*This PR refactors the integration tests by creating a separate class query_e2e.dart. Also added some new query tests.*
- Yes, this is a breaking change.
=> test(firebase_database): refactored and added some query integration tests

packages/firebase_performance/firebase_performance/README.md, packages/firebase_performance/firebase_performance/pubspec.yaml, packages/firebase_performance/firebase_performance_platform_interface/CHANGELOG.md, packages/firebase_performance/firebase_performance_platform_interface/lib/src/platform_interface/platform_interface_firebase_performance.dart, packages/firebase_performance/firebase_performance_platform_interface/pubspec.yaml
`PlatformInterface.verifyToken` function incorrectly throws error "'Platform interfaces must not be implemented with `implements`'"  for the web plugin (in the coming PR), which is due to the wrong token field declarations. The fix here is based on what [cloud function does](https://github.com/FirebaseExtended/flutterfire/blob/2287ba083e8b4b7e3ac0f99e4534684978b7eb8b/packages/cloud_functions/cloud_functions_platform_interface/lib/src/platform_interface/platform_interface_firebase_functions.dart#L52). 
No related issues. No user facing issues. This issue is just present in web plugin (in the coming PR), which needs to be fixed before that PR.
This will ensure a smooth …
=> fix(firebase_performance): fix the token verification

docs/firestore/usage.mdx
Corrected typographical error "cause" -> "case"
=> fix: Update firestore documentation usage.mdx

packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_tests/method_channel_firebase_auth_test.dart
This prepares for landing https://dart-review.googlesource.com/c/sdk/+/190360 into the analyzer.
=> test(auth): Fix pre-existing HintCode.UNNECESSARY_TYPE_CHECK_TRUE

packages/firebase_crashlytics/firebase_crashlytics/example/lib/main.dart
move into `runZonedGuard` function.
closes https://github.com/FirebaseExtended/flutterfire/issues/6772
=> chore(crashlytics): update example

packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
No settings getter on Firestore web was breaking with this error:
```
Error: UnimplementedError: settings getter is not implemented at Object.throw_ [as throw] (http://localhost:7357/dart_sdk.js:5348:11) at cloud_firestore_web.FirebaseFirestoreWeb.new.get settings (http://localhost:7357/packages/cloud_firestore_platform_interface/src/platform_interface/utils/load_bundle_task_state.dart.lib.js:2146:17) at cloud_firestore_web.FirebaseFirestoreWeb.new.get settings [as settings]
```
because the universal Firestore instance is expecting to call the settings getter on the Firestore web delegate [here](packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart).
fixes https://github.com/FirebaseExtended/flutterfire/issues/6781 …
=> fix(firestore, web): implement missing getter for settings on Firestore web

.github/workflows/all_plugins.yaml, packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart, packages/firebase_database/firebase_database/example/macos/.gitignore, packages/firebase_database/firebase_database/example/pubspec.yaml, packages/firebase_performance/firebase_performance/example/pubspec.yaml, packages/firebase_performance/firebase_performance_web/lib/firebase_performance_web.dart, packages/firebase_performance/firebase_performance_web/test/firebase_performance_web_test.dart, packages/firebase_remote_config/firebase_remote_config/example/macos/.gitignore, packages/firebase_storage/firebase_storage_platform_interface/lib/src/method_channel/method_channel_firebase_storage.dart
=> chore: fix analyze issues

packages/cloud_functions/cloud_functions/android/src/main/java/io/flutter/plugins/firebase/functions/FlutterFirebaseFunctionsPlugin.java
Adding Android V2 embedding to Firebase Functions plugin.
fixes #6770
=> fix(firebase_functions): android V2 embedding

docs/auth/social.mdx
This PRs updates the example and uses better-supported [twitter_login]((https://pub.dev/packages/twitter_login)) plugin
closes https://github.com/FirebaseExtended/flutterfire/issues/6860 …
=> docs(firebase_auth): fix twitter sign in docs

README.md, docs/performance/overview.mdx, website/plugins.js
We recently added web support to the Firebase Performance Monitoring plugin ([PR](https://github.com/FirebaseExtended/flutterfire/pull/6920)). This PR adds announcement and related instructions. …
=> docs(performance): add web support announcement and instructions.

packages/firebase_database/firebase_database/README.md, packages/firebase_database/firebase_database/example/ios/Runner/GoogleService-Info.plist, packages/firebase_database/firebase_database/example/lib/main.dart, packages/firebase_database/firebase_database/example/macos/Runner.xcodeproj/project.pbxproj, packages/firebase_database/firebase_database/example/macos/Runner/GoogleService-Info.plist, packages/firebase_database/firebase_database/example/test_driver/firebase_database_e2e.dart, packages/firebase_database/firebase_database/example/test_driver/query_e2e.dart, packages/firebase_database/firebase_database/lib/src/database_reference.dart, packages/firebase_database/firebase_database/lib/src/firebase_database.dart, packages/firebase_database/firebase_database/lib/src/on_disconnect.dart, packages/firebase_database/firebase_database/lib/src/query.dart, packages/firebase_database/firebase_database_platform_interface/lib/firebase_database_platform_interface.dart, packages/firebase_database/firebase_database_platform_interface/lib/src/method_channel/method_channel_database.dart, packages/firebase_database/firebase_database_platform_interface/lib/src/method_channel/method_channel_database_reference.dart, packages/firebase_database/firebase_database_platform_interface/lib/src/method_channel/method_channel_on_disconnect.dart, packages/firebase_database/firebase_database_platform_interface/lib/src/method_channel/method_channel_query.dart, packages/firebase_database/firebase_database_platform_interface/lib/src/platform_interface/database_reference.dart, packages/firebase_database/firebase_database_platform_interface/lib/src/platform_interface/on_disconnect.dart, packages/firebase_database/firebase_database_platform_interface/lib/src/platform_interface/query.dart, packages/firebase_database/firebase_database_platform_interface/test/firebase_database_test.dart, packages/firebase_database/firebase_database_web/lib/firebase_database_web.dart, packages/firebase_database/firebase_database_web/lib/src/database_reference_web.dart, packages/firebase_database/firebase_database_web/lib/src/interop/database.dart, packages/firebase_database/firebase_database_web/lib/src/ondisconnect_web.dart, packages/firebase_database/firebase_database_web/lib/src/query_web.dart
none
- Yes, this is a breaking change.
=> refactor(database): rename reference() to ref([String? path])

packages/firebase_auth/firebase_auth/android/build.gradle, packages/firebase_auth/firebase_auth/example/android/build.gradle, packages/firebase_auth/firebase_auth/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_auth/firebase_auth/example/ios/Flutter/AppFrameworkInfo.plist, packages/firebase_auth/firebase_auth/example/ios/Runner.xcodeproj/project.pbxproj, packages/firebase_auth/firebase_auth/example/lib/signin_page.dart, packages/firebase_auth/firebase_auth/example/pubspec.yaml
Temporary fix for passing CI on auth package.
none.
=> chore: remove google-signin plugin temporarily to fix CI

packages/firebase_analytics/firebase_analytics/example/android/build.gradle, packages/firebase_analytics/firebase_analytics/example/android/gradle/wrapper/gradle-wrapper.properties
=> chore: update gradle for analytics example app

packages/cloud_firestore/cloud_firestore/example/android/build.gradle, packages/cloud_firestore/cloud_firestore/example/android/gradle/wrapper/gradle-wrapper.properties, packages/cloud_functions/cloud_functions/example/android/build.gradle, packages/cloud_functions/cloud_functions/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_app_check/firebase_app_check/example/android/build.gradle, packages/firebase_core/firebase_core/example/android/build.gradle, packages/firebase_core/firebase_core/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_crashlytics/firebase_crashlytics/example/android/build.gradle, packages/firebase_crashlytics/firebase_crashlytics/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_database/firebase_database/example/android/build.gradle, packages/firebase_database/firebase_database/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_dynamic_links/example/android/app/gradle/wrapper/gradle-wrapper.properties, packages/firebase_dynamic_links/example/android/build.gradle, packages/firebase_dynamic_links/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_in_app_messaging/example/android/build.gradle, packages/firebase_in_app_messaging/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_messaging/firebase_messaging/example/android/build.gradle, packages/firebase_messaging/firebase_messaging/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_ml_custom/example/android/build.gradle, packages/firebase_ml_custom/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_performance/firebase_performance/example/android/build.gradle, packages/firebase_performance/firebase_performance/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_remote_config/firebase_remote_config/example/android/build.gradle, packages/firebase_remote_config/firebase_remote_config/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_storage/firebase_storage/example/android/build.gradle, packages/firebase_storage/firebase_storage/example/android/gradle/wrapper/gradle-wrapper.properties
Update all example app build gradle versions.
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTIN …
=> chore: update gradle version across packages

docs/messaging/notifications.mdx
=> docs(firebase_messaging):  RemoteMessage? returned from getInitialMessage is nullable

docs/installation/web.mdx
the generated `index.html` from `flutter create` no longer includes a script tag for `main.dart.js`; it's dynamically generated as part of the service worker code instead.
This will ensure a smooth and …
=> docs: remove `main.dart.js` script from `index.html` for web setup.

melos.yaml
Updated the description for macOS since desktop is now on stable.
=> docs: update melos example macos description

docs/messaging/overview.mdx
=> docs(firebase_messaging): update import to "firebase_messaging"

packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart, packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart, packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart, packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart
Allow setLanguage to accept `null` as a value as per documentation.
=> fix(firebase_auth): allow setLanguage to accept null

docs/auth/usage.mdx
- [*] I read the [Contributor Guide] and followed the process outlined there for …
=> fix(typo): unterminated string

packages/firebase_auth/firebase_auth/example/lib/main.dart, packages/firebase_auth/firebase_auth/example/lib/register_page.dart, packages/firebase_auth/firebase_auth/example/lib/signin_page.dart, packages/firebase_auth/firebase_auth/example/pubspec.yaml, packages/firebase_auth/firebase_auth/example/test_driver/firebase_auth_e2e.dart, packages/firebase_auth/firebase_auth/example/test_driver/firebase_auth_e2e_test.dart, packages/firebase_auth/firebase_auth/example/test_driver/instance_e2e.dart, packages/firebase_auth/firebase_auth/example/test_driver/test_utils.dart, packages/firebase_auth/firebase_auth/example/test_driver/user_e2e.dart
Migrates the example app & its tests to null-safety.
=> refactor(firebase_auth): migrate example app to null-safety

docs/overview.mdx, packages/firebase_analytics/firebase_analytics/ios/Classes/FLTFirebaseAnalyticsPlugin.m, packages/firebase_core/firebase_core/android/gradle.properties, packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
Bump iOS SDK versions. 
Merge this PR in first to fix iOS CI failure: https://github.com/FirebaseExtended/flutterfire/pull/7295 …
=> feat: bump Firebase iOS SDK to `8.9.0`

packages/firebase_crashlytics/firebase_crashlytics/android/build.gradle, packages/firebase_crashlytics/firebase_crashlytics/example/android/app/build.gradle
=> chore: update Crashlytics example app Android `minSdkVersion 19` as it uses Analytics plugin with `minSdkVersion 19`

packages/cloud_firestore/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/streamhandler/TransactionStreamHandler.java
=> fix(cloud_firestore): suppress Java unchecked cast lint warning in Android plugin

docs/crashlytics/usage.mdx
* Fix spelling of Crashlytics: from Crashytlics to Crashlytics
* None
=> docs(firebase_crashlytics): Fix Crashlytics typo

packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
Bump to fix an RTDB issue highlighted in #7202
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTI …
=> feat(web): bump Firebase JS SDK to `8.10.0`

packages/firebase_messaging/firebase_messaging_platform_interface/test/notification_test.dart
I felt bad for not having tests added when https://github.com/FirebaseExtended/flutterfire/pull/7430 was merged. That's being made up for.
Please also take note of [this comment](https://github.com/FirebaseExtended/flutterfire/pull/7430#issuecomment-984792041). …
=> test(firebase_messaging): add tests for #7430

docs/ml-model-downloader/overview.mdx, docs/sidebars.js, website/plugins.js
Docs updates to `firebase_ml_model_downloader`:
3. Add command-line installation. …
=> docs(firebase_ml_model_downloader): remove legacy instructions

docs/app-check/overview.mdx
=> docs(app-check): remove legacy instructions

docs/database/overview.mdx, docs/database/usage.mdx, docs/sidebars.js
=> docs(rtdb): update documentation for dev release

docs/performance/overview.mdx, docs/performance/usage.mdx
=> docs(firebase_performance): update overview.mdx & incorrect type

docs/ui/widgets.mdx, packages/firebase_auth/firebase_auth/example/test_driver/instance_e2e.dart, packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart, packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart, packages/firebase_remote_config/firebase_remote_config/pubspec.yaml, packages/flutterfire_ui/example/lib/main.dart, packages/flutterfire_ui/example/lib/stories/screens/email_link_sign_in_screen.dart, packages/flutterfire_ui/example/lib/stories/screens/forgot_password_screen.dart, packages/flutterfire_ui/example/lib/stories/screens/phone_input_screen.dart, packages/flutterfire_ui/example/lib/stories/screens/sms_code_input_screen.dart, packages/flutterfire_ui/example/test_driver/utils.dart, packages/flutterfire_ui/lib/src/auth/configs/email_link_provider_configuration.dart, packages/flutterfire_ui/lib/src/auth/flows/email_link_flow.dart, packages/flutterfire_ui/lib/src/auth/oauth/provider_resolvers.dart, packages/flutterfire_ui/lib/src/auth/oauth/providers/facebook_provider.dart, packages/flutterfire_ui/lib/src/auth/oauth/providers/google_provider.dart, packages/flutterfire_ui/lib/src/auth/oauth/providers/twitter_provider.dart, packages/flutterfire_ui/lib/src/auth/screens/phone_input_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/profile_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/register_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/sign_in_screen.dart, packages/flutterfire_ui/lib/src/auth/views/email_link_sign_in_view.dart, packages/flutterfire_ui/lib/src/auth/widgets/apple_sign_in_button.dart, packages/flutterfire_ui/lib/src/auth/widgets/different_method_sign_in_dialog.dart, packages/flutterfire_ui/lib/src/auth/widgets/email_form.dart, packages/flutterfire_ui/lib/src/auth/widgets/email_link_sign_in_button.dart, packages/flutterfire_ui/lib/src/auth/widgets/email_sign_up_dialog.dart, packages/flutterfire_ui/lib/src/auth/widgets/phone_verification_button.dart, website/src/theme/MDXComponents/index.tsx
=> docs: Fix typos and remove unused imports

packages/firebase_database/firebase_database/lib/src/query.dart, packages/firebase_database/firebase_database_platform_interface/lib/src/query_modifiers.dart, packages/firebase_database/firebase_database_platform_interface/test/query_modifiers_test.dart
=> fix: add missing `path` getter for Query (fixes #7495)

packages/firebase_database/firebase_database/lib/src/firebase_database.dart
=> docs: update documentation of `setPersistenceEnabled` to reflect updated return type (fixes #7496)

docs/auth/overview.mdx
Removing a duplicate section in Firebase Auth overview.
=> docs(firebase_auth): remove redundant section

docs/ui/database.mdx, docs/ui/firestore.mdx, packages/flutterfire_ui/example/lib/stories.dart, packages/flutterfire_ui/example/lib/stories/widgets/firebase_database_list_view.dart, packages/flutterfire_ui/example/lib/stories/widgets/firebase_table.dart, packages/flutterfire_ui/example/pubspec.yaml, packages/flutterfire_ui/example/test_driver/firestore_query_builder_test.dart, packages/flutterfire_ui/example/test_driver/utils.dart, packages/flutterfire_ui/lib/database.dart, packages/flutterfire_ui/lib/firestore.dart, packages/flutterfire_ui/lib/src/firebase_database/query_builder.dart, packages/flutterfire_ui/lib/src/firebase_database/table_builder.dart, packages/flutterfire_ui/lib/src/firestore/query_builder.dart, packages/flutterfire_ui/lib/src/firestore/table_builder.dart
=> fix!: rename `QueryBuilderSnapshot` ->  `FirebaseQueryBuilderSnapshot` plus internal improvements and additional documentation

docs/analytics/usage.mdx, packages/firebase_analytics/firebase_analytics/example/lib/main.dart, packages/firebase_analytics/firebase_analytics_web/lib/interop/analytics.dart, packages/firebase_analytics/firebase_analytics_web/lib/interop/analytics_interop.dart
Parameters need to be jsify'd otherwise they are not sent with event
Google Analytics debugger console output for example `logEvent` once parameters are  jsify'd:
fixes https://github.com/FirebaseExtended/flutterfire/issues/7444 …
=> fix(analytics): use `jsify()` with event parameters for `logEvent()` so they are sent 

melos.yaml, packages/firebase_database/firebase_database/example/test_driver/database_e2e.dart, packages/firebase_database/firebase_database_platform_interface/lib/src/method_channel/method_channel_query.dart, packages/firebase_database/firebase_database_web/lib/src/query_web.dart, packages/flutterfire_ui/test/firebase_ui_test.dart
=> fix: database path should default to `/` if no path specified rather than an empty string (fixes #7515)

docs/ui/auth.mdx
Links on https://firebase.flutter.dev/docs/ui/auth/ seem to be broken! 
=> docs(ui): links to child pages

packages/firebase_analytics/firebase_analytics/example/lib/main.dart
=> chore: update `logLogin` `loginMethod` value in example app

docs/ui/auth/navigation.mdx
Updates the name to the one that actually exists
Closes #7547
=> docs(ui): fix action name

packages/firebase_crashlytics/firebase_crashlytics/android/src/main/res/values/values.xml
=> fix: set build id as not required, to allow Dart default app initialization

packages/cloud_firestore/cloud_firestore/pubspec.yaml, packages/cloud_firestore_odm/cloud_firestore_odm/pubspec.yaml, packages/cloud_functions/cloud_functions/pubspec.yaml, packages/firebase_app_check/firebase_app_check/pubspec.yaml, packages/firebase_app_installations/firebase_app_installations/pubspec.yaml, packages/firebase_auth/firebase_auth/pubspec.yaml, packages/firebase_core/firebase_core/pubspec.yaml, packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart, packages/firebase_core/firebase_core_platform_interface/pubspec.yaml, packages/firebase_crashlytics/firebase_crashlytics/pubspec.yaml, packages/firebase_dynamic_links/firebase_dynamic_links/pubspec.yaml, packages/firebase_in_app_messaging/firebase_in_app_messaging/pubspec.yaml, packages/firebase_messaging/firebase_messaging/pubspec.yaml, packages/firebase_ml_model_downloader/firebase_ml_model_downloader/pubspec.yaml, packages/firebase_performance/firebase_performance/pubspec.yaml, packages/firebase_remote_config/firebase_remote_config/pubspec.yaml, packages/firebase_storage/firebase_storage/pubspec.yaml
Update `pubspec.yaml` files so false secrets are ignored. …
=> chore: exclude example apps in `pubspec.yaml` `false_secrets` options

packages/firebase_database/firebase_database/lib/src/firebase_database.dart, packages/firebase_database/firebase_database/test/instance_test.dart, packages/firebase_database/firebase_database/test/mock.dart
See title.
fixes https://github.com/FirebaseExtended/flutterfire/issues/7536
=> fix(firebase_database): remove trailing `/` from `databaseUrl` if present.

packages/flutterfire_ui/lib/src/auth/widgets/different_method_sign_in_dialog.dart, packages/flutterfire_ui/lib/src/i10n/default_localizations.dart, packages/flutterfire_ui/lib/src/i10n/lang/en.dart
=> fix(flutterfire_ui): fix various typos in i10n text

packages/flutterfire_ui/example/lib/io_init.dart, packages/flutterfire_ui/example/macos/Runner.xcodeproj/project.pbxproj, packages/flutterfire_ui/lib/src/auth/screens/internal/login_screen.dart, packages/flutterfire_ui/lib/src/auth/widgets/email_form.dart
This PR adds missing `auth` property to `LoginView` and `AuthFlowBuilder` in `EmailForm`
Closes #7615
=> fix(ui): pass auth down to LoginView

docs/messaging/usage.mdx
Update index.html example in Background web setup section from `firebase_messaging` package.
closes #7305
=> docs(firebase_messaging): update index.html example of web background setup

docs/auth/usage.mdx
Simplify sentence to remove confusing/unneeded duplicate use of "user"
Does your PR …
=> docs(firebase_auth): Reword confusing documentation.

website/src/styles.scss
=> docs: update alert bg & text colors for readability

docs/ui/auth/configuring-providers.mdx, docs/ui/auth/integrating-your-first-screen.mdx
=> docs(ui): fix `AppleProviderConfiguration` and `TwitterProviderConfiguration` props

docs/versions.js, packages/firebase_messaging/firebase_messaging/example/web/firebase-messaging-sw.js
=> chore(firebase_messaging): Update `firebase-js-sdk` version in example to `8.10.0`.

packages/firebase_messaging/firebase_messaging/example/web/index.html
see title.
fixes https://github.com/FirebaseExtended/flutterfire/issues/7669
=> chore(messaging): Add service worker script back to Firebase Messaging example.

docs/functions/usage.mdx
Added description of how to use endpoint calling with parameters and event-based cloud functions.
With that addition, the current possibilities of cloud functions in combination with flutter are completed.
This would have saved me a lot of time if it were present before.
- …
=> docs(functions): document calling functions with parameters 

packages/firebase_dynamic_links/firebase_dynamic_links_platform_interface/lib/src/pending_dynamic_link_data.dart
=> fix(dynamic_links): PendingDynamicLinkData.asString() prints out instance type with mapped values.

docs/performance/usage.mdx
see title.
https://github.com/FirebaseExtended/flutterfire/issues/5888
=> docs(performance): Caution users that automatic screen rendering traces are not possible at the moment.

packages/flutterfire_ui/lib/auth.dart, packages/flutterfire_ui/lib/src/auth/screens/sign_in_screen.dart
=> fix(ui): export DifferentSignInMethodsFound auth state and make sure to add it to the list of provided actions

docs/firestore/overview.mdx, docs/manual-installation.mdx, packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
See title
fixes https://github.com/FirebaseExtended/flutterfire/issues/7766
=> feat: bump Firebase iOS SDK version to `8.10.0`.

docs/auth/usage.mdx
See title.
fixes https://github.com/FirebaseExtended/flutterfire/issues/5530
=> docs(firebase_auth): add note about Dynamic Links setup requirement for passwordless authentication.

docs/overview.mdx
=> docs: fix manual installation link

docs/ui/auth/building-a-custom-ui.mdx, docs/ui/auth/integrating-your-first-screen.mdx, docs/ui/auth/navigation.mdx, docs/ui/database.mdx, docs/ui/firestore.mdx
Fixed a couple of typos and grammar mistakes
=> docs(ui): fix typos and grammar mistakes

packages/cloud_functions/cloud_functions/android/build.gradle, packages/firebase_analytics/firebase_analytics/android/build.gradle, packages/firebase_app_check/firebase_app_check/android/build.gradle, packages/firebase_app_installations/firebase_app_installations/android/build.gradle, packages/firebase_auth/firebase_auth/android/build.gradle, packages/firebase_core/firebase_core/android/build.gradle, packages/firebase_crashlytics/firebase_crashlytics/android/build.gradle, packages/firebase_database/firebase_database/android/build.gradle, packages/firebase_in_app_messaging/firebase_in_app_messaging/android/build.gradle, packages/firebase_messaging/firebase_messaging/android/build.gradle, packages/firebase_performance/firebase_performance/android/build.gradle, packages/firebase_remote_config/firebase_remote_config/android/build.gradle, packages/firebase_storage/firebase_storage/android/build.gradle
Hi all,
[Currently Android code latest stable version is 1.7.0](https://developer.android.com/jetpack/androidx/releases/core)
This PR is to support Android core 1.7.0 due to the opened issue:  
[[firebase_core][firebase_analytics][firebase_crashlytics] Build APK failed:verifyReleaseResources'. in Android core 1.7.0 and compileVersion 31 #7723
](https://github.com/FirebaseExtended/flutterfire/issues/7723)
By upgrading `compileSDKVersion` to 31 solve the issue since the issue:
[AAPT: error: resource android:attr/lStar not found.](https://stackoverflow.com/questions/69041630/android-build-error-lstar-not-found)
**lStar which is a system attribute that's new as of API level 31**
This is why causing the error and failed to compile and build APK
*Replace this paragraph with a list of issues …
=> fix(*): bump Android `compileSdkVersion` to 31

docs/dynamic-links/apple-integration.mdx
See title.
fixes https://github.com/FirebaseExtended/flutterfire/issues/7686
=> docs(dynamic_links): Make note in documentation that Apple platform requires manual installation for Dynamic Links to function.

docs/firestore/usage.mdx
Add FlutterFire's Distributed Counters snippets.
closes #7845
=> docs(firestore): add Distributed Counters snippets

docs/firestore-odm/defining-models.mdx, packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/model.dart, packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/model.g.dart, packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/simple.dart, packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/simple.g.dart, packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/collection_generator.dart
=> feat: Added error handling for when the Firestore reference and the Model class are defined in two separate files.

docs/app-check/usage.mdx
Added instructions how to use App Check for Functions with Firebase Local Emulator Suite. …
=> docs(firebase_app_check): Demonstrate how to use App Check with Cloud Functions including with the Firebase Emulator.

docs/crashlytics/usage.mdx
Updated the crashlytcis docs to describe how to reset the user id. I found the solution itself in the [android-sdk issues](https://github.com/firebase/firebase-android-sdk/issues/1512) and it also mentioned in the [firbase doc](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#set-user-ids)
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONT …
=> docs(crashlytics): Add a description for reseting a user ID when using `setUserIdentifier()` API.

docs/firestore-odm/defining-models.mdx
Code generated by `cloud_firestore_odm_generator` has a private `_$assertUser` but the code used in the model class for validation uses `$assertUser`. 
```dart
@JsonSerializable()
class User {
User({
required this.age,
}) {
// Apply the validator
$assertUser(this); // Error in this line 
}
@Min(0)
final int age;
}
```
```dart
@JsonSerializable()
class User {
User({
required this.age,
}) {
// Apply the validator
_$assertUser(this); // No error
}
@Min(0)
final int age;
}
``` …
=> fix: [cloud_firestore_odm] Changed `assertUser` scope to private.

docs/installations/usage.mdx
=> docs(firebase_app_installations): Update usage.mdx to use correct implementation of `FirebaseInstallations` class.

docs/cli.mdx
…ude all supported platforms
Does your PR require plugin users to manually update their …
=> docs: modified note about Google auth manual installation

packages/flutterfire_ui/lib/src/auth/widgets/email_form.dart, packages/flutterfire_ui/lib/src/auth/widgets/email_input.dart, packages/flutterfire_ui/lib/src/auth/widgets/internal/universal_text_form_field.dart, packages/flutterfire_ui/lib/src/auth/widgets/password_input.dart, packages/flutterfire_ui/lib/src/auth/widgets/phone_input.dart, packages/flutterfire_ui/lib/src/auth/widgets/sms_code_input.dart
This PR adds autofill hints to the email / password and OTP fields. …
=> feat(flutterfire_ui): add autofillhints

packages/flutterfire_ui/assets/countries.json
=> chore(ui): add Estonia code to countries list

packages/flutterfire_ui/example/lib/stories/screens/sign_in_screen.dart
Small typo fix
Simply fixing a one-word typo
N/A
[CLA]: …
=> chore(flutterfire_ui): Fix a typo in the word "Screen" in storybook example.

packages/firebase_storage/firebase_storage_platform_interface/lib/src/settable_metadata.dart
There is no such thing as `Cache-Disposition`. I also added links for all headers.
=> docs(firebase_storage): Correct metadata docs

packages/cloud_functions/cloud_functions/android/src/main/java/io/flutter/plugins/firebase/functions/FlutterFirebaseFunctionsPlugin.java
See title.
fixes https://github.com/FirebaseExtended/flutterfire/issues/7446
=> fix(functions): Remove deprecated Android API and update with the latest: `useEmulator()`.

packages/cloud_firestore/cloud_firestore/example/test_driver/transaction_e2e.dart, packages/firebase_auth/firebase_auth/example/test_driver/instance_e2e.dart, packages/firebase_auth/firebase_auth/example/test_driver/user_e2e.dart, packages/flutterfire_ui/lib/src/auth/actions.dart, packages/flutterfire_ui/lib/src/auth/screens/profile_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/universal_email_sign_in_screen.dart, packages/flutterfire_ui/lib/src/auth/widgets/email_sign_up_dialog.dart, packages/flutterfire_ui/lib/src/auth/widgets/phone_input.dart
This PR fixes analyzer errors on latest stable flutter
* `package:pedantic` was discontinued
* new lint rule: `body_might_complete_normally_nullable`
[CLA]: …
=> chore: fix analyzer errors on latest stable flutter

packages/flutterfire_ui/example/android/app/build.gradle, packages/flutterfire_ui/example/pubspec.yaml, packages/flutterfire_ui/pubspec.yaml
package version bump
Closes #7881
=> fix(ui): bump flutter_facebook_auth version

packages/flutterfire_ui/lib/src/auth/oauth/providers/google_provider.dart
See the issue for more details
Closes #7980
=> fix(ui): prompt user to select google account on web

docs/ui/auth/integrating-your-first-screen.mdx
add `initialData: FirebaseAuth.instance.currentUser` in  SignInScreen to avoid get `null`  in authStateChanges() even with user is signed in.
This will ensure a smooth and quick review process. …
=> docs(flutterfire_ui): Update documentation to use `currentUser` as `initialData` property when using `StreamBuilder`.

docs/firestore/overview.mdx
=> docs(cloud_firestore): Update `iOS` version in documentation from `8.10.0` to `8.11.0`.

docs/firestore-odm/overview.mdx
First contribution ever
[📚] Add what "ODM" stands for #7780
Add a paragraph for what ODM stands for in [here](https://firebase.flutter.dev/docs/firestore-odm/overview/)
Closes https://github.com/FirebaseExtended/flutterfire/issues/7780 …
=> docs(cloud_firestore_odm): Update documentation with a brief outline of what an "odm" does.

docs/remote-config/usage.mdx
Replaced all deprecated methods in the usage.mdx :
- RemoteConfig with FirebaseRemoteConfig 
- remoteConfig with firebaseRemoteConfig
There are no related issues
- [ x] I updated/added relevant documentation (doc comments with `///`).
- [ x] I signed the [CLA].
- [x ] I am willing to follow-up on review comments in a timely manner.
- [ x] No, this is *not* a breaking …
=> docs(firebase_remote_config): Update `firebase_remote_config` "usage.mdx" with updated plugin API naming: `FirebaseRemoteConfig`.

docs/firestore-odm/references.mdx
``AsyncSnapshot.data()`` is not a function. The property should be accessed via ``AsyncSnapshot.data``.
This PR fixes this inconsistency in the [Reading Document](https://firebase.flutter.dev/docs/firestore-odm/references#reading-documents) section of the Firestore ODM docs. …
=> docs(cloud_firestore_odm): Fix code snippet as `snapshot.data` is not a function.

docs/database/start.mdx
=> docs(firebase_database): Fix broken links to official Firebase documentation.

packages/firebase_performance/firebase_performance/android/src/main/java/io/flutter/plugins/firebase/performance/FlutterHttpMetric.java
=> fix(firebase_performance): Fix firebase_performance not recording response payload size on Android.

packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
There is a security vulnerability in version `8.10.0`: https://nvd.nist.gov/vuln/detail/CVE-2022-0235
There is a security patch from Firebase in web SDK version `8.10.1` that fixes this vulnerability. …
=> feat: Bump Firebase Web SDK version to 8.10.1 (CVE-2022-0235) for security patch purposes.

melos.yaml
=> chore: Update to "melos.yaml" to include script for running web e2e tests locally.

docs/cli.mdx, packages/firebase_core/firebase_core_platform_interface/lib/src/method_channel/method_channel_firebase.dart
See title.
fixes https://github.com/FirebaseExtended/flutterfire/issues/8119
=> docs(firebase_core): update docs about native SDK warnings

AUTHORS, packages/flutterfire_ui/lib/src/i10n/default_localizations.dart, packages/flutterfire_ui/lib/src/i10n/lang/de.dart
Added German localization support of flutterfire_ui.
=> feat(flutterfire_ui): Add German localization language support

packages/firebase_dynamic_links/firebase_dynamic_links/ios/Classes/FLTFirebaseDynamicLinksPlugin.m, packages/firebase_dynamic_links/firebase_dynamic_links_platform_interface/lib/src/method_channel/method_channel_firebase_dynamic_links.dart, packages/firebase_dynamic_links/firebase_dynamic_links_platform_interface/lib/src/pending_dynamic_link_data.dart
See title.
fixes https://github.com/FirebaseExtended/flutterfire/issues/8217
=> fix(firebase_dynamic_links): pass through `utmParameters` on `iOS` and make property on `PendingDynamicLinkData`.

packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
=> fix(firebase_messaging): Update notification key to `NSApplicationLaunchUserNotificationKey` for macOS.

docs/auth/social.mdx
The docs were pointing to an older version of the [github_sign_in}(https://pub.dev/packages/github_sign_in) package. I have updated it to a null safety version.
=> docs(firebase_auth): Update `github_sign_in` dependency in  "auth/social.mdx" documentation.

packages/firebase_dynamic_links/firebase_dynamic_links_platform_interface/lib/src/pending_dynamic_link_data.dart, packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
=> chore: Format 2 different files correctly.

tests/test_driver/cloud_functions/cloud_functions_e2e.dart
=> chore: format "/test_driver/cloud_functions/cloud_functions_e2e.dart " file.

docs/messaging/usage.mdx
Fixed broken link on use of properties of official Firebase documentation. 
The current link results in a 404 on Firebase's official website …
=> docs(firebase_messaging): Fix broken link to Firebase `TokenMessage` documentation.

docs/messaging/server-integration.mdx
This PR updates the sample code for getting and saving FCM device token in the [Saving Tokens section](https://firebase.flutter.dev/docs/messaging/server-integration#saving-tokens), Cloud Messaging - Server Integration.
Fixes #8239  …
=> docs(firebase_messaging): Update sample code in Cloud Messaging - Server Integration.

docs/app-check/custom-resource.mdx, docs/app-check/debug-provider.mdx, docs/app-check/default-providers.mdx, docs/app-check/overview.mdx, docs/sidebars.js
Add App Check material from f.g.c …
=> docs(firebase_appcheck): Add material from official docs

packages/flutterfire_ui/lib/src/auth/oauth/oauth_providers.dart, packages/flutterfire_ui/lib/src/auth/oauth/providers/apple_provider.dart, packages/flutterfire_ui/lib/src/auth/oauth/providers/facebook_provider.dart, packages/flutterfire_ui/lib/src/auth/oauth/providers/google_provider.dart, packages/flutterfire_ui/lib/src/auth/oauth/providers/sign_out_mixin.dart, packages/flutterfire_ui/lib/src/auth/oauth/providers/sign_out_mixin_web.dart, packages/flutterfire_ui/lib/src/auth/oauth/providers/twitter_provider.dart
Sign out wasn't working properly on desktop and web (introduced in #8120)
#8246
=> fix(ui): fix sign out issue on desktop and web

packages/flutterfire_ui/lib/src/auth/widgets/editable_user_display_name.dart
=> fix(ui): Avoid layout jumps when editing user name.

packages/flutterfire_ui/lib/src/auth/widgets/delete_account_button.dart, packages/flutterfire_ui/lib/src/auth/widgets/internal/loading_button.dart, packages/flutterfire_ui/lib/src/auth/widgets/internal/platform_widget.dart, packages/flutterfire_ui/lib/src/auth/widgets/internal/subtitle.dart, packages/flutterfire_ui/lib/src/auth/widgets/internal/universal_button.dart, packages/flutterfire_ui/lib/src/auth/widgets/internal/universal_icon_button.dart, packages/flutterfire_ui/lib/src/auth/widgets/sign_out_button.dart, packages/flutterfire_ui/lib/src/loading_indicator.dart
* use `PlatformWidget` instead if manual `isCupertino` checks
* new `ButtonVariant` (outlined)
* add `UniversalIconButton`
[CLA]: …
=> refactor(ui): refactor platform specific widget styling

docs/remote-config/get-started.mdx
=> docs(firebase_remote_config): Fix broken website link.

docs/firestore-odm/defining-models.mdx
=> docs(cloud_firestore_odm): Fix spelling mistake in documentation.

packages/flutterfire_ui/example/android/app/src/main/AndroidManifest.xml, packages/flutterfire_ui/example/ios/Podfile, packages/flutterfire_ui/example/ios/Runner.xcodeproj/project.pbxproj, packages/flutterfire_ui/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/flutterfire_ui/example/lib/main.dart, packages/flutterfire_ui/lib/auth.dart, packages/flutterfire_ui/lib/src/auth/actions.dart, packages/flutterfire_ui/lib/src/auth/configs/email_provider_configuration.dart, packages/flutterfire_ui/lib/src/auth/email_verification.dart, packages/flutterfire_ui/lib/src/auth/flows/email_flow.dart, packages/flutterfire_ui/lib/src/auth/screens/email_verification_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/profile_screen.dart, packages/flutterfire_ui/lib/src/auth/widgets/error_text.dart, packages/flutterfire_ui/lib/src/auth/widgets/internal/oauth_provider_button.dart, packages/flutterfire_ui/lib/src/auth/widgets/internal/subtitle.dart
This PR implements email verifiaction and provider unlinking
Closes #7609
> `actionCodeSettings` parameter was dropped from the `EmailProviderConfiguration` since it is no longer used …
=> feat(ui)!: add email verification and allow to unlink social providers from profile screen

docs/firestore/overview.mdx, docs/manual-installation.mdx, packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
=> feat: Bump Firebase iOS SDK to `8.14.0`.

packages/flutterfire_ui/lib/src/auth/oauth/providers/google_provider.dart
=> fix(ui): allow passing oauth scopes for google sign in

packages/flutterfire_ui/lib/src/auth/widgets/email_form.dart, packages/flutterfire_ui/lib/src/auth/widgets/email_input.dart
=> fix(ui): trim email before submitting

tests/test_driver/driver_e2e.dart
=> chore: Temporarily comment out Firebase Storage CI as Storage emulator is broken on uploads.

packages/firebase_performance/firebase_performance_web/pubspec.yaml
=> chore: update pubspec description of `firebase_performance_web` package

docs/manual-installation/ios.mdx
a new version of flutter_facebook_auth requires iOS deployment target 11
https://pub.dev/packages/flutter_facebook_auth/changelog …
=> docs(ui): add flutterfire_ui deployment target

docs/firestore-odm/defining-models.mdx, docs/firestore-odm/references.mdx, docs/firestore-odm/subcollections.mdx
=> docs(firestore_odm): Use `explicitToJson` when defining data models.

CHANGELOG.md, packages/firebase_crashlytics/firebase_crashlytics/CHANGELOG.md, packages/firebase_crashlytics/firebase_crashlytics/pubspec.yaml
=> chore(release): prepare release

packages/flutterfire_ui/example/lib/main.dart, packages/flutterfire_ui/lib/src/auth/email_verification.dart, packages/flutterfire_ui/lib/src/auth/flows/phone_auth_flow.dart
=> fix(ui): fix phone linking on web

packages/flutterfire_ui/lib/src/auth/widgets/email_input.dart
=> fix(ui): filter out whitespaces in email with input formatter

packages/firebase_analytics/firebase_analytics/ios/Classes/FLTFirebaseAnalyticsPlugin.m
See title. Print out of arguments on Xcode console:
fixes https://github.com/firebase/flutterfire/issues/8008
=> fix(firebase_analytics): Send default parameters for iOS when using `setDefaultEventParameters()` API.

.github/workflows/e2e_tests.yaml, packages/firebase_database/firebase_database_web/lib/src/interop/database.dart
See title.
fixes https://github.com/firebase/flutterfire/issues/7244
=> fix(firebase_database): Remove sync as `true` on Stream broadcast for web platform.

packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart, packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart, packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
See title.
fixes https://github.com/firebase/flutterfire/issues/6594
=> fix(firebase_auth): Allow `rawNonce` to be passed through on web via the `OAuthCredential`.

CHANGELOG.md, packages/firebase_analytics/firebase_analytics/CHANGELOG.md, packages/firebase_analytics/firebase_analytics/pubspec.yaml, packages/firebase_auth/firebase_auth/CHANGELOG.md, packages/firebase_auth/firebase_auth/pubspec.yaml, packages/firebase_auth/firebase_auth_web/CHANGELOG.md, packages/firebase_auth/firebase_auth_web/pubspec.yaml, packages/firebase_database/firebase_database/CHANGELOG.md, packages/firebase_database/firebase_database/pubspec.yaml, packages/firebase_database/firebase_database_web/CHANGELOG.md, packages/firebase_database/firebase_database_web/pubspec.yaml, packages/firebase_storage/firebase_storage/CHANGELOG.md, packages/firebase_storage/firebase_storage/pubspec.yaml, packages/flutterfire_ui/CHANGELOG.md, packages/flutterfire_ui/example/pubspec.yaml, packages/flutterfire_ui/pubspec.yaml
=> chore: Prepare for release on the 07/04/22.

docs/firestore/overview.mdx, docs/manual-installation.mdx, packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
=> feat: Update Firebase iOS SDK to `8.15.0`

.github/workflows/firebase_firestore_odm.yaml, packages/cloud_firestore_odm/cloud_firestore_odm/example/pubspec.yaml, packages/cloud_firestore_odm/cloud_firestore_odm/example/test_driver/cloud_firestore_odm_e2e.dart, packages/cloud_firestore_odm/cloud_firestore_odm/example/test_driver/collection_reference_test.dart, packages/cloud_firestore_odm/cloud_firestore_odm/example/test_driver/common.dart, packages/cloud_firestore_odm/cloud_firestore_odm/example/test_driver/document_reference_test.dart, packages/cloud_firestore_odm/cloud_firestore_odm/example/test_driver/firestore_builder_test.dart, packages/cloud_firestore_odm/cloud_firestore_odm/example/test_driver/path_test.dart, packages/cloud_firestore_odm/cloud_firestore_odm/example/test_driver/query_reference_test.dart
=> ci: enable Firestore ODM e2e tests

packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/movie.g.dart, packages/cloud_firestore_odm/cloud_firestore_odm/example/pubspec.yaml, packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/simple.g.dart, packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/pubspec.yaml, packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/test/collection_test.dart, packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/test/setup_firestore_mock.dart, packages/cloud_firestore_odm/cloud_firestore_odm_generator/pubspec.yaml
fixes https://github.com/firebase/flutterfire/issues/8103
=> feat: upgrade analyzer, freezed_annotation and json_serializable dependencies

packages/flutterfire_ui/pubspec.yaml
package version dump
Closes [#8405](https://github.com/firebase/flutterfire/issues/8405)
=> fix(ui): Bump `twitter_login` version to fix Android build failure.

docs/manual-installation.mdx, packages/firebase_core/firebase_core/android/gradle.properties
=> feat: bump Firebase Android SDK to `29.3.1`

tests/android/app/build.gradle, tests/android/app/google-services.json, tests/android/build.gradle, tests/lib/firebase_options.dart, tests/test_driver/firebase_core/firebase_core_e2e.dart
See title. 
Android CI is failing to build as a result.
None.
=> test: Update test app with latest firebase options settings.

packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
See title.
related https://github.com/firebase/flutterfire/issues/8444
=> fix(firebase_auth): Use iterator instead of enhanced for loop on android.

packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
=> refactor(firebase_auth): remove deprecated `Tasks.call()` API from Android.

tests/test_driver/firebase_messaging/firebase_messaging_e2e.dart
=> docs: fix typo "regresion" in `firebase_messaging_e2e.dart`

CHANGELOG.md, packages/firebase_auth/firebase_auth/CHANGELOG.md, packages/firebase_auth/firebase_auth/pubspec.yaml, packages/firebase_dynamic_links/firebase_dynamic_links/CHANGELOG.md, packages/firebase_dynamic_links/firebase_dynamic_links/pubspec.yaml, packages/firebase_messaging/firebase_messaging/CHANGELOG.md, packages/firebase_messaging/firebase_messaging/pubspec.yaml, packages/firebase_messaging/firebase_messaging_platform_interface/CHANGELOG.md, packages/firebase_messaging/firebase_messaging_platform_interface/pubspec.yaml, packages/firebase_messaging/firebase_messaging_web/CHANGELOG.md, packages/firebase_messaging/firebase_messaging_web/pubspec.yaml, packages/firebase_storage/firebase_storage/CHANGELOG.md, packages/firebase_storage/firebase_storage/pubspec.yaml, packages/flutterfire_ui/CHANGELOG.md, packages/flutterfire_ui/example/pubspec.yaml, packages/flutterfire_ui/pubspec.yaml
=> chore(release): prepare for release

docs/auth/anonymous-auth.mdx
=> docs(firebase_auth): Simple spelling correction.

packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart
=> fix(crashlytics): re-add support for `recordFlutterFatalError` method from previous EAP API

tests/test_driver/driver_e2e.dart
latest firebase-tools landed with Storage emulator fixes https://github.com/firebase/firebase-tools/pull/4407 …
=> test(firebase_storage): run e2e tests for iOS now latest firebase-tools with emulator fixes has been released.

CONTRIBUTING.md
=> docs: update release process documentation.

CONTRIBUTING.md
=> docs: Update CONTRIBUTING.md release process.

packages/firebase_crashlytics/firebase_crashlytics/macos/Classes/ExceptionModel_Platform.h
See title
fixes https://github.com/firebase/flutterfire/issues/8562
=> fix(firebase_crashlytics): symlink `ExceptionModel_Platform.h` to macOS.

docs/auth/anonymous-auth.md
=> docs(auth): Restore Monzim@'s typo fix

.github/workflows/publish_old_docs.yaml
=> ci: add old publish docs workflow

website/firebase.json
=> chore: add redirects for UI & ODM

website/firebase.json
=> docs: fix some Auth redirects

docs/setup/_setup_main.md, docs/setup/_setup_prereq_android.md, docs/setup/_setup_prereq_ios.md, docs/setup/_setup_prereq_web.md
=> docs: Add setup docs from firebase.google.com

packages/firebase_crashlytics/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/FlutterFirebaseCrashlyticsPlugin.java
=> refactor(firebase_crashlytics): remove deprecated `Tasks.call` for android and replace with `TaskCompletionSource`.

packages/flutterfire_ui/lib/src/auth/screens/email_verification_screen.dart
Flutter 3.0.0 caused failing the CI: https://github.com/firebase/flutterfire/runs/6398175458?check_suite_focus=true
```
Nils-MBP-13-M1-3:flutterfire_ui nils$ flutter analyze
Analyzing flutterfire_ui...                                             
info • A value for optional parameter 'actionCodeSettings' isn't ever given • lib/src/auth/screens/email_verification_screen.dart:78:10 •
unused_element
warning • The '!' will have no effect because the receiver can't be null • lib/src/auth/screens/email_verification_screen.dart:95:30 •
unnecessary_non_null_assertion
2 issues found. (ran in 3.4s)
```
This PR fixes the `flutter analyze` command. Additionally, the `unused_element` lint found this bug:
* #8650 
Closes #8650 
Closes #8645
Part of #8644 
Before you create this PR confirm that it meets …
=> fix(flutterfire_ui): use `EmailVerificationScreen.actionCodeSettings` & and fix `flutter analyze` with Flutter 3.0.0

packages/firebase_database/firebase_database_platform_interface/test/method_channel_test.dart
Flutter 3.0.0 caused failing the CI: https://github.com/firebase/flutterfire/runs/6398175458?check_suite_focus=true
```
Nils-MBP-13-M1-3:firebase_database_platform_interface nils$ flutter analyze
Running "flutter pub get" in firebase_database_platform_interface...      1,625ms
Analyzing firebase_database_platform_interface...                       
warning • The '!' will have no effect because the receiver can't be null • test/method_channel_test.dart:32:41 • unnecessary_non_null_assertion
1 issue found. (ran in 2.7s)
```
Closes #8647
Part of #8644 
Does …
=> refactor(firebase_database_platform_interface): fix analyzer issue introduced in Flutter 3.0.0

docs/auth/manage-users.md, docs/crashlytics/_get-started.md, docs/perf-mon/get-started.md, docs/setup/_setup_main.md
=> docs: Misc setup tweaks

.github/workflows/all_plugins.yaml
=> ci: use `dart pub` for `pub` command

docs/storage/handle-errors.md
=> docs: Fix typo in handle-errors.md

docs/README.md
=> docs: Add some info about our docs

docs/app-check/debug-provider.md
=> docs(firebase_app_check): add stub documentation about debug provider

packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
=> refactor(cloud_firestore): remove deprecated `Tasks.call` for android and replace with `TaskCompletionSource`.

.github/workflows/e2e_tests.yaml
=> ci: use Java 11 for emulators to run for e2e tests.

packages/cloud_firestore_odm/doc/defining-models.md
=> docs: Update defining-models.md

packages/cloud_firestore_odm/cloud_firestore_odm/pubspec.yaml
https://firebase.flutter.dev/docs/firestore/odm returns 404
Fixes #8723
=> refactor(cloud_firestore_odm): link for `homepage` in `pubspec.yaml` to `README.md`

packages/firebase_ml_model_downloader/firebase_ml_model_downloader/README.md
=> docs(firebase_ml_model_downloader): use camel case style for "FlutterFire" in `README.md`

packages/firebase_crashlytics/firebase_crashlytics/README.md
=> docs(firebase_crashlytics): use camel case style for "FlutterFire" in `README.md`

packages/firebase_auth/firebase_auth/README.md
=> docs(firebase_auth): use camel case style for "FlutterFire" in `README.md`

packages/cloud_functions/cloud_functions/README.md
=> docs(cloud_functions): use camel case style for "FlutterFire" in `README.md`

packages/flutterfire_ui/lib/src/auth/screens/email_verification_screen.dart
Removing the null check breaks the build for dart 2.16.2 (used by flutter 2.10.5) which should still be supported. This reverts the change, and instead manually suppresses the error.
```
Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
SchedulerBinding.instance.addPostFrameCallback(_sendEmailVerification);
```
#8645
Before you create this PR confirm that it meets all requirements listed below by …
=> fix(ui): correctly fix lint error from issue #8651 for dart `2.16`

.github/workflows/publish_old_docs.yaml
=> chore: Update publish_old_docs.yaml to publish old-docs branch

packages/firebase_app_check/firebase_app_check/pubspec.yaml
=> refactor(firebase_app_check): use `firebase.google.com` link for `homepage` in `pubspec.yaml`

packages/flutterfire_ui/README.md
=> docs(flutterfire_ui): fix readme link

CONTRIBUTING.md
`melos bs` with fvm might use to the wrong Dart SDK. Added information on how to use --sdk-path …
=> docs: update contributing guide with fvm (flutter version manager) information

packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart
=> docs(firebase_messaging): fix typo "RemoteMesage" in `messaging.dart`

packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
=> docs(firebase_auth): fix two typos.

packages/firebase_core/firebase_core/lib/src/firebase_app.dart
Makes it more clear for a user.
Closes #8888
=> docs(firebase_core): add note that deleting the default Firebase app is not possible.

packages/firebase_storage/firebase_storage_web/lib/src/interop/storage.dart, packages/firebase_storage/firebase_storage_web/lib/src/interop/storage_interop.dart, packages/firebase_storage/firebase_storage_web/lib/src/reference_web.dart, packages/firebase_storage/firebase_storage_web/lib/src/utils/metadata.dart, tests/test_driver/firebase_storage/reference_e2e.dart
Keep the putString method by bridging it to uploadByteResumable …
=> feat(storage, web): bridge putString to uploadByteResumable

docs/auth/email-link-auth.md
Documentation on email-link-auth had a false example in Account Linking section. The existing example showed that in order to link the an account with email-link auth in an existing user, you should sign in to the user account that is related to the email-link with the usual method ```await FirebaseAuth.instance.signInWithEmailLink(email: emailAuth, emailLink: emailLink);``` which is false because If you sign in first the existing user is replaced and the linking fails. 
The PR replaces that behavior with an example code from another official documentation page [here](https://firebase.google.com/docs/auth/flutter/account-linking#link_auth_provider_credentials_to_a_user_account).
And practically using the ```EmailAuthProvider``` class to get the credentials related to that email link …
=> docs: email-link-auth fixed code example in account linking

.github/workflows/all_plugins.yaml, .github/workflows/firebase_firestore_odm.yaml, .github/workflows/scripts/install-tools.sh, melos.yaml
The following jobs had a flaky rate of (I ran every job 100 times):
* `analyze` 15.00% flaky (https://github.com/nilsreichardt/flutterfire/runs/6887635553?check_suite_focus=true)
* 10% because of `The analysis server shut down unexpectedly.`
* 5% `melos bootstrap` took longer than the action timeout
* `pub_get_check` 2.00% flaky (https://github.com/nilsreichardt/flutterfire/runs/6887680143?check_suite_focus=true)
* 2% `melos bootstrap` took longer than the action timeout
* `format` 5.00% flaky (https://github.com/nilsreichardt/flutterfire/runs/6887693001?check_suite_focus=true)
* 5% `melos bootstrap` took longer than the action timeout
* `build_example_dart` 1.00% flaky (https://github.com/nilsreichardt/flutterfire/runs/6887701442?check_suite_focus=true)
* 1% `melos bootstrap` took longer …
=> ci: fix flaky `analyze`, `pub_get_check`, `format`, `build_example_dart` and `test` jobs.

tests/integration_test/e2e_test.dart, tests/integration_test/firebase_analytics/firebase_analytics_e2e_test.dart
=> test(firebase_analytics): migrate to `integration_test` package

README.md
Improves the accessibility for the `REAMDE.md`.
=> docs: add alt text for Flutter + Firebase image in `README.md`

packages/flutterfire_ui/lib/src/auth/screens/email_verification_screen.dart
This PR migrates the flutterfire_ui package to be compatible with Flutter version 3.
#8948 
=> fix(flutterfire_ui): migrate flutterfire_ui to flutter v3

packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
try to fix https://github.com/firebase/flutterfire/issues/8444
=> fix(firebase_auth): java.util.ConcurrentModificationException

docs/auth/federated-auth.md, packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java, packages/firebase_auth/firebase_auth/example/ios/Runner.xcodeproj/project.pbxproj, packages/firebase_auth/firebase_auth/example/ios/Runner/Info.plist, packages/firebase_auth/firebase_auth/example/lib/auth.dart, packages/firebase_auth/firebase_auth/example/lib/main.dart, packages/firebase_auth/firebase_auth/example/macos/Runner.xcodeproj/project.pbxproj, packages/firebase_auth/firebase_auth/example/pubspec.yaml, packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m, packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart
update android GitHub sign in implementation to use underlying platform and not expose secret (#8943)
#8943 
#8950 
=> feat(auth): update GitHub sign in implementation

.clang-format, .github/workflows/all_plugins.yaml, .github/workflows/scripts/install-tools.sh, packages/firebase_core/firebase_core/ios/Classes/FLTFirebaseCorePlugin.h, packages/firebase_core/firebase_core/ios/Classes/FLTFirebasePlugin.h, packages/firebase_core/firebase_core/ios/Classes/FLTFirebasePluginRegistry.h, packages/firebase_core/firebase_core/ios/Classes/messages.g.h, packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
flutter_plugin_tools use `style=file` while we use `style=Google` in `melos run format`.
Add a `.clang-format` file to make formatting consistent …
=> improvement: update format CI step to match local melos format

packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart, packages/firebase_auth/firebase_auth/lib/src/user.dart, packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_recaptcha_verifier_factory.dart
Fixes #4377
After showing a recaptcha in web for SMS login, the recaptcha icon
overlay persists on the app until it is reloaded, often blocking an
app's buttons and other interactive widgets. This adds removal of the
web UI element in the clear method, and ensures that clear is called on
any RecaptchaVerifier() objects created by flutterfire.
*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers …
=> fix(ui): Web recaptcha hover removed after use.
