packages/firebase_admob/CHANGELOG.md, packages/firebase_admob/README.md, packages/firebase_admob/android/src/main/java/io/flutter/plugins/firebaseadmob/FirebaseAdMobPlugin.java, packages/firebase_admob/android/src/main/java/io/flutter/plugins/firebaseadmob/MobileAd.java, packages/firebase_admob/example/lib/main.dart, packages/firebase_admob/ios/Classes/FLTMobileAd.h, packages/firebase_admob/ios/Classes/FLTMobileAd.m, packages/firebase_admob/ios/Classes/FirebaseAdMobPlugin.m, packages/firebase_admob/lib/firebase_admob.dart, packages/firebase_admob/pubspec.yaml, packages/firebase_admob/test/firebase_admob_test.dart
Apparently I didn't actually get this PR in before the transfer. Adding it here.
Original PR: https://github.com/flutter/plugins/pull/1925
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
=> Add horizontal commit from flutter/plugins repo

packages/cloud_firestore/test/cloud_firestore_test.dart, packages/cloud_functions/test/cloud_functions_test.dart, packages/firebase_admob/test/firebase_admob_test.dart, packages/firebase_analytics/example/pubspec.yaml, packages/firebase_analytics/test/firebase_analytics_test.dart, packages/firebase_analytics/test/observer_test.dart, packages/firebase_auth/test/firebase_auth_test.dart, packages/firebase_core/test/firebase_core_test.dart, packages/firebase_crashlytics/test/firebase_crashlytics_test.dart, packages/firebase_database/test/firebase_database_test.dart, packages/firebase_database/test/firebase_list_test.dart, packages/firebase_dynamic_links/test/firebase_dynamic_links_test.dart, packages/firebase_messaging/test/firebase_messaging_test.dart, packages/firebase_ml_vision/test/firebase_ml_vision_test.dart, packages/firebase_ml_vision/test/image_labeler_test.dart, packages/firebase_performance/test/firebase_performance_test.dart, packages/firebase_remote_config/test/firebase_remote_config_test.dart, packages/firebase_storage/test/firebase_storage_test.dart
Fixes tests that were broken by flutter/flutter#38464
See also flutter/flutter#39077
=> Fix unit tests by calling TestWidgetsFlutterBinding.ensureInitialized()

packages/firebase_database/CHANGELOG.md, packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java, packages/firebase_database/pubspec.yaml
This PR fixes a possible NullPointerException that happens when the plugin is registered without a valid Activity.
I took the opportunity to add some nullability annotations that the IDE was suggesting, those are in the interfaces that are being implemented in the plugin, so should be safe to use.
https://github.com/FirebaseExtended/flutterfire/issues/19
=> [Firebase_Database] Fix possible NullPointerException

packages/firebase_remote_config/CHANGELOG.md, packages/firebase_remote_config/example/test_driver/firebase_remote_config.dart, packages/firebase_remote_config/lib/src/remote_config.dart, packages/firebase_remote_config/pubspec.yaml
Migrates flutter/plugins#1966 by @IchordeDionysos
I ended up rewriting it a bit.
Note: It seems the plugin was working fine and the behavior is covered by a test, but there was a spurious error message in the logs. This PR is removing the error message in the logs, and I don't think I can easily cover that in a test.
Fixes flutter/flutter#38060
=> [firebase_remote_config] Fix Future already completed RemoteConfig.instance

packages/firebase_auth/CHANGELOG.md, packages/firebase_auth/example/test/firebase_auth.dart, packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m, packages/firebase_auth/lib/src/firebase_auth.dart, packages/firebase_auth/pubspec.yaml
Migrates flutter/plugins#2002 by @timtraversy
I ended up rewriting the PR a bit:
* updated documentation
* added integration test
* updated CHANGELOG
* put the coalescing on the native side
https://github.com/firebase/firebase-ios-sdk/issues/3655
=> [firebase_auth] Consistent platform behavior for fetchSignInMethodsForEmail

packages/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/example/test_driver/cloud_firestore.dart, packages/cloud_firestore/pubspec.yaml
I have a theory about why this test is timing out on CI, although I can't reproduce it locally -- if `hasPendingWrites` and `isFromCache` update at the same time, the test could fail.
=> [cloud_firestore] Improve reliability of includeMetadataChanges integration test

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Contributors don't have the ability to add tags to PRs but they can choose a title and that's probably just as good for our purposes.
=> Update docs to encourage contributors to title PRs with the plugin they affect

packages/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java, packages/cloud_firestore/pubspec.yaml
This should resolve #70.
I assume that the `RuntimeException`s I am seeing there happen in the `doInBackground` `AsyncTask` of `Transaction#set`, which is why I added a `try-catch` block there.
`Transaction#update` and `Transaction#get` already had `try-catch` blocks, however, they only caught `IllegalStateException`'s and since I got `RuntimeException`s and there is no need to be specific about the type of exception when only `e.getMessage` is called anyway, I generalized the `catch` block for those as well.
Additionally, I applied the same logic to `Transaction#delete`, just to be consistent.
=> [cloud_firestore] Catch exceptions for transactions on Android

.cirrus.yml
We aren't using emulators any more, and they are causing the tests to time out.
=> Remove emulators references from .cirrus.yaml

packages/firebase_messaging/CHANGELOG.md, packages/firebase_messaging/README.md, packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java, packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseMessagingService.java, packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/LatchResult.java, packages/firebase_messaging/lib/firebase_messaging.dart, packages/firebase_messaging/pubspec.yaml, packages/firebase_messaging/test/firebase_messaging_test.dart
When Flutter app is in the background or terminated allow it to handle incoming FCM messages. This update uses a similar strategy to the one used by the [android_alarm_manager](https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager) plugin. When the application starts an additional background channel is started to handle incoming messages when the app is not in the foreground.
Migration of flutter/plugins#1900
flutter/flutter#32372
TODOs before this can be merged
=> [firebase_messaging] Add support for handling messages in background

packages/firebase_analytics/CHANGELOG.md, packages/firebase_analytics/ios/Classes/FirebaseAnalyticsPlugin.m, packages/firebase_analytics/pubspec.yaml
Fixes `setAnalyticsCollectionEnabled` on iOS.
When a boolean is passed across the bridge, it arrives as an `NSNumber *`. That means that when call.arguments has a `NO` `boolValue`, our code will call `[FIRAnalytics setAnalyticsCollectionEnabled:YES];` because the pointer isn't `nil`. This PR fixes the issue.
Unfortunately I can't think of a good way to integration test this.
=> [firebase_analytics] Fix setAnalyticsCollectionEnabled

packages/firebase_crashlytics/CHANGELOG.md, packages/firebase_crashlytics/example/lib/main.dart, packages/firebase_crashlytics/pubspec.yaml
Fix pre-existing dartanalyzer finding:
info - Prefer const with constant constructors at example/lib/main.dart:77:42 - (prefer_const_constructors)
=> [firebase_crashlytics] Fix pre-existing dartanalyzer finding

packages/firebase_ml_vision/CHANGELOG.md, packages/firebase_ml_vision/README.md, packages/firebase_ml_vision/example/ios/Runner.xcodeproj/project.pbxproj, packages/firebase_ml_vision/example/lib/material_barcode_scanner.dart, packages/firebase_ml_vision/example/test_driver/face_detector.dart, packages/firebase_ml_vision/pubspec.yaml
Fix example in firebase_ml_vision to use minimum deployment target of API.
And fixes analyzer const warnings.
=> [firebase_ml_vision] Update firebase_ml_vision example app deployment target to 9.0

packages/firebase_auth/CHANGELOG.md, packages/firebase_auth/example/lib/register_page.dart, packages/firebase_auth/example/lib/signin_page.dart, packages/firebase_auth/pubspec.yaml, packages/firebase_in_app_messaging/CHANGELOG.md, packages/firebase_in_app_messaging/example/lib/main.dart, packages/firebase_in_app_messaging/pubspec.yaml
Fixes CI analyze tests where the correct `const` constructor was not used.
=> [firebase_auth] [firebase_in_app_messaging] Update example apps with correct `const` constructors.

packages/firebase_crashlytics/CHANGELOG.md, packages/firebase_crashlytics/example/android/app/build.gradle, packages/firebase_crashlytics/example/android/gradle.properties, packages/firebase_crashlytics/pubspec.yaml
=> [firebase_crashlytics] Fix example app build by increasing compileSdkVersion to 28

.github/PULL_REQUEST_TEMPLATE.md
2nd item already says:
```
```
=> Remove duplicate instruction from PR checklist

packages/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java, packages/cloud_firestore/pubspec.yaml
* Fixes crash on Android when run a transaction and without internet connection.
* This occurred because:
`Tasks.await(transactionTCSTask, timeout, TimeUnit.MILLISECONDS)`
throws a `Exception`
→ `result.error("Error performing transaction", e.getMessage(), null)` will be called
→ transaction result is `null`
→ in `addOnCompleteListener`#`onComplete`:
```java
if (task.isSuccessful()) { // result is null
result.success(task.getResult());
}
```
will also be called
→ **result#success has been called after result#error**
→ This cause `java.lang.IllegalStateException: Reply already submitted`
fix #79  …
=> [cloud_firestore] Fixes crash on Android when run a transaction

packages/firebase_dynamic_links/CHANGELOG.md, packages/firebase_dynamic_links/example/android/gradle.properties, packages/firebase_dynamic_links/example/pubspec.yaml, packages/firebase_dynamic_links/pubspec.yaml
Fix example app build by updating version of `url_launcher` that is compatible with androidx apps.
=> [firebase_dynamic_links] Update url_launcher dependency

packages/cloud_firestore/lib/src/snapshot_metadata.dart
Fix SnapshotMetadata comments that referenced Android classes to reference the dart mechanism instead. It is now clear how the developer can use the metadata feature of Firestore.
=> [cloud_firestore] Documentation Fix for SnapshotMetadata.

.ci/Dockerfile, .cirrus.yml
Updates the FirebaseExtended repo CI to have the same testing on Firebase Test Lab that is used for flutter/plugins.
Eventually I'd like to refactor to eliminate duplicated code, but I'm not sure how to do that.
The only differences between flutter/plugins and FirebaseExtended/flutterfire are the encrypted Firebase Test Lab key, and the all plugins tests.
=> Enable Firebase Test Lab testing

packages/cloud_firestore/example/android/app/gradle.properties, packages/cloud_functions/example/android/app/gradle.properties, packages/firebase_admob/example/android/app/gradle.properties, packages/firebase_admob/example/android/gradle.properties, packages/firebase_analytics/example/android/app/gradle.properties, packages/firebase_analytics/example/android/gradle.properties, packages/firebase_auth/example/android/app/gradle.properties, packages/firebase_core/example/android/app/gradle.properties, packages/firebase_database/example/android/app/gradle.properties, packages/firebase_database/example/android/gradle.properties, packages/firebase_dynamic_links/example/android/app/gradle.properties, packages/firebase_in_app_messaging/example/android/app/gradle.properties, packages/firebase_in_app_messaging/example/android/gradle.properties, packages/firebase_messaging/example/android/app/gradle.properties, packages/firebase_messaging/example/android/gradle.properties, packages/firebase_ml_vision/android/gradle.properties, packages/firebase_ml_vision/example/android/app/gradle.properties, packages/firebase_ml_vision/example/android/gradle.properties, packages/firebase_performance/example/android/app/gradle.properties, packages/firebase_remote_config/example/android/app/gradle.properties, packages/firebase_storage/example/android/app/gradle.properties
Following @blasten investigation these files are not needed, and may create some AndroidX related issues.
These files were introduced in: flutter/plugins#1103
=> delete all example/android/app/gradle.properties files

.cirrus.yml
See https://cirrus-ci.com/task/5375987256131584
This unused environment variable is copy pasta from the flutter/plugins version of .cirrus.yml. seems to be causing other encrypted data to fail to decrypt, so the Firebase Test Lab tests aren't running.
=> Remove unused encrypted variables

packages/firebase_analytics/CHANGELOG.md, packages/firebase_analytics/android/build.gradle, packages/firebase_analytics/pubspec.yaml, packages/firebase_core/CHANGELOG.md, packages/firebase_core/android/build.gradle, packages/firebase_core/pubspec.yaml
Fixes possible version conflict issues. This would cause runtime class not found errors if any of these plugins relied on Lifecycle at runtime, but they do not.
Test is pending in flutter/plugin_tools#62.
flutter/flutter#43383 …
=> [firebase_core][firebase_analytics] Fix bug with transitive lifecycle dependencies

packages/firebase_crashlytics/CHANGELOG.md, packages/firebase_crashlytics/lib/src/firebase_crashlytics.dart, packages/firebase_crashlytics/pubspec.yaml
Always log crash details in debug mode, even if `enableInDevMode=true`.
And for Flutter error, log even when not inDebugMode -- with FlutterError.dumpErrorToConsole, keeping existing Flutter behavior.
=> [firebase_crashlytics] Always log crash details in debug mode

packages/firebase_ml_vision/CHANGELOG.md, packages/firebase_ml_vision/pubspec.yaml, packages/firebase_ml_vision/test/firebase_ml_vision_e2e.dart
This PR skips the e2e on Android. The test fails unless the emulator deletes the data in the Google Play Services app. Issue to track this problem is here https://github.com/FirebaseExtended/flutterfire/issues/1371 …
=> [firebase_ml_vision] Fix Android e2e test

packages/firebase_crashlytics/CHANGELOG.md, packages/firebase_crashlytics/ios/Classes/FirebaseCrashlyticsPlugin.m, packages/firebase_crashlytics/lib/src/firebase_crashlytics.dart, packages/firebase_crashlytics/pubspec.yaml
Make logging more obvious and to the right point of verbosity.
This change also gets rid of XCode build warnings about potential security issue with format string.
=> [firebase_crashlytics] Logging improvements

packages/firebase_core/lib/src/firebase_app.dart, packages/firebase_core/test/firebase_core_test.dart
Remove @visibleForTesting annotation from FirebaseApp constructor. This will resolve CI issues while a new FirebaseApp creation strategy is WIP.
=> Remove @visibleForTesting from FirebaseApp constructor

.cirrus.yml
Current iOS simulator is not available in CI. This PR updates the selected simulator to one that is available in CI.
=> [CI] Use available simulator for CI

packages/firebase_core/CHANGELOG.md, packages/firebase_core/android/build.gradle, packages/firebase_core/pubspec.yaml
- Remove [deprecated firebase-core](https://firebase.google.com/support/release-notes/android) dependency.
- Update firebase-common dependency.
This PR resolves a CI build failure where android dependencies are not being resolved between core and other plugins.
[Eg](https://cirrus-ci.com/task/5018600573763584?command=main#L205)
```
* What went wrong:
Could not resolve all files for configuration ':firebase_core:releaseCompileClasspath'.
> Could not resolve android.arch.lifecycle:runtime:1.1.1.
```
=> Remove deprecated firebase-core dependency

packages/firebase_auth/CHANGELOG.md, packages/firebase_auth/example/test/firebase_auth.dart, packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m, packages/firebase_auth/pubspec.yaml
Currently, we have different behavior in Android and iOS implementation for token refreshing. On Android we are expecting to get a `boolean` value, so everything works as expected:
`getIdToken(refresh: false)` - will not update token and `getIdToken(refresh: true)` will refresh it.
On iOS we are checking if `refresh` object exists in the dictionary, so `getIdToken(refresh: false)` will force token refreshing.
https://github.com/FirebaseExtended/flutterfire/issues/847 …
=> [firebase_auth] getIdToken use actual refresh value instead of checking if object exists

.cirrus.yml
Update CI version of XCode to allow use of iOS 13, and resolve [CI build failures](https://cirrus-ci.com/task/4616326890389504).
=> [CI] update xcode to v11

packages/cloud_firestore/test/cloud_firestore_test.dart, packages/cloud_functions/test/cloud_functions_test.dart, packages/firebase_database/test/firebase_database_test.dart, packages/firebase_storage/test/firebase_storage_test.dart
Fix creation of FirebaseApp in tests. Remove the use of `const` for creating FirebaseApp objects.
=> Update FirebaseApp creation in tests

packages/firebase_messaging/CHANGELOG.md, packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m, packages/firebase_messaging/pubspec.yaml
Fixed strict compilation errors.
1) Cast error.code to long
2) Changes return "bool" to "BOOL"
=> Fixes strict compilation errors.

packages/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/lib/src/document_change.dart, packages/cloud_firestore/lib/src/query_snapshot.dart, packages/cloud_firestore/pubspec.yaml, packages/firebase_performance/CHANGELOG.md, packages/firebase_performance/lib/src/http_metric.dart, packages/firebase_performance/lib/src/performance_attributes.dart, packages/firebase_performance/lib/src/trace.dart, packages/firebase_performance/pubspec.yaml
Analyzer is complaining about fields that are unused. We can safely remove them.
=> [cloud_firestore] [firebase_performance] fix analyzer warnings

packages/firebase_performance/CHANGELOG.md, packages/firebase_performance/example/test_driver/firebase_performance.dart, packages/firebase_performance/pubspec.yaml
Skip flaky firebase_performance driver tests.
=> [CI] Skip flaky firebase_performance driver tests

AUTHORS, packages/firebase_auth/CHANGELOG.md, packages/firebase_auth/lib/src/firebase_user.dart, packages/firebase_auth/pubspec.yaml
Added missing ERROR_WRONG_PASSWORD Exception to the `reauthenticateWithCredential` docs.
#1448
=> [firebase_auth] Added missing Exception to the reauthenticateWithCredential docs (#1448)

packages/firebase_remote_config/CHANGELOG.md, packages/firebase_remote_config/android/build.gradle, packages/firebase_remote_config/android/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfig/MethodCallHandlerImpl.java, packages/firebase_remote_config/example/android/build.gradle, packages/firebase_remote_config/example/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_remote_config/pubspec.yaml
Simple dependency update on the Firebase Remote Config package.
The version bump to 0.3.0 (indicating a major change) is due to the major version dependency increase on firebase.
Should help to finally close https://github.com/flutter/flutter/issues/28397 . …
=> [firebase_remote_config] Bumps Android Firebase dependency to 19.0.3

packages/firebase_messaging/CHANGELOG.md, packages/firebase_messaging/README.md, packages/firebase_messaging/android/gradle.properties, packages/firebase_messaging/example/android/gradle.properties, packages/firebase_messaging/example/ios/Runner/AppDelegate.m, packages/firebase_messaging/example/test_driver/firebase_messaging.dart, packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m, packages/firebase_messaging/lib/firebase_messaging.dart, packages/firebase_messaging/pubspec.yaml
<s>Switch to use `UNUserNotificationCenter` once https://github.com/flutter/engine/pull/9864 lands in flutter master.</s> Landed
Follows instructions from: https://firebase.google.com/docs/cloud-messaging/ios/client#register_for_remote_notifications
This includes a test that can run locally on Android and iOS. We can't run it on our CI because it requires a valid Firebase project and a server token.
Should fix https://github.com/flutter/flutter/issues/22099
**Possibly Related Issues**
https://github.com/flutter/flutter/issues/35375
https://github.com/flutter/flutter/issues/36201 …
=> [firebase_messaging] Use UNUserNotificationCenter for ios 10+

CONTRIBUTING.md
Removes obsolete recommendations about removing mockito (which is now used in testing federated plugins).
https://github.com/flutter/flutter/issues/34284
=> Update CONTRIBUTING.md to allow mockito

packages/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/pubspec.yaml, packages/cloud_firestore/test/cloud_firestore_test.dart
This fixes a test in `cloud_firestore` that set a mock handler on `FirebaseApp.channel`, which has been deleted.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/1475
[CLA]: …
=> [cloud_firestore] Fix test that used FirebaseApp.channel

packages/firebase_core/firebase_core_platform_interface/CHANGELOG.md, packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart, packages/firebase_core/firebase_core_platform_interface/lib/src/platform_firebase_app.dart, packages/firebase_core/firebase_core_platform_interface/pubspec.yaml
This is not a breaking change. Just use a better supported library.
=> [firebase_core] Switch away from quiver_hashcode

.ci/Dockerfile
Adds Chrome to the docker instance so we can run web tests on Cirrus
See https://github.com/FirebaseExtended/flutterfire/issues/1495
=> Add Chrome to the Dockerfile for Cirrus

packages/firebase_messaging/CHANGELOG.md, packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m, packages/firebase_messaging/pubspec.yaml
The line 
```objc
if (!@available(iOS 10.0, *)) {
```
causes this warning: `@available does not guard availability here; use if (@available) instead`.
I'm replacing this logic to not use this line.
[CLA]: …
=> [firebase_messaging] Fix availability check on ios

.cirrus.yml
Flutterfire equivalent for https://github.com/flutter/plugins/pull/2203
Avoids testing web plugins until support is available on the stable channel.
=> Avoid testing web plugins on stable

packages/firebase_core/firebase_core_web/CHANGELOG.md, packages/firebase_core/firebase_core_web/README.md, packages/firebase_core/firebase_core_web/pubspec.yaml
Some extra steps are necessary to initialize the default app on web. This adds documentation for how to do that.
=> [firebase_core_web] Add documentation for how to initialize the default app

packages/firebase_crashlytics/CHANGELOG.md, packages/firebase_crashlytics/example/lib/main.dart, packages/firebase_crashlytics/pubspec.yaml
Removed the `async` from the `runZoned()` in the example, as there's no `await` to be executed.
=> [firebase_crashlytics] No need for async as there's no await

packages/firebase_messaging/CHANGELOG.md, packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m, packages/firebase_messaging/pubspec.yaml
In iOS < 10, we would have to wait for an `UIApplication` callback `[UIApplication :didRegisterUserNotificationSettings:notificationSettings]` to get which settings were authorized. 
In iOS >= 10, you should call [requestAuthorizationWithOptions:completionHandler:](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649527-requestauthorizationwithoptions?language=objc) to get the authorized settings.
This PR makes the callback when using iOS >= 10 so that the PR is backwards compatible (iOS 8+).
Fixes https://github.com/FirebaseExtended/flutterfire/issues/1508 …
=> [firebase_messaging] Make onIosSettingsRegistered callback on iOS >= 10

packages/firebase_storage/CHANGELOG.md, packages/firebase_storage/example/lib/main.dart, packages/firebase_storage/pubspec.yaml
With new flutter versions, the firebase_storage example doesn't run.
A runtime exception occurs:
```
Exception has occurred.
FlutterError (ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.)
```
This is a fix for it, as described on SO: https://stackoverflow.com/questions/57689492/flutter-unhandled-exception-servicesbinding-defaultbinarymessenger-was-acc …
=> [firebase_storage] add ensureInitialized

CONTRIBUTING.md
Copy-pasted the release process from the flutter/plugins README. It's a bit wasteful to duplicate all this text, but we want to let the FlutterFire repo evolve in its own direction over time so maybe it's better not to point to the same place.
=> Update CONTRIBUTING.md to match flutter/plugins

packages/firebase_auth/firebase_auth_platform_interface/CHANGELOG.md, packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel_firebase_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml, packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_firebase_auth_test.dart
Fixes bug where we crashed if the platform returned an auth result with no `additionalUserInfo`.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/1580
=> [firebase_auth] Fix crash with null additionalUserInfo

packages/firebase_messaging/CHANGELOG.md, packages/firebase_messaging/README.md, packages/firebase_messaging/pubspec.yaml
Added extra step for Android setup in Firebase Cloud Messaging readme because I had problems with my app crashing and it was because I didn't realize I had to change the package name. This commit adds this extra step to the readme.
=> [cloud_messaging] Added step for Android instructions

.cirrus.yml
flutterfire version for https://github.com/flutter/plugins/pull/2396
=> [skip ci] don't run Cirrus on tags

packages/firebase_core/firebase_core/CHANGELOG.md, packages/firebase_core/firebase_core/lib/firebase_core.dart, packages/firebase_core/firebase_core/lib/src/default_app_name.dart, packages/firebase_core/firebase_core/lib/src/default_app_name_io.dart, packages/firebase_core/firebase_core/lib/src/firebase_app.dart, packages/firebase_core/firebase_core/pubspec.yaml
This should make the plugin register as supporting Web on pub.dev.
=> [firebase_core] Put the 'dart:io' import behind a configurable import

packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/FlutterFirebaseAppRegistrar.java, packages/cloud_functions/android/src/main/java/io/flutter/plugins/firebase/cloudfunctions/FlutterFirebaseAppRegistrar.java, packages/firebase_analytics/firebase_analytics/android/build.gradle, packages/firebase_analytics/firebase_analytics/android/src/main/java/io/flutter/plugins/firebaseanalytics/FlutterFirebaseAppRegistrar.java, packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FlutterFirebaseAppRegistrar.java, packages/firebase_core/firebase_core/android/build.gradle, packages/firebase_core/firebase_core/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseAppRegistrar.java, packages/firebase_crashlytics/android/build.gradle, packages/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/firebasecrashlytics/FlutterFirebaseAppRegistrar.java, packages/firebase_database/android/build.gradle, packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FlutterFirebaseAppRegistrar.java, packages/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebasedynamiclinks/FlutterFirebaseAppRegistrar.java, packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseAppRegistrar.java, packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/FlutterFirebaseAppRegistrar.java, packages/firebase_performance/android/build.gradle, packages/firebase_performance/android/src/main/java/io/flutter/plugins/firebaseperformance/FlutterFirebaseAppRegistrar.java, packages/firebase_remote_config/android/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfig/FlutterFirebaseAppRegistrar.java, packages/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FlutterFirebaseAppRegistrar.java, script/incremental_build.sh
fixes: #1337
When using proguard the registrar classes are removed from FlutterFire plugins. This change adds the keep annotation to the registrar classes.
=> [All] Add keep annotation to Firebase registrar

.cirrus.yml
Stable CI was temporarily disabled waiting for the next stable release, now that it's out re-enabling.
flutter/flutter#46258
=> Re-enable CI on stable

packages/firebase_core/firebase_core_web/CHANGELOG.md, packages/firebase_core/firebase_core_web/android/.gitignore, packages/firebase_core/firebase_core_web/android/build.gradle, packages/firebase_core/firebase_core_web/android/gradle.properties, packages/firebase_core/firebase_core_web/android/gradle/wrapper/gradle-wrapper.properties, packages/firebase_core/firebase_core_web/android/settings.gradle, packages/firebase_core/firebase_core_web/android/src/main/AndroidManifest.xml, packages/firebase_core/firebase_core_web/android/src/main/java/io/flutter/plugins/firebase_core_web/FirebaseCoreWebPlugin.java, packages/firebase_core/firebase_core_web/pubspec.yaml
Add a non-op android folder to avoid build errors.
The current flutter dev channel has a bug that it requires all plugins to have at least a non-op android folder to build.
https://github.com/flutter/flutter/issues/46898 …
=> [firebase_core_web] add non op android folder

packages/cloud_functions/CHANGELOG.md, packages/cloud_functions/example/test/cloud_functions_test.dart, packages/cloud_functions/example/test_driver/cloud_functions_test.dart, packages/cloud_functions/pubspec.yaml
Fixes some analysis failures in cloud_firestore.
This PR demonstrates that our CI isn't turning red on documentation failures (there are 8 public members that lack documentation)
=> Fix analysis failures in cloud_functions

packages/firebase_auth/firebase_auth_web/android/src/main/java/io/flutter/plugins/firebaseauth_web/FirebaseAuthWebPlugin.java
Removed onMethodCall override and related imports.
(Part 2 of: https://github.com/FirebaseExtended/flutterfire/pull/1628)
=> [firebase_auth_web] Removed onMethodCall override and related imports.

packages/firebase_storage/CHANGELOG.md, packages/firebase_storage/lib/src/storage_reference.dart, packages/firebase_storage/pubspec.yaml
I assume that these were accidentally left in with https://github.com/FirebaseExtended/flutterfire/pull/1295.
=> [firebase_storage] Removed "i am working" print statements

packages/firebase_auth/firebase_auth/CHANGELOG.md, packages/firebase_auth/firebase_auth/pubspec.yaml
https://github.com/FirebaseExtended/flutterfire/pull/1526 added OAuth support to firebase_auth. I overlooked this in the review, but since this is adding new API surface area, it shouldn't be patch update -- it should at least be a minor update.
I thought about making it a breaking change since the Android `api` dependency changed to 'com.google.firebase:firebase-auth:19.2.0': https://github.com/FirebaseExtended/flutterfire/pull/1526/files#diff-d8d76dca3eb1a8679bd5baa6e8b330c3
We may want to move this to being an implementation dependency, see https://github.com/FirebaseExtended/flutterfire/pull/39
We'll be bumping this plugin to 1.0 soon but I think we're not quite done making breaking changes yet.
=> Update firebase_auth version for release

packages/firebase_auth/firebase_auth_platform_interface/CHANGELOG.md, packages/firebase_auth/firebase_auth_platform_interface/lib/firebase_auth_platform_interface.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel_firebase_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml, packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_firebase_auth_test.dart
This PR lays the foundation for a future PR to be able to handle the whole password reset flow from within the app.
#1739 
=> [firebase_auth] support confirmPasswordReset

.cirrus.yml, script/lint_darwin_plugins.sh
Updates FlutterFire with the CI checks that were added to the flutter/plugins repo in https://github.com/flutter/plugins/pull/2334 and https://github.com/flutter/plugins/pull/2396
=> [all] Add macos checks to to CI

packages/firebase_auth/firebase_auth_platform_interface/CHANGELOG.md, packages/firebase_auth/firebase_auth_platform_interface/lib/firebase_auth_platform_interface.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel_firebase_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml, packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_firebase_auth_test.dart
The `FirebaseAuthPlatform.confirmPasswordReset` method should accept `String app` as an argument to be consistent with the rest of the interface (and existing implementations, particularly for `firebase_auth_web`).
cc: @lanmonster, @hterkelsen 
#1778  …
=> [firebase_auth] Correct method signature for confirmPasswordReset 

packages/firebase_auth/firebase_auth_platform_interface/CHANGELOG.md, packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel_firebase_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml
Fixed typo in private method of the MethodChannel implementation of the plugin.
```
$ flutter test
00:07 +59: All tests passed!
```
* https://github.com/flutter/flutter/issues/46045
[CLA]: …
=> [firebase_auth_platform_interface] Fix typo in the MethodChannel implementation.

packages/firebase_auth/firebase_auth_web/CHANGELOG.md, packages/firebase_auth/firebase_auth_web/pubspec.yaml, packages/firebase_auth/firebase_auth_web/test/firebase_auth_web_test.dart
Fix firebase auth test by wrapping Dart functions in js.allowInterop
And also fix the Promise.then mock. The JS version of Promise.then takes
two parameters.
Dart functions need to be wrapped in js.allowInterop to be called from
JavaScript. The current test is failing on dart2js.
=> [firebase_auth_web] Fix firebase auth test by wrapping Dart functions in js.allowInterop

packages/firebase_auth/firebase_auth_web/CHANGELOG.md, packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart, packages/firebase_auth/firebase_auth_web/pubspec.yaml, packages/firebase_auth/firebase_auth_web/test/firebase_auth_web_test.dart, packages/firebase_auth/firebase_auth_web/test/mock/firebase_mock.dart
Prevent `null` users (unauthenticated) from breaking the `onAuthStateChanged` stream.
* https://github.com/FirebaseExtended/flutterfire/issues/1685
=> [firebase_auth_web] Add null check to _fromJsUser.

packages/cloud_firestore/cloud_firestore/example/lib/main.dart
Firestore example risks widgets not being initialized resulting in an exception eg: `E/flutter (32544): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.`. This PR adds `WidgetsFlutterBinding.ensureInitialized()` to ensure that this exception is avoided.
=> Ensure Firestore example widgets are initialized

AUTHORS, packages/cloud_functions/cloud_functions/CHANGELOG.md, packages/cloud_functions/cloud_functions/android/src/main/java/io/flutter/plugins/firebase/cloudfunctions/CloudFunctionsPlugin.java, packages/cloud_functions/cloud_functions/ios/Classes/CloudFunctionsPlugin.m, packages/cloud_functions/cloud_functions/pubspec.yaml
Solves the error `No implementation found for method CloudFunctions#call` introduced in the `0.4.1+7` release
#1866 
It even solves a break from the `0.4.1+7` release
=> [cloud_functions] No implementation found for method CloudFunctions#call

packages/firebase_auth/firebase_auth/CHANGELOG.md, packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java, packages/firebase_auth/firebase_auth/pubspec.yaml
This was caught during google3 roll. When `confirmPasswordReset` is called, it will throw a `notImplemented` error since there's no break in the case statement.
=> Fix fallthrough bug

packages/firebase_auth/firebase_auth_web/CHANGELOG.md, packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart, packages/firebase_auth/firebase_auth_web/pubspec.yaml
Implements the missing auth behavior for web except for  `verifyPhoneNumber`.
#1682 
=> [firebase_auth] implement missing auth functionality for web

packages/cloud_functions/cloud_functions_web/.metadata, packages/cloud_functions/cloud_functions_web/CHANGELOG.md, packages/cloud_functions/cloud_functions_web/android/.gitignore, packages/cloud_functions/cloud_functions_web/android/build.gradle, packages/cloud_functions/cloud_functions_web/android/gradle.properties, packages/cloud_functions/cloud_functions_web/android/gradle/wrapper/gradle-wrapper.properties, packages/cloud_functions/cloud_functions_web/android/settings.gradle, packages/cloud_functions/cloud_functions_web/android/src/main/AndroidManifest.xml, packages/cloud_functions/cloud_functions_web/android/src/main/kotlin/com/example/cloud_functions_web/CloudFunctionsWebPlugin.kt, packages/cloud_functions/cloud_functions_web/android/src/main/kotlin/io/flutter/plugins/cloud_functions_web/CloudFunctionsWebPlugin.kt, packages/cloud_functions/cloud_functions_web/ios/cloud_functions_web.podspec, packages/cloud_functions/cloud_functions_web/pubspec.yaml
To make builds work for iOS and Android, this PR adds no-op plugin stubs for the `cloud_functions_web` plugin for those platforms.
flutter/flutter#45299
=> [cloud_functions] create no-op stubs for iOS/Android in cloud_functions_web

.gitignore, packages/firebase_analytics/firebase_analytics/CHANGELOG.md, packages/firebase_analytics/firebase_analytics/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java, packages/firebase_analytics/firebase_analytics/pubspec.yaml, packages/firebase_core/firebase_core/CHANGELOG.md, packages/firebase_core/firebase_core/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java, packages/firebase_core/firebase_core/pubspec.yaml, packages/firebase_crashlytics/CHANGELOG.md, packages/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/firebasecrashlytics/FirebaseCrashlyticsPlugin.java, packages/firebase_crashlytics/pubspec.yaml
- fix overrides a deprecated API
- firebase_analytics and firebase_crashlytics Raise minimum required Flutter SDK version to 1.12.13+hotfix.4
#1703 
#1650 
#1389 
- [X ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs. …
=> [firebase_core, firebase_analytics, firebase_crashlytics] fix overrides a deprecated API

packages/cloud_firestore/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/cloud_firestore/example/test_driver/cloud_firestore.dart, packages/cloud_firestore/cloud_firestore/lib/src/query.dart, packages/cloud_firestore/cloud_firestore/pubspec.yaml
This fix ensures that all values passed to `Query#where` is encoded properly before the query get passed to the platform interface. 
#1954 
=> [cloud_firestore] Fix crashes when using DocumentReference with Query

packages/cloud_firestore/cloud_firestore_web/CHANGELOG.md, packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
During a file renaming a pubspec.yaml property slipped through the cracks. This change fixes it.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/1973
=> [cloud_firestore_web] Fix fileName prop in pubspec.yaml

packages/cloud_firestore/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/cloud_firestore/example/web/index.html, packages/cloud_firestore/cloud_firestore/pubspec.yaml
This change endorses `cloud_firestore_web` as the official implementation of `cloud_firestore` for the Web target.
It also adds web support to the `example` app.
Fixes https://github.com/flutter/flutter/issues/45293 …
=> [cloud_firestore] Endorse cloud_firestore_web.

README.md, packages/cloud_firestore/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/cloud_firestore/README.md, packages/cloud_firestore/cloud_firestore/pubspec.yaml, packages/cloud_firestore/cloud_firestore_web/CHANGELOG.md, packages/cloud_firestore/cloud_firestore_web/README.md, packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
* Mark cloud_firestore and cloud_functions as being Web ready in main README support matrix.
* Add more detailed setup instructions about the Web platform on READMEs.
* Update install instructions post-federation.
flutter/flutter#45293 …
=> [cloud_firestore, cloud_firestore_web] Update Firestore web documentation.

packages/cloud_firestore/cloud_firestore_web/CHANGELOG.md, packages/cloud_firestore/cloud_firestore_web/pubspec.yaml, packages/cloud_firestore/cloud_firestore_web/test/field_value_factory_web_test.dart
The problematic test was attempting to coerce a wrong type into a function call, and that causes problems in environments where linting is more strict. Remove the test, since it's not actually testing our functionality, but dart-lang's.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/1991 …
=> [cloud_firestore_web] Remove unit test that was only testing dart-lang.

packages/firebase_admob/CHANGELOG.md, packages/firebase_admob/android/src/main/java/io/flutter/plugins/firebaseadmob/FirebaseAdMobPlugin.java, packages/firebase_admob/android/src/main/java/io/flutter/plugins/firebaseadmob/RewardedVideoAdWrapper.java, packages/firebase_admob/ios/Classes/FLTFirebaseAdMobPlugin.m, packages/firebase_admob/ios/Classes/FLTRewardedVideoAdWrapper.h, packages/firebase_admob/ios/Classes/FLTRewardedVideoAdWrapper.m, packages/firebase_admob/lib/firebase_admob.dart, packages/firebase_admob/pubspec.yaml, packages/firebase_admob/test/firebase_admob_test.dart
Enable the use of custom parameters for [rewarded video Server-side verification callbacks](https://developers.google.com/admob/android/rewarded-video-ssv)
I added setter methods for the custom parameters `user_id` and `custom_data`. Two new methods have been added to the by RewardedVideoAd class. I tried to keep them similar to the methods used in the android implementation
[`setUserId(String userId)`)](https://developers.google.com/android/reference/com/google/android/gms/ads/reward/RewardedVideoAd#setUserId(java.lang.String))
[`setCustomData(String userId)`](https://developers.google.com/android/reference/com/google/android/gms/ads/reward/RewardedVideoAd#setCustomData(java.lang.String))
FirebaseExtended/flutterfire#164
flutter/flutter#33033
Before you create this PR confirm that it …
=> [firebase_admob] Parameters for rewarded video SSV Callbacks

packages/firebase_core/firebase_core_platform_interface/CHANGELOG.md, packages/firebase_core/firebase_core_platform_interface/lib/firebase_core_platform_interface.dart, packages/firebase_core/firebase_core_platform_interface/pubspec.yaml, packages/firebase_core/firebase_core_platform_interface/test/firebase_core_platform_interface_test.dart
Migrates `firebase_core_platform_interface` to use `plugin_platform_interface`
Partially addresses https://github.com/FirebaseExtended/flutterfire/issues/2064
=> [firebase_core_platform_interface] Migrate to plugin_platform_interface

packages/firebase_core/firebase_core/CHANGELOG.md, packages/firebase_core/firebase_core/pubspec.yaml, packages/firebase_core/firebase_core/test/firebase_core_test.dart
Updates `firebase_core` to use version `1.0.4` of the platform interface, which also requires modifying the tests.
Partially addresses https://github.com/FirebaseExtended/flutterfire/issues/2064
[CLA]: …
=> [firebase_core] Update to use new platform interface

packages/firebase_auth/firebase_auth_platform_interface/CHANGELOG.md, packages/firebase_auth/firebase_auth_platform_interface/lib/firebase_auth_platform_interface.dart, packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml, packages/firebase_auth/firebase_auth_platform_interface/test/firebase_auth_platform_interface_test.dart
Updates the `firebase_auth` platform interface to use `package:plugin_platform_interface`.
Partially addresses https://github.com/FirebaseExtended/flutterfire/issues/2064 and https://github.com/FirebaseExtended/flutterfire/issues/1939 …
=> [firebase_auth_platform_interface] Use plugin_platform_interface

packages/cloud_firestore/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/cloud_firestore/example/run-tests-web, packages/cloud_firestore/cloud_firestore/example/test_driver/cloud_firestore.dart, packages/cloud_firestore/cloud_firestore/lib/src/utils/platform_utils.dart, packages/cloud_firestore/cloud_firestore/pubspec.yaml, packages/cloud_firestore/cloud_firestore_web/CHANGELOG.md, packages/cloud_firestore/cloud_firestore_web/lib/src/field_value_factory_web.dart, packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
This change reproduces the issue reported in #2044 with an Integ test, and fixes it.
While running Integ tests, I discovered some extra changes required to get them all to pass (on Android, at least), and shaved that Yak.
This also fixes another encoding issue in _web that was recently introduced. Web still has one broken Integ test (re: encoding of Timestamp objects), that I'll attempt to fix next.
/cc @amrfarid140 
Closes #2044.  …
=> [cloud_firestore, cloud_firestore_web] Fix encoding issues in DocumentSnapshotPlatform and FieldValueFactoryWeb

packages/firebase_crashlytics/CHANGELOG.md, packages/firebase_crashlytics/example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, packages/firebase_crashlytics/pubspec.yaml
Removes a file that shouldn't be checked in. 
https://github.com/flutter/plugins/pull/2592 - I believe this fixed the build on Cirrus for flutter/plugins, so hopefully it will do that here too.
https://github.com/FirebaseExtended/flutterfire/pull/2099 - PR waiting for this fix to land on green
=> [firebase_crashlytics] Remove WorkspaceSettings.xcsettings

packages/firebase_admob/CHANGELOG.md, packages/firebase_admob/README.md, packages/firebase_admob/pubspec.yaml
Added note about GoogleService-list.plist which is not required in order to use Admob's latest version.  Without this file, the app will crash on startup.
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review …
=> [Firebase-Admob]Added note about GoogleService-list.plist

packages/cloud_firestore/cloud_firestore_platform_interface/README.md
=> [cloud_firestore] Fix firebase <-> firestore typo in platform_interface README

packages/firebase_admob/CHANGELOG.md, packages/firebase_admob/pubspec.yaml
https://github.com/FirebaseExtended/flutterfire/pull/2106 didn't bump the version, so adds the version bump.
=> [firebase_admob] Bump admob version for iOS Native Ads

packages/cloud_firestore/cloud_firestore_platform_interface/test/method_channel_cloud_firestore_test.dart
Even though my last push didn't have conflicts with the base branch (according to Github), there was a change that I missed:
https://github.com/FirebaseExtended/flutterfire/commit/4d7b2bdd7fbdee65551754968b140653ea16128f#diff-e36a6cd96b7ef43422dfb1197627e7f8
I fixed the same issue in my change, but deleting the OTHER 'source' key in the map:
https://github.com/FirebaseExtended/flutterfire/commit/bd9bcd49f7dffe757df48bed54f0cb67552c2eec#diff-e36a6cd96b7ef43422dfb1197627e7f8
The result is now that the file has zero entries in said Map, and tests broke in `master`.
This commit reverts my part of the change, so tests pass again.
* https://cirrus-ci.com/task/5459203800170496?command=test#L175
Before you create this PR confirm that it meets all requirements listed below by checking the relevant …
=> [cloud_firestore_platform_interface] Fix three-way merge in test file.

packages/firebase_admob/CHANGELOG.md, packages/firebase_admob/README.md, packages/firebase_admob/pubspec.yaml
As of version 0.9.3 of the firebase_admob plugin, native ads are supported (at least for the basic part), so took out a line that says "There's no support for native ads." from README.md.
[CLA]: …
=> [firebase_admob] Deleted a line from README.md about not supporting native ads

packages/firebase_database/CHANGELOG.md, packages/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/MethodCallHandlerImpl.java, packages/firebase_database/example/test_driver/firebase_database_e2e.dart, packages/firebase_database/pubspec.yaml
Dart `int` value is passed to Android as a Long or Integer depending on the size of the value.
Fixes #81
=> fix(database): fix #81 - setPersistenceCacheSizeBytes call on Android

.cirrus.yml
This same change as: https://github.com/flutter/plugins/pull/2710.
It should fix the iOS simulator creation failures on CI.
https://github.com/FirebaseExtended/flutterfire/issues/2499
=> Use the catalina xcode 11.3.1 osx_instance on CI

packages/cloud_functions/cloud_functions/CHANGELOG.md, packages/cloud_functions/cloud_functions/example/android/gradle.properties, packages/cloud_functions/cloud_functions/pubspec.yaml, packages/cloud_functions/cloud_functions_platform_interface/CHANGELOG.md, packages/cloud_functions/cloud_functions_platform_interface/pubspec.yaml, packages/cloud_functions/cloud_functions_web/CHANGELOG.md, packages/cloud_functions/cloud_functions_web/pubspec.yaml
Fix for CI failures highlighted in #2499.
- Added missing `gradle.properties` AndroidX properties to `cloud_functions` example repository
- Updated environment SDK version range to fix `Packages with an SDK constraint on a pre-release of the Dart SDK should themselves be published as a pre-release version. If this package needs Dart version 2.0.0-dev.28.0, consider publishing the package as a pre-release instead.` CI publishable issue.
- #2499  - "CI is red" …
=> fix(cloud_functions): ci failures

packages/firebase_admob/CHANGELOG.md, packages/firebase_admob/pubspec.yaml
A recent pub publish check requires a non release Dart SDK, bumping the requirement so we don't get the warning.
This change is a no-op as the minimally required Flutter version for v2 embedding is (1.12.13+hotfix.5) and it already requires Dart 2.7.0.
=> [firebase_admob] Bump dart version requirement

packages/firebase_auth/firebase_auth_web/CHANGELOG.md, packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart, packages/firebase_auth/firebase_auth_web/pubspec.yaml
This adds the `confirmPasswordReset` implementation to `firebase_auth_web`. Currently missing.
* None I could see.
/cc @hterkelsen
/cc @bparrishMines
=> feat(firebase_auth_web): add support for `confirmPasswordReset`

packages/firebase_crashlytics/README.md
Recommended to use runZonedGuarded instead runZoned with Flutter 1.17
=> Update Readme to use runZonedGuarded

packages/firebase_analytics/firebase_analytics/README.md
https://codelabs.developers.google.com/codelabs/flutter-firebase/#4 contains irrelevant steps for building a UI
The right Url for platform-specific steps is https://codelabs.developers.google.com/codelabs/flutter-firebase/#6
=> Update readme with correct link for config steps

packages/cloud_firestore/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java, packages/cloud_firestore/cloud_firestore/pubspec.yaml
TL;dr: Remove Android Firestore listeners when the host Activity is destroyed or the engine is detached.
The Cloud Firestore plugins does not currently clean up listeners after the user leaves the app on Android. This results in snapshot listeners sticking around even though associated resources like the channel is no longer available.
When a change occurs to the data, the stranded listeners try to report the updates via the channel that is no longer available. This results in a null pointer exception.
This PR uses lifecycle callbacks of both v1 and v2 embedding to remove listeners before either the app's Activity is destroyed (v1) or the Flutter engine is detached (v2).
fixes #2517 
fixes #2390 
Before you create this PR confirm that it meets all requirements listed below by checking the …
=> [cloud_firestore] Clean up Android Firestore listeners

packages/firebase_analytics/firebase_analytics/test/observer_test.dart
A part of a test is breaking in `master`, seemingly because of a change in Dart behavior. Comment out the test until the root cause is found.
https://github.com/FirebaseExtended/flutterfire/issues/2850
[CLA]: …
=> [firebase_analytics] Disable expectation that breaks in flutter master.

packages/firebase_remote_config/CHANGELOG.md, packages/firebase_remote_config/lib/src/remote_config.dart, packages/firebase_remote_config/pubspec.yaml
Any error thrown by `RemoteConfig.fetch` that doesn't have the code `fetchFailedThrottled` is "swallowed" because we're only returning the string "Unable to fetch remote config". This PR replaces the generic message with the message returned from the native side in order to improve debuggability (if this word exists 😅 ).
I couldn't find one related to this specific problem. …
=> [remote_config] Propagate native error message on #fetch

packages/firebase_analytics/firebase_analytics_web/CHANGELOG.md, packages/firebase_analytics/firebase_analytics_web/ios/firebase_analytics_web.podspec, packages/firebase_analytics/firebase_analytics_web/pubspec.yaml
We [tried to endorse](https://github.com/FirebaseExtended/flutterfire/pull/2794) this plugin as the web implementation of **firebase_analytics** but the integration tests failed due to missing ios files. This PR adds those missing files.
flutter/flutter#45289 …
=> [firebase_analytics_web] Add missing iOS files

packages/firebase_crashlytics/CHANGELOG.md, packages/firebase_crashlytics/lib/src/firebase_crashlytics.dart, packages/firebase_crashlytics/pubspec.yaml, packages/firebase_crashlytics/test/firebase_crashlytics_test.dart
Put current stack trace into report if no other stack trace is supplied. This may give a clue if `reportError` was called manually.
=> [firebase_crashlytics] Use current stacktrace when null

packages/firebase_crashlytics/README.md
Add documentation on installing an error listener on Isolate
=> [firebase_crashlytics] Add documentation on installing an error listener on Isolate

packages/firebase_dynamic_links/CHANGELOG.md, packages/firebase_dynamic_links/README.md, packages/firebase_dynamic_links/example/lib/main.dart, packages/firebase_dynamic_links/ios/Classes/FLTFirebaseDynamicLinksPlugin.m, packages/firebase_dynamic_links/pubspec.yaml
Description:
This is my first contribution to this project so I'm sorry if I made this in improper way.
Fix race conditions related to the dynamic links initialization process.
1. During installation flow `- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation` might be called by OS after `FirebaseDynamicLinks.instance.getInitialLink()` is called. In such a case the app won't retrieve the deep-link.
2. If `FirebaseDynamicLinks.instance.getInitialLink()` is called while processing `[FIRDynamicLinks dynamicLinks]  openURL:(NSURL *)url handleUniversalLink`, the url is lost.
3. Documentation fix: `FirebaseDynamicLinks.instance.getInitialLink()` call should be called after …
=> [dynamic_links]: fix initialization process

packages/firebase_core/firebase_core/ios/Classes/FLTFirebasePlugin.h
This issue relates to the new Firebase Core as per #2582.
Fixes an issue that causes MacOS builds to fail due to Swift usage. Copy of https://github.com/invertase/flutterfire/pull/28/commits/f2147b12bfc8e46cac3a6a13ea776874d0eafb37
Example failure can be seen here: https://github.com/invertase/flutterfire/runs/832934288 with this change applied CI now passes: https://github.com/invertase/flutterfire/runs/838908028
Before you create this PR confirm that it meets all requirements listed below by checking the relevant …
=> fix(core,macos): don't use umbrella Firebase header

packages/firebase_core/firebase_core_platform_interface/lib/firebase_core_platform_interface.dart, packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_core_exceptions.dart, packages/firebase_core/firebase_core_platform_interface/pubspec.yaml
These plugins should be very selective of which packages they depend on since they are core functionality to many Flutter apps. Let's avoid creating dependencies outside of the core Flutter/Dart packages.
=> chore(firebase_core): remove dependency on 'universal_platform'

packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_transaction.dart, packages/cloud_firestore/cloud_firestore_platform_interface/test/method_channel_tests/method_channel_transaction_test.dart
Assertion on ensuring that all reads (via `get`) on transactions are updated is no longer required.
N/A
=> fix(cloud_firestore): remove get-write validation

packages/firebase_core/firebase_core/CHANGELOG.md, packages/firebase_core/firebase_core/pubspec.yaml, packages/firebase_core/firebase_core_platform_interface/CHANGELOG.md, packages/firebase_core/firebase_core_platform_interface/pubspec.yaml, packages/firebase_core/firebase_core_web/CHANGELOG.md, packages/firebase_core/firebase_core_web/pubspec.yaml
Version bump in preparation for publishing the updated `firebase_core` plugin. This will be a "pre release" version of the core plugin. Bumping to `v0.5.0-dev.1`. `firebase_core_web` and `firebase_core_platform_interface` are also bumped in a similar way.
=> chore(firebase_core): bump core versions

packages/cloud_firestore/cloud_firestore/test/collection_reference_test.dart, packages/cloud_firestore/cloud_firestore/test/document_reference_test.dart
Adds additional tests to collection & document reference equality checks.
Closes https://github.com/FirebaseExtended/flutterfire/pull/2524 (problem has been resolved via rework).
=> tests(cloud_firestore): add additional equality tests

packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/timestamp.dart, packages/cloud_firestore/cloud_firestore_platform_interface/test/timestamp_test.dart
- Ensures out of range math values are rounded down.
- Adds Timestamp tests
Fixes https://github.com/FirebaseExtended/flutterfire/issues/1222
=> fix(firestore): add timestamp tests & fix

packages/cloud_firestore/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/cloud_firestore/pubspec.yaml, packages/cloud_firestore/cloud_firestore_platform_interface/CHANGELOG.md, packages/cloud_firestore/cloud_firestore_platform_interface/pubspec.yaml, packages/cloud_firestore/cloud_firestore_web/CHANGELOG.md, packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
In preparation for Firestore prerelease versions, update Firestore to depend on Firebase Core prerelease versions.
=> chore(release): prerelease cloud_firestore* packages

packages/firebase_auth/firebase_auth/README.md
The **google_sign_in** package from [pub.dev/packages/google_sign_in](https://pub.dev/packages/google_sign_in) is being used but no import statement is mentioned for the same in the README. And it is mandatory to import the google_sign_in package for creating an instance of GoogleSignIn i.e. working with Google Authentication.
* This PR simply places an import statement for the package - **google_sign_in**.
* Beginners might come across the documentation and be confused as to what else is needed to import for Google auth.
* This slightly makes it insightful for the document reader that he/she needs to import the google_sign_in package from pub.dev [link provided above].
* In fact the firebase_auth documentation for auth does mention using the plugin to implement Google authentication, but …
=> docs(auth): add missing import statement for google sign-in

packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart
The CI is currently failing randomly on the `endBeforeDocument` tests. The previous test shares the same collection path, so I believe this may be causing the issue.
=> tests(cloud_firestore): add unique query test path

packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart
Attempts to remove another query flake by using a unique ID. See https://github.com/FirebaseExtended/flutterfire/pull/2931/checks?check_run_id=859462526
https://github.com/FirebaseExtended/flutterfire/pull/2931
=> tests(cloud_firestore): add unique query test path (2)

packages/cloud_functions/cloud_functions/CHANGELOG.md, packages/cloud_functions/cloud_functions/pubspec.yaml, packages/cloud_functions/cloud_functions_platform_interface/CHANGELOG.md, packages/cloud_functions/cloud_functions_platform_interface/pubspec.yaml, packages/cloud_functions/cloud_functions_web/CHANGELOG.md, packages/cloud_functions/cloud_functions_web/pubspec.yaml
Move the functions plugin to use the v1 core plugin.
=> chore: migrate functions to use new core plugin

packages/cloud_firestore/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_collection_reference.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_document_reference.dart, packages/cloud_firestore/cloud_firestore_platform_interface/test/platform_interface_tests/platform_interface_collection_reference_test.dart, packages/cloud_firestore/cloud_firestore_platform_interface/test/platform_interface_tests/platform_interface_document_reference_test.dart
This expands on #2929: I think the collection reference was missing the `==` override and it also seems to make more sense to check if the pointers are equal rather than the paths, which are derived from the pointers. Essentially, this makes changing the `Pointer` behavior more easily.
Additionally, I added some tests that ensure that no regression occurs. The changelog entries that @IchordeDionysos added already reflect exactly what these changes do, so there is no need for another entry.
#2929 …
=> fix(firestore): collection and document equality checking

docs/auth/social.mdx, docs/firestore/overview.mdx, docs/firestore/usage.mdx, docs/versions.js, website/api.js, website/docusaurus-plugins/source-api-reference.js, website/docusaurus-plugins/source-versions.js, website/docusaurus.config.js, website/src/theme/MDXComponents/index.tsx
Updates the documentation website with the following changes:
- Uses the latest published version (not `latest`) to include pre-releases.
- Updates Firestore docs to work with latest changes.
- Allows outbound reference links to work with the current version.
- Moves social auth 3rd party plugins to use versions config.
- Fixes the edit link going to `next`, it now points to `master`.
=> docs: use latest plugin versions

packages/cloud_firestore/cloud_firestore/CHANGELOG.md
This fixes something that I introduced in #2931. It seems like there was a very weird Git diff bug there because I had it exactly like this in my local file 😶 (the diff on GitHub showed the opposite, i.e. `[UNPUBLISHED]` was still there and I added the version 🤷🏽‍♀️
=> docs(cloud_firestore): update changelog

README.md, packages/cloud_firestore/cloud_firestore/README.md, packages/cloud_functions/cloud_functions/README.md, packages/firebase_admob/README.md, packages/firebase_analytics/firebase_analytics/README.md, packages/firebase_auth/firebase_auth/README.md, packages/firebase_core/firebase_core/README.md, packages/firebase_crashlytics/README.md, packages/firebase_database/README.md, packages/firebase_dynamic_links/README.md, packages/firebase_in_app_messaging/README.md, packages/firebase_messaging/README.md, packages/firebase_ml_vision/README.md, packages/firebase_performance/README.md, packages/firebase_remote_config/README.md, packages/firebase_storage/README.md
There are three changes: 
* Flutter**F**ire typo
* Comma before "and" (not an enumeration, so there should not be one)
* "send a pull request" → "open a pull request"; I think that "open" is idiomatic in this context
I did not add any changelog entries because I do not think that it is worth mentioning. …
=> docs: fix readme typos

packages/cloud_firestore/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/cloud_firestore/ios/cloud_firestore.podspec, packages/cloud_firestore/cloud_firestore/macos/cloud_firestore.podspec
Define the module by setting `DEFINES_MODULE` in the podspec.  
> If enabled, the product will be treated as defining its own module. This enables automatic production of LLVM module map files when appropriate, and allows the product to be imported as a module.
See also [CocoaPod modular headers docs](http://blog.cocoapods.org/CocoaPods-1.5.0/).
https://github.com/FirebaseExtended/flutterfire/issues/1258
=> [cloud_firestore] Allow iOS and macOS to be imported as a module

packages/firebase_core/firebase_core/CHANGELOG.md, packages/firebase_core/firebase_core/ios/firebase_core.podspec, packages/firebase_core/firebase_core/macos/firebase_core.podspec, packages/firebase_core/firebase_core/pubspec.yaml
Define the module by setting `DEFINES_MODULE` in the podspec.  
> If enabled, the product will be treated as defining its own module. This enables automatic production of LLVM module map files when appropriate, and allows the product to be imported as a module.
See also [CocoaPod modular headers docs](http://blog.cocoapods.org/CocoaPods-1.5.0/).
https://github.com/FirebaseExtended/flutterfire/issues/1258
=> feat(firebase_core): allow iOS/macOS to be imported as a module

packages/cloud_firestore/cloud_firestore/example/test_driver/document_reference_e2e.dart, packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart, packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/document_reference_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/transaction_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/utils/exception.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/write_batch_web.dart
Currently, Firestore web errors throw an internal Firebase error. This change wraps all delegate calls and catches errors, ensuring a `FirebaseException` is thrown to mimic native behaviour.
=> fix(cloud_firestore): throw FirebaseException on web errors

packages/firebase_dynamic_links/CHANGELOG.md, packages/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebasedynamiclinks/FirebaseDynamicLinksPlugin.java, packages/firebase_dynamic_links/lib/src/firebase_dynamic_links.dart, packages/firebase_dynamic_links/pubspec.yaml, packages/firebase_dynamic_links/test/firebase_dynamic_links_test.dart
[iOS FIRDynamicLink#url](https://firebase.google.com/docs/reference/ios/firebasedynamiclinks/api/reference/Classes/FIRDynamicLink#url) and [Android PendingDynamicLinkData#getLink()](https://firebase.google.com/docs/reference/android/com/google/firebase/dynamiclinks/PendingDynamicLinkData#public-uri-getlink) may return nil/null. In sucha a case we get to the following stack trace:
```
flutter: Stack Trace:
flutter: #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
flutter: #1      Uri.parse  (dart:core/uri.dart:794:17)
flutter: #2      FirebaseDynamicLinks.getPendingDynamicLinkDataFromMap 
package:firebase_dynamic_links/src/firebase_dynamic_links.dart:67
flutter: #3      FirebaseDynamicLinks.getInitialLink 
package:firebase_dynamic_links/src/firebase_dynamic_links.dart:3 …
```
=> [firebase_dynamic_links]: fix plugin crash when link is null

packages/firebase_ml_vision/CHANGELOG.md, packages/firebase_ml_vision/lib/src/image_labeler.dart, packages/firebase_ml_vision/lib/src/text_recognizer.dart, packages/firebase_ml_vision/pubspec.yaml, packages/firebase_ml_vision/test/firebase_ml_vision_test.dart, packages/firebase_ml_vision/test/image_labeler_test.dart
When `confidence` (used by `ImageLabel` and `TextContainer`) is 1 or 0 and the value is passed over the channel, on the Dart side it is decoded as `int`, which leads to the following error:
```
Unhandled Exception: type 'int' is not a subtype of type 'double'
```
This fix forces the value to be interpreted as `double`.
Does your PR require plugin …
=> [firebase_ml_vision] Bug fix: if confidence is 1 or 0 it is decoded as int

AUTHORS, packages/cloud_functions/cloud_functions/CHANGELOG.md, packages/cloud_functions/cloud_functions/android/src/main/java/io/flutter/plugins/firebase/cloudfunctions/CloudFunctionsPlugin.java
Fixes HttpsCallable#call not working with a String (or any other type which is not a Map) parameter on Android
#2492
=> [cloud_functions] Fix callable parameter type support on Android

packages/firebase_auth/firebase_auth/CHANGELOG.md, packages/firebase_auth/firebase_auth/example/pubspec.yaml, packages/firebase_auth/firebase_auth/pubspec.yaml
Use new core (dev version) in Auth example since auth plugin already depends on new core.
=> [firebase_auth] Update example in Auth to use new core

packages/firebase_auth/firebase_auth/example/lib/signin_page.dart
Should say sign in here for more clarity
=> [Firebase_auth] Text says register instead of sign in auth example

packages/firebase_ml_custom/example/lib/main.dart, packages/firebase_ml_custom/example/pubspec.yaml, packages/firebase_ml_vision/CHANGELOG.md, packages/firebase_ml_vision/README.md, packages/firebase_ml_vision/android/src/main/java/io/flutter/plugins/firebasemlvision/TextRecognizer.java, packages/firebase_ml_vision/example/lib/picture_scanner.dart, packages/firebase_ml_vision/example/pubspec.yaml, packages/firebase_ml_vision/example/test_driver/text_recognizer.dart, packages/firebase_ml_vision/ios/Classes/TextRecognizer.m, packages/firebase_ml_vision/lib/src/firebase_vision.dart, packages/firebase_ml_vision/lib/src/text_recognizer.dart, packages/firebase_ml_vision/pubspec.yaml, packages/firebase_ml_vision/test/firebase_ml_vision_test.dart
Added CloudTextRecognizerOptions for cloud TextRecognizer.
Options specify hinted languages and type of image text density (sparse or dense).
In most cases, an empty value for hinted languages yields the best results since it enables automatic language detection.
However, there are cases when those hints are helpful to a user, specifically when the language is known.
Choosing 'sparse' or 'dense' option will lead the recognizer to use one of two different models, which differ by handling text densities in an image.
Options EnforceCertFingerprintMatch for Android and APIKeyOverride for IOS are **not added**.
[Flutterfire issue #2467](https://github.com/FirebaseExtended/flutterfire/issues/2467): Add support for FirebaseVisionCloudTextRecognizerOptions in the Text Recognition API
Before you …
=> [firebase_ml_vision] Options for Cloud TextRecognizer

.github/workflows/docs.yaml
Add direct trigger to docs workflow so publishing of documentation can be done on doc updates and as needed.
=> [infra] Add direct trigger for docs workflow

packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
When chaining `where` statements, the web encoded FieldPath key/values were being encoded before required, throwing a JS object error.
Fixes #3171 
=> fix(cloud_firestore): web - remove encode on "where" delegate

packages/cloud_firestore/cloud_firestore/lib/src/query.dart
Calling `FieldPath.documentId` returns an internal `FieldPathType`. This allows users to use this sentinel value as a query field.
Fixes #3171
=> fix(cloud_firestore): allow FieldPath.documentId as query field

packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart, packages/cloud_firestore/cloud_firestore/lib/src/query.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
Currently `orderBy` assumes the field to be a FieldPath or String - this adds a check for FieldPathTypes, plus additional tests and cleanup.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/3210
[CLA]: …
=> fix(cloud_firestore): add FieldPathType check & tests

packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_document_reference.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_query.dart
Fixes 2 race conditions:
1. When a snapshot stream unsubscribes, the Dart Stream is removed at the same time an async request to remove the native listener is sent. In some cases, an event is sent from native before the native listener has been removed, but after the Dart Stream is removed, causing an assertion error.
2. If a widget updates in a very short period of time, the `onCancel` stream handler is called pretty much straight away. Since setting up the stream handler takes longer than removing, in some edge cases it's trying to remove a listener which hasn't been created.
- https://github.com/FirebaseExtended/flutterfire/issues/3222
- https://github.com/FirebaseExtended/flutterfire/issues/3237
Before you create this PR confirm that it meets all requirements listed below by checking …
=> fix(cloud_firestore): prevent snapshot race conditions

website/docusaurus.config.js
Add Google Analytics to FlutterFire documentation.
=> [docs] Add Google Analytics to Docs

website/docusaurus.config.js
Google Analytics docusauras plugin does not seem to work. Trying the gtag plugin instead.
=> [docs] Try gtag for docs analytics

docs/overview.mdx
There was a copy/paste bug where the Android version was used for the iOS Pod version.  @Salakar asked me to submit a PR to fix it.
Related to #3328.
=> docs: corrected bad iOS pod version for Firebase SDK

packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
Secondary apps correctly get the cached authenticated user, however on iOS, the default app user was always being returned and setting the current user (for the wrong app instance).
Fixes https://github.com/FirebaseExtended/flutterfire/issues/3283 …
=> fix(firebase_auth): use correct FIRAuth instance on for listeners

packages/firebase_auth/firebase_auth/example/lib/signin_page.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/action_code_settings.dart, packages/firebase_auth/firebase_auth_platform_interface/test/action_code_settings_test.dart, packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_tests/method_channel_user_test.dart, packages/firebase_auth/firebase_auth_web/lib/utils.dart
The current implementation of the `android` and `iOS` keys on `ActionCodeSettings` is error prone. 
This PR deprecates those dynamic maps in favour of named arguments. The logic attempts to use the new arguments and falls back to the deprecated ones.
https://github.com/FirebaseExtended/flutterfire/issues/3259 …
=> feat(firebase_auth): use named arguments for ActionCodeSettings

packages/cloud_firestore/cloud_firestore/CHANGELOG.md, packages/cloud_firestore/cloud_firestore/lib/src/document_snapshot.dart, packages/cloud_firestore/cloud_firestore/test/document_snapshot_test.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_document_snapshot.dart, packages/cloud_firestore/cloud_firestore_platform_interface/test/platform_interface_tests/platform_interface_document_snapshot_test.dart
Add a [] operator to DocumentSnapshot, acting as get()
No issues, but the idea came up [here](https://github.com/FirebaseExtended/flutterfire/discussions/3369#discussioncomment-58145)
[CLA]: …
=> feat(cloud_firestore): add a [] operator to DocumentSnapshot, acting as get()

packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_firestore.dart
There's currently a race condition somewhere which causes a native event to be sent to user land after the Dart stream has been removed, causing an error/crash.
This PR adds a check to ensure events are only sent when those Streams are still available.
Although this doesn't fully solve the issue, it does prevent crashes. I don't think there is any side effects here, since if the Dart listener is removed users don't care about the events anyway.
Resolves https://github.com/FirebaseExtended/flutterfire/issues/3222 & https://github.com/FirebaseExtended/flutterfire/issues/3382 …
=> fix(firebase_auth): check for Stream existence before sending event

packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/blob.dart
No behavior was changed. Document was spelled as "documnent" in the description of the `update` method for the `DocumentReference` class. This was changed to the correct spelling of "document"
No related issues. …
=> docs(cloud_firestore): Fixed docs typo

packages/firebase_crashlytics/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/Constants.java, packages/firebase_crashlytics/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/FlutterFirebaseCrashlyticsPlugin.java, packages/firebase_crashlytics/firebase_crashlytics/example/lib/main.dart, packages/firebase_crashlytics/firebase_crashlytics/example/test_driver/firebase_crashlytics_e2e.dart, packages/firebase_crashlytics/firebase_crashlytics/ios/Classes/FLTFirebaseCrashlyticsPlugin.m, packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart, packages/firebase_crashlytics/firebase_crashlytics/test/firebase_crashlytics_test.dart, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/lib/src/method_channel/method_channel_crashlytics.dart, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/lib/src/platform_interface/platform_interface_crashlytics.dart, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/test/method_channel_tests/method_channel_crashlytics_test.dart
The `context` parameter of `recordError()` should be renamed to `reason` as it's very easy to be confused with Flutter's `BuildContext` `context` parameter that's very common on Flutter Widgets.
Also, `reason` matches the iOS API, and the Firebase Console uses `reason` to show this `String`:
I am not experienced with iOS, I didn't see any method channel code in the iOS folder so I don't know how this breaking change will affect iOS devices.
I also changed one of the tests to add a `contain` clause to the test file path. I don't think it was breaking for any changes that I did, maybe it's a difference in IDE or OS behavior, so I thought `contains` would make it more generic.
Closes #1542
Before you create this PR confirm that it meets all requirements listed below by checking the relevant …
=> refactor(firebase_crashlytics): changes context to reason (#1542)

packages/firebase_crashlytics/firebase_crashlytics/CHANGELOG.md, packages/firebase_crashlytics/firebase_crashlytics/pubspec.yaml, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/CHANGELOG.md, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/pubspec.yaml
Promoting Crashlytics to a stable release version. Additionally includes changes from https://github.com/FirebaseExtended/flutterfire/pull/3334.
N/A
=> chore: promote Crashlytics to stable

docs/auth/social.mdx
The example for Apple Sign-In was tested on iOS. It's supposed to work on Android as well (Android currently seems broken due to [this issue](https://github.com/firebase/firebase-android-sdk/issues/1943))
*Provide code example for Sign-In with apple*
*Not applicable*
*Not applicable - no code changes*
=> Add example for Sign-In with Apple

AUTHORS, docs/installation/android.mdx
This PR updated the [paragraph](https://firebase.flutter.dev/docs/installation/android#generating-a-firebase-project-configuration-file) that talks about adding the package name when setting up Firebase for Android to match the [official documentation](https://firebase.google.com/docs/android/setup#register-app).
Fixes [3698]
[3698]: https://github.com/FirebaseExtended/flutterfire/issues/3698 …
=> docs: update section on Android package name

docs/overview.mdx
From "initilization" to "initialization".
=> docs: fix typo in getting started guide

packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
Ensures that listeners are removed only if they're available.
Fixes #3354
=> fix(cloud_firestore): remove listener if available

packages/firebase_admob/pubspec.yaml, packages/firebase_messaging/lib/firebase_messaging.dart, packages/firebase_messaging/pubspec.yaml, packages/firebase_messaging/test/firebase_messaging_test.dart
`platform` package is currently causing issues with versioning. Removing for now. 
Not in use on `admob` anyway.
=> fix: remove `platform` package usage

docs/crashlytics/overview.mdx
This fixes a small error in the crashlytics overview docs where it is incorrectly stated that the plugin should be applied at the bottom of the file.
- [Issue #3741](https://github.com/FirebaseExtended/flutterfire/issues/3741)
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-re …
=> docs(firebase_crashlytics): corrects plugin apply location

packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
The `isCollectionGroupQuery` flag on web is not being set, causing an assertion error.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/3751 …
=> fix(cloud_firestore): ensure isCollectionGroupQuery is initialised

packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_firestore.dart, packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
This fixes an issue (specifically for web) whereby returning a none-standard value from a transaction threw an error. This change ignores the return value of the delegate transaction handler and instead only returns the user result.
- Fixes https://github.com/FirebaseExtended/flutterfire/issues/3495
[Flutter Style …
=> fix(cloud_firestore): fix returning of transaction result

packages/firebase_crashlytics/firebase_crashlytics/pubspec.yaml
Change minimum version of stack_trace package dependency to ^1.9.3 to support the minimum flutter version we support.
I have not updated the changelog in hopes that this can make it in to the published 2.0 release... (in which case, it's not a change)
fixes #3503 
=> fix(firebase_crashlytics): Change minimum version of stack_trace package

docs/auth/usage.mdx
Use of toString() method  is not required when printing objects to the console as the print(obj) function already uses obj.toString()
cc @TahaTesser
=> docs(firebase_auth): remove use of toString() on error

docs/installation/ios.mdx, docs/installation/macos.mdx
Updates the ios and macos installation docs wording to explicitly specify a click target as "`Runner` from the left-hand ..." rather than "project name" to match the description in migration-guide.mdx.
This can help avoid confusion, since "Runner" isn't a name chosen by the user, the user may be seeing it now for the first time, and the user may be unfamiliar with Xcode (in which case they wouldn't know that the text at this specific location is indeed the project's name. …
=> docs: clarify Xcode project name

packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
=> fix(ios): don't replace `UNUserNotificationCenter` delegate when protocol conforms to `FlutterApplicationLifeCycleDelegate`

packages/firebase_core/firebase_core_web/lib/src/interop/utils/utils.dart
Iterable lists are currently being converted without a custom converteor, in cases of Firestore this means sub-items within an array/list are not converted as expected.
Fixes #4063 …
=> fix(firebase_core,web): ensure list items are converted

docs/functions/usage.mdx
Added fix for an error that is encountered on the iOS simulator while using the local Firebase emulator for Cloud Functions. 
- Fixes #2792
- Fixes #3505
=> docs(firebase_functions): updated usage doc

docs/storage/usage.mdx
- Couldn't find directory if I didn't use `path` property.
- Wrong error type caused error.
=> docs(firebase_storage): storage usage example update 

packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_exception.dart, packages/firebase_core/firebase_core_platform_interface/test/firebase_exception_test.dart
Cherry picks stack trace support on FirebaseException from https://github.com/FirebaseExtended/flutterfire/pull/3159
[CLA]: …
=> feat(firebase_core): add FirebaseException.stackTrace support

docs/auth/social.mdx
This PR adds to the docs to explain how to implement Sign In with Apple on different platforms.
This should resolve #3610.
The example for iOS/macOS is not working currently because of #3674.
[CLA]: …
=> docs(auth): add docs for Sign In with Apple

.github/workflows/scripts/drive-example.sh, packages/firebase_storage/firebase_storage/example/pubspec.yaml, packages/firebase_storage/firebase_storage/example/test_driver/firebase_storage_e2e.dart, packages/firebase_storage/firebase_storage/example/test_driver/firebase_storage_e2e_test.dart, packages/firebase_storage/firebase_storage/example/test_driver/instance_e2e.dart, packages/firebase_storage/firebase_storage/example/test_driver/list_result_e2e.dart, packages/firebase_storage/firebase_storage/example/test_driver/reference_e2e.dart, packages/firebase_storage/firebase_storage/example/test_driver/task_e2e.dart, packages/firebase_storage/firebase_storage/example/test_driver/test_utils.dart
This change opts-out tests from firebase_storage so they are not compiled with null-safety, which had started failing.
<details>
<summary><tt>flutter drive --target test_driver/firebase_storage_e2e.dart -d web</tt></summary>
```
Warning: You are using these overridden dependencies:                   
! firebase_core 0.5.2 from path ../../../firebase_core/firebase_core    
! firebase_storage 5.0.1 from path ..                                   
! firebase_storage_platform_interface 1.0.1 from path ../../firebase_storage_platform_interface
! firebase_storage_web 0.1.0 from path ../../firebase_storage_web       
Running "flutter pub get" in example...                            540ms
Launching test_driver/firebase_storage_e2e.dart on Web Server in debug mode...
Syncing files to device Web …
```
=> test(firebase_storage): Opt-out from null safety.

packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java, packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
Stops `authStateChanges` from firing twice initially on native platforms. 
fixes #4049 
=> fix(firebase_auth): stop authStateChange firing twice for initial event

packages/cloud_functions/cloud_functions_platform_interface/lib/src/method_channel/method_channel_firebase_functions.dart
Fix typo in method channel comment.
=> docs: update code doc typo

packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
stops the web `authStateListener` listener from firing twice upon initialisation.
#4049
=> fix(auth): web now fires once on authStateListener initialisation

packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
`FIRAuth canHandleNotification` is defined for iOS build targets only, so macOS should not be using this.
Have confirmed macOS example app now builds and runs successfully when including the `firebase_auth` plugin;
Fixes #4136.
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-r …
=> fix(messaging): macOS should not use `FIRAuth canHandleNotification` as it's iOS only (fixes #4136)

packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java
Added check for callback handler type (Long or Integer) for Android native code of plugin. Flutter's StandardMessageCodec packs Dart's int in to 32 or 64 bits (depends on the number). If RawHandler is suits for 32 bits, it will be packed as 32 bit int and then it will be unpacked to Integer on Java side.
Fixes FirebaseExtended/flutterfire#2654
Fixes FirebaseExtended/flutterfire#170
=> fix(messaging): fixed callback handler type casting on Android

docs/auth/usage.mdx
Links are broken. They are pointing to `docs/auth/usage` but the root is `docs/auth/social`
TBH, I'm not sure if this is the right way to fix the link.
=> docs: Links to social media auth. are broken

packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java
Manually create a `FlutterShellArgs` instance from an Android activity intent.
Doing it this way means we can supports both Flutter Activity types:
- `io.flutter.embedding.android.FlutterFragmentActivity`
- `io.flutter.embedding.android.FlutterActivity`
`getFlutterShellArgs()` that was used previously is only available on `FlutterActivity`.
Fixes #4078. …
=> fix(messaging): manually create a `FlutterShellArgs` instance from Android activity intent (fixes #4078)

packages/cloud_firestore/cloud_firestore/example/test_driver/field_value_e2e.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
FieldValues were currently going through the core `jsify` utils which skipped conversion of Firestore types. This forces the values back through the cloud firestore types.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/4224 …
=> fix(cloud_firestore): ensure web FieldValue types are converted

packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_notification.dart
List values returned from native are not being cast correctly, this change forces the list items contain `String` types.
https://github.com/FirebaseExtended/flutterfire/issues/4359 …
=> fix(firebase_messaging): cast args lists to string values

packages/firebase_core/firebase_core/android/gradle.properties
The last commit from #4331 fixed builds on firebase_ml_vision for firebase-android-sdk >= 25.13.0
https://github.com/FirebaseExtended/flutterfire/commit/024a11cfe50e492e2ec46774d9cd32c34d894bc3
It was part of this PR originally but was committed already, so this PR is now *just* bumping the SDK to latest stable before the firebase-android-sdk v26.x.x breaking change
Original PR rationale here:
---------
Specifically, these BoMs are documented upstream to not contain the correct dependencies, and because they are deprecated (and then removed in later BoMs) there is no fix coming.
This workaround is the only way to allow for the module to compile and be used
This is identical to the work done in react-native-firebase: https://github.com/invertase/react-native-firebase/commit/dc4f57a952a7076a …
=> feat(firebase_core, android): bump Android BoM to v25.13.0, fix firebase_ml_vision build

packages/cloud_firestore/cloud_firestore/example/ios/Podfile, packages/cloud_firestore/cloud_firestore/ios/cloud_firestore.podspec, packages/cloud_functions/cloud_functions/ios/cloud_functions.podspec, packages/firebase_admob/ios/firebase_admob.podspec, packages/firebase_analytics/firebase_analytics/ios/firebase_analytics.podspec, packages/firebase_auth/firebase_auth/ios/firebase_auth.podspec, packages/firebase_core/firebase_core/android/build.gradle, packages/firebase_core/firebase_core/example/android/app/build.gradle, packages/firebase_core/firebase_core/ios/firebase_core.podspec, packages/firebase_crashlytics/firebase_crashlytics/ios/firebase_crashlytics.podspec, packages/firebase_database/ios/firebase_database.podspec, packages/firebase_dynamic_links/ios/firebase_dynamic_links.podspec, packages/firebase_in_app_messaging/android/build.gradle, packages/firebase_in_app_messaging/ios/firebase_in_app_messaging.podspec, packages/firebase_messaging/firebase_messaging/example/android/app/build.gradle, packages/firebase_messaging/firebase_messaging/ios/firebase_messaging.podspec, packages/firebase_ml_custom/android/build.gradle, packages/firebase_ml_custom/ios/firebase_ml_custom.podspec, packages/firebase_ml_vision/android/build.gradle, packages/firebase_ml_vision/example/android/app/build.gradle, packages/firebase_ml_vision/ios/firebase_ml_vision.podspec, packages/firebase_performance/example/android/app/build.gradle, packages/firebase_performance/example/android/build.gradle, packages/firebase_performance/ios/firebase_performance.podspec, packages/firebase_remote_config/ios/firebase_remote_config.podspec, packages/firebase_storage/firebase_storage/android/build.gradle, packages/firebase_storage/firebase_storage/ios/firebase_storage.podspec
The logic to specify a baseline firebase SDK version and accept an override for same is fairly standardized across the repository but not applied uniformly or used everywhere
This PR harmonizes the logic across the repository, depends on firebase_core as needed in place of lower-level direct pod dependencies on ios and uses the BoM and core pod versions where ever possible
This is related to the forward port PR #4249 but is not a core part of that change, rather it makes that change easier while being independently correct and useful, so I'm submitting it separately for immediate consideration in order to shrink that PR and get feedback on utility …
=> fix(build): Use one version of firebase SDKs everywhere

packages/firebase_core/firebase_core/lib/src/firebase_app.dart, packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart
=> refactor(firebase_core)!: remove deprecated APIs

packages/cloud_functions/cloud_functions/lib/cloud_functions.dart, packages/cloud_functions/cloud_functions/lib/src/firebase_functions.dart, packages/cloud_functions/cloud_functions/lib/src/https_callable.dart, packages/cloud_functions/cloud_functions/test/firebase_functions_test.dart, packages/cloud_functions/cloud_functions/test/https_callable_test.dart, packages/cloud_functions/cloud_functions_platform_interface/lib/src/firebase_functions_exception.dart
=> refactor(firebase_functions)!: remove deprecated APIs

packages/firebase_storage/firebase_storage/lib/src/firebase_storage.dart, packages/firebase_storage/firebase_storage/lib/src/reference.dart, packages/firebase_storage/firebase_storage/lib/src/task.dart
Remove deprecated `firestore_storage` API ahead of the next major release.
=> refactor(firebase_storage)!: remove deprecated APIs

packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart, packages/firebase_auth/firebase_auth/lib/src/user.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/action_code_settings.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/email_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/facebook_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/github_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/google_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/oauth.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/phone_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/twitter_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/test/action_code_settings_test.dart
Remove deprecated `firestore_auth` API ahead of the next major release.
=> refactor(firestore_auth)!: remove deprecated APIs

packages/cloud_firestore/cloud_firestore/lib/src/collection_reference.dart, packages/cloud_firestore/cloud_firestore/lib/src/document_change.dart, packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart, packages/cloud_firestore/cloud_firestore/lib/src/document_snapshot.dart, packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart, packages/cloud_firestore/cloud_firestore/lib/src/query.dart, packages/cloud_firestore/cloud_firestore/lib/src/query_snapshot.dart, packages/cloud_firestore/cloud_firestore/lib/src/write_batch.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_field_value.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
Remove deprecated `cloud_firestore` API ahead of the next major release.
=> refactor(cloud_firestore)!: remove deprecated APIs

packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
Fixes an issue where a NPE occurs when user metadata is null. 
The Firebase Android SDK also annotates this as nullable, so we should definitely handle it;
Fixes #3643.
Closes #4448. …
=> fix(auth,android): null pointer exception if user metadata null

packages/firebase_storage/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FlutterFirebaseStorageTask.java
Additionally simplified `cancelInProgressTasks` to use `valueAt` rather than 2 calls of `keyAt` & `get`.
Fixes #4334.
[CLA]: …
=> fix(storage,android): handle ArrayIndexOutOfBoundsException (fixes #4334)

packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart, packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/platform_interface/platform_interface_messaging.dart
Updates the documentation currently displayed on https://pub.dev/documentation/firebase_messaging/8.0.0-dev.11/firebase_messaging/FirebaseMessaging/subscribeToTopic.html. 
Changing quotations to backticks will allow the brackets to be displayed in the example provided.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/4578 …
=> docs: fix messaging regex examples

packages/firebase_crashlytics/firebase_crashlytics/example/android/app/src/main/java/io/flutter/plugins/firebasecrashlyticsexample/EmbeddingV1Activity.java, packages/firebase_crashlytics/firebase_crashlytics/example/test_driver/firebase_crashlytics_e2e.dart, packages/firebase_crashlytics/firebase_crashlytics/example/test_driver/firebase_crashlytics_e2e_test.dart, packages/firebase_crashlytics/firebase_crashlytics/ios/Classes/FLTFirebaseCrashlyticsPlugin.m
Bug fix for didCrashOnPOreviousExecution.
Testing library switched to drive (matches other plugins) on Crashlytics as e2e was exiting as 'successful' despite test failures.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/4658 …
=> fix(crashlytics): didCrashOnPreviousExecution

packages/cloud_firestore/cloud_firestore/example/macos/Podfile
https://github.com/invertase/firestore-ios-sdk-frameworks should now be compatible with macOS, this PR adds it back in to improve build times on CI.
https://github.com/FirebaseExtended/flutterfire/issues/2751
https://github.com/invertase/firestore-ios-sdk-frameworks/issues/11 …
=> chore(macos,firestore): use precompiled frameworks in example app

packages/cloud_firestore/cloud_firestore/example/pubspec.yaml, packages/cloud_functions/cloud_functions/example/pubspec.yaml, packages/cloud_functions/cloud_functions/pubspec.yaml, packages/cloud_functions/cloud_functions_platform_interface/pubspec.yaml, packages/cloud_functions/cloud_functions_web/pubspec.yaml, packages/firebase_admob/example/pubspec.yaml, packages/firebase_analytics/firebase_analytics/example/pubspec.yaml, packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml, packages/firebase_core/firebase_core/example/pubspec.yaml, packages/firebase_core/firebase_core/pubspec.yaml, packages/firebase_core/firebase_core_platform_interface/CHANGELOG.md, packages/firebase_core/firebase_core_platform_interface/pubspec.yaml, packages/firebase_core/firebase_core_web/CHANGELOG.md, packages/firebase_core/firebase_core_web/pubspec.yaml, packages/firebase_crashlytics/firebase_crashlytics/example/pubspec.yaml, packages/firebase_database/example/pubspec.yaml, packages/firebase_dynamic_links/example/pubspec.yaml, packages/firebase_in_app_messaging/example/pubspec.yaml, packages/firebase_messaging/firebase_messaging/example/pubspec.yaml, packages/firebase_ml_custom/example/pubspec.yaml, packages/firebase_ml_vision/example/pubspec.yaml, packages/firebase_performance/example/pubspec.yaml, packages/firebase_remote_config/firebase_remote_config/example/pubspec.yaml, packages/firebase_storage/firebase_storage/example/pubspec.yaml
This bumps firebase_core and firebase_core_web to respect the conventions around null-safety versioning
=> chore: bump firebase_core and firebase_core_web

packages/firebase_auth/firebase_auth/pubspec.yaml
remove the dependency_overrides temporarily to be able to publish `firebase_auth`
=> chore: Remove dependency_override in firebase_auth

packages/firebase_auth/firebase_auth/pubspec.yaml
Now that firebase_auth was published, let's revert https://github.com/FirebaseExtended/flutterfire/pull/4763
=> chore: Re-enable dependency_overrides in firebase_auth

docs/overview.mdx
Semicolon was missing in overview section of flutterfire doc [website](https://firebase.flutter.dev/docs/overview) .
This PR fix the issue.
=> docs: add missing semicolon

packages/firebase_core/firebase_core_web/lib/src/interop/utils/utils.dart
Fixes the following analysis warning:
```
firebase_core/web/lib/src/interop/utils/utils.dart:121
The return type 'void' isn't assignable to 'FutureOr<Null>', as required by 'Future.catchError'. #return_type_invalid_for_catch_error
```
`return_type_invalid_for_catch_error` analysis option should probably be enabled to avoid this in the future
=> fix: Analysis error with firebase_core/web

analysis_options.yaml, melos.yaml, packages/firebase_admob/example/lib/main.dart, packages/firebase_core/firebase_core/example/lib/main.dart, packages/firebase_core/firebase_core_web/lib/src/interop/utils/utils.dart, packages/firebase_crashlytics/firebase_crashlytics/example/lib/main.dart, packages/firebase_dynamic_links/example/lib/main.dart, packages/firebase_in_app_messaging/example/lib/main.dart, packages/firebase_messaging/firebase_messaging/example/lib/permissions.dart, packages/firebase_ml_vision/example/lib/material_barcode_scanner.dart, packages/firebase_performance/example/lib/main.dart
This PR enables --fatal-infos for `dart analyze`. Additionally excludes generated plugin files from being analyzed.
[CLA]: …
=> ci: enable `--fatal-infos` on Dart Analyzer

packages/cloud_firestore/cloud_firestore/pubspec.yaml, packages/cloud_firestore/cloud_firestore_platform_interface/pubspec.yaml, packages/cloud_firestore/cloud_firestore_web/pubspec.yaml, packages/cloud_functions/cloud_functions/example/pubspec.yaml, packages/cloud_functions/cloud_functions/pubspec.yaml, packages/cloud_functions/cloud_functions_platform_interface/pubspec.yaml, packages/cloud_functions/cloud_functions_web/pubspec.yaml, packages/firebase_auth/firebase_auth/example/pubspec.yaml, packages/firebase_auth/firebase_auth/pubspec.yaml, packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml, packages/firebase_auth/firebase_auth_web/pubspec.yaml, packages/firebase_core/firebase_core/pubspec.yaml, packages/firebase_core/firebase_core_platform_interface/pubspec.yaml, packages/firebase_core/firebase_core_web/pubspec.yaml, packages/firebase_crashlytics/firebase_crashlytics/example/pubspec.yaml, packages/firebase_crashlytics/firebase_crashlytics/pubspec.yaml, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/pubspec.yaml, packages/firebase_messaging/firebase_messaging/pubspec.yaml, packages/firebase_messaging/firebase_messaging_platform_interface/pubspec.yaml, packages/firebase_messaging/firebase_messaging_web/pubspec.yaml
This change addresses the following:
- Removal of upper bound flutter sdk constraint on packages, see https://dart.dev/go/flutter-upper-bound-deprecation
- Removal of unused dependencies, e.g. pedantic & e2e.
- Remove of no longer required dependency overrides, e.g. http & http_parser - as these are now have nullsafety releases and are used on latest flutter dev channel.
- Update several dependencies such as `plugin_platform_interface` to their latest nullsafety version. …
=> refactor: pubspec & dependency updates

packages/cloud_firestore/cloud_firestore_platform_interface/test/timestamp_test.dart
The unix epoch is actually in year 1969 in the US! Converting the time
to UTC makes sure that the test will pass even when the local time zone
is negative. …
=> tests: convert DateTime to UTC before getting the year in tests.

packages/cloud_firestore/cloud_firestore/test/test_firestore_message_codec.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/utils/firestore_message_codec.dart, packages/cloud_firestore/cloud_firestore_platform_interface/test/utils/test_firestore_message_codec.dart
The return type for `getValue()` has been changed to Object? upstream.
This cannot be implicitly converted into other modes when sound null
safety is enabled. …
=> fix(cloud_firestore): Fix type issue.

packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/remote_config_value.dart
When parsing booleans from iOS, consider `'1'` as `true`
Closes https://github.com/FirebaseExtended/flutterfire/issues/2629
[CLA]: …
=> fix(firebase_remote_config): Consider '1' as boolean on iOS

packages/cloud_firestore/cloud_firestore/pubspec.yaml, packages/firebase_analytics/firebase_analytics/pubspec.yaml, packages/firebase_core/firebase_core/pubspec.yaml, packages/firebase_database/pubspec.yaml, packages/firebase_messaging/firebase_messaging/pubspec.yaml, packages/firebase_remote_config/firebase_remote_config/pubspec.yaml, packages/firebase_storage/firebase_storage/pubspec.yaml
cannot run `melos bootstrap` on stable channel as dependency resolution fails. This fixes it.
=> chore: rm dev dependencies breaking CI

docs/auth/usage.mdx, docs/firestore/usage.mdx, docs/functions/usage.mdx, docs/installation/android.mdx, docs/installation/ios.mdx, docs/installation/macos.mdx
Android, iOS and macOS all enforce encrypted connections for networking, but
the firebase emulator suite uses unencrypted connections to avoid encryptiong
setup. These instructions explain how to allow unencrypted connections so
native apps can use the emulators
#5102 - firestore emulator docs request
https://github.com/FirebaseExtended/flutterfire/issues/5096#issuecomment-784122845 - firestore auth docs request
This is a change to .mdx files - docs - only, so should be easy though I am always open to wording improvements of course - sometimes takes a couple passes before the wording is as good as it can be
Cheers …
=> docs(emulators): add instructions for firebase emulator suite networking

packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
This is a simple documentation change requested by a user, to avoid future user pain until the issue is resolved
firebase-js-sdk 8.2.4+ is required, but v8+ is not supported yet
https://github.com/FirebaseExtended/flutterfire/issues/5096#issuecomment-783398448 …
=> docs(auth, web): note that auth emulator is not supported for web

packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart, packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
My original implementation of auth.useEmulator for FlutterFire in #4263 used the underlying firebase-js-sdk incorrectly for the web implementation
Underlying web API for useEmulator is sync not async, so attempting to await it and call .then resulted in an error since no Promise was returned.
Supporting auth.useEmulator officially should still require the Firestore issue uncovered in firebase-js-sdk >= v8.0.1 to be resolved, tracked here #4127 - but if users are willing to pin firebase-js-sdk === v8.0.1 auth.useEmulator will now work for them and firebase web in general should work
**For people testing this and using firestore on web: firebase-js-sdk v8.0.1 is reported to work with auth.useEmulator without triggering the problem described in #4127 - thanks to @wtfiwtz for success report** …
=> fix(auth, web): correct use of underlying useEmulator API, sync not async

docs/auth/usage.mdx
The example code for deleting a user cannot be compiled, because `catch` is in the wrong place. 
No related issues found.
=> docs(firebase_auth): fixed example code to delete a user

packages/cloud_firestore/cloud_firestore_web/lib/src/interop/utils/utils.dart, packages/firebase_core/firebase_core_web/lib/src/interop/utils/utils.dart
* Fixed signature of `dartify` and `jsify` utils funtions
* Improved documentation of `dartify` and `jsify` utils funtions
* Removed wrong cast from `Function(Object)` to `Function(Object?)`
when `core_interop.dartify(...)` is called with a `customDartify` parameter
* Removed wrong cast from `Function(Object?)` to `Function(Object)`
when `core_interop.jsify(...)` is called with a `customJsify` parameter
I don't know why `melos run format` changed the indentation.
I did not add tests, because I essentially did not add new code.
This fixes the issue #5050 (as well as the duplicate #5238)
- Fixes #5050
- Fixes #5238
This will ensure a smooth and quick review process. …
=> fix(cloud_firestore_web): Fix wrong cast (FirebaseExtended#5050)

.github/ISSUE_TEMPLATE/config.yml
Fix issue template discussion's link to specific categories
=> chore(repository): fix issue template discussion categories' links

packages/firebase_crashlytics/firebase_crashlytics/example/test_driver/firebase_crashlytics_e2e.dart, packages/firebase_crashlytics/firebase_crashlytics/test/firebase_crashlytics_test.dart, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/lib/src/method_channel/method_channel_crashlytics.dart, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/test/method_channel_tests/method_channel_crashlytics_test.dart, packages/firebase_crashlytics/firebase_crashlytics_platform_interface/test/platform_interface_tests/platform_interface_crashlytics_test.dart
This is a follow up PR for [FF-19](https://yt.invertase.io/youtrack/issue/FLUTTERFIRE-19) & [FF-20](https://yt.invertase.io/youtrack/issue/FLUTTERFIRE-20). 
Unsure if this is a breaking change as I've updated this [checkForUnsentReports()](https://github.com/FirebaseExtended/flutterfire/compare/@russell/crashlytics-follow-up-pr?expand=1#diff-ec378bc3ccbeedd0a391d573aacc9b6d96edbd7c82ab8bfc2993661151e8085aR43-R46) to throw an error if `isCrashlyticsCollectionEnabled` is set to `true`. This now matches the behaviour of [RNFB Crashlytics](https://github.com/invertase/react-native-firebase/blob/master/packages/crashlytics/lib/index.js#L52) and is the reason this [test](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/example/test_dr …
=> fix(crashlytics)!: `checkForUnsentReports` should error if `isCrashlyticsCollectionEnabled` is false

README.md, docs/admob/usage.mdx, docs/sidebars.js, docs/versions.js, website/plugins.js, website/src/pages/index.tsx
Points to [remote source](https://github.com/googleads/googleads-mobile-flutter) following deprecation of admob package from this repository.
[CLA]: …
=> docs(admob): update docs to reference new external plugin

.github/PULL_REQUEST_TEMPLATE.md
From what I understand we should no longer manually update the changelog or increment the version numbers, right?
This change does update the template to reflect that new workflow.
none …
=> chore: Remove note on updating changelog and major version from PR template

packages/cloud_firestore/cloud_firestore/example/test_driver/document_change_e2e.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/interop/utils/utils.dart, packages/firebase_core/firebase_core_web/lib/src/interop/utils/utils.dart
With the introduction of null safety you are not being able to store nested null values in Firestore on the web anymore.
Not working before this fix:
```dart
await FirebaseFirestore.instance.collection("collection").doc("test").update(<String, dynamic>{
'test': {
'nestedKey': null  // <--- causes 
},
});
```
Exception:
`Expected a value of type 'Object', but got one of type 'Null'` …
=> fix: cannot store null values in firestore on the web

docs/firestore/usage.mdx, packages/firebase_database/example/lib/main.dart
While executing a single line return statement the body should remain without a semicolon indicating the end of it.
With the semicolon added, it doesn't compile!
firebaseextended/flutterfire#3711 …
=> docs: removed semicolon on single line return statement

docs/auth/usage.mdx
When a user uninstalls an application, the user will remain logged in but an auth token will no longer be available. This is because of the underlying Firebase iOS SDK persisting on a keychain.
This PR updates the documentation to warn developers of this issue until a resolution can be found.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/4661 …
=> docs(firebase-auth,apple): uninstallation warning for logged in users

docs/auth/usage.mdx
In the documentation for Authentication under the Emulator Usage there is an instruction on how to use the emulator. This section seems to be copied from the instructions for Cloud Functions and is suggesting you can connect to the cloud functions emulator from the firebase authentication package. 
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not …
=> docs: Refer to Authentication emulator in docs

docs/auth/social.mdx
FacebookAuth instance's login method is returning AccessToken but in the example code result was of type LoginResult which was causing error. Just changes it to AccessToken and made changes accordingly while creating credential also.
=> docs(firebase_auth): Facebook Auth Example Code Fix

packages/firebase_crashlytics/firebase_crashlytics/ios/firebase_crashlytics.podspec
https://github.com/flutter/flutter/pull/78592 stopped trying Flutter against pods that don't explicitly declare `Flutter` as a dependency (to fix a bitcode linking issue).  This means that all Flutter plugins rely on correct podspec dependencies set up, so either `s.dependency 'Flutter'` or  `s.dependency 'FlutterMacOS'`.
I don't see any other podspecs that are missing it.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/5440
=> fix(firebase_crashlytics): Add Flutter dependency to podspec

packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingUtils.java, packages/firebase_messaging/firebase_messaging/example/lib/main.dart, packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_notification.dart
Users can send a tag with each RemoteNotification on android.
fixes #5432
=> feat(messaging): android.tag property on Notification

packages/firebase_core/firebase_core/android/gradle.properties
Remove `android.enableR8=true`
Remove deprecated gradle property
```
> Configure project :firebase_core
WARNING: The option setting 'android.enableR8=true' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8
``` …
=> refactor(core): Remove deprecated gradle property `android.enableR8=true`

packages/cloud_firestore/cloud_firestore/lib/src/collection_reference.dart, packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart, packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/blob.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/field_path.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/geo_point.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/internal/pointer.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_field_value.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/settings.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/timestamp.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/field_value_web.dart, packages/firebase_core/firebase_core/lib/src/firebase.dart, packages/firebase_core/firebase_core/lib/src/firebase_app.dart, packages/firebase_core/firebase_core/test/firebase_core_test.dart, packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_exception.dart, packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart, packages/firebase_core/firebase_core_platform_interface/lib/src/platform_interface/platform_interface_firebase_app.dart, packages/firebase_core/firebase_core_platform_interface/test/platform_interface_tests/platform_interface_firebase_core_test.dart, packages/firebase_storage/firebase_storage/lib/src/firebase_storage.dart, packages/firebase_storage/firebase_storage/lib/src/reference.dart
Replace `operator ==(dynamic other)` with `operator ==(Object other)` everywhere.
If this seems reasonable, I'll follow up on the checklist.
Fixes #5288 …
=> fix(*): operator `==` takes `Object` parameter

packages/firebase_dynamic_links/CHANGELOG.md, packages/firebase_dynamic_links/example/lib/main.dart, packages/firebase_dynamic_links/example/pubspec.yaml, packages/firebase_dynamic_links/lib/firebase_dynamic_links.dart, packages/firebase_dynamic_links/lib/src/dynamic_link_parameters.dart, packages/firebase_dynamic_links/lib/src/firebase_dynamic_links.dart, packages/firebase_dynamic_links/pubspec.yaml, packages/firebase_dynamic_links/test/firebase_dynamic_links_e2e.dart, packages/firebase_dynamic_links/test/firebase_dynamic_links_test.dart
This PR updates firebase dynamic links to sound null safety.
The primary uncertainty is integration_test package consuming e2e. It appears flutter_driver is holding packages back. It also appeared in other null-safe releases of other flutterfire packages (e.g., firebase_core), the integration tests were removed (not sure if this is a temporary measure or not). Hence, I followed suit and removed the dependency on e2e & flutter_driver.
https://github.com/FirebaseExtended/flutterfire/discussions/4182
Does your PR require plugin users to manually update their …
=> feat!: Migrate firebase_dynamic_links to sound null safety

docs/analytics/overview.mdx, docs/auth/overview.mdx, docs/core/usage.mdx, docs/crashlytics/overview.mdx, docs/database/overview.mdx, docs/firestore/overview.mdx, docs/functions/overview.mdx, docs/messaging/overview.mdx, docs/performance/overview.mdx, docs/remote-config/overview.mdx, docs/storage/overview.mdx, website/api.js, website/plugins.js
Null safety is now available in the `stable` Flutter channel for Web, Android & iOS targets.
~~Null-safe support for [Desktop](https://flutter.dev/desktop) is in `beta` (although there is a "snapshot" in `stable`, I figure it is best to point users to the channel which will be regularly updated).~~
Also documented its availability for Desktop even if it is a "snapshot".
This will ensure a smooth …
=> docs: stable channel is null-safe

packages/firebase_analytics/firebase_analytics/lib/firebase_analytics.dart
The reserved events have changed. You can find the list here: https://firebase.google.com/docs/reference/swift/firebaseanalytics/api/reference/Classes/Analytics
The screen_view event is no longer in this list.
This PR removes screen_view from the list of reserved events. There are more events to update, but it looks like `screen_view` is the only removal. We should make future migrations as easy as possible and remove the screen_view so that users can already migrate to logging custom screen_view events.
Updating the other events is a potential breaking change, so I decided to keep them out of this PR. If you like to include them as well, please tell me, I'll add them.
fixes #3267 …
=> fix(firebase_analytics): remove screen_view from reservedEventNames

docs/auth/usage.mdx
Function needs the compulsory argument. …
=> docs: Remove optional parameter from FirebaseAuth.instance.useEmulator

packages/cloud_firestore/cloud_firestore/lib/src/query_document_snapshot.dart
QueryDocumentSnapshot, by definition, should always have data and therefore the `.data()` method can be non-null.
Adds an override that calls the super `.data()` method with the added `!`.
FIxes #5475 
**There was no existing test for `Query.get()`, but the change is just from nullable to non-nullable.**
[Flutter …
=> fix(firestore): made `QueryDocumentSnapshot.data()` non-nullable

packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/method_channel/method_channel_messaging.dart
There is a bug in the method `getNotificationSettings()` for Firebase Messaging after migrating to null safety. With the current stable an error appears when calling  `getNotificationSettings()`: 
```
> [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'Future<Map<String, int>?>' is not a subtype of type 'FutureOr<Map<String, int>>' in type cast
> #0      convertPlatformException (package:firebase_messaging_platform_interface/src/method_channel/utils/exception.dart:12:5)
> #1      MethodChannelFirebaseMessaging.getNotificationSettings (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:245:13)
> #2      FirebaseMessaging.getNotificationSettings (package:firebase_messaging/src/messaging.dart:154:22)
```
The reason for this error is the …
=> fix(firebase_messaging): fix getNotificationSettings for null safety

packages/cloud_firestore/cloud_firestore/pubspec.yaml, packages/cloud_functions/cloud_functions/pubspec.yaml, packages/firebase_analytics/firebase_analytics/pubspec.yaml, packages/firebase_auth/firebase_auth/pubspec.yaml, packages/firebase_core/firebase_core/pubspec.yaml, packages/firebase_crashlytics/firebase_crashlytics/pubspec.yaml, packages/firebase_database/pubspec.yaml, packages/firebase_messaging/firebase_messaging/pubspec.yaml, packages/firebase_performance/pubspec.yaml, packages/firebase_remote_config/firebase_remote_config/pubspec.yaml, packages/firebase_storage/firebase_storage/pubspec.yaml
Now there is a documentation website, the `homepage` url within the `pubspec.yaml` files can point the hub for the specific package. This PR then adds the `repository` url to the pubspecs where the `homepage` no longer points to the repo. …
=> chore: add repository urls to pubspecs

.github/workflows/cancel.yaml
Previously, only workflows older then the current workflow were canceled
In very deep queues this means the current instance may not even run until there are future
runs enqueued, and those will not run - and thus will not cancel - the current run, leaving
the queue in a clogged state
Now any time a run instance finally gets off the queue and runs it will check all runs -
including runs queued after the current one - and it will clear all non-current runs including
itself, hopefully unclogging the queue
https://github.com/styfle/cancel-workflow-action/pull/62 is the upstream PR
In the process I removed the github_token as in current versions of the action it is optional, and the one that was specified here is now the default.
No related issue logged, but @Salakar and @rrousselGit …
=> chore(workflows): add ability to cancel all but latest workflow run

packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_notification.dart
For IOS devices, if we have CriticalSound value in the APS payload, seems like FirebaseMessaging.onMessageOpenedApp.listen doesn't get triggered.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/5398
[pub …
=> fix(messaging): APN message with critical sound causing a hidden error

docs/functions/usage.mdx
The instructions on how to use the emulator for functions were not in line with emulator usages from other packages (Auth, Firestore).
Also, the example code would not work if one needed to use the callable's return value.
This makes the instructions more clear and easier to follow. …
=> docs(cloud_functions): update emulator usage instructions

packages/firebase_storage/firebase_storage/example/test_driver/instance_e2e.dart, packages/firebase_storage/firebase_storage/lib/src/utils.dart, packages/firebase_storage/firebase_storage/test/firebase_storage_test.dart, packages/firebase_storage/firebase_storage/test/utils_test.dart
Allows storage references to be created via URLs with spaces and `+` symbols. 
Fixes https://github.com/FirebaseExtended/flutterfire/issues/5673
Fixes https://github.com/FirebaseExtended/flutterfire/issues/4908
[pub …
=> fix: improve refFromURL http regex

.github/workflows/cancel.yaml
Upstream has integrated the "all_but_latest" feature - https://github.com/styfle/cancel-workflow-action/releases/tag/0.9.0
https://github.com/styfle/cancel-workflow-action/pull/35
https://github.com/styfle/cancel-workflow-action/pull/67
#5637  …
=> chore(workflows): use new cancel-workflow-action release

packages/firebase_performance/lib/firebase_performance.dart, packages/firebase_performance/lib/src/firebase_performance.dart, packages/firebase_performance/lib/src/http_metric.dart, packages/firebase_performance/lib/src/performance_attributes.dart, packages/firebase_performance/lib/src/trace.dart, packages/firebase_performance/test/firebase_performance_e2e.dart, packages/firebase_performance/test/firebase_performance_test.dart
This migrates firebase_performance to non-nullable types
=> feat!: Migrate firebase_performance to sound null safety

packages/firebase_in_app_messaging/CHANGELOG.md, packages/firebase_in_app_messaging/example/lib/main.dart, packages/firebase_in_app_messaging/example/pubspec.yaml, packages/firebase_in_app_messaging/lib/firebase_in_app_messaging.dart, packages/firebase_in_app_messaging/pubspec.yaml, packages/firebase_in_app_messaging/test/firebase_in_app_messaging_e2e.dart, packages/firebase_in_app_messaging/test/firebase_in_app_messaging_test.dart
This migrates firebase_in_app_messaging to non-nullable types
This is a "Breaking" Change because it is upgrading to null safety, the user code will not be needed to change as the dart lib was almost ready to be null safe already checking for null value and throwing error
=> feat: migrate in_app_messaging to sound null safety

packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
Since version 8.0.2 of the Firestore web sdk, it seems passing `null` to `docChanges` causes the underlying SDK to assume the user passed options, which causes a "null pointer exception".
This change wraps the options check, and doesn't pass arguments (`undefined`) instead.
Line of code: https://github.com/firebase/firebase-js-sdk/blob/626c05b36cfe7f91ac9b6aad730c0f04d6bb8c01/packages/firestore/src/exp/snapshot.ts#L445
Fixes https://github.com/FirebaseExtended/flutterfire/issues/4127
Unblocks https://github.com/FirebaseExtended/flutterfire/pull/5170
Does …
=> fix(cloud_firestore): conditionally pass options to docChanges

.editorconfig, .github/workflows/scripts/functions/src/index.ts, packages/cloud_functions/cloud_functions/example/test_driver/cloud_functions_e2e.dart, packages/cloud_functions/cloud_functions_platform_interface/lib/src/method_channel/method_channel_https_callable.dart
If a cloud function returns an object, the return type ought to be `Map<String, dynamic>`, not `Map<dynamic, dynamic>` as per JSON spec. This problem affects `iOS` & `android`, `web` returns the correct type.
fixes #4059 …
=> fix(functions): return correct type on native

packages/firebase_auth/firebase_auth/example/lib/signin_page.dart
The auth example sign-in page could use some feedback for when the user is signed in plus an example of how to display user info.
[CLA]: …
=> docs(firebase_auth): Add UserInfoCard widget in auth example SignInPage

packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart
Errors already printed with `FlutterError.dumpErrorToConsole` (L135). No need to print again with `recordError`.
None
[CLA]: …
=> fix(firebase_crashlytics): Avoid duplicate prints

packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
This part was missing int he cloud_firestore work previously.
Event listeners should be reset when firebase core is reinitialised.
Discussed in #4416  …
=> fix(cloud_firestore): Clear event listeners when firebase core is reinitialised 

packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/oauth.dart, packages/firebase_auth/firebase_auth_platform_interface/test/providers_tests/oauth_test.dart, packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart, packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart, packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
Makes `OAuthProvider.parameters` non nullable. Alternatively, a null check could have been added to https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart#L185
Closes https://github.com/FirebaseExtended/flutterfire/issues/5654
**Is it a breaking change for implementations of `firebase_auth_platform_interface`?** …
=> feat(firebase_auth): OAuthProvider.parameters is now non-nullable

docs/auth/social.mdx
The `credential` method of `GoogleAuthProvider` returns `OAuthCredential`, and *not* a `GoogleAuthCredential`.
This agrees with the latest [documentation page for it](https://pub.dev/documentation/firebase_auth_platform_interface/latest/firebase_auth_platform_interface/GoogleAuthProvider/credential.html) on Firebase Auth.
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBU …
=> fix: Incorrect type Annotation for GoogleAuthProvider.credential()

packages/firebase_storage/firebase_storage/example/test_driver/task_e2e.dart, packages/firebase_storage/firebase_storage_web/lib/src/firebase_storage_web.dart, packages/firebase_storage/firebase_storage_web/lib/src/interop/firebase_interop.dart, packages/firebase_storage/firebase_storage_web/lib/src/interop/storage.dart
Web storage bucket was always default. This allows user to choose bucket for each Firebase project.
fixes #5803
=> fix(storage,web): secondary storage buckets now work as expected on Web

packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart
IMHO it is better to have explicit types of fields, and it seems that other fields have them.
The real reason is that we are making a small change to the analyzer inference that makes it an error when there is a cycle in the references during inference. Specifically, here `_onMessageController` references itself in its initializer, so potentially its type depends on itself. It could be improved, but for now a less sophisticated way it is.
=> fix: provide explicit types for StreamController(s).

packages/cloud_functions/cloud_functions_platform_interface/lib/src/method_channel/method_channel_https_callable.dart, packages/cloud_functions/cloud_functions_platform_interface/lib/src/method_channel/utils/exception.dart, packages/cloud_functions/cloud_functions_platform_interface/test/method_channel/utils/exception_test.dart, packages/cloud_functions/cloud_functions_web/lib/https_callable_web.dart, packages/cloud_functions/cloud_functions_web/lib/utils.dart
Replacement of https://github.com/FirebaseExtended/flutterfire/pull/4420
When debugging on VSCode, exceptions aren't bubbled up the chain back to the user if using try/catch with a Future .catchError. This changes that behaviour, along with improving some tests and naming of functions.
Issue for context: https://github.com/FirebaseExtended/flutterfire/issues/3475 …
=> fix(cloud_functions): bubble exceptions

packages/firebase_dynamic_links/ios/Classes/FLTFirebaseDynamicLinksPlugin.m
People have posted some issues:
- #100 
- #33 
on iOS dynamic links behavior. All of this use cases worked before iOS 12 release so I assume Firebase update and iOS 12 have changed things.
I've based my work on the release of rn-firebase 6.0 that had the same problems and were fixed so this PR takes some ideas from them.
- Fixes #100 
- Fixes #33  …
=> fix(dynamic_links,ios): retry handling iOS universal link on network failure

packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
Firebase_auth was not registered as a plugin, which broke auth
fixes https://github.com/FirebaseExtended/flutterfire/issues/5952
fixes https://github.com/FirebaseExtended/flutterfire/issues/5979 …
=> fix(firebase_auth): Fix firebase_auth not being registered as a plugin

packages/cloud_functions/cloud_functions/android/src/main/java/io/flutter/plugins/firebase/functions/FlutterFirebaseFunctionsPlugin.java
Fixed NullPointerException
IOException getMessage() sometimes returns null
Fixes https://github.com/FirebaseExtended/flutterfire/issues/6007
=> fix(android,functions): possible null pointer exception when comparing error codes

docs/installation/ios.mdx
There is no any file located at `ios/MyApp/Info.plist`. You have to change `Info.plist` in Runner folder.
Type in Documentation
[CLA]: …
=> docs:  use Flutter specific iOS plist file location

docs/firestore/2.0.0_migration.mdx, docs/sidebars.js
Follow-up to the addition of `withConverter` and references taking an extra generic parameter.
=> docs: Add migration guide for cloud_firestore 2.0.0

packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
Correctly iterates Dictionary values during cleanup / hot restart.
Fixes https://github.com/FirebaseExtended/flutterfire/issues/6036
[CLA]: …
=> fix(firebase_auth): correctly cleanup Dictionary handlers

docs/firestore/usage.mdx
In the current source code, a subscription starts at every build, which leads a bad user experience with the screen blinking or flashing at every build.
Fix example source code about Firestore subscription. Current source code has a problem. It starts to listen to Firestore at every build. It has to start to listen to Firestore once in `initState()`. `.snapshots()` should be in `initState()`
[Contributor …
=> docs: Start to listen once.

packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
`GetOptions` were not being passed to `Query.get`. Also the test for this was commented out for web.
Fixes #6076
=> fix(cloud_firestore): pass GetOptions to web Query.get

packages/cloud_firestore/cloud_firestore/macos/cloud_firestore.podspec, packages/cloud_functions/cloud_functions/macos/cloud_functions.podspec, packages/firebase_auth/firebase_auth/macos/firebase_auth.podspec, packages/firebase_core/firebase_core/macos/firebase_core.podspec, packages/firebase_crashlytics/firebase_crashlytics/macos/firebase_crashlytics.podspec, packages/firebase_database/firebase_database/macos/firebase_database.podspec, packages/firebase_messaging/firebase_messaging/macos/firebase_messaging.podspec, packages/firebase_remote_config/firebase_remote_config/macos/firebase_remote_config.podspec, packages/firebase_storage/firebase_storage/macos/firebase_storage.podspec
The previous ruby scripts would error if the user had a deployment target greater than `10.12` due to the explicit `user_osx_target == "10.11"` - this PR updates the script to check the version is less than the required minimum version rather than a explicit equals comparison.
N/A …
=> fix: podspec osx version checking script should use a version range instead of a single fixed version

docs/auth/phone.mdx
iOS does not support the `resendToken` in the codeSent callback.
closes #4542
=> docs(auth): codeSent doc update

docs/firestore/usage.mdx
The withConverter example needed to specify the type in angle brackets because toJson() can not be called on Object class. This is also how the code is written on the pub.dev example page.
I didn't raise an issue, I discovered the example was wrong and solved it after some searching. Figured I'd pass on the fix. 
- All I did edit one line in the documentation. 
- [ no Only changed docs] My PR includes unit or integration tests for *all* changed/updated/fixed …
=> fix(firebase_firestore): Update Cloud Firestore Usage.mx 

docs/firestore/usage.mdx
i found some code example typo on firebase_firestore when i am doing integration with my flutter project, so here i try to fix the typo with the correct one. 
=> fix(firebase_firestore): fix typo on firebase_firestore real time example

packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
Remove suggestion to handle `user-not-found` error when using sendSignInLinkToEmail().
Fixes #4442
Fixes #4442
=> docs(firebase-auth): remove suggestion to handle `user-not-found` when using sendSignInLinkToEmail()

packages/cloud_firestore/cloud_firestore/lib/src/query.dart, packages/cloud_firestore/cloud_firestore/test/query_test.dart
Not possible to use a `isNotEqualTo` filter with another `where()` query that uses a `FieldPath.documentId` field.
closes #6174
[CLA]: …
=> test(firestore): update and assert documentId field & isNotEqualTo filter test

packages/cloud_firestore/cloud_firestore/lib/src/query.dart, packages/cloud_firestore/cloud_firestore/test/query_test.dart
cannot use orderBy on `not-in` operators as well as inequality operators.
closes https://github.com/FirebaseExtended/flutterfire/issues/4906
[CLA]: …
=> test(firestore): improve query assertions

packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java, packages/firebase_auth/firebase_auth/example/test_driver/instance_e2e.dart, packages/firebase_auth/firebase_auth/example/test_driver/user_e2e.dart, packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m, packages/firebase_auth/firebase_auth/lib/src/user.dart, packages/firebase_auth/firebase_auth/test/user_test.dart, packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_user.dart
User.updateProfile is now deprecated in favor of these new methods.
This change is to fix an issue where it was not possible to set a displayName/photoURL to null.
fixes #6199
fixes #6194 …
=> feat: add User.updateDisplayName and User.updatePhotoURL

docs/messaging/usage.mdx, packages/firebase_messaging/firebase_messaging/example/lib/main.dart, packages/firebase_messaging/firebase_messaging/example/lib/message_list.dart, packages/firebase_messaging/firebase_messaging/example/lib/token_monitor.dart
- only show local notifications for native.
- list of messages received was throwing error as `messageId` is not part of web `RemoteMessage` API.
- update docs to show web requires serviceWorker registration to stop error being thrown on initialisation.
- pass vapidKey in messaging example for web messaging.
closes https://github.com/FirebaseExtended/flutterfire/issues/5975
closes https://github.com/FirebaseExtended/flutterfire/issues/5515 …
=> chore(messaging, web): fix broken messaging example

docs/firestore/usage.mdx
The classState UserInformationState is missing '**r**' in UserInformationState
None
=> docs: fix typo in firestore example

packages/firebase_messaging/firebase_messaging/example/test_driver/instance_e2e.dart, packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart, packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/platform_interface/platform_interface_messaging.dart
=> fix(firebase_messaging): Fix FirebaseMessaging.onMessage and onMessageOpenedApp potentially throwing

docs/auth/usage.mdx, website/dictionary.js
Update `firebase_auth` documentation surrounding the three different auth event listeners
- `authStateChanges()`
- `idTokenChanges()`
- `userChanges()`
closes #4700
closes #5415
closes #3994 …
=> docs(auth): update auth state events

packages/firebase_core/firebase_core/android/gradle.properties
Update the Android SDK to Version 28.1.0. The updated Android Firebase SDK contains a fix that skips backoff when App enters Foreground
Fixes #4305
[CLA]: …
=> feat(*): Upgrade Firebase Android BoM version to 28.1.0

packages/firebase_storage/firebase_storage/lib/src/utils.dart, packages/firebase_storage/firebase_storage/test/firebase_storage_test.dart
When allowed special characters are in the url, they can often truncate the path due to a buggy regex. This PR removes the regex implementation for something more straight forward.
closes #5965 …
=> fix(storage): refFromUrl parse url

packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/Constants.java, packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java, packages/firebase_auth/firebase_auth/example/test_driver/instance_e2e.dart, packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart, packages/firebase_auth/firebase_auth/test/firebase_auth_test.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart, packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_tests/method_channel_firebase_auth_test.dart, packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
allow `auth.setSettings()` to update parameters on android platform as per [reference here](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuthSettings)
closes https://github.com/FirebaseExtended/flutterfire/issues/5205 …
=> feat(auth, android): setSettings now possible for android

packages/firebase_crashlytics/firebase_crashlytics/ios/Classes/FLTFirebaseCrashlyticsPlugin.m
improve stacktrace on iOS Crashlytics dashboard by creating a symbol comprised of the class and method name i.e. `className.methodName`.
closes https://github.com/FirebaseExtended/flutterfire/issues/6371 …
=> fix(crashlytics): improve stack trace symbol. "class.method" signature.

packages/firebase_auth/firebase_auth/lib/src/user.dart
Update documentation relating to behaviour of Firebase auth once a `PhoneAuthCredential` has been used to attempt to link `PhoneAuthCredential` to Firebase auth account.
closes https://github.com/FirebaseExtended/flutterfire/issues/6006 …
=> docs(auth): phone provider account linking update

packages/firebase_analytics/firebase_analytics/README.md, packages/firebase_analytics/firebase_analytics/ios/firebase_analytics.podspec
As a part of Analytics 7.11.0 SDK there is a special analytics pod to follow AppTrackingTransparency. As mentioned at https://github.com/FirebaseExtended/flutterfire/discussions/6030 there is no solution to use this pod in a flutter. 
This pull request involve the new FirebaseAnalyticsWithoutAdIdSupport variable and it can be used to ovveride the default pod the same way as FirebaseSDKVersion used to [override sdk version](https://firebase.flutter.dev/docs/overview/#iosmacos)
Just add following line somewere in the head of your ios/Podfile  and  got the flutter app with AnalyticsWithoutAdIdSupport
`$FirebaseAnalyticsWithoutAdIdSupport = true`
Closes #6030
=> feat: firebase_analytics plugin with AnalyticsWithoutAdIdSupport pod

packages/firebase_storage/firebase_storage/lib/src/firebase_storage.dart
Use `mappedHost` instead of `host` for `useStorageEmulator` implementation.
Before this change, `mappedHost` wasn't used mistakenly.
It should be used like this: https://github.com/FirebaseExtended/flutterfire/blob/73f1eeae137ea466c4b5776f627738bb323c3616/packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart#L92
- Not tests added because there are no exiting tests about it.  …
=> fix(firebase_storage): Use `mappedHost` instead of `host`

packages/cloud_firestore/cloud_firestore/lib/cloud_firestore.dart, packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
export `PersistenceSettings` & also pass settings to Firebase JS SDK. There is an [additional property](https://firebase.google.com/docs/reference/js/firebase.firestore.PersistenceSettings#optional-experimentalforceowningtab) on `FirebaseSettings` which is experimental and will possibly be removed, therefore, it hasn't been implemented.
none. …
=> fix(firestore): export PersistenceSettings

docs/migration-guide.mdx, packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart, packages/firebase_storage/firebase_storage/lib/src/firebase_storage.dart
Reinstate deprecated API for `auth` & `storage` packages for ease of use. 
Cannot reinstate `functions` because the `useFunctionsEmulator` has been reused and arguments have changed. No change to `firestore` as it didn't have a specific API in the first place. 
none. …
=> fix(*): reinstate deprecated emulator apis

docs/crashlytics/usage.mdx
Fix #6657 according to an official handling errors guide: https://flutter.dev/docs/testing/errors#errors-not-caught-by-flutter
=> docs(crashlytics): Move `ensureInitialized` into runZonedGuarded

packages/firebase_analytics/firebase_analytics/ios/Classes/FLTFirebaseAnalyticsPlugin.m, packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m, packages/firebase_dynamic_links/ios/Classes/FLTFirebaseDynamicLinksPlugin.m, packages/firebase_ml_custom/ios/Classes/FLTFirebaseMLCustomPlugin.h, packages/firebase_ml_vision/ios/Classes/FLTFirebaseMlVisionPlugin.h
Use angle bracket import consistently when importing Firebase.h
=> fix: Use angle bracket import consistently when importing Firebase.h for iOS

docs/remote-config/overview.mdx
Since remote-config package is stable and null-safety, I dropped their caution sections.
https://pub.dev/packages/firebase_remote_config/changelog
[CLA]: …
=> docs(remote_config): removed null-safety caution 

packages/firebase_database/firebase_database/example/test_driver/firebase_database_e2e.dart, packages/firebase_database/firebase_database/lib/src/event.dart, packages/firebase_database/firebase_database/lib/src/query.dart, packages/firebase_database/firebase_database/test/firebase_list_test.dart
`DataSnapshot` is always returned from a `get()` request.
`DataSnapshot.exists` ascertains whether value exists at RTDB location.
fixes https://github.com/FirebaseExtended/flutterfire/issues/6747 …
=> fix(database): DataSnapshot is always present

docs/installation/macos.mdx
outgoing connections on macOS. Replacement PR for https://github.com/FirebaseExtended/flutterfire/pull/6376
closes https://github.com/FirebaseExtended/flutterfire/issues/6356 …
=> docs: update macOS docs regarding outgoing connections

packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
Just corrects the docs for the default transaction timeout.
=> docs(cloud_firestore): Transaction timeout correction

packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart, packages/cloud_firestore/cloud_firestore/lib/src/query.dart
Firestore allows `where()` queries on properties which are null or not null.
closes https://github.com/FirebaseExtended/flutterfire/issues/6712
[CLA]: …
=> fix(firestore): allow querying on 'is not null' properties

packages/cloud_firestore/cloud_firestore/ios/Classes/FLTTransactionStreamHandler.m
We believe this ought to resolve the bug whereby the transaction handler was losing a reference to itself when executing code in callback blocks. For further context, this is a solution we've [implemented on RNFB](https://github.com/invertase/react-native-firebase/blob/master/packages/firestore/ios/RNFBFirestore/RNFBFirestoreCollectionModule.m#L88).
closes https://github.com/FirebaseExtended/flutterfire/issues/6722 …
=> fix(firestore): transactionHandler was losing ref to self in blocks

packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
Error from `firebase-ios-sdk` had an underlying error with a more precise description of the issue. 
Using the auth example app, the following errors were produced trying to login to Twitter, Github & Facebook using the auth emulator:
closes https://github.com/FirebaseExtended/flutterfire/issues/6775
[Flutter …
=> fix(auth): precise error message is propagated

docs/installation/ios.mdx, docs/installation/macos.mdx, packages/firebase_analytics/firebase_analytics/ios/firebase_analytics.podspec, packages/firebase_app_check/firebase_app_check/ios/firebase_app_check.podspec, packages/firebase_app_check/firebase_app_check/macos/firebase_app_check.podspec, packages/firebase_core/firebase_core/ios/firebase_core.podspec, packages/firebase_crashlytics/firebase_crashlytics/ios/firebase_crashlytics.podspec
Replacement PR for https://github.com/FirebaseExtended/flutterfire/pull/4626
Following deployment targets in the `podspec` files for each plugin within the [firebase-ios-sdk](https://github.com/firebase/firebase-ios-sdk).
Please note `dynamic_links`, `analytics`, `in_app_messaging` & `performance` did not have an `osx` deployment target within their `podspec` file. So it is assumed, like the other plugins, they target a minimum version of `10.12`.
closes https://github.com/FirebaseExtended/flutterfire/issues/6204
Does your PR require plugin users to manually …
=> feat: lower iOS & macOS deployment targets for relevant plugins

packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
This prevents `onMessage` from firing on a notification tap when `contentAvailable` is set and the app is in a quit-state,
Currently, the library causes the notification to display twice - once when the app is quit, and again when the notification is tapped to open the app
It's in both apple and firebase docs, that `didReceiveRemoteNotification` can be triggered when  :
[Firebase](https://firebase.google.com/docs/cloud-messaging/ios/receive#handle_silent_push_notifications) :
```
// If you are receiving a notification message while your app is in the background,
// this callback will not be fired till the user taps on the notification launching the application.
```
[Apple](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application?language=objc):
`If the …
=> fix: onMessage event handler for notifcations with `contentAvailable:true`

docs/overview.mdx, packages/firebase_core/firebase_core/android/gradle.properties, packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
Updates the Android Bill of Materials to 28.3.1 and the iOS Firebase SDK to 8.6.0.
The version changes between 28.1.0 and 28.3.1 can be seen here:
https://firebase.google.com/support/release-notes/android
We've had problems with Firestore not properly detecting the network status which might have been fixed in Firestore 23.0.2 (23.0.3 is included in the BoM).
- Yes, this is a breaking change.
[Contributor …
=> feat: update Firebase Android SDK to `28.3.1` & Firebase iOS SDK to `8.6.0`

packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/oauth.dart, packages/firebase_auth/firebase_auth_platform_interface/test/providers_tests/oauth_test.dart, packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
When using `signInWithPopup` as auth method for Twitter login, the received Firebase JS object contains more data than mapped to the `OAuthCredential` object. One of them is the `accessSecret` field which is crucial when working with the Twitter API to perform requests on behalf of other users (with their consent). This field is `null` when received via the `UserCredentials` object and the only available token is the `accessToken`. 
This PR is mapping the `accessSecret` field from the JS Auth object (`oAuthCredential`) to the `OAuthCredential` object.
No issue reported from me, neither found existing ones.
This will ensure a smooth and quick review process. Updating …
=> feat(auth): Add support for `secret` on `OAuthCredential` on web

packages/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebasedynamiclinks/FirebaseDynamicLinksPlugin.java
firebase-android-sdk requires a `@NonNull` Intent argument to the `getDynamicLink(Intent)`
call, despite the documentation indicating otherwise
Related https://github.com/firebase/firebase-android-sdk/issues/2336
Related https://github.com/invertase/react-native-firebase/pull/5662 - with all credit to @daltonpurnell - thanks Dalton! …
=> fix(dynamic-links, android): null-check intent before calling getDynamicLink

packages/firebase_analytics/firebase_analytics/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java
- Currently, pass `List` instance with unsupported type element (such as `String`) to `firebase_analytics` plugin's `logEvent` function will throw a Exception. But error message is incorrect. It always shows `value` 's type.
- Fix error message to show list's `item` type.
None …
=> fix(firebase_analytics): Fix incorrect type name in error message

packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPluginException.java
If you specify no root, it uses devices locale, which is problematic for non-user-facing
items such as error codes, as you may end up with different codes on different devices,
so they won't match for proper error handling 
Fixes #6330 …
=> fix(auth, android): use Locale.ROOT while processing error code

packages/cloud_firestore/cloud_firestore/lib/src/query.dart, packages/cloud_firestore/cloud_firestore/lib/src/snapshot_cache.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_query.dart, packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/settings.dart, packages/cloud_firestore/cloud_firestore_platform_interface/test/settings_test.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
This updates the `hashCode` method of various objects to reduce conflicts.
It also fixes a bug with `Setting`'s hashCode, which was not deterministic. …
=> refactor: Reduce hash conflicts on objects

packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart
Fixes a bug where a new `FirebaseMessaging` instance was created each time `FirebaseMessaging.instance` was called which was invocating a new `StreamController` each time.
I've also made `instanceFor` factory private so that the default app is the only `FirebaseMessaging` one that can be instantiated.
fixes https://github.com/FirebaseExtended/flutterfire/issues/5389 …
=> fix(messaging): was creating a new instance each time

docs/auth/social.mdx
Docs suggest outdated versions of plugins
@Salakar @Ehesp could we make sure these are kept up-to-date automatically?
None
[CLA]: …
=> docs(auth): bump plugins versions to null-safe

packages/firebase_crashlytics/firebase_crashlytics/example/lib/main.dart
Ensure `WidgetsFlutterBinding.ensureInitialized();` is called within `runZonedGuard`.
fixes https://github.com/FirebaseExtended/flutterfire/issues/6964 …
=> chore(crashlytics): fix example to include "ensureInitialized" within runZonedGuarded

packages/firebase_performance/firebase_performance/README.md
There was a link in the README file that redirected to a Google corporate sign-in page.
None.
=> docs(performance): remove usage of private link address

packages/firebase_messaging/firebase_messaging/example/lib/main.dart, packages/firebase_messaging/firebase_messaging/example/lib/message.dart, packages/firebase_messaging/firebase_messaging/example/lib/message_list.dart, packages/firebase_messaging/firebase_messaging/example/lib/permissions.dart, packages/firebase_messaging/firebase_messaging/example/lib/token_monitor.dart, packages/firebase_messaging/firebase_messaging/example/pubspec.yaml, packages/firebase_messaging/firebase_messaging/example/test_driver/firebase_messaging_e2e.dart, packages/firebase_messaging/firebase_messaging/example/test_driver/firebase_messaging_e2e_test.dart, packages/firebase_messaging/firebase_messaging/example/test_driver/test_utils.dart
Migrates the example app in Firebase Messaging package to null-safety and fixes a small overflow issue.
closes #6987
=> chore(firebase_messaging): migrate example app to null-safety

packages/cloud_firestore/cloud_firestore/lib/src/query.dart, packages/cloud_firestore/cloud_firestore/test/query_test.dart
Fixes a bug where  query.== throws when using withConverter
=> fix(firestore): an issue where `Query.==` throws when using `withConverter`

packages/firebase_storage/firebase_storage/example/test_driver/instance_e2e.dart, packages/firebase_storage/firebase_storage/lib/src/utils.dart
`refFromUrl` was not parsing `localhost` urls needed for using the emulator.
fixes https://github.com/FirebaseExtended/flutterfire/issues/6944
**update on additional fix**
-  used optional items to capture preceding regex: https://www.regular-expressions.info/optional.html
-  also used non-capturing group so the port number doesn't mess up the groupings: https://www.regular-expressions.info/refcapture.html
- link to regex: https://regex101.com/r/hlI7zP/1
fixes https://github.com/FirebaseExtended/flutterfire/issues/7019 …
=> fix(firebase_storage): fix localhost url parsing for Storage Emulator

packages/firebase_database/firebase_database/example/test_driver/firebase_database_e2e.dart, packages/firebase_database/firebase_database_platform_interface/lib/src/platform_interface/event.dart
transactions don't pass `childKeys` so we pass the data back as it is.
fixes https://github.com/FirebaseExtended/flutterfire/issues/6583
[CLA]: …
=> fix(firebase_database): List of values erroring on transaction result

packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart, packages/cloud_firestore/cloud_firestore/lib/src/query.dart
=> fix: fixed a bug where `withConverter.endBeforeDocument` incorrectly behaved as `endAtDocument`

docs/overview.mdx, packages/firebase_core/firebase_core/android/gradle.properties, packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
Bump android and iOS sdk versions.
fixes https://github.com/FirebaseExtended/flutterfire/issues/6794
fixes https://github.com/FirebaseExtended/flutterfire/issues/6882 …
=> feat: bump Firebase iOS SDK to `8.7.0` & Android SDK to `28.4.1`

packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java
This fixes NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext() as propagated by @talent-apps in Issue #6998
fixes #6998
=> fix(firebase_messaging): Fix crash on Android in onDetachedFromEngine

docs/messaging/apple-integration.mdx
- To follow to instructions the image notification extension must be added with Objective-C language.
- Podfile target should include `use_frameworks!`
- Lines to be modified in `NotificationService.m` are 24-27 and not 25-28.
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-re …
=> docs: update apple-integration.mdx line numbers

packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreException.java, packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestoreUtils.m
Propagate the query index link to user when they use a composite `collectionGroup` query. Only for iOS & android. Web works as intended.
fixes https://github.com/FirebaseExtended/flutterfire/issues/7010 …
=> fix(cloud_firestore): propagate query index link  to firebase console for user

packages/firebase_dynamic_links/README.md
According to the documentation, the query parameter referent to the iOS bundle id is called "ibi" and not "ibn"
The long link example has a wrong query parameter. …
=> docs(firebase_dynamic_links): changed "ibn" to "ibi" iOS param name in long dynamic link example

packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
Fixes the failure in web tests [here](https://github.com/FirebaseExtended/flutterfire/pull/7111).
=> fix(firebase_auth): null-safety migration issue for web types

packages/firebase_crashlytics/firebase_crashlytics/example/lib/main.dart, packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart, packages/firebase_crashlytics/firebase_crashlytics/test/firebase_crashlytics_test.dart
Changes `dumpErrorToConsole` to `presentError` and also removes unneeded piece of code from the `example`
See https://github.com/flutter/flutter/pull/88253 and https://github.com/flutter/website/issues/6164 …
=> fix(firebase_crashlytics): switch usage of `dumpErrorToConsole` to `presentError` to remove duplicate logging

packages/firebase_storage/firebase_storage/ios/Classes/FLTFirebaseStoragePlugin.m
`iOS` was returning download URL with the port number which is inconsistent with `web` and `android`. We cannot test as we use the emulator for testing which uses a different port number. So I did a before and after of the url returned by printing in the console:
before:
https://firebasestorage.googleapis.com:443/v0/b/react-native-firebase-testing.appspot.com/o/putString.json?alt=media&token=faabe1fc-1c51-4d63-8986-7c89bfdb9916
after:
https://firebasestorage.googleapis.com/v0/b/react-native-firebase-testing.appspot.com/o/putString.json?alt=media&token=faabe1fc-1c51-4d63-8986-7c89bfdb9916
fixes https://github.com/FirebaseExtended/flutterfire/issues/7036
This will …
=> fix(firebase_storage): remove https port number from `downloadUrl` for `iOS`

docs/messaging/usage.mdx, packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java, packages/firebase_messaging/firebase_messaging/example/lib/permissions.dart, packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart, packages/firebase_messaging/firebase_messaging/test/firebase_messaging_test.dart, packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/method_channel/method_channel_messaging.dart, packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/utils.dart
On Android, the plugin always returns permissions granted when queried for the notification permissions. Given an Android API exist for actually checking whether a user has notifications enabled or disabled for the app in the OS settings, it makes sense to utilise this API on Android.
- Update messaging plugin on android to use NotificationManagerCompat to get notification permissions.
- Renamed androidNotificationSettings to defaultNotificationSettings.
- Update the example add to give functionality to the reload permissions
button.
* #4492
Does your PR …
=> fix(firebase_messaging): Add Android implementation to get notification permissions

packages/firebase_analytics/firebase_analytics/ios/Classes/FLTFirebaseAnalyticsPlugin.m
Fix `firebase_analytics` channel name which caused CI failure.  …
=> fix(firebase_analytics, ios): fix channel name

packages/cloud_firestore/cloud_firestore/example/web/index.html, packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart, packages/cloud_functions/cloud_functions/example/web/index.html, packages/cloud_functions/cloud_functions_web/lib/cloud_functions_web.dart, packages/firebase_analytics/firebase_analytics/example/web/index.html, packages/firebase_analytics/firebase_analytics_web/lib/firebase_analytics_web.dart, packages/firebase_app_check/firebase_app_check_web/lib/firebase_app_check_web.dart, packages/firebase_auth/firebase_auth/example/web/index.html, packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart, packages/firebase_core/firebase_core/example/web/index.html, packages/firebase_database/firebase_database/example/web/index.html, packages/firebase_database/firebase_database_web/lib/firebase_database_web.dart, packages/firebase_messaging/firebase_messaging/example/web/index.html, packages/firebase_messaging/firebase_messaging_web/lib/firebase_messaging_web.dart, packages/firebase_performance/firebase_performance_web/lib/firebase_performance_web.dart, packages/firebase_remote_config/firebase_remote_config_web/lib/firebase_remote_config_web.dart, packages/firebase_storage/firebase_storage/example/web/index.html, packages/firebase_storage/firebase_storage_web/lib/src/firebase_storage_web.dart, packages/firebase_storage/firebase_storage_web/lib/src/reference_web.dart
Allow web plugins to register without crashing on missing initialization script, and allow to initialize web plugins only from Dart lazily.
Possibly fixes #3962 …
=> feat: allow web to initialize from Dart lazily without crashing on missing initialization script

packages/cloud_functions/cloud_functions_web/lib/cloud_functions_web.dart
Allow region to be set on cloud functions web.
fixes https://github.com/FirebaseExtended/flutterfire/issues/7318
=> fix(functions,web): correctly pass `region` to JS functions interop instance

packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_notification.dart
On cloud messaging web, one can optionally deliver `fcmOptions` (containing image link, analyticsLabel and link) to the client app, which has already been implemented for the most part. However, there was a missing link so that the info could be extracted from the `RemoteMessage` to, e.g., register the analytics event, navigate to the url or extract and display the image within the Flutter app. This is being added here. …
=> feat(firebase_messaging): add support for `RemoteMessage` on web

README.md
The current `README` has the link to pub.dev that is broken for `firebase_core`. In this PR I fixed it. (One line change)
[CLA]: …
=> docs: fix `pub.dev` link in `README`

packages/firebase_crashlytics/firebase_crashlytics/ios/Classes/Crashlytics_Platform.h, packages/firebase_crashlytics/firebase_crashlytics/ios/Classes/FLTFirebaseCrashlyticsPlugin.m
Adds a private header in the Crashlytics iOS plugin so that we can log the development platform (as "flutter") during initialization.
[CLA]: …
=> feat: log development platform to Crashlytics in Crashlytics iOS plugin

packages/firebase_storage/firebase_storage/example/ios/Runner/Info.plist, packages/firebase_storage/firebase_storage/example/lib/main.dart, packages/firebase_storage/firebase_storage/example/pubspec.yaml, packages/firebase_storage/firebase_storage/example/test_driver/reference_e2e.dart, packages/firebase_storage/firebase_storage/example/test_driver/task_e2e.dart
Upgrade `image_picker` to `^0.8.4+4` in Firebase Storage example app, and added the iOS permissions as the app was crashing.
None opened.
The example app was crashing on iOS due to lack of permission strings in `info.plist`. …
=> chore(firebase_storage): upgrade image_picker and add iOS permissions in example app

docs/in-app-messaging/overview.mdx, website/plugins.js
Docs updates to firebase_in_app_messaging:
2. Add command-line installation.
[CLA]: …
=> docs(firebase_in_app_messaging): remove legacy instructions

docs/remote-config/overview.mdx
Docs updates to `firebase_remote_config`:
2. Add command-line installation.
3. Remove the web-only section since the SDKs is now auto injected.
[pub …
=> docs(remote_config): remove legacy instructions

docs/analytics/overview.mdx
Docs updates to `firebase_analytics`:
2. Add command-line installation.
3. Remove the web-only section since the SDKs is now auto injected.
[pub …
=> docs(firebase_analytics): remove legacy instructions

packages/firebase_database/firebase_database/example/lib/main.dart, packages/firebase_database/firebase_database_web/lib/firebase_database_web.dart
Hot restart on web doesn't refresh the window scripts, causing the instance to recall emulator.
=> fix(firebase_database): ignore emulator already set error on web (hot restart issue)

docs/installations/overview.mdx, docs/remote-config/overview.mdx
Docs updates to `firebase_app_installations `:
2. Add command-line installation.
3. Rename the plugin. …
=> docs(firebase_app_installations): remove legacy instructions + update plugin name

packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/test_driver/firebase_ml_model_downloader_e2e.dart, packages/firebase_ml_model_downloader/firebase_ml_model_downloader_platform_interface/lib/src/method_channel/method_channel_firebase_ml_model_downloader.dart
Fixes a cast error with method `listDownloadedModels`.
=> fix(firebase_ml_model_downloader): listDownloadedModels cast error

packages/firebase_core/firebase_core_platform_interface/lib/src/method_channel/method_channel_firebase.dart
=> fix(firebase_core): loosen duplicate app detection checks to allow unset options not to cause a duplicate app exception

docs/dynamic-links/usage.mdx
the correct return type of 'buildShortLink' is 'ShortDynamicLink' not 'Uri'
*The return type of `await FirebaseDynamicLinks.instance.buildShortLink(parameters)` is `ShortDynamicLink` not `Uri` as the documentation stated. To get the uri of the ShortDynamicLink is ```final Uri uri = shortDynamicLink.shortUrl;``` therefore, the final code looks like this:*
*```final ShortDynamicLink shortDynamicLink = await FirebaseDynamicLinks.instance.buildShortLink(parameters);```*
*```final Uri uri = shortDynamicLink.shortUrl;```*
*This PR does not fix any existing known issue.*
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not …
=> docs(dynamic_links): correct the return type of `buildShortLink`

packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_core_exceptions.dart, packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart, packages/firebase_messaging/firebase_messaging_web/lib/firebase_messaging_web.dart
Additionally, correctly detect not-initialized errors and provide a better error message.
Fixes #7511  …
=> fix: messaging `isSupported()` check on web should be used lazily in `_delegate`

packages/firebase_analytics/firebase_analytics/android/src/main/java/io/flutter/plugins/firebase/analytics/FlutterFirebaseAnalyticsPlugin.java
To remove the user identifier from Firebase Analytics, we can pass the null value of user_id. But in Android, it is expecting only a non-null value. Now it will accept null.
fixes #7532 …
=> fix(firebase_analytics): userId can be null

packages/firebase_database/firebase_database/android/build.gradle, packages/firebase_database/firebase_database/example/android/app/build.gradle
Don't know the reason Why the minSdkVersion is 21 from version `9.0.0`. So making it 19 similar to most of the other firebase packages.
[CLA]: …
=> fix(firebase_database): downgrade the Android min SDK to 19

packages/firebase_analytics/firebase_analytics/example/lib/main.dart, packages/firebase_analytics/firebase_analytics/example/lib/tabs_page.dart, packages/firebase_analytics/firebase_analytics/lib/firebase_analytics.dart, packages/firebase_analytics/firebase_analytics/lib/src/observer.dart
Reinstate analytics observer.
fixes https://github.com/FirebaseExtended/flutterfire/issues/7526
=> fix(analytics): reinstate Analytics screen navigation observer.

docs/messaging/overview.mdx
In the docs for Firebase Cloud Messaging, the installation references `firebase_auth`. It should reference `firebase_messaging `
=> docs: firebase_auth -> firebase_messaging in overview

docs/analytics/usage.mdx, packages/firebase_analytics/firebase_analytics/example/test_driver/firebase_analytics_e2e.dart, packages/firebase_analytics/firebase_analytics_web/lib/firebase_analytics_web.dart
See title.
fixes https://github.com/FirebaseExtended/flutterfire/issues/7521
=> fix(analytics, web): ensure `setDefaultEventParameters()` API throws stating not supported on web.

packages/flutterfire_ui/example/ios/Podfile, packages/flutterfire_ui/example/macos/Podfile, packages/flutterfire_ui/example/macos/Runner/GoogleService-Info.plist
Firebase-only init doesn't work on macos, this PR brings `GoogleService-Info.plist` back to the example project
None
[CLA]: …
=> chore(ui, example): update UI example Firebase configuration

docs/ui/auth/integrating-your-first-screen.mdx
It seems like some class and file names have changed since the demo code was written.  This changes fixes those so that the demo code compiles and works by itself. …
=> fix: Make Firebase UI Sign In Screen demo work

docs/firestore-odm/defining-models.mdx
The example of the cloud_firestore_odm validator starts with a lowercase letter. Corrected `min` to `Min` and `max` to `Max`.
[CLA]: …
=> docs: Fixed validator names in cloud_firestore_odm to start with an uppercase letters

docs/ui/auth/building-a-custom-ui.mdx
Twitter Provider info was mislabeled as Google.
=> docs(ui): fix twitter provider typo

packages/firebase_crashlytics/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/FlutterFirebaseCrashlyticsPlugin.java, packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java
=> fix(firebase_messaging, firebase_crashlytics): Return app constants for default app only on `Android`.

analysis_options.yaml
This PR makes analyzer ignore `generated_plugin_registrant.dart` in web examples
#7576
> melos run analyze is failing on my machine with several depend_on_referenced_packages issues. I am not sure if I should use older Dart SDK, I did not found anything about this in Contributor Guide. This is my first contribution to this FlutterFire, am I missing something? …
=> chore: exclude generated_plugin_registrant.dart from anlaysis

packages/flutterfire_ui/lib/src/auth/oauth/providers/facebook_provider.dart, packages/flutterfire_ui/lib/src/auth/oauth/providers/google_provider.dart
I just found that some `flutterfire_ui` oauth providers work under mobile web, but platform detection gives incorrect result when running under desktop web.
[google_sign_in](https://pub.dev/packages/google_sign_in), [sign_in_with_apple](https://pub.dev/packages/sign_in_with_apple), [flutter_facebook_auth](https://pub.dev/packages/flutter_facebook_auth) work on web as noted on `pub.dev`.
We could use `os_detect` package for better platform detection but I am not sure about that and decided to start with a simplest change.
Note:
- I not added tests - currently I don't see any existing tests for `flutterfire_ui` package.
- `melos run analyze` is failing on my machine with several `depend_on_referenced_packages` issues. I am not sure if I should use older Dart SDK, I did not found anything …
=> fix(ui): some OAuth providers now work on macOS & web

packages/flutterfire_ui/lib/src/auth/widgets/internal/oauth_provider_button.dart
I fixed not working onTap in OAuthProviderButtonWidget (flutterfire_ui)
I added the 'onTap' to 'OAuthProviderButton' where are in 'build' method in 'OAuthProviderButtonWidget' 
Because "GoogleSignInButton Widget's onTap function" wasn't working.
I found no 'onTap' in 'OAuthProviderButton' where are in 'build' method in 'OAuthProviderButtonWidget',
so, I think this is the reason.
I'm sure 'GoogleSignInButton' works correctly with this change.
Hopefully you can review this PR and if something is wrong I would be glad to hear this.
I hope this will help for many as well as for me. Thank you!
nothing …
=> fix(flutterfire_ui): not working onTap in OAuthProviderButtonWidget

docs/crashlytics/overview.mdx
Fixes the incorrect step numbering:
=> docs(firebase_crashlytics): Fix step numbering in crashlytics/overview.mdx.

docs/ui/auth.mdx
Add in a missing 'for' in the auth 'Getting Started' section.
No related issues.
=> docs(firebase_auth): add missing word to auth getting started page.

packages/flutterfire_ui/README.md
The code example in the README was missing a required `providerConfigs` parameter. I added it.
No issue, afaik
=> docs(flutterfire_ui): add missing providerConfigs in example

docs/analytics/usage.mdx
The `logAdImpression` method had the description of `logAddToWishlist`. This PR fixes it.
=> docs(firebase_analytics): Correct the logAdImpression description.

docs/firestore-odm/overview.mdx
Link at the bottom of [flutterfire cloud_firestore_odm](https://firebase.flutter.dev/docs/firestore-odm/overview/#next-steps) is broken. Clicking "defining models" under "Next steps" returns 404. (NB: There are 2 "defining models" links). One returns 404 while the other goes to the right page.)
[Flutter Style …
=> docs: broken link in cloud_firestore_odm

packages/flutterfire_ui/lib/src/auth/validators.dart, packages/flutterfire_ui/pubspec.yaml
This PR changes the RegExp based email validator to [email_validator](https://pub.dev/packages/email_validator) package
Closes #7761
Closes #7680 
=> fix(ui): validate email with the library instead of the RegExp

packages/flutterfire_ui/pubspec.yaml
The repository url in the pubspec is broken. I updated it to the master channel of the flutterfire_ui package.
Didn't make an issue for this
[CLA]: …
=> docs: update repository and homepage url

packages/firebase_analytics/firebase_analytics/android/src/main/java/io/flutter/plugins/firebase/analytics/FlutterFirebaseAnalyticsPlugin.java
=> fix(firebase_analytics): `setUserProperty` should now accept null as a valid value on Android

packages/flutterfire_ui/lib/src/auth/screens/internal/responsive_page.dart
This PR fixes this:
none
- Yes, this is a breaking change.
=> fix(ui): fix `ResponsivePage` overflow issue

packages/firebase_analytics/firebase_analytics/ios/Classes/FLTFirebaseAnalyticsPlugin.m
This PR adds the equivalent fixes for iOS described in #7662
Without these changes the null value is converted to NSNull in iOS MethodChannel and we see the following messages in log when setting user property or user id to null on iOS:
> User ID must be NSString. User ID: (nil)
> User property must be NSString. Value: (nil)
#7662 (is already fixed for Android with #7735)
#7545 (allows to set user id to null on Android)
=> fix(firebase_analytics): user id and user properties can be null so `NSNull` should be converted to `nil` on iOS/macOS

packages/firebase_crashlytics/firebase_crashlytics/ios/firebase_crashlytics.podspec
Adds a pubspec flag to set the dSYM file format for all iOS build modes to DWARF with dSYM file. See [this flutter issue](https://github.com/flutter/flutter/issues/94607) for additional context.  …
=> feat(firebase_crashlytics): Set the dSYM file format through the Crashlytic's podspec to allow symbolicating crash reports. 

docs/auth/social.mdx
Code snippet for the Twitter Login in the [**Social Auth**](https://firebase.flutter.dev/docs/auth/social#twitter) documentation updated with the missing `await` for the Login call.
None
=> docs(firebase_Auth): Missing `await` for the `twitter_login` package `login()` API.

docs/manual-installation.mdx, packages/firebase_core/firebase_core/android/gradle.properties, packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
Bump android and iOS sdk versions. …
=> feat: bump Firebase iOS SDK to `8.11.0` & Android SDK to `29.0.4`

packages/firebase_database/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java, packages/firebase_database/firebase_database/ios/Classes/FLTFirebaseDatabasePlugin.m
In retrospect, I don't think we need to track the event channel names at all. In other plugins, we keep a map of stream handlers so we can clean up. In this implementation, we pass a "dispose of" function to the event channel to clean up the stream handler. So the event names aren't used for anything.
So, I think we can remove the `queryListeners` and associated code. Thoughts, @Salakar? 
Will roll out for iOS once I have a second opinion 😄.
**Update**
Every event stream has a new number id for android & iOS. 
fixes https://github.com/FirebaseExtended/flutterfire/issues/7795
fixes https://github.com/FirebaseExtended/flutterfire/issues/7556
I suspect it fixes this issue as well: https://github.com/FirebaseExtended/flutterfire/issues/7618 …
=> fix(firebase_database): Fix `MissingPluginException` caused by malformed EventChannel name.

packages/firebase_core/firebase_core_platform_interface/lib/src/method_channel/method_channel_firebase.dart
See title.
fixes https://github.com/FirebaseExtended/flutterfire/issues/7938
=> fix(firebase_core): allow secondary Firebase App initialization without duplicate app error on hot restart

packages/firebase_crashlytics/firebase_crashlytics/macos/Classes/Crashlytics_Platform.h
- Create symlink for Crashlytics_Platform.h file. This should fix the compilation error `'Crashlytics_Platform.h' file not found (macos)`
* #7558
[CLA]: …
=> fix(firebase_crashlytics): Fixed macOS project not compiling by symlinking missing header file: `Crashlytics_Platform.h`

packages/flutterfire_ui/lib/src/auth/screens/email_link_sign_in_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/forgot_password_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/internal/login_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/internal/responsive_page.dart, packages/flutterfire_ui/lib/src/auth/screens/phone_input_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/register_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/sign_in_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/sms_code_input_screen.dart
=> fix(ui): make breakpoints of all screens configurable

docs/firestore-odm/references.mdx, packages/cloud_firestore_odm/cloud_firestore_odm/lib/annotation.dart
The PR fixes an issue caused by following the demo code in this section of the firestore-odm docs: https://firebase.flutter.dev/docs/firestore-odm/references#performing-queries
Triggering code generation with `@Collection<User>('/users')` yields the following error:
_The annotation @Collection received "/users" as collection path,  but this path points to a document instead of a collection_
This can be fixed by using `@Collection<User>('users')`.
[pub …
=> docs(cloud_firestore_odm): Update code snippets by removing incorrect forward slash for `@Collection` annotations.

packages/firebase_dynamic_links/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebase/dynamiclinks/FlutterFirebaseDynamicLinksPlugin.java
See title.
fixes https://github.com/FirebaseExtended/flutterfire/issues/6784
=> fix(dynamic_links): Ensure Dynamic link is retrieved from the Intent just once for `getInitialLink()` on Android as per the documentation.

packages/cloud_firestore/cloud_firestore_platform_interface/lib/cloud_firestore_platform_interface.dart
FlutterFire's example at https://firebase.flutter.dev/docs/firestore/usage/#data-bundles uses the enum LoadBundleTaskState (snippet below). 
However, the package currently does not export, requiring the developer to import from source. 
```dart
// Use .stream API to expose a stream which listens for LoadBundleTaskSnapshot events.
task.stream.listen((taskStateProgress) {
if(taskStateProgress.taskState == LoadBundleTaskState.success){
//bundle is loaded into app cache!
}
});
```
N/A …
=> fix(cloud_firestore): Export enum `LoadBundleTaskState` from Platform Interface package.

packages/flutterfire_ui/lib/src/auth/widgets/internal/oauth_provider_button.dart
This PR adds an error text that is rendered under the oauth button when error occurs
=> feat(ui): Enhance the oauth provider button widget by showing error text underneath.

packages/firebase_remote_config/firebase_remote_config/pubspec.yaml
[Firebase remote config](https://pub.dev/packages/firebase_remote_config) dependency already has web implementation but the pub.dev shows only "Android", "iOS", "MacOS" platforms supported by the plugin.
=> fix(firebase_remote_config): add missing `default_package` entry for web in `pubspec.yaml`

packages/firebase_app_check/firebase_app_check/example/android/app/src/main/AndroidManifest.xml, packages/firebase_app_installations/firebase_app_installations/example/android/app/src/main/AndroidManifest.xml, packages/firebase_messaging/firebase_messaging/example/android/app/src/main/AndroidManifest.xml, packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/android/app/src/main/AndroidManifest.xml, packages/flutterfire_ui/example/android/app/src/main/AndroidManifest.xml
omiting "io.flutter.embedding.android.SplashScreenDrawable" because it is deprecated – in Flutter 2.5 and later.
=> chore: Removed `io.flutter.embedding.android.SplashScreenDrawable` from example app `AndroidManifest.xml` files as it is deprecated.

docs/ui/auth/configuring-providers.mdx
It looks like the code examples are switched from their descriptions.
Fix documentation
=> docs(ui): Switched Twitter `apiSecretKey` examples that were in the incorrect position in the documentation.

packages/flutterfire_ui/lib/src/auth/oauth/providers/facebook_provider.dart, packages/flutterfire_ui/lib/src/auth/oauth/providers/google_provider.dart, packages/flutterfire_ui/lib/src/auth/oauth/providers/twitter_provider.dart, packages/flutterfire_ui/pubspec.yaml
Upgrade `desktop_webview_auth` to 0.0.4.
Fixes an issue with Google sign in with emulator in macOS.
=> fix(flutterfire_ui): Upgrade `desktop_webview_auth` package causing a problem on macOS.

packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/templates/query_reference.dart
Generated `orderBy*` queries hardcoded `descending: false` instead of using the passed through value. This PR fixes that.
- Fixes #7932
[CLA]: …
=> fix(cloud_firestore_odm): Use descending in orderBy*

packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/document_reference_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/internals.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/transaction_web.dart, packages/cloud_firestore/cloud_firestore_web/lib/src/write_batch_web.dart, packages/firebase_analytics/firebase_analytics_web/lib/firebase_analytics_web.dart, packages/firebase_analytics/firebase_analytics_web/lib/utils/exception.dart, packages/firebase_app_check/firebase_app_check_web/lib/firebase_app_check_web.dart, packages/firebase_app_check/firebase_app_check_web/lib/src/internals.dart, packages/firebase_app_installations/firebase_app_installations_web/lib/firebase_app_installations_web.dart, packages/firebase_app_installations/firebase_app_installations_web/lib/src/guard.dart, packages/firebase_core/firebase_core/lib/src/internals.dart, packages/firebase_messaging/firebase_messaging_web/lib/firebase_messaging_web.dart, packages/firebase_messaging/firebase_messaging_web/lib/src/internals.dart, packages/firebase_performance/firebase_performance_web/lib/src/internals.dart, packages/firebase_performance/firebase_performance_web/lib/src/trace.dart, packages/firebase_storage/firebase_storage_web/lib/src/utils/errors.dart
Just an internal function rename, nothing to see here 
=> chore: Rename internal `guard`  function to `convertWebException` to be clearer

docs/overview.mdx
See title.
fixes https://github.com/FirebaseExtended/flutterfire/issues/7866
=> docs: Update "overview.mdx" regarding when to use manual installation for initializing app.

packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
If a token has been deleted, and a new one requested, android streams to user via `onTokenRefresh`. This PR ensures behaviour is the same for iOS.
fixes https://github.com/FirebaseExtended/flutterfire/issues/8122
[pub …
=> fix(firebase_messaging): Stream new token via `onTokenRefresh` when `getToken` invoked for iOS.

docs/ui/auth/integrating-your-first-screen.mdx, packages/flutterfire_ui/example/lib/main.dart, packages/flutterfire_ui/lib/auth.dart, packages/flutterfire_ui/lib/src/auth/configs/oauth_provider_configuration.dart, packages/flutterfire_ui/lib/src/auth/flows/oauth_flow.dart, packages/flutterfire_ui/lib/src/auth/oauth/oauth_providers.dart, packages/flutterfire_ui/lib/src/auth/oauth/providers/apple_provider.dart, packages/flutterfire_ui/lib/src/auth/oauth/providers/facebook_provider.dart, packages/flutterfire_ui/lib/src/auth/oauth/providers/google_provider.dart, packages/flutterfire_ui/lib/src/auth/oauth/providers/twitter_provider.dart, packages/flutterfire_ui/lib/src/auth/screens/email_link_sign_in_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/internal/multi_provider_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/internal/provider_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/profile_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/register_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/sign_in_screen.dart, packages/flutterfire_ui/lib/src/auth/screens/universal_email_sign_in_screen.dart, packages/flutterfire_ui/lib/src/auth/widgets/delete_account_button.dart, packages/flutterfire_ui/lib/src/auth/widgets/internal/rebuild_scope.dart, packages/flutterfire_ui/lib/src/auth/widgets/sign_out_button.dart, packages/flutterfire_ui/pubspec.yaml
Alongside fixing the issue, this PR introduces a new mechanism to configure auth providers.
The underlying issue requires storing auth providers globally, this PR updates existing screens to fetch provider configurations from global storage if none passed as an argument. 
Fixes #7801 …
=> feat(ui): Add support for configuring authentication providers globally (additionally fixes #7801)

packages/firebase_analytics/firebase_analytics/lib/src/firebase_analytics.dart
The logAdImpression doc comments refers to `add_to_wishlist` instead of `ad_impression`
https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event.html#AD_IMPRESSION
[pub …
=> docs(analytics): code comment typo - `logAdImpression` mentions wrong event
