firebase/flutterfire

- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
From combing the iOS SDK, it appears if you wish to remove the email address you ought to actually set the email address once you unlink the password provider. [See here](https://github.com/firebase/firebase-ios-sdk/issues/3858). Unlinking the password provider will only remove the password provider, not remove the email address from the `currentUser`.
fixes https://github.com/FirebaseExtended/flutterfire/issues/4163 …
> fix(auth): Fixed bug that sets email to `nil` on `iOS` when the `User` has no provider.

- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPluginException.java
> fix(android,auth): return correct error code for linkWithCredential `provider-already-linked` on Android

- packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
See title.
fixes https://github.com/FirebaseExtended/flutterfire/issues/8042
> fix(firebase_messaging): Ensure `onMessage` callback is consistently called on `iOS` platform.

- docs/installations/overview.mdx
- docs/installations/usage.mdx
…page to match the imported package in the usage page
the overview page was install a package (firebase_app_installations) and in the usage page importing another one (flutterfire_installations), it's confusing even though both package offer same functionality so I did changed the download command to get the flutterfire_installations package
no issue
- [ x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor …
> docs(firebase_app_installations):  Changed import statement in documentation.

- packages/cloud_firestore/cloud_firestore/lib/src/query.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_query.dart
There is method name typo in cloud_firestore query documentation. This PR fix it.
There is no related issues 
> docs(cloud_firestore): Fix method name typo in code documentation

- packages/flutterfire_ui/lib/src/auth/widgets/internal/loading_button.dart
A CupertinoButton color should **not** be overridden by a custom color if it is not set. It should pick the theme primary color instead. The default blue color will be created by the default CupertinoTheme, so no need to use it explicitly either.
This PR fixes the aforementioned behavior.
To see the bug in action, add the `SignInScreen` with `EmailProviderConfiguration` to your cupertino app and change the primary color of the cupertino theme to something different than blue.
Expected behavior: the "Sign in"/"Register" button picks the primary color of the theme.
Actual behavior: the color of the button stays blue.
There seem to be no related issues. Instead of creating one myself, I have decided to provide a PR directly.
Before you create this PR confirm that it meets all requirements …
> fix(flutterfire_ui): Fix Flutter Cupertino button color bug.

- docs/storage/upload-files.mdx
Fixing a small code error in a Cloud Storage Flutter snippet. There was a missing variable declaration that would break the snippet if copied.
N/A, only a documentation fix …
> docs(storage): adds missing line of code in upload file snippet

- packages/flutterfire_ui/lib/src/auth/screens/forgot_password_screen.dart
- packages/flutterfire_ui/lib/src/auth/screens/internal/login_screen.dart
- packages/flutterfire_ui/lib/src/auth/screens/register_screen.dart
- packages/flutterfire_ui/lib/src/auth/screens/sign_in_screen.dart
The UniversalScaffold used by LoginScreen() and SignInScreen() (among others) sets resizeToAvoidBottomInset=false, which means on smaller screen devices (particularly on mobile web, which pulls in relatively high resolution devices eg. the Pixel 4a) and means the password box is obscured when a header is set.
This change is to expose resizeToAvoidBottomInset as an option which can be set directly from the externally exposed api points, while not breaking any of the expected behaviour elsewhere unless explicit.
There are other screens I could implement this on as well (eg. sign in link.) 
Happy to provide screenshots if necessary.
Closes #8084
This will ensure a smooth …
> feat(ui): Allow setting `resizeToAvoidBottomInset` from LoginScreen and set as default `false` for backwards compatibility.

- packages/firebase_crashlytics/firebase_crashlytics/ios/crashlytics_add_upload_symbols
Modifies the changes made for the iOS automated onboarding to exit the add upload-symbols script if the required app ID json isn't present.
Fixes https://github.com/firebase/flutterfire/issues/8376 …
> fix(firebase_crashlytics): Exit the add crashlytics upload-symbols script if the required json isn't present

- docs/cli.mdx
- docs/crashlytics/overview.mdx
- docs/overview.mdx
> docs: update documentation to support latest CLI release.

- packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart
Fix typo "manully" to "manually
Simply replacing a typo I found while working in flutter.
None found
- [x ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x ] All existing and new tests are passing.
- [x ] I updated/added relevant documentation (doc comments with `///`).
- [x ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x ] I read and followed the [Flutter Style …
> docs(firebase_core): Fix typo in "firebase_core_web.dart" documentation.

- CONTRIBUTING.md
- README.md
This PR just adds a sentence to the README and CONTRIBUTING files, in order to deter 3P contributors from contributing to docs while we migrate.
[CLA]: …
> docs: contributing hold note

- packages/firebase_dynamic_links/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebase/dynamiclinks/FlutterFirebaseDynamicLinksPlugin.java
> refactor(firebase_dynamic_links): Remove deprecated Tasks.call() API from android.

- packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_message.dart
- packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_notification.dart
- packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/utils.dart
- packages/firebase_messaging/firebase_messaging_platform_interface/test/notification_test.dart
- packages/firebase_messaging/firebase_messaging_platform_interface/test/remote_message_test.dart
- packages/firebase_messaging/firebase_messaging_platform_interface/test/utils_test.dart
This PR allows users of `firebase_messaging` to convert a `RemoteMessage` to a Map by calling its `toMap()` method. 
A use case could be if the user wants to send a received background message via a `SendPort` to the application while the application is running in the background and is not terminated. Since a  `SendPort` is only allowe to send primitive data types, Maps and Lists, one have to convert the message to a Map. 
No related issues. …
> feat(firebase_messaging): add `toMap()` method to `RemoteMessage` and its properties

- packages/firebase_storage/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FlutterFirebaseStoragePlugin.java
- packages/firebase_storage/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FlutterFirebaseStorageTask.java
See title
fixes https://github.com/firebase/flutterfire/issues/8375
> refactor(firebase_storage): Remove deprecated `Tasks.call()` API from android.

- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java
- packages/firebase_messaging/firebase_messaging/example/android/app/build.gradle
See title.
related to https://github.com/firebase/flutterfire/issues/8073
> refactor(firebase_messaging): Remove deprecated `Tasks.call()` API from android.

- packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/method_channel/method_channel_messaging.dart
Prevent removal of `_firebaseMessagingCallbackDispatcher` during the release build with `--split-debug-info` flag being used
Fixes: #8305 
[CLA]: …
> fix(firebase_messaging): prevent isolate callback removal during split debug symbols

- packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
- packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/notification_settings.dart
- packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/utils.dart
- packages/firebase_messaging/firebase_messaging_web/lib/src/utils.dart
- packages/firebase_messaging/firebase_messaging_web/test/firebase_messaging_web_test.dart
See title.
fixes https://github.com/firebase/flutterfire/issues/8112
> feat(firebase_messaging): retrieve `timeSensitiveSetting` for iOS 15+.

- packages/flutterfire_ui/lib/src/auth/widgets/internal/loading_button.dart
- packages/flutterfire_ui/pubspec.yaml
- packages/flutterfire_ui/test/auth/widgets/email_form_test.dart
- packages/flutterfire_ui/test/test_utils.dart
The PR provides a fix for #8443, by setting the default buttonVariant of the LoadingButton to Outlined. This results in the UI-s using a LoadingButton to behave like they did before #8333 was merged. Before the #8333 was merged, the LoadingButton used to be an OutlinedButton, but in the current implementation it defaults to being a TextButton, which can not be overridden from composite UI elements using a LoadingButton (e.g. EmailForm or SignInScreen). This is poses a problem on these UI elements, because it makes it impossible to style the UI elements seperatly. (In the case of the EmailForm, the Sign in button and the Forgotton password button can only be styled together - Using TextButtonTheme).
Resolves #8443 
Resolves #8480  …
> fix(ui): set the default variant of LoadingButton to outlined (#8443)

- packages/firebase_dynamic_links/firebase_dynamic_links_platform_interface/test/mock.dart
Flutter 3.0.0 caused failing the CI: https://github.com/firebase/flutterfire/runs/6398175458?check_suite_focus=true
```
Nils-MBP-13-M1-3:firebase_dynamic_links_platform_interface nils$ flutter analyze
Running "flutter pub get" in firebase_dynamic_links_platform_interface...      1,220ms
Analyzing firebase_dynamic_links_platform_interface...                  
warning • The '!' will have no effect because the receiver can't be null • test/mock.dart:78:33 • unnecessary_non_null_assertion
1 issue found. (ran in 2.5s)
```
Closes #8646
Part of #8644 
Does your PR …
> refactor(firebase_dynamic_links_platform_interface): fix analyzer issue introduced in Flutter 3.0.0

- CONTRIBUTING.md
The `pub` command was removed. Instead, we should use `dart pub`. …
> docs: use `dart pub` instead of `pub` in `CONTRIBUTING.md`

- docs/auth/federated-auth.md
We should prefer using `const`. See https://youtu.be/B1fIqdqwWw8 …
> docs(firebase_auth): use `const` instead of `final` for generating nonce

- packages/cloud_firestore/cloud_firestore_platform_interface/test/method_channel_tests/method_channel_cloud_firestore_test.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/test/utils/test_common.dart
Flutter 3.0.0 caused failing the CI: https://github.com/firebase/flutterfire/runs/6398175458?check_suite_focus=true
```
Nils-MBP-13-M1-3:cloud_firestore_platform_interface nils$ flutter analyze
Running "flutter pub get" in cloud_firestore_platform_interface...      1,793ms
Analyzing cloud_firestore_platform_interface...                         
info • Avoid redundant argument values • test/method_channel_tests/method_channel_cloud_firestore_test.dart:74:31 • avoid_redundant_argument_values
warning • The '!' will have no effect because the receiver can't be null • test/utils/test_common.dart:81:39 • unnecessary_non_null_assertion
warning • The '!' will have no effect because the receiver can't be null • test/utils/test_common.dart:112:39 • unnecessary_non_null_assertion
warning • The '!' …
```
> refactor(cloud_firestore_platform_interface): fix analyzer issues introduced in Flutter 3.0.0

- packages/flutterfire_ui/README.md
The flutterfire_ui README file had some links broken, as they were pointing to a 'docs' folder instead of 'doc'. This PR intends to fix it. 
#8628
- [*] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [NA] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [NA] All existing and new tests are passing.
- [NA] I updated/added relevant documentation (doc comments with `///`).
- [NA] The analyzer (`melos run analyze`) does not report any problems on my PR.
- …
> fix: flutterfire_ui README links

- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/movie.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/simple.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/test/collection_test.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/test/setup_firestore_mock.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/templates/collection_reference.dart
This prevents from writing `moviesRef.doc('foo/bar/baz')` as that is not something that makes sense in the ODM.
The document reference returned will be typed as if it's a movie, when it most definitely is something different.
Users should instead use nested collections:
```dart
@Collection<Movie>('movies')
@Collection<Comments>('movies/*/bar')
final moviesRef = MovieCollectionReference();
void main() {
moviesRef.doc('123').comments.doc('baz');
}
``` …
> feat: Assert that collection.doc(id) does not point to a separate collection

- .github/ISSUE_TEMPLATE/---documentation-feedback.md
The documentation is now located under `firebase.google.com/docs/flutter`. Therefore, we should update in the issue template.
[CLA]: …
> chore: use `firebase.google.com` url in docs issue template

- packages/cloud_firestore_odm/README.md
Fix path do doc `doc/defining-models.md` which is located on `/doc` instead of `./docs`.
Fix path do doc `doc/defining-models.md` which is located on `/doc` instead of `./docs`.
N/A
- [N/A] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [N/A] All existing and new tests are passing.
- [N/A] I updated/added relevant documentation (doc comments with `///`).
- [N/A] The analyzer (`melos run analyze`) does not report any problems on my PR.
Does your PR require plugin users to manually update their …
> docs(firestore_odm): fix Firestore ODM readme broken link.

- packages/firebase_dynamic_links/firebase_dynamic_links/ios/Classes/FLTFirebaseDynamicLinksPlugin.m
See title
fixes https://github.com/firebase/flutterfire/issues/8556
> fix(firebase_dynamic_links): `getInitialLink()` returns `null` on 2nd call.

- packages/firebase_storage/firebase_storage/README.md
> docs(firebase_storage): use camel case style for "FlutterFire" in `README.md`

- packages/firebase_core/firebase_core/README.md
> docs(firebase_core): use camel case style for "FlutterFire" in `README.md`

- packages/firebase_remote_config/firebase_remote_config/pubspec.yaml
> refactor(firebase_remote_config): use `firebase.google.com` link for `homepage` in `pubspec.yaml`

- packages/firebase_messaging/firebase_messaging/pubspec.yaml
> refactor(firebase_messaging): use `firebase.google.com` link for `homepage` in `pubspec.yaml`

- packages/firebase_in_app_messaging/firebase_in_app_messaging/pubspec.yaml
All other packages are linking to `firebase.google.com`. Therefore, we should also do this for Firebase Dynamic Links.
Part of #8612
[CLA]: …
> refactor(firebase_in_app_messaging): use `firebase.google.com` link for `homepage` in `pubspec.yaml`

- packages/firebase_database/firebase_database/pubspec.yaml
> refactor(firebase_database): use `firebase.google.com` link for `homepage` in `pubspec.yaml`

- packages/flutterfire_ui/lib/src/auth/widgets/email_sign_up_dialog.dart
On smaller devices the profile email linking modal would overflow. Adding a singleChildScrollView allows the user to scroll to be able to see the full modal and doesn't overflow.
I am willing to work more in order to fix the null safe checking which is currently failing the melos analyze, but that is out of scope for this PR. 
I haven't really messed with flutter testing, but would be willing to add testing on this feature if it's required.
resolves #8682 
[issue …
> fix(ui): fixed profile email modal overflow occurring on smaller devices

- packages/firebase_auth/firebase_auth/README.md
- packages/firebase_database/firebase_database/README.md
- packages/firebase_messaging/firebase_messaging/README.md
- packages/firebase_storage/firebase_storage/README.md
As described in #8613 are linking all `README.md` to the archived docs. We should change this because the docs are archived and it makes the impression that the packages are not maintained anymore, when you are linking to archived docs.
This is one of the two proposals for fixing this issue (other proposal: https://github.com/firebase/flutterfire/pull/8813). In this proposal, we just link to the first article of the docs.
Advantages:
* Fit into the existing style of the `README.md` files
* No maintaining (in comparison to #8813)
Disadvantages:
* The links are sometimes a bit random because the format doesn't fit anymore. For the old docs we had in most cases a "Usage". But now we have a lot of small pages.
This PR is a proposal and should show a proof of concept for the new format. If …
> docs: point to "firebase.google" domain for hyperlinks in the usage section of `README.md` files

- packages/firebase_auth/firebase_auth/example/lib/main.dart
The main `flutterfire_auth example`, when compiled either on a device or through web will throw a connection error without this line commented out:
```
A network error (such as timeout, interrupted connection or unreachable host) has occurred.
```
removing the emulator setting, removes this error, helping people out there that are trying out this example.
(https://github.com/firebase/firebase-ios-sdk/issues/7864)](https://github.com/firebase/firebase-ios-sdk/issues/7864)
- [] All existing and new tests are passing.
- [] The analyzer (`melos run analyze`) …
> fix: update firebase_auth example to not be dependent on an emulator

- packages/firebase_crashlytics/firebase_crashlytics/pubspec.yaml
> refactor(firebase_crashlytics): use `firebase.google.com` link for `homepage` in `pubspec.yaml`

- packages/firebase_app_installations/firebase_app_installations/pubspec.yaml
> refactor(firebase_app_installations): use `firebase.google.com` link for `homepage` in `pubspec.yaml`

- packages/firebase_performance/firebase_performance/pubspec.yaml
> refactor(firebase_performance): use `firebase.google.com` link for `homepage` in `pubspec.yaml`

- packages/cloud_firestore/cloud_firestore/pubspec.yaml
> refactor(cloud_firestore): use `firebase.google.com` link for `homepage` in `pubspec.yaml`

- packages/firebase_auth/firebase_auth/pubspec.yaml
> refactor(firebase_auth): use `firebase.google.com` link for `homepage` in `pubspec.yaml`

- packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
Fix `FirebaseMessaging.onMessage` not firing on iOS if `UNUserNotificationCenterDelegate` is assigned to `UNUserNotificationCenter.currentNotificationCenter.delegate` by the app developer or another plugin / SDK.
The shouldReplaceDelegate was originally added to prevent an infinite
loop due to double swizzling. This only happens however if the app
developer set UNUserNotificationCenterDelegate to the AppDelegate. This
check was added in PR #4043. However this check does not consider if the
non-nil was set to something else, either by the app developer or
another SDK. FluterFire should swizzle in this case, so it does not miss
these events.
To address the above this commit checks if notificationCenter.delegate
conformsToProtocol FlutterAppLifeCycleProvider. This forwards events so
this is …
> fix(firebase_messaging): Swizzle check for FlutterAppLifeCycleProvider instead of UNUserNotificationCenterDelegate

- packages/flutterfire_ui/doc/auth/configuring-providers.md
In the Twitter section, Facebook was mistakenly referred to. So this corrects it back to Twitter.
> docs: Change Facebook Typo to Twitter in the documentation

- packages/firebase_crashlytics/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/FlutterFirebaseCrashlyticsPlugin.java
Fix a depreciation warning in Crashlytics
Fix #8896 
> fix(firebase_crashlytics): fix deprecation warning in Android

- packages/firebase_analytics/firebase_analytics/example/test_driver/firebase_analytics_e2e.dart
- packages/firebase_analytics/firebase_analytics/lib/src/firebase_analytics.dart
- packages/firebase_analytics/firebase_analytics_platform_interface/lib/src/method_channel/method_channel_firebase_analytics.dart
- packages/firebase_analytics/firebase_analytics_platform_interface/lib/src/platform_interface/platform_interface_firebase_analytics.dart
- packages/firebase_analytics/firebase_analytics_web/lib/firebase_analytics_web.dart
- packages/firebase_analytics/firebase_analytics_web/lib/interop/analytics.dart
- packages/firebase_analytics/firebase_analytics_web/lib/interop/analytics_interop.dart
- tests/test_driver/firebase_analytics/firebase_analytics_e2e.dart
Similiar to [#8860](https://github.com/firebase/flutterfire/pull/8860) this PR implements isSupported() in Firebase Analytics. We need to check if the Browser supports Analytics in our Flutter Web app.
- https://github.com/firebase/flutterfire/pull/8860
This PR changes the result type of isSupported in `analytics_interop.dart` from `bool` to `PromiseJsImpl<bool>`
> feat(firebase_analytics): provide isSupported for v9/analytics

- docs/messaging/overview.mdx
Set caution notice for the old Firebase Messaging docs were missing. Therefore, I added them. I copied the style from the cloud functions notice.
Fixes #8873
[CLA]: …
> docs(firebase_messaging): add caution notice for old docs

- packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart
Makes it more clear when you need to pass `vapidKey`
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING …
> docs(firebase_messaging): clarify when `vapidKey` parameter is needed when calling `getToken()`

- packages/firebase_analytics/firebase_analytics_web/lib/interop/analytics.dart
- packages/firebase_analytics/firebase_analytics_web/lib/interop/analytics_interop.dart
Modify the way Dart sends user properties to native Javascript with the setUserProperties() method. Now using jsify() in the same way that it's used in logEvent() method.
Fixes [firebase/flutterfire#8757](https://github.com/firebase/flutterfire/issues/8757)
> fix(analytics, web): use jsify with user properties

- tests/integration_test/e2e_test.dart
- tests/integration_test/firebase_core/firebase_core_e2e_test.dart
Migrates the Flutter Driver tests to Flutter Integration tests. I just copied the Flutter Driver. So have not changed any test.  
Part of #6829 
[CLA]: …
> test(firebase_core): migrate to `integration_test` package

- packages/firebase_app_check/firebase_app_check/lib/src/firebase_app_check.dart
Follows Effective Dart: [DO separate the first sentence of a doc comment into its own paragraph.](https://dart.dev/guides/language/effective-dart/documentation#do-separate-the-first-sentence-of-a-doc-comment-into-its-own-paragraph)
Does your PR require plugin users to manually update …
> docs(firebase_app_check): separate the first sentence of a doc comment into its own paragraph for `getToken()`

- tests/pubspec.yaml
- tests/test_driver/firebase_app_check/firebase_app_check_e2e.dart
There was a comment that adding Firebase App Check to the app crashes the RTDB emulator. I tried it out again and it worked. Therefore, it has been fixed :) …
> test(firebase_app_check): enable tests

- docs/crashlytics/_deobfuscated.md
see title.
fixes https://github.com/firebase/flutterfire/issues/8744
> docs(crashlytics): rm double quotes from scripts for deobfuscated stack traces on iOS

- tests/integration_test/e2e_test.dart
- tests/integration_test/firebase_app_installations/firebase_app_installations_e2e_test.dart
> test(firebase_app_installations): migrate to `integration_test` package

- docs/dynamic-links/receive.md
As in #8990 described, I think the step 4) c) in the [Firebase Dynamic Links docs](https://firebase.google.com/docs/dynamic-links/flutter/receive) is wrong. There is not a for Associated Domains in the Firebase Console. The step should say that you need to add the Associated Domains in XCode (like shown in the [iOS Firebase Dynamic Links](https://firebase.google.com/docs/dynamic-links/ios/receive#open-dynamic-links-in-your-app)).
Fixes #8990 …
> docs(firebase_dynamic_links): adjust wording for adding Associated Domains

- tests/integration_test/cloud_functions/cloud_functions_e2e_test.dart
- tests/integration_test/cloud_functions/sample_data.dart
- tests/integration_test/e2e_test.dart
> test(cloud_functions): migrate to `integration_test` package

- packages/firebase_messaging/firebase_messaging/README.md
the Usage link in the README of `firebase_messaging` was pointing to the `firestore` documentation. this PR changes that link to point to the `firebase_messaging` documentation. …
> docs(firebase_messaging): fix usage link to the documentation in the README.md

- tests/integration_test/e2e_test.dart
- tests/integration_test/firebase_crashlytics/firebase_crashlytics_e2e_test.dart
> test(firebase_crashlytics): migrate tests to `integration_test` package

- tests/integration_test/e2e_test.dart
- tests/integration_test/firebase_in_app_messaging/firebase_in_app_messaging_e2e_test.dart
> test(firebase_in_app_messaging): migrate to `integration_test` package

- tests/integration_test/e2e_test.dart
- tests/integration_test/firebase_database/data_snapshot_e2e.dart
- tests/integration_test/firebase_database/database_e2e.dart
- tests/integration_test/firebase_database/database_reference_e2e.dart
- tests/integration_test/firebase_database/firebase_database_configuration_e2e.dart
- tests/integration_test/firebase_database/firebase_database_e2e_test.dart
- tests/integration_test/firebase_database/on_disconnect_e2e.dart
- tests/integration_test/firebase_database/query_e2e.dart
> test(firebase_database): migrate to `integration_test` package

- tests/integration_test/e2e_test.dart
- tests/integration_test/firebase_messaging/firebase_messaging_e2e_test.dart
> test(firebase_messaging): migrate to `integration_test` package

- packages/firebase_auth/firebase_auth/example/lib/auth.dart
- packages/firebase_auth/firebase_auth/example/lib/profile.dart
- packages/firebase_auth/firebase_auth/lib/firebase_auth.dart
- packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
- packages/firebase_auth/firebase_auth/lib/src/multi_factor.dart
- packages/firebase_auth/firebase_auth/lib/src/recaptcha_verifier.dart
- packages/firebase_auth/firebase_auth/lib/src/user.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_multi_factor.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_multi_factor.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_recaptcha_verifier_factory.dart
- packages/firebase_auth/firebase_auth_platform_interface/test/platform_interface_tests/platform_interface_recaptcha_verifier_factory_test.dart
- packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_confirmation_result.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_multi_factor.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_recaptcha_verifier_factory.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_user_credential.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/multi_factor.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/utils/utils.dart
- packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
- tests/test_driver/firebase_auth/firebase_auth_multi_factor_e2e.dart
> feat(auth, web): add phone mfa

- packages/firebase_analytics/firebase_analytics/android/src/main/java/io/flutter/plugins/firebase/analytics/FlutterFirebaseAnalyticsPlugin.java
- packages/firebase_analytics/firebase_analytics/example/android/app/build.gradle
- packages/firebase_analytics/firebase_analytics/example/lib/main.dart
- packages/firebase_analytics/firebase_analytics/example/test_driver/firebase_analytics_e2e.dart
- packages/firebase_analytics/firebase_analytics/ios/Classes/FLTFirebaseAnalyticsPlugin.m
- packages/firebase_analytics/firebase_analytics/lib/src/firebase_analytics.dart
- packages/firebase_analytics/firebase_analytics/test/firebase_analytics_test.dart
- packages/firebase_analytics/firebase_analytics/test/mock.dart
- packages/firebase_analytics/firebase_analytics_platform_interface/lib/src/method_channel/method_channel_firebase_analytics.dart
- packages/firebase_analytics/firebase_analytics_platform_interface/lib/src/platform_interface/platform_interface_firebase_analytics.dart
- packages/firebase_analytics/firebase_analytics_platform_interface/test/method_channel_tests/method_channel_firebase_analytics_test.dart
- packages/firebase_analytics/firebase_analytics_platform_interface/test/mock.dart
- packages/firebase_analytics/firebase_analytics_platform_interface/test/platform_interface_tests/platform_interface_analytics_test.dart
- packages/firebase_analytics/firebase_analytics_web/lib/firebase_analytics_web.dart
- tests/test_driver/firebase_analytics/firebase_analytics_e2e.dart
Add an appInstanceId property on FirebaseAnalytics, exporting the API from the underlying native Firebase library implementations.
This value is needed to send server-side events through the Measurement Protocol as a part of the same session, and also useful for debugging to pair up with the data visible in DebugView and BigQuery. …
> feat(firebase_analytics): retrieves `appInstanceId` property on native platforms if available

- packages/firebase_auth/firebase_auth/lib/firebase_auth.dart
- packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
- packages/firebase_auth/firebase_auth/lib/src/multi_factor.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/firebase_auth_multi_factor_exception.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/utils/exception.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_multi_factor.dart
- packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
MultiFactor classes weren't exposed through the universal package. This fixes the missing classes.
It is not breaking since the facing classes have the same name for the user.
https://github.com/firebase/flutterfire/issues/9190 …
> feat(auth): expose the missing MultiFactor classes through the universal package

- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/integration.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/integration/query.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/movie.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/test_driver/common.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/lib/src/firestore_reference.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/test/common.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/simple.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/templates/collection_reference.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/templates/document_reference.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/templates/document_snapshot.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/templates/query_document_snapshot.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/templates/query_reference.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/templates/query_snapshot.dart
This change is breaking, as classes such as FirestoreDcoumentReference
now take two generic arguments instead of one.
> feat!: The low-level interface of Queries/Documentreferences are improved to no-longer use `Object?` in various situations

- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/movie.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/test_driver/collection_reference_test.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/simple.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/simple.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/collection_generator.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/templates/query_reference.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/test/document_reference_test.dart
> feat: Add where(arrayContains) support

- docs/auth/start.md
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/types.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart
It restores the previous (and correct) persistence location, so it shouldn't be considered as breaking.
See correct order here: https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/platform_browser/index.ts#L47
https://github.com/firebase/flutterfire/issues/9243 …
> fix(auth, web): restore default persistence to IndexedDB that was incorrectly set to localStorage

- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
As discussed internally, there is an issue with dart2js compilation in release mode. 
One of the workaround is to type those functions as Object.
The tests for Cloud Firestore are currently skipped, we'll bring back those tests in another PR.
fixes https://github.com/firebase/flutterfire/issues/9106 …
> fix(firestore, web): change the interop to fix an issue with `startAt()` & `endAt()` when compiling with dart2js in release mode

- packages/firebase_database/firebase_database/example/pubspec.yaml
- packages/firebase_database/firebase_database_platform_interface/lib/src/server_value.dart
- tests/test_driver/firebase_database/database_reference_e2e.dart
See title.
fixes https://github.com/firebase/flutterfire/issues/7933
> feat(firebase_database): `ServerValue.increment()` now correctly accepts a `num`  to support both integers and doubles.

- packages/firebase_database/firebase_database_web/lib/src/interop/database.dart
- packages/firebase_database/firebase_database_web/lib/src/interop/database_interop.dart
As discussed internally, there is an issue with dart2js compilation in release mode.
One of the workaround is to type those functions as Object.
Fixes #9091
[CLA]: …
> fix(database, web): change the interop to fix an issue with startAt/endAt/limitTo when compilating with dart2js in release mode

- README.md
This is a left over piece of copy which should now be removed.
> chore: remove experimental status on readme

- packages/firebase_auth/firebase_auth/test/user_test.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/user_metadata.dart
```js
// On firebase-admin (server)
console.log(user.metadata.creationTime); // Mon, 18 Jul 2022 10:17:31 GMT
```
```dart
// As currently implemented
print('${DateTime.fromMillisecondsSinceEpoch(_creationTimestamp!)}'); // 2022-07-18 11:17:31.699
// Fix
print('${DateTime.fromMillisecondsSinceEpoch(_creationTimestamp!, isUtc: true)}'); // 2022-07-18 10:17:31.699Z
```
fixes https://github.com/firebase/flutterfire/issues/9162 …
> fix(firebase_auth): use correct UTC time from server for `currentUser?.metadata.creationTime` & `currentUser?.metadata.lastSignInTime`

- packages/firebase_messaging/firebase_messaging/example/lib/main.dart
- packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
This fixes the scenario where a push notification is sent but the user presses the app icon to open app. This PR ensures that the notification that was tapped to open the app is the RemoteMessage from `getInitialMessage()`.
This also fixes `onMessageOpenedApp` which was opening the app when tapping a notification from a terminated state.
I've also discovered that when the app is in a terminated state and a push notification is sent, the `initState()` and `build()` functions within the Flutter application are called before the app has been opened. Therefore, the `getInitialMessage()` cannot be put into`initState()`. Otherwise, the `RemoteMessage` returned from `getInitialMessage()` will be `null` as it is not known whether the app was opened via notification yet.
This bug is being tracked …
> fix(firebase_messaging, iOS): ensure initial notification was tapped to open app. fixes `getInitialMessage()` & `onMessageOpenedApp()` .

- packages/firebase_core/firebase_core/pubspec.yaml
Adds `/` in homepage url in `pubspec.yaml` to get response status `200`
<details>
<summary>Screenshots</summary>
Without `/`
<br />
With `/`
</details>
Fixes #9313  …
> fix(firebase_core): broken homepage link in pubspec.yaml

- packages/firebase_auth/firebase_auth/lib/src/user.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_user.dart
see title.
fixes https://github.com/firebase/flutterfire/issues/8171
> docs(firebase_auth): explicit mention that `refreshToken` is empty string on native platforms on the `User`instance

- packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
see title.
fixes https://github.com/firebase/flutterfire/issues/6216
> fix(cloud_firestore, web): stop `FirebaseError` appearing in console on hot restart & hot refresh

- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/GeneratedAndroidFirebaseAuth.java
- packages/firebase_auth/firebase_auth/example/ios/Runner.xcodeproj/project.pbxproj
- packages/firebase_auth/firebase_auth/example/lib/profile.dart
- packages/firebase_auth/firebase_auth/ios/Classes/messages.g.h
- packages/firebase_auth/firebase_auth/ios/Classes/messages.g.m
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/utils/pigeon_helper.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/pigeon/messages.pigeon.dart
- packages/firebase_auth/firebase_auth_platform_interface/pigeons/messages.dart
Even tho it doesn't happen in e2e tests, factorId can be null on iOS, causing a null exception.
I've changed the pigeon interface to be nullable on factorId, and added a default value.
https://github.com/firebase/flutterfire/issues/9363 …
> fix(auth, iOS): fix an error where MultifactorInfo factorId could be null on iOS

- packages/cloud_firestore/cloud_firestore/example/test_driver/second_app_e2e.dart
Fixing Firestore android e2e test that is timing out on the CI. It does work locally.
Created an issue to start tracking skipped e2e tests: https://github.com/firebase/flutterfire/issues/9375 …
> test(cloud_firestore, android): skip end 2 end test that is timing out on CI

- packages/firebase_crashlytics/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/FlutterFirebaseCrashlyticsPlugin.java
- packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart
- packages/firebase_crashlytics/firebase_crashlytics/lib/src/utils.dart
- packages/firebase_crashlytics/firebase_crashlytics/test/firebase_crashlytics_test.dart
- packages/firebase_crashlytics/firebase_crashlytics_platform_interface/lib/src/method_channel/method_channel_crashlytics.dart
- packages/firebase_crashlytics/firebase_crashlytics_platform_interface/lib/src/platform_interface/platform_interface_crashlytics.dart
- packages/firebase_crashlytics/firebase_crashlytics_platform_interface/test/method_channel_tests/method_channel_crashlytics_test.dart
As requested, this PR reverts firebase/flutterfire#9365
> chore(firebase_crashlytics, android): Revert PR to send Flutter Build Id to Crashlytics to get --split-debug-info working

- docs/auth/federated-auth.md
- packages/firebase_auth/firebase_auth/example/ios/Podfile
- packages/firebase_auth/firebase_auth/example/ios/Runner.xcodeproj/project.pbxproj
- packages/firebase_auth/firebase_auth/example/ios/Runner/Runner.entitlements
- packages/firebase_auth/firebase_auth/example/lib/auth.dart
- packages/firebase_auth/firebase_auth/example/macos/Podfile
- packages/firebase_auth/firebase_auth/example/macos/Runner.xcodeproj/project.pbxproj
- packages/firebase_auth/firebase_auth/example/macos/Runner/DebugProfile.entitlements
- packages/firebase_auth/firebase_auth/example/macos/Runner/Release.entitlements
- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
- packages/firebase_auth/firebase_auth/ios/Classes/Public/FLTFirebaseAuthPlugin.h
- packages/firebase_auth/firebase_auth/lib/firebase_auth.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/firebase_auth_platform_interface.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/apple_auth.dart
- packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
We currently rely on [sign_in_with_apple](https://pub.dev/packages/sign_in_with_apple) for Sign In With Apple. We now recommend directly using directly Firebase to connect with Apple.
Closes https://github.com/firebase/flutterfire/discussions/5560 …
> feat(auth): add Sign in with Apple directly in Firebase Auth for Android, iOS 13+ and Web

- packages/firebase_analytics/firebase_analytics_web/lib/interop/analytics.dart
[setCurrentScreen()](https://firebase.google.com/docs/reference/js/analytics#setcurrentscreen) is now obsolete. Using `logEvent()` as documentation recommends. 
Using `firebase_screen` parameter as mentioned in [docs](https://firebase.google.com/docs/reference/js/analytics.eventparams.md#eventparamsfirebase_screen).
fixes https://github.com/firebase/flutterfire/issues/8403 …
> fix(analytics, web): `setCurrentScreen()` API is now obsolete, using `logEvent()` instead

- packages/firebase_in_app_messaging/firebase_in_app_messaging/android/src/main/java/io/flutter/plugins/firebase/inappmessaging/FirebaseInAppMessagingPlugin.java
See title.
As part of https://github.com/firebase/flutterfire/issues/8073
> chore(firebase_in_app_messaging, android): update deprecated `Task.call()` to `TaskCompletionSource` API

- packages/firebase_messaging/firebase_messaging/android/build.gradle
- packages/firebase_messaging/firebase_messaging/android/src/main/AndroidManifest.xml
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingUtils.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebasePermissionManager.java
- packages/firebase_messaging/firebase_messaging/example/android/app/build.gradle
- packages/firebase_messaging/firebase_messaging/example/android/app/src/main/AndroidManifest.xml
- tests/android/app/build.gradle
- tests/android/app/src/main/java/io/flutter/app/FlutterMultiDexApplication.java
PR checks if the app is running on android 13 and will check the app notification permissions. If none set or permissions not granted, a dialog box will appear requesting user notification permission.
I consider this a breaking change as there is certain configuration required such as `targetSdkVersion` & `compileSdkVersion` targeting android API 33. 
Users will also need to have the `android:exported="true"` property set in app manifest on apps running on android 12 or higher.
closes https://github.com/firebase/flutterfire/issues/8720 …
> feat(firebase_messaging, android)!: android 13 notifications permission request

- packages/firebase_app_check/firebase_app_check/android/src/main/java/io/flutter/plugins/firebase/appcheck/FlutterFirebaseAppCheckPlugin.java
See title.
As part of https://github.com/firebase/flutterfire/issues/8073
> chore(firebase_app_check, android): update deprecated `Tasks.call()`  to `TaskCompletionSource` API

- packages/firebase_remote_config/firebase_remote_config/android/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfig/FirebaseRemoteConfigPlugin.java
- packages/firebase_remote_config/firebase_remote_config/example/android/app/build.gradle
See title.
As part of https://github.com/firebase/flutterfire/issues/8073
> refactor(firebase_remote_config, android): update deprecated `Tasks.call()` to `TaskCompletionSource` API

- packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart
Replace null or empty stack traces with the current stack trace. This will fix an issue where crashes with non-null, but empty, stack traces were not being routed to the console. …
> fix(crashlytics): Replace null or empty stack traces with the current stack trace

- docs/cloud-messaging/receive.md
- packages/firebase_messaging/firebase_messaging/example/lib/main.dart
see title.
closes https://github.com/firebase/flutterfire/issues/9446
> docs(messaging): update docs to use `@pragma('vm:entry-point')` annotation for messaging background handler

- docs/auth/federated-auth.md
- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
- packages/firebase_auth/firebase_auth/example/macos/Runner.xcodeproj/project.pbxproj
- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
- packages/firebase_auth/firebase_auth/lib/src/user.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_user.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_user_credential.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_user.dart
We were lacking the ability to link AuthProvider with currently connected users.
It's needed to upgrade anonymous users.
Closes #9442
[CLA]: …
> feat(auth): add `linkWithProvider` to support for linking auth providers

- docs/auth/federated-auth.md
- packages/firebase_analytics/firebase_analytics/lib/src/firebase_analytics.dart
- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
- packages/firebase_auth/firebase_auth/example/lib/auth.dart
- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
- packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart
See title - this method has been renamed to match naming conventions used in other Firebase SDKs and the old API marked as deprecated (to be removed in a later release).
N/A …
> refactor(auth): deprecate `signInWithAuthProvider` in favor of `signInWithProvider`

- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/movie.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/collection_generator.dart
fixes #9551
No clue on how to write tests for this, as this is related to watch mode.
The code generator was stateful, so some state was preserved between builds, triggering an unwanted exception.
This PR refactors the generator to make it stateless, preventing the issue. …
> fix: a false positive by checking that there are no prefix duplicates.

- docs/auth/federated-auth.md
- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
- packages/firebase_auth/firebase_auth/example/lib/auth.dart
- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
- packages/firebase_auth/firebase_auth/lib/src/user.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_user.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_user.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_user.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
> feat(auth): add `reauthenticateWithProvider`

- packages/firebase_database/firebase_database/lib/src/query.dart
Removes consecutively duplicated word in dart doc comments.
Fixes #9619
> docs(firebase_database): removed duplicated words in dart doc comment

- docs/app-check/debug-provider.md
See title.
fixes #8969 
fixes #6551 
fixes https://github.com/firebase/flutterfire/issues/8425
> docs(firebase_app_check): Add debug provider documentation.

- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
> feat(auth, ios): fix an iOS crash when using Sign In With Apple due to invalid return of nil instead of NSNull

- packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart
Fixes the `FirebaseAuth.setSettings` docs, which @russellwheatley forgot to update in #6367. That is, the docs were missing documentation of the newly added parameters.
Additionally, I correctly the spelling of "Android" and adjusted the formatting of the different paragraphs to be consistent. …
> docs(auth): update `setSettings()` inline documentation

- packages/_flutterfire_internals/lib/src/exception.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_document_reference.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_firestore.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_load_bundle_task.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_query.dart
- packages/firebase_app_check/firebase_app_check_platform_interface/lib/src/method_channel/method_channel_firebase_app_check.dart
- packages/firebase_app_installations/firebase_app_installations_platform_interface/lib/src/method_channel/method_channel_firebase_app_installations.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart
- packages/firebase_auth/firebase_auth_platform_interface/pubspec.yaml
- packages/firebase_database/firebase_database_platform_interface/lib/src/method_channel/method_channel_query.dart
Due to `StreamController.onListen` shenanigans, exceptions within its callback have an incorrect stacktrace.
To fix this, we can keep a reference on the caller stacktrace, and on error, report the error with that stacktrace instead.
While we're at this, this PR also changes a few `EventChanne.receiveBroadcastStream` that did not implement a "handleError", so platform exceptions were not converted to FirebaseExceptions.
fixes #6743 …
> fix: Exceptions inside Query.snapshots() and more now have a stack trace that correctly points to the invocation of the throwing method

- docs/crashlytics/_customize-crash-reports.md
- packages/firebase_crashlytics/firebase_crashlytics/lib/firebase_crashlytics.dart
- packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart
Updated `recordError` so it now allows `Iterable<Object` in the `information` parameter. This makes it backwards compatible, but also allows users to pass in whatever object they wish (e.g. ['something', 'version']) and it will write it to a `String` for logging in the Crashlytics dashboard in release mode.
I've tested in release mode using this input:
```dart
final err = Exception('AAAAAAAA');
Iterable<Object> properties = ['in release mode'];
FirebaseCrashlytics.instance.recordError(err, StackTrace.current,
information: properties, fatal: true);
```
It shows on the dashboard correctly:
fixes https://github.com/firebase/flutterfire/issues/7912
This will ensure a …
> fix(crashlytics): parameter `information` accepts `Iterable<Object>` for further diagnostic logging information

- packages/firebase_auth/firebase_auth_platform_interface/test/method_channel_tests/method_channel_firebase_auth_test.dart
- packages/firebase_dynamic_links/firebase_dynamic_links_platform_interface/test/method_channel_tests/method_channel_firebase_dynamic_links_test.dart
*I removed the `StreamSubscription` which was useless in the tests.*
*No related issues*
> test: Remove useless `StreamSubscription` from e2e tests

- packages/firebase_dynamic_links/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebase/dynamiclinks/FlutterFirebaseDynamicLinksPlugin.java
The activity is accessed potentially unsafely, and we are seeing some null reference crashes from this file.
https://github.com/firebase/flutterfire/issues/9544
- [-] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
> fix: Add speculative fix for null object reference crash

- packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
- packages/firebase_ui_localizations/example/pubspec.yaml
- packages/firebase_ui_localizations/pubspec.yaml
1. CI failing because `firebase_ui_localizations` package doesn't have false secrets set:https://github.com/firebase/flutterfire/actions/runs/3248718911/jobs/5331015686
2. Loosened version constraints for dart SDK. (Just encountered issue when running `melos bootstrap`).
3. speculative fix for formatting CI bug. 
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and …
> chore: fix CI analyze issue and temporary fix for formatting CI issue

- packages/flutterfire_ui/example/pubspec.yaml
- packages/flutterfire_ui/pubspec.yaml
> fix(ui): update dependencies to latest. Last release as `flutterfire_ui` is deprecated and no longer supported.

- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/integration.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/freezed.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/simple.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/simple.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/collection_data.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/test/query_reference_test.dart
The ODM used to generate methods such as `whereHashCode`
closes #9419
Does your PR …
> fix: The ODM correctly no-longer generates query utilities for getters.

- docs/auth/federated-auth.md
- packages/firebase_auth/firebase_auth/example/lib/auth.dart
- packages/firebase_auth/firebase_auth/lib/src/user.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_user.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_user.dart
As noted by [this comment](https://github.com/firebase/flutterfire/pull/9570#issuecomment-1272286181) the web methods were not currently exposed  …
> feat(auth, web): expose `reauthenticateWithRedirect` and `reauthenticateWithPopup`

- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
- packages/firebase_auth/firebase_auth/lib/src/user.dart
- packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_confirmation_result.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_multi_factor.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_user.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_user_credential.dart
- packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
> fix(auth): properly propagate the `FirebaseAuthMultiFactorException` for all reauthenticate and link methods

- tests/test_driver/firebase_storage/reference_e2e.dart
> test(storage): skip flaky e2e test that keeps timing out in CI

- packages/firebase_ui_auth/example/macos/Podfile
- packages/firebase_ui_auth/example/test_driver/apple_sign_in_test.dart
- packages/firebase_ui_auth/example/test_driver/firebase_ui_auth_e2e.dart
- packages/firebase_ui_oauth_apple/lib/src/provider.dart
> fix(ui_oauth_apple): set default scope to 'email' and add a way to provide custom scopes

- packages/firebase_dynamic_links/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebase/dynamiclinks/FlutterFirebaseDynamicLinksPlugin.java
- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/app/src/main/AndroidManifest.xml
This exception:
```
Attempt to invoke virtual method 'void ce.j.c(java.lang.String, java.lang.Object)'
```
is this [line of code](https://github.com/firebase/flutterfire/blob/ec2ac7cd6cbfb5e4429144fc9c14b78c81e068b9/packages/firebase_dynamic_links/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebase/dynamiclinks/FlutterFirebaseDynamicLinksPlugin.java#L113):
```
channel.invokeMethod("FirebaseDynamicLink#onLinkSuccess", dynamicLink);
```
The [important change](https://github.com/firebase/flutterfire/compare/%40russell/dynamic-links-8516?expand=1#diff-279c05314f8201e2db23679d738073b04bef856810b327d22bc260d3be96fbc2L65) here is checking if `channel` is `null`. If it is, it means the FlutterEngine is in a detached state and we shouldn't be calling the method channel.
I've …
> fix(dynamic-links): check if `MethodChannel` is `null` which was causing `NullPointerException`

- packages/firebase_ui_oauth_google/lib/src/provider.dart
I started noticing flutter/flutter#114304 when migrating to `firebase_ui` from `flutterfire_ui`, and tried to fix it, since I really need to ship an update that depends on not including all the providers. I found that the `clientId` is not passed into `GoogleSignIn`, so I tried adding it, which works. I also checked the previous provider implementation from `flutterfire_ui` which added it too, so I assume this is a mistake that `firebase_ui` doesn't ATM.
Note that I use Dart-only initialization, it may not surface when the Google plist is included in the iOS app.
By the way, the issue prevents users from logging out regardless of the authentication method they used to log in.
Regarding the checklist: I couldn't manage to run the e2e tests with Melos, I had a ton of Xcode compilation …
> fix(auth): Pass the clientId into GoogleSignIn

- packages/firebase_ui_auth/example/test_driver/google_sign_in_test.dart
- packages/firebase_ui_oauth/lib/src/oauth_provider_button_base.dart
- packages/firebase_ui_oauth/test/flutterfire_ui_oauth_test.dart
> fix(ui_oauth): initialize auth and auth listener in standalone OAuth buttons

- packages/_flutterfire_internals/lib/src/exception.dart
1. We send `additionalData` property as part of exception [here](https://github.com/firebase/flutterfire/blob/master/packages/firebase_dynamic_links/firebase_dynamic_links/ios/Classes/FLTFirebaseDynamicLinksPlugin.m#L52-L75). This causes an uncaught exception [here](https://github.com/firebase/flutterfire/blob/master/packages/_flutterfire_internals/lib/src/exception.dart#L41-L42) because it is expecting `Map<String, String>` type. I've updated to allow nested maps (i.e. `Map<String, Object>`). 
The other issue I want to highlight is `code` and `message`. They are really unhelpful. On the other hand, `additionalData` has more accurate information. 
As you can see from the below noted, `additionalData` has the `additionalData.message`: "Requested entity was not found" compared to the …
> fix(dynamic-link): fix unhandled exception caused by "additionalData" map

- packages/firebase_ui_auth/lib/src/views/phone_input_view.dart
- packages/firebase_ui_auth/lib/src/widgets/phone_input.dart
- packages/firebase_ui_auth/test/widgets/phone_input_test.dart
> fix(ui): allow null countryCode for phone input

- packages/firebase_messaging/firebase_messaging/example/lib/main.dart
- packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
Tested the different behavior:
- Receiving multiples notification and check the good one is in the initialMessage
- Receiving multiple notifications but opening the app with the icon
- Opening the app in background state from a notification and check that the initialMessage is null
- Opening the app in terminated state from a notification and check that the initialMessage is correct
#9906 
[Contributor …
> fix(messaging, ios): prevent getInitialMessage from being null at the start of the app

- packages/firebase_ui_auth/lib/src/views/forgot_password_view.dart
- packages/firebase_ui_auth/test/firebase_ui_test.dart
- packages/firebase_ui_auth/test/views/forgot_password_view_test.dart
> fix(firebase_ui_auth): clear the error on ForgotPasswordScreen after submitting a valid email

- packages/firebase_ui_auth/lib/src/screens/internal/responsive_page.dart
> fix(firebase_ui_auth): preserve UI form state when device rotates

- packages/firebase_dynamic_links/firebase_dynamic_links_platform_interface/lib/src/method_channel/method_channel_firebase_dynamic_links.dart
- packages/firebase_dynamic_links/firebase_dynamic_links_platform_interface/lib/src/pending_dynamic_link_data.dart
> fix(dynamic_links, ios): allow for nullable utm values as send per the iOS SDK

- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingStore.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingUtils.java
Since we don't have access to the `notification` field in the RemoteMessage Builder, we are forced to add a second field to hold the value of the notification and restore it from the SharedPreferences
closes #9813 …
> fix(messaging, android): fix an issue where the notification wasn't restored when going into terminated state

- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
We weren't using the correct FirebaseAuth instance when Sign In With Apple, which could cause issues when running secondary apps.
closes #10001 
[CLA]: …
> fix(auth, ios): Apple Sign In on a secondary app doesnt sign in the correct Firebase Auth instance

- packages/firebase_ui_auth/lib/firebase_ui_auth.dart
- packages/firebase_ui_auth/lib/src/widgets/layout_flow_aware_padding.dart
- packages/firebase_ui_oauth/lib/src/oauth_provider_button_base.dart
- packages/firebase_ui_oauth/test/flutterfire_ui_oauth_test.dart
> fix(firebase_ui_oauth): fix OAuth provider buttons paddings

- packages/firebase_messaging/firebase_messaging/example/android/build.gradle
- packages/firebase_messaging/firebase_messaging/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/firebase_messaging/firebase_messaging/example/pubspec.yaml
> chore(messaging): updating flutter_local_notifications to 12.0.4 in the example app

- packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
- packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart
- packages/firebase_ui_auth/example/lib/main.dart
fix https://github.com/firebase/flutterfire/issues/10008
> fix(auth, web): `currentUser` is now populated right at the start of the application without needing to wait for `authStateChange``

- packages/cloud_firestore/cloud_firestore/example/integration_test/instance_e2e.dart
- packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
> feat: `setIndexConfigurationFromJSON()` API. Allow users to pass JSON string

- packages/firebase_ui_auth/example/lib/main.dart
- packages/firebase_ui_auth/lib/src/auth_flow.dart
- packages/firebase_ui_auth/lib/src/auth_state.dart
- packages/firebase_ui_auth/lib/src/providers/auth_provider.dart
- packages/firebase_ui_auth/lib/src/providers/email_auth_provider.dart
> fix(ui_auth): automatically upgrade anonymous accounts

- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart
- packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
Add support to SAMLProvider on web
closes #8527
> feat(auth, web): add SAMLProvider support to Web

- packages/cloud_functions/cloud_functions/android/src/main/java/io/flutter/plugins/firebase/functions/FlutterFirebaseFunctionsPlugin.java
> refactor(cloud_functions): remove deprecated Task APIs

- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/utils/load_bundle_task_state.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/action_code_info.dart
- packages/firebase_auth/firebase_auth_platform_interface/test/action_code_info_test.dart
- packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
`FallThroughError` is deprecated and will be removed with Dart 3.0. Since this rolls into g3, it's blocking us [landing the removal](https://dart-review.googlesource.com/c/sdk/+/259041).
This PR migrates the errors to `UnsupportedError`s.
* https://github.com/dart-lang/sdk/issues/49529
* https://github.com/firebase/flutterfire/issues/10079
Users should _not_ catch `Error`s, only `Exceptions`. As such this is not a breaking change. …
> chore: Replace `FallThroughError` with `UnsupportedError`

- packages/firebase_ui_auth/README.md
- packages/firebase_ui_auth/doc/providers/email-link.md
- packages/firebase_ui_auth/doc/providers/email.md
- packages/firebase_ui_auth/doc/providers/oauth.md
- packages/firebase_ui_auth/doc/providers/phone.md
> docs(ui_auth): add docs links to the package README, add naming conflicts resolution instructions

- packages/firebase_ui_firestore/lib/src/query_builder.dart
- packages/firebase_ui_firestore/lib/src/table_builder.dart
- packages/firebase_ui_firestore/test/table_builder_test.dart
> feat(ui_firestore): use aggregate query to display total rows count in DataTable

- packages/firebase_auth/firebase_auth/example/android/app/google-services.json
Updated google-service.json after adding SHA1 and SHA256 in Firebase console.
Since we moved to `flutterfire-e2e` project we couldn't use MFA without. …
> chore(auth): updating the google-services.json

- packages/firebase_ui_auth/lib/src/screens/sms_code_input_screen.dart
> fix(ui_auth): fix default SMSCodeInputScreen breakpoint

- packages/firebase_ui_auth/lib/firebase_ui_auth.dart
- packages/firebase_ui_auth/lib/src/auth_flow.dart
- packages/firebase_ui_auth/lib/src/auth_state.dart
- packages/firebase_ui_auth/lib/src/flows/email_flow.dart
Check for additional user info and emit `UserCreated` when `credential.additionalUserInfo?.isNewUser` is true
Closes #10124
[CLA]: …
> fix(ui_auth): emit UserCreated state when signed in user is new

- packages/firebase_performance/firebase_performance/example/integration_test/firebase_performance_e2e_test.dart
- packages/firebase_performance/firebase_performance/ios/Classes/FLTFirebasePerformancePlugin.m
By returning nil, we have the same behavior as Android :) 
closes #10240 
> fix(performance, ios): fix a crash that would occur when creating a trace with performance collection disabled

- packages/firebase_ui_auth/lib/src/widgets/email_form.dart
Currently, when clicking the Sign In button, the in-screen keyboard is not dismissed. This PR automatically dismisses the keyboard (by unfocusing) when the form is submitted.
Fixes #10207 …
> fix(ui_auth): unfocus to dismiss keyboard when submitting email form

- packages/firebase_ui_auth/doc/navigation.md
- packages/firebase_ui_auth/doc/providers/email-link.md
- packages/firebase_ui_auth/doc/providers/email-verification.md
- packages/firebase_ui_auth/doc/providers/email.md
Little readme fixes
I also made this PR, but no issues: https://github.com/firebase/flutterfire/pull/10247
> docs(ui_auth): Removed extra header and fixed typos

- packages/cloud_firestore_odm/doc/defining-models.md
In defining-models.md one could read "Note: JsonSerializable(fieldRename: ...) and JsonKey(ignore: true) are currently not supported" but it seems that now those features are supported. See: https://github.com/firebase/flutterfire/pull/9030 @rrousselGit. 
https://github.com/firebase/flutterfire/issues/9419
[Flutter Style …
> docs(cloud_firestore_odm): update doc to reflect json_serializable's field rename/property ignore support

- packages/cloud_firestore_odm/doc/defining-models.md
Also include various small improvements to defining-models.md.
While useful information can be found in the discussion linked in doc, I added the bits I would have loved to find directly in the doc when I take interest in Cloud Firestore ODM. Especially data type support.  …
> docs(cloud_firestore_odm): details supported data types

- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
- packages/cloud_firestore/cloud_firestore/lib/src/query.dart
- packages/cloud_firestore/cloud_firestore/test/query_test.dart
> fix(cloud_firestore): startAfterDocument with where a DocumentReference throws

- packages/firebase_performance/firebase_performance/example/integration_test/firebase_performance_e2e_test.dart
- packages/firebase_performance/firebase_performance/ios/Classes/FLTFirebasePerformancePlugin.m
> fix(performance, ios): fix a crash that could occur with httpMetricStart when disabling collection

- packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestoreWriter.m
close https://github.com/firebase/flutterfire/issues/10314 (another instance of the issue) …
> fix(firestore, ios): fix an issue when removing a value that didn't exist in ServerTimestampBehavior map

- packages/firebase_analytics/firebase_analytics/lib/src/firebase_analytics.dart
- packages/firebase_analytics/firebase_analytics_platform_interface/lib/src/platform_interface/platform_interface_firebase_analytics.dart
When I used `logEvent` I tried to get Dart documentation about the limitations of `logEvent`. However, there was no helpful information (like length of `name`, reversed names, data types for `parameters`). Therefore, I copied the documentation from firebase.google.com/docs into the Dart source code.
Copied from: https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#public-void-logevent-string-name,-bundle-params
...
[issue …
> docs(firebase_analytics): add more documentation for `logEvent`

- packages/firebase_database/firebase_database/lib/src/database_reference.dart
Removed two words in function description which were too many there.
> docs(database): remove duplicate wording in documentation

- docs/crashlytics/_deobfuscated.md
- docs/crashlytics/_get-started.md
See title.
part of: https://github.com/firebase/flutterfire/issues/8934#issuecomment-1410781888
> docs(crashlytics, android): update obfuscated crash reports documentation

- packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
- packages/cloud_firestore/cloud_firestore/example/integration_test/document_reference_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/ios/Runner.xcodeproj/project.pbxproj
- packages/cloud_firestore/cloud_firestore/example/ios/Runner/Info.plist
- packages/cloud_firestore/cloud_firestore/example/lib/main.dart
- packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart
- packages/cloud_firestore/cloud_firestore/lib/src/utils/codec_utility.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_document_reference.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_document_reference.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/test/method_channel_tests/method_channel_document_reference_test.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/test/utils/test_firestore_message_codec.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/document_reference_web.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/utils/encode_utility.dart
This PR allows users to use FieldPath when running `DocumentReference.update`.
All the String are now turned into FieldPath before being send to native in order to minimise the number of cases to handle on the native side.
closes #10367 …
> feat(firestore): add support to update using FieldPath

- packages/firebase_ui_oauth_google/lib/src/provider.dart
- packages/firebase_ui_oauth_google/pubspec.yaml
> fix(ui_oauth_google): allow GoogleService-Info.plist based configuration

- packages/firebase_dynamic_links/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebase/dynamiclinks/FlutterFirebaseDynamicLinksPlugin.java
- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/app/build.gradle
1. `buildShortLink` will always have arguments object so I've made that object non-nullable.
2. `uriPrefix` is a required property. Made this non-nullable.
3. Suppressed warnings for objects that could be `null` but they are checked whether `null` before accessing. We use suppress this warning in other plugins when we know it is checked first.
4. Updated `compileSdkVersion` for example.
part of https://github.com/firebase/flutterfire/issues/8073 …
> chore(dynamic-links, android): suppress "unchecked" API & annotate non-nullable API

- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
- packages/cloud_firestore/cloud_firestore/lib/src/query.dart
- packages/cloud_firestore/cloud_firestore/lib/src/utils/codec_utility.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_query.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/utils/firestore_message_codec.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_query.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
We should support Iterable instead of List to make the API easier for the end user.
closes #10407 
> fix(firestore): supports Iterable in queries instead of List

- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/utils/encode_utility.dart
With the added support of updating fields containing a "." using FieldPath in update, a mistake was done during the casting of FieldPath.
This PR does not add tests because the case was already covered. There is an issue with the Firestore CI not catching the error. The method is properly failing on master locally before those changes.
CI being fixed here: https://github.com/firebase/flutterfire/pull/10461
fixes #10451  …
> fix(firestore, web): fix a casting error with the update method

- tests/integration_test/firebase_messaging/firebase_messaging_e2e_test.dart
see title
closes https://github.com/firebase/flutterfire/issues/9651
closes https://github.com/firebase/flutterfire/issues/9650
[CLA]: …
> test(messaging, android): reinstate subscription to topics e2e tests

- docs/app-check/default-providers.md
- docs/ml/use-custom-models.md
> docs: Sync docs from Google repo

- packages/firebase_core/firebase_core_web/lib/firebase_core_web.dart
- packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart
Calling `toString` on the object would use the dart `toString` instead of the JS `toString`.
This fix will use the proper `toString` method.
We currently don't have the proper testing env for this. Should be investigated in another ticket.
Was manually tested.
closes #10474  …
> fix(core, web): fix wrong toString js interop in TrustedTypes

- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
The current implementation would work in debug mode but could be stripped away in some cases during compilation.
fixes #10475 
fixes #10478
fixes #10483
[CLA]: …
> fix(firestore, web): change interop type of updateDoc to force the JS interop to keep the value

- packages/firebase_ui_auth/example/macos/Podfile
- packages/firebase_ui_auth/example/macos/Runner.xcodeproj/project.pbxproj
- packages/firebase_ui_auth/example/pubspec.yaml
- packages/firebase_ui_oauth_google/pubspec.yaml
Closes #10519
Even though `google_sign_in` has a major version bump, it affects only web, `firebase_ui_auth` doesn't use it on web.
[CLA]: …
> fix(ui_auth_google): bump google_sign_in version

- docs/dynamic-links/receive.md
As [reported by this user](https://github.com/firebase/flutterfire/issues/7546#issuecomment-1432042420), the iOS app could receive the link from a terminated state from either the `getInitialLink` method call or the event listener `onLink`. I believe the user can call `getInitialLink` before it has been passed to the app and therefore I have updated the documentation to reflect this.
If you wish to test this yourself, you can:
1. Run the app in release mode.
2. Open the app from a terminated state using a Dynamic Link you're created in the Firebase console and configured for your app.
3. Use the below noted, crude code snippet in your `main.dart` file. Open the app and note the success rate of `getInitialLink`. It doesn't always successfully retrieve the Dynamic Link upon app opening. It …
> docs(dynamic-links): update Firebase documentation on how to receive link from terminated state

- packages/firebase_ui_auth/example/lib/main.dart
- packages/firebase_ui_auth/lib/src/screens/internal/responsive_page.dart
- packages/firebase_ui_auth/lib/src/widgets/error_text.dart
> fix(ui_auth): fix ResponsivePage layout causing unexpected overflows

- packages/firebase_auth/firebase_auth/example/lib/auth.dart
- packages/firebase_auth/firebase_auth/example/lib/main.dart
- packages/firebase_auth/firebase_auth/example/lib/profile.dart
- packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
- packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart
I'm using localstorage when connecting to the emulator to save the emulator origin. 
On restart, if I detect an emulator origin in localstorage I directly connect to the emulator.
It allows for a good developer experience in debug mode; the only problem is that we cannot switch back from emulator to production during this Chrome session, and the developer has to relaunch the Flutter app completely to connect to a prod env. But I think it's the best behaviour. It allows Android, iOS and Web to finally have the same behaviour.
Message in console:
fixes #10200 …
> fix(auth, web): fix currentUser being null when using emulator or named instance

- docs/cloud-messaging/first-message.md
Currently no documentation for `getInitialMessage()` & `onMessageOpenedApp`. Update docs to show their usage.
closes https://github.com/firebase/flutterfire/issues/8795 …
> docs(messaging): illustrate how to use `getInitialMessage()` & `onMessageOpenedApp`

- packages/firebase_crashlytics/firebase_crashlytics/lib/src/utils.dart
- packages/firebase_crashlytics/firebase_crashlytics/test/firebase_crashlytics_test.dart
Make plugin  to send abs address to Crashlytics to make deobfuscation works on iOS.
Crashlytics is smart enough to grouping same errors with different abs addresses  in the same issue.
#8934  …
> fix(crashlytics, ios): fix Crashlytics obfuscation for iOS on the Flutter side

- packages/firebase_auth/firebase_auth/example/lib/auth.dart
- packages/firebase_auth/firebase_auth/example/lib/profile.dart
- packages/firebase_auth/firebase_auth/lib/src/multi_factor.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_multi_factor.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_multi_factor.dart
- tests/integration_test/firebase_auth/firebase_auth_multi_factor_e2e_test.dart
By returning directly the Future and not await it, the error will never be catched by firebase.
closes #10543 
> fix(auth): fix an issue where unenroll would not throw a FirebaseException

- packages/firebase_auth/firebase_auth/example/lib/auth.dart
- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/utils/exception.dart
Currently cannot be tested since we cannot activate this feature on the emulator.
The error code is properly returned on Web. But is not correctly parsed on iOS (it's hidden in a details object), and is not returned on Android (only available in a String).
#10588 …
> feat(auth): improve error handling when Email enumeration feature is on

- packages/firebase_ui_auth/lib/src/screens/register_screen.dart
Pass the breakpoint from RegisterScreen to LoginScreen.
Changing the breakpoint had no effect on the RegisterScreen.
> fix(firebase_ui_auth): pass breakpoint from RegisterScreen to LoginScreen

- .github/workflows/scripts/functions/package-lock.json
- .github/workflows/scripts/functions/package.json
- .github/workflows/scripts/functions/src/index.ts
- packages/cloud_functions/cloud_functions/android/src/main/java/io/flutter/plugins/firebase/functions/FlutterFirebaseFunctionsPlugin.java
- packages/cloud_functions/cloud_functions/example/android/app/build.gradle
- packages/cloud_functions/cloud_functions/example/ios/Runner.xcodeproj/project.pbxproj
- packages/cloud_functions/cloud_functions/example/ios/Runner/Info.plist
- packages/cloud_functions/cloud_functions/example/lib/main.dart
- packages/cloud_functions/cloud_functions/ios/Classes/FLTFirebaseFunctionsPlugin.m
- packages/cloud_functions/cloud_functions/lib/src/firebase_functions.dart
- packages/cloud_functions/cloud_functions/test/mock.dart
- packages/cloud_functions/cloud_functions_platform_interface/lib/src/method_channel/method_channel_firebase_functions.dart
- packages/cloud_functions/cloud_functions_platform_interface/lib/src/method_channel/method_channel_https_callable.dart
- packages/cloud_functions/cloud_functions_platform_interface/lib/src/platform_interface/platform_interface_firebase_functions.dart
- packages/cloud_functions/cloud_functions_platform_interface/lib/src/platform_interface/platform_interface_https_callable.dart
- packages/cloud_functions/cloud_functions_platform_interface/test/method_channel/method_channel_https_callable_test.dart
- packages/cloud_functions/cloud_functions_platform_interface/test/platform_interface/platform_interface_https_callable_test.dart
- packages/cloud_functions/cloud_functions_web/lib/cloud_functions_web.dart
- packages/cloud_functions/cloud_functions_web/lib/https_callable_web.dart
- packages/cloud_functions/cloud_functions_web/lib/interop/functions.dart
- packages/cloud_functions/cloud_functions_web/lib/interop/functions_interop.dart
- tests/integration_test/cloud_functions/cloud_functions_e2e_test.dart
- tests/integration_test/e2e_test.dart
There are now 2 new functions, 
httpsCallableFromUrl and httpsCallableFromUri that can take a String Url or a parsed Uri to use a 2nd gen Cloud Function.
#10541  …
> feat(functions): add support for 2nd gen functions

- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
This feature relies on this PR from Firebase Native iOS SDK: https://github.com/firebase/firebase-ios-sdk/pull/10068
fix #9662 
[CLA]: …
> feat(auth, ios): automatically save the Apple Sign In display name

- packages/firebase_ui_auth/lib/src/screens/profile_screen.dart
- packages/firebase_ui_auth/lib/src/widgets/delete_account_button.dart
- packages/firebase_ui_auth/lib/src/widgets/email_link_sign_in_button.dart
- packages/firebase_ui_auth/lib/src/widgets/sign_out_button.dart
- packages/firebase_ui_shared/lib/src/loading_button.dart
- packages/firebase_ui_shared/lib/src/universal_button.dart
Allows to pass `cupertinoColor`, `materialColor`, `cupertinoIcon` and `materialIcon` to the `UniversalButton` and `LoadingButton` instead of checking `isCupertino` in the parent each time
none
This is technically a breaking change, but `firebase_ui_shared` wasn't released yet. …
> feat(ui_shared): pass platform-specific icons and colors explicitly

- .github/workflows/ossf-scorecard.yml
Add an OSSF audit to check security compliance to show a scorecard for the security of the repo.
> chore: add an OSSF audit scorecard workflow

- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
This is a private definition and is only ever used in a `with` clause. It should just be changed to `mixin` to become compatible with Dart language 3.0.
This is *not* a breaking change.
> refactor(firestore): Dart 3 compatibility: change _Updatable to be an actual `mixin`

- packages/firebase_ui_auth/example/test_driver/firebase_ui_auth_e2e_test.dart
- packages/firebase_ui_auth/lib/src/screens/profile_screen.dart
- packages/firebase_ui_database/example/pubspec.yaml
- packages/firebase_ui_firestore/example/pubspec.yaml
- packages/firebase_ui_firestore/example/test_driver/firebase_ui_firestore_e2e_test.dart
> fix: allow to unlink providers only in edit mode

- packages/firebase_remote_config/firebase_remote_config/CHANGELOG.md
There was round bracket `)` too much in the changelog of the `firebase_remote_config` package.
Before:
After:
See https://github.com/firebase/flutterfire/pull/10692#discussion_r1157233107 …
> chore(firebase_remote_config): fix to link to merged pull request in `CHANGELOG.md`

- packages/firebase_app_check/firebase_app_check/example/ios/Podfile
- packages/firebase_app_check/firebase_app_check/ios/Classes/FLTAppCheckProvider.m
The Podfile modifications cannot be moved to the podspec (and are unrelated to AppCheck) since it concerns another library.
fixes #10694 
[CLA]: …
> fix(app-check): fix 'Semantic Issue (Xcode): `new` is unavailable' on XCode 14.3

- packages/firebase_remote_config/firebase_remote_config/lib/src/firebase_remote_config.dart
- packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/platform_interface/platform_interface_firebase_remote_config.dart
- packages/firebase_remote_config/firebase_remote_config_web/lib/firebase_remote_config_web.dart
You might expect that the methods are returning `null` or throwing an exception. But Firebase returns default values. Therefore, I added the values which are returned when the key for the methods does not exist.
Got the values from here:https://firebase.google.com/docs/reference/android/com/google/firebase/remoteconfig/FirebaseRemoteConfig
Zapp Online Demo for default values: https://zapp.run/edit/firebaseremoteconfig-3014-zd6206xrd630?entry=lib/main.dart&file=lib/main.dart
... …
> docs(firebase_remote_config): add documentation what is returned when the key does not exist for `getBool`, `getInt`, `getDouble` and `getString`

- packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestorePlugin.m
As observed by this [user's comment](https://github.com/firebase/flutterfire/issues/10504#issuecomment-1458911747), there is a difference between iOS and android clean up implementation for Firestore.
iOS cleans up Firestore instances & event listeners on Flutter engine detachment & reinitialisation of core. 
android cleans up event listeners only on Flutter engine detachment. Firestore instances & event listeners are cleaned up on reinitialisation of core.
Made iOS the same as android. 
I've had a play, hot reloading and putting phone into background state. It doesn't affect the behaviour. I couldn't find anything more comprehensive on situations when the Flutter engine is detached which might make this implementation a problem. If there are any concerns about this then please comment on …
> fix(firestore, ios): clean up event listeners on engine detach only

- packages/firebase_ui_auth/doc/providers/phone.md
Added handling for the auth state of SMSCodeRequested in the custom AuthFlowBuilder example, matching the implementation of the PhoneInputView.
This PR includes only a small documentation edit for the phone auth provider in the firebase_ui_auth package.
The [example](https://github.com/firebase/flutterfire/blob/master/packages/firebase_ui_auth/doc/providers/phone.md#building-a-custom-widget-with-authflowbuilder) for building a custom widget with AuthFlowBuilder, doesn't handle the auth state for SMSCodeRequested. When copy-pasting this example, it temporarily returns an unknown state text widget during login (see image below). I've fixed the example, modifying it based on the condition in the [PhoneInputView](https://github.com/firebase/flutterfire/blob/master/packages/firebase_ui_auth/lib …
> docs(firebase_ui_auth): fix phone provider's widget example

- packages/firebase_ui_auth/example/pubspec.yaml
- packages/firebase_ui_auth/pubspec.yaml
- packages/firebase_ui_oauth/pubspec.yaml
Remove the dependency `package:flutter_svg` from `firebase_ui_auth` because it is not used.
In `firebase_ui_oauth`, upgrade the minimum version to `^2.0.0`. Version 2 was published 3 months ago.
/ …
> chore(deps): Upgrade package:flutter_svg version

- packages/firebase_core/firebase_core/windows/CMakeLists.txt
1.  Fixed paths to SDK libraries depending on the build config.
2.  Using existing SDK on system according [desktop-workflow] to speed up the build. 
fix #10931  …
> fix(core, windows): building improvements

- packages/firebase_ui_auth/lib/src/screens/profile_screen.dart
firebase_ui_auth throws an error when building for version 1.4.0.:
`../../.pub-cache/hosted/pub.dev/firebase_ui_auth-1.4.0/lib/src/screens/profile_screen.dart:393:19: Error: Cannot invoke a non-'const' constructor where a const expression is expected. Try using a constructor or factory that is 'const'. const Row( ^^^`
[Issue](https://github.com/firebase/flutterfire/issues/10954)
- [ x] My PR includes unit or integration tests for *all* changed/updated/fixed …
> fix(firebase_ui_auth): Error added in ProfileScreen in firebase_ui_auth 1.4.0

- packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/lib/src/firestore_reference.dart
See title.
closes https://github.com/firebase/flutterfire/issues/10471
> docs(firestore): improve wording of what `set()` API does

- .github/workflows/e2e_tests.yaml
- packages/cloud_firestore/cloud_firestore/example/integration_test/document_reference_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/load_bundle_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/second_app_e2e.dart
Skipped certain Firestore e2e tests that were failing due to a different exception that was propagated on web platform. Tracking issue here:https://github.com/firebase/flutterfire/issues/11099
Created a new, cached AVD instance. Previous one was failing consistently. …
> ci: fix CI pipeline

- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundExecutor.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java
Countermeasures for the deprecation of the 'getParcelableExtra(String key)' method in Android API version 33.
ref: https://developer.android.com/sdk/api_diff/t-beta2-incr/changes/android.content.Intent …
> fix(firebase messaging, android):  update `getParcelableExtra()` for Android 33.

- packages/firebase_app_check/firebase_app_check_web/lib/firebase_app_check_web.dart
- packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
- packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart
- packages/firebase_remote_config/firebase_remote_config_web/lib/firebase_remote_config_web.dart
Currently it seems that unnecessary web libraries are loaded on start of a Flutter Web application. 
In our case, we only want to use Firebase Analytics to send tracking data. For this we need to install the firebase_core and firebase_analytics package as dependencies in our project. But when we launch the bundled app in the browser, there are additional JS libraries loaded to the expected `firebase-app.js` and `firebase-analytics.js` files. At launch of our app, these JS libraries are loaded.
- firebase-app.js
- firebase-analytics.js
- firebase-app-check.js
- firebase-remote-config.js
- firebase-firestore.js
The `firebase-firestore.js`dependency comes from the firebase_core and firebase_analytics using shared functionality from _flutterfire_internals, which has the …
> fix(core): Omit unnecessary libraries for web

- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundExecutor.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java
The PR #10921 has broken the CI pipeline because of missing formatting (see https://github.com/firebase/flutterfire/actions/runs/5244736709/jobs/9471167396?pr=11118). In this PR, I ran `melos run format` to fix the CI.
Related to #10921 …
> chore(firebase_messaging): fix broken CI because missing formatting in `firebase_messaging`

- packages/firebase_remote_config/firebase_remote_config/example/macos/Runner.xcodeproj/project.pbxproj
- packages/firebase_remote_config/firebase_remote_config/example/macos/Runner/DebugProfile.entitlements
- packages/firebase_remote_config/firebase_remote_config/example/macos/Runner/Release.entitlements
Added the "Keychain Sharing" capability to the example. Please note that because of the added capability, an Apple developer account is now required to build the example (similar as it is for `firebase_messaging`).
Applies setup steps from the docs (see #11110) …
> chore(firebase_remote_config): add "Keychain Sharing" capabilty to example

- packages/firebase_remote_config/firebase_remote_config/example/lib/home_page.dart
https://github.com/firebase/flutterfire/blob/fe0f20cf6d2f5db754fa1be7d9991d51ef3a4d2c/docs/remote-config/_get-started.md#L145-L154
The docs show that you need to call `remoteConfig.activate()` before using the values. I added the missing line in the example of the `firebase_remote_config`.
Fixes #11104
[Flutter Style …
> chore(firebase_remote_config): activate the values after real time update for example

- packages/cloud_firestore/cloud_firestore/example/integration_test/instance_e2e.dart
- packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestoreReader.m
- packages/cloud_firestore/cloud_firestore/test/query_test.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/settings.dart
A few things to note.
1. `kFIRFirestoreCacheSizeUnlimited ` & anything more/less than acceptable cache size (1mb/100mb) was crashing apple apps.
2. I've created an assertion within the `copy()` function of `Settings`, cannot do on creation of `Settings` as it would change the user facing API from `const Settings` to `Settings(cacheSizeBytes: 10000000)`.
3. Wrote tests for assertion as it is a tricky one. also wrote a few e2e tests.
fix: https://github.com/firebase/flutterfire/issues/11138 …
> fix(firestore, apple): issue where setting persistence caused a crash. `kFIRFirestoreCacheSizeUnlimited` no longer usable.

- .github/workflows/e2e_tests.yaml
- tests/integration_test/firebase_messaging/firebase_messaging_e2e_test.dart
Refreshed gradle cache and skipped `subscribeFromTopic` & `unsubscribeFromTopic` tests for android until we can understand the problem. They work locally: …
> ci: change gradle cache

- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
- packages/cloud_firestore/cloud_firestore/lib/src/query.dart
- packages/cloud_firestore/cloud_firestore/test/query_test.dart
Circled back to this and it seems the response has changed. I've reinserted commented out tests, and allowed "in" & "array-contains-any" queries to have up to 30 filters.
closes https://github.com/firebase/flutterfire/issues/11085 …
> fix(firestore): allow 30 conjunctive & disjunctive queries for "in" & "array-contains-any" via where() API

- packages/firebase_core/firebase_core/windows/CMakeLists.txt
- packages/firebase_core/firebase_core/windows/firebase_core_plugin.cpp
- packages/firebase_core/firebase_core/windows/firebase_core_plugin.h
- packages/firebase_core/firebase_core/windows/firebase_core_plugin_c_api.cpp
- packages/firebase_core/firebase_core/windows/include/firebase_core/firebase_core_plugin_c_api.h
Add apis to firebase_core windows to access firebase cpp object like App*, Auth* etc.
N/A
> feat(core, windows): Add api to access firebase cpp objects

- docs/crashlytics/_customize-crash-reports.md
- docs/crashlytics/_force-test-crash.md
- packages/firebase_crashlytics/firebase_crashlytics/example/lib/main.dart
see title.
Replaces this PR: https://github.com/firebase/flutterfire/pull/10772
> docs(crashlytics): illustrate different methods for recording crashes

- packages/firebase_ui_storage/example/lib/src/storage_image_app.dart
- packages/firebase_ui_storage/lib/src/widgets/image.dart
> feat(ui_storage): add shimmer for loading images

- packages/firebase_auth/firebase_auth/ios/Classes/Private/FLTPhoneNumberVerificationStreamHandler.h
- packages/firebase_auth/firebase_auth/ios/Classes/Private/PigeonParser.h
- packages/firebase_auth/firebase_auth/ios/Classes/Public/FLTFirebaseAuthPlugin.h
Importing messages.g.h could cause issues in other packages if they are using the same file name.
closes #11825
> fix(auth, ios): fix scoping of import for message.g.h, could cause incompatibility with other packages

- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
> fix(auth, apple): pass in Firebase auth instance for correct app when using Provider sign in

- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
- packages/cloud_firestore/cloud_firestore/lib/src/query.dart
- packages/cloud_firestore/cloud_firestore/test/query_test.dart
See title.
fixes https://github.com/firebase/flutterfire/issues/11203
> fix(firestore): remove assertion for `arrayContainsAny` & `whereIn` query combined

- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthUser.java
- packages/firebase_auth/firebase_auth/example/android/build.gradle
- tests/integration_test/firebase_auth/firebase_auth_user_e2e_test.dart
see title.
fixes https://github.com/firebase/flutterfire/issues/11297
> fix(auth, android): `getIdToken()` `IllegalStateException` crash fix

- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/PhoneNumberVerificationStreamHandler.java
Implicitly using the default locale is a common source of bugs: Use toLowerCase(Locale) instead. For strings meant to be internal use Locale.ROOT.
None
- [0] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
> fix(firebase_auth, Android): Remove implicit default locale used in error message

- packages/firebase_app_check/firebase_app_check_platform_interface/lib/src/apple_provider.dart
Fixes a typo found in the enum AppleProvider code comments
> fix(firebase_app_check): fix typo in code comment

- packages/firebase_crashlytics/firebase_crashlytics/ios/crashlytics_add_upload_symbols
Related to https://github.com/firebase/firebase-ios-sdk/issues/11400, Xcode 15 enforces tighter requirements on Input Files for Run Scripts. This automatically includes Crashlytics Input Files.
> fix: Modify input files for xcode15

- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/filters.dart
see title.
fixes https://github.com/firebase/flutterfire/issues/11422
> fix(firestore): allow `FieldPath.documentId` as a field argument in queries

- packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/method_channel/method_channel_messaging.dart
- packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/platform_interface/platform_interface_messaging.dart
For example, imagine we had this setup, and no other FirebaseMessaging API calls. None of the event handlers would ever fire on native platforms. If the line `FirebaseMessaging.instance.isAutoInitEnabled` is uncommented, they will work because it will instantiate `MethodChannelFirebaseMessaging` that creates the method channels necessary for them to work. 
This PR will always create the method channel handlers before `MethodChannelFirebaseMessaging` is instantiated.
```dart
Future<void> main() async {
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
// Uncomment the line below and the event listeners will fire.
// FirebaseMessaging.instance.isAutoInitEnabled; …
```
> fix(messaging): Method channel handlers were not created if `FirebaseMessaging.instance.*` is not invoked beforehand

- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
Fix how forceRefresh is converted in iOS plugin before calling native API
No, this is *not* a breaking change.
> fix(firebase_auth): Fix forceRefresh parameter conversion before calling native API

- packages/cloud_firestore_odm/cloud_firestore_odm/example/integration_test/collection_reference_test.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/integration_test/common.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/integration/freezed.freezed.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/movie.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/movie.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/simple.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/simple.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/collection_data.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/templates/query_reference.dart
Support generating query methods for Sets.
#11344
> feat(cloud_firestore_odm_generator): Support Sets as well as Lists for query method generation

- README.md
Since #11493 moved the "firebase_ui" packages to https://github.com/firebase/FirebaseUI-Flutter, we need also to update the links in the README.md
No issue.
[CLA]: …
> docs: fix broken links to "firebase_ui" in README.md

- packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/remote_config_settings.dart
Removes the dartdocs mentioning defaults in the `RemoteConfigSettings`, since there currently aren't any defaults applied.
> docs(firebase_remote_config): Remove comment about defaults in `RemoteConfigSettings`

- packages/firebase_auth/firebase_auth/README.md
Simple update of the "getting started" link to point to the latest documentation instead of the archived one
> docs(auth): update the incorrect "getting started" link 

- packages/firebase_analytics/firebase_analytics/android/src/main/java/io/flutter/plugins/firebase/analytics/FlutterFirebaseAnalyticsPlugin.java
- packages/firebase_analytics/firebase_analytics/ios/Classes/FLTFirebaseAnalyticsPlugin.m
- packages/firebase_analytics/firebase_analytics/lib/src/firebase_analytics.dart
- packages/firebase_analytics/firebase_analytics_platform_interface/lib/src/method_channel/method_channel_firebase_analytics.dart
- packages/firebase_analytics/firebase_analytics_platform_interface/lib/src/platform_interface/platform_interface_firebase_analytics.dart
- packages/firebase_analytics/firebase_analytics_platform_interface/test/method_channel_tests/method_channel_firebase_analytics_test.dart
- packages/firebase_analytics/firebase_analytics_platform_interface/test/platform_interface_tests/platform_interface_analytics_test.dart
- packages/firebase_analytics/firebase_analytics_web/lib/firebase_analytics_web.dart
- tests/integration_test/firebase_analytics/firebase_analytics_e2e_test.dart
> feat(firebase_analytics): support `getSessionId` for android and apple platforms

- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
`providers` can be `nil`:https://github.com/firebase/flutterfire/blob/master/packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m#L1047
This PR check ifs `nil` and passes empty array.
The other issue is that the response seems to always come back as `nil`. I checked with a user that has email/password & google providers enabled and it still responded with `nil`. Appears to be a bug on the firebase-ios-sdk.
fixes https://github.com/firebase/flutterfire/issues/11293 …
> fix(auth, apple): `fetchSignInMethodsForEmail` if value is `nil`, pass empty array.

- packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestorePlugin.m
Correct an error in the definition of `serverTimestampMap`.
It was not changed from `NSMutableDictionary` to `NSCache` as part of #11501
None
[CLA]: …
> fix(firestore): Correct static property getter `serverTimestampMap`

- packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart
- packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
When the plugin is initialised by Flutter, initialise `FirebaseAuth` without any persistence. This causes a error to be thrown when calling `FirebaseAuth.instanceFor` with a persistence value as firebase_auth tries to reinitialise the auth instance with a new persistence. 
We cannot use `setPersistence` to fix this since it's a `Future` and `instanceFor` is synchronous, and the user cannot provide the persistence they want before the plugin is initialised. Therefore, the `persistence` parameter is being deprecated and users are expected to call `setPersistence` separately to set the `persistence` of the auth object.
Only affects web
Fixes #10961
This will ensure a …
> fix(auth): deprecate `FirebaseAuth.instanceFor`'s `persistence` parameter

- docs/app-check/default-providers.md
- packages/firebase_app_check/firebase_app_check/example/lib/main.dart
- packages/firebase_app_check/firebase_app_check/lib/firebase_app_check.dart
- packages/firebase_app_check/firebase_app_check/lib/src/firebase_app_check.dart
- packages/firebase_app_check/firebase_app_check/test/firebase_app_check_test.dart
- packages/firebase_app_check/firebase_app_check_platform_interface/lib/firebase_app_check_platform_interface.dart
- packages/firebase_app_check/firebase_app_check_platform_interface/lib/src/method_channel/method_channel_firebase_app_check.dart
- packages/firebase_app_check/firebase_app_check_platform_interface/lib/src/platform_interface/platform_interface_firebase_app_check.dart
- packages/firebase_app_check/firebase_app_check_platform_interface/lib/src/web_providers.dart
- packages/firebase_app_check/firebase_app_check_platform_interface/test/method_channel_tests/method_channel_firebase_app_check_test.dart
- packages/firebase_app_check/firebase_app_check_platform_interface/test/platform_interface_tests/platform_interface_app_check_test.dart
- packages/firebase_app_check/firebase_app_check_web/lib/firebase_app_check_web.dart
- packages/firebase_app_check/firebase_app_check_web/lib/src/interop/app_check.dart
- packages/firebase_app_check/firebase_app_check_web/lib/src/interop/app_check_interop.dart
- packages/firebase_app_check/firebase_app_check_web/test/firebase_app_check_web_test.dart
- packages/firebase_app_check/firebase_app_check_web/test/firebase_app_check_web_test.mocks.dart
- tests/integration_test/firebase_app_check/firebase_app_check_e2e_test.dart
**Breaking change**
Updates user facing API `activate()` which now accepts `ReCaptchaEnterpriseProvider(siteKey)` or `ReCaptchaV3Provider(siteKey)` as an argument for `webProvider`.
We've also implemented an exception if `webProvider` argument is not provided when running on web as it is a requirement when initialising App Check via `initializeAppCheck()` https://firebase.google.com/docs/reference/js/app-check.md#initializeappcheck.
If a provider is not passed on web:
```js
const options = {
provider: {},
};
const appCheck = initializeAppCheck(undefined, options);
```
The following exception occurs:
*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by …
> feat(app-check, web)!: support for `ReCaptchaEnterpriseProvider`. User facing API updated.

- packages/firebase_database/firebase_database/ios/Classes/FLTFirebaseDatabasePlugin.m
Receiving this warning in the console without this fix:
```
[VERBOSE-2:shell.cc(1004)] The 'plugins.flutter.io/firebase_database' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
```
This just ensures platform channel call in transaction operates on the main thread to comply with Flutter requirement. See documentation about executing platform channel requests on the main thread: https://docs.flutter.dev/platform-integration/platform-channels?tab=type-mappings- …
> fix(database, apple): ensure platform channel is invoked on main thread

- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundService.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingReceiver.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingService.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseRemoteMessageLiveData.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseTokenLiveData.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/JobIntentService.java
- packages/firebase_messaging/firebase_messaging/example/android/app/build.gradle
- packages/firebase_messaging/firebase_messaging/example/android/build.gradle
- packages/firebase_messaging/firebase_messaging/example/android/gradle.properties
- packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart
This effects the `refreshToken` & `onMessage` API. For completeness, I also tested the `onMessageOpenedApp` & the `onBackgroundMessage` handler. They all worked as intended.
List of changes made:
- Removed `LocalBroadcastManager` API in favour of the recommended `LiveData` API.
- Updated AGP to v8.
- Removed Jetifier as it is not needed anymore.
- deprecated `sendMessage()` as the underlying android API `send()` is deprecated and will be decommissioned in June 2024.
- Update some API according to android studio linting for unchecked API.
Addressed some messaging warnings for this issue: https://github.com/firebase/flutterfire/issues/8073
Still need to return and work on the JobIntentService which has a number of deprecated API. …
> refactor(messaging, android): removed unsafe & deprecated API. E.g. `LocalBroadcastManager` replaced by `LiveData`

- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
- packages/firebase_auth/firebase_auth/ios/Classes/Private/PigeonParser.h
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/utils/exception.dart
Whilst testing this code, I observed a few issues:
```dart
TwitterAuthProvider twitterProvider =
TwitterAuthProvider();
try {
await FirebaseAuth.instance.currentUser!
.linkWithProvider(twitterProvider);
} on FirebaseAuthException catch (e) {
if (e.code == 'credential-already-in-use') {
print(
'The account already exists for that email. - ${e.credential}');
await FirebaseAuth.instance.signOut();
final cred = await FirebaseAuth.instance
.signInWithCredential(e.credential!);
}
}
```
1. We were not passing back the `AuthCredential` when present on the exception which was an issue for both andriod and iOS. [Fixed here](https://github.com/firebase/flutterfire/pull/11683/files#diff-a2a0fb36528efebd6ce2a82ec76ffb25fde2eef6ccd166e3b4c68c38dc887906R61-R80).
2. We were passing back a dictionary of …
> fix(auth): ensure `PigeonAuthCredential` is passed back to Dart side within try/catch

- packages/firebase_app_check/firebase_app_check_web/lib/firebase_app_check_web.dart
- packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart
Right now on web, auth gets initialized before developers get a chance to activate app check. This means that the startup auth check fails when app check is enforced and the app is logged out on every start.
Closes #11334
[pub …
> fix(firebase_app_check_web): Activate web app check on startup if it was previously activated

- packages/firebase_app_check/firebase_app_check/android/src/main/java/io/flutter/plugins/firebase/appcheck/FlutterFirebaseAppCheckPlugin.java
Allows use of non-default app for Android debug provider. Currently the debug provider is limited to the default app instance, while other providers (and Apple debug provider) can use a non-default app.
closes https://github.com/firebase/flutterfire/issues/11668 …
> fix(firebase_app_check): Allow non-default app for Android debug provide

- .github/workflows/all_plugins.yaml
Removing fixed Flutter version from `build_examples_dart` job as [the fix mentioned in the removed TODO (](https://github.com/flutter/flutter/issues/132711) states that the fix is already available on stable.
- …
> ci: Remove hardcoded Flutter version for examples building

- packages/firebase_app_check/firebase_app_check/android/build.gradle
App Check dependencies are available in Firebase BOM for some time already, so it makes sense to keep versions of App Check artifacts aligned with what BOM provides. Moreover, seems like current version of App Check for Flutter had quite old corresponding Android dependencies, so this change will also bump version of App Check Android.
- …
> feat(app_check): Use Android dependencies from Firebase BOM

- packages/cloud_firestore_odm/README.md
Following https://github.com/firebase/flutterfire/commit/f4c21f834569bb363c80af583b53164f7cbd5ada merge, ODM fail to generate models if create_per_field_to_json is not enabled for json_serializable. 
> docs(cloud_firestore_odm_generator): ODM now need create_per_field_to_json: true

- CHANGELOG.md
Like stated in https://github.com/firebase/flutterfire/pull/11728, ODM generator v1.0.0-dev.70 require a config change to continue working. All ODM users are concerned, the more we communicate about this (thus preventing issue creation and blocked users) the better. Some might check the changelog, hence this PR.
> docs(cloud_firestore_odm_generator): 1.0.0-dev.70 is a breaking change

- packages/firebase_core/firebase_core/windows/firebase_core_plugin.cpp
- packages/firebase_core/firebase_core/windows/firebase_core_plugin.h
Before we used a STATIC compilation of the different Windows plugins, we needed to recreate the Firebase App in each plugin. I've removed this stale code that we don't use anymore. 
closes #11684  …
> fix(core, windows): remove unused map of string that was causing a crash

- packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
- packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestorePlugin.m
see title.
fixes https://github.com/firebase/flutterfire/issues/11740
> fix(firestore): cleaned up use of previous method channel

- packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
- packages/cloud_firestore/cloud_firestore/example/lib/main.dart
Throwing exception when setting the following:
```dart
FirebaseFirestore.instance.settings = const Settings(
persistenceEnabled: true,
);
```
without `cacheSizeBytes` also set. 
fixes https://github.com/firebase/flutterfire/issues/11738 …
> fix(firestore, android): `cacheSizeBytes` value cannot be null when setting `persistenceEnabled`

- packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestorePlugin.m
Fix this warning
```
[NSError init] called; this results in an invalid NSError instance. It will raise an exception in a future release. Please call errorWithDomain:code:userInfo: or initWithDomain:code:userInfo:. This message shown only once.
``` …
> fix(firestore, ios): remove a warning that would be printed when using transactions

- packages/firebase_auth/firebase_auth/example/lib/main.dart
- packages/firebase_auth/firebase_auth/example/pubspec.yaml
- packages/firebase_auth/firebase_auth/example/windows/flutter/generated_plugin_registrant.cc
- packages/firebase_auth/firebase_auth/example/windows/flutter/generated_plugins.cmake
- packages/firebase_auth/firebase_auth/windows/firebase_auth_plugin.cpp
Fix Windows' parsing of Providers argument, and add in the example app how to use `google_sign_in_dartio` in order to get the correct values.
closes #11752
[CLA]: …
> feat(auth, windows): add Windows support for Google Sign In

- packages/firebase_storage/firebase_storage/ios/Classes/FLTFirebaseStoragePlugin.m
see title.
fixes https://github.com/firebase/flutterfire/issues/11833
> fix(storage, apple): set the storage emulator only once to stop it from crashing on hot restart

- packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
- packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart
The inline documentation was currently wrong:
Android
```java
@Override
public void setLanguageCode(
@NonNull GeneratedAndroidFirebaseAuth.AuthPigeonFirebaseApp app,
@Nullable String languageCode,
@NonNull GeneratedAndroidFirebaseAuth.Result<String> result) {
try {
FirebaseAuth firebaseAuth = getAuthFromPigeon(app);
if (languageCode == null) {
firebaseAuth.useAppLanguage();
} else {
firebaseAuth.setLanguageCode(languageCode);
}
result.success(firebaseAuth.getLanguageCode());
} catch (Exception e) {
result.error(e);
}
}
```
iOS
```ObjC
- (void)setLanguageCodeApp:(nonnull AuthPigeonFirebaseApp *)app
languageCode:(nullable NSString *)languageCode
completion:
(nonnull void (^)(NSString *_Nullable, FlutterError *_Nullable))completion {
FIRAuth *auth = [self …
```
> fix(auth, web): use the device language when using setLanguageCode with null

- packages/firebase_core/firebase_core/example/android/build.gradle
- packages/firebase_core/firebase_core/example/ios/Runner.xcodeproj/project.pbxproj
- packages/firebase_core/firebase_core/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/firebase_core/firebase_core/example/ios/Runner/Info.plist
- packages/firebase_core/firebase_core/ios/Classes/FLTFirebaseCorePlugin.m
- tests/lib/firebase_options.dart
As mentioned in the reference docs, those parameters are unused by the SDK:
https://firebase.google.com/docs/reference/ios/firebasecore/api/reference/Classes/FIROptions#trackingid
closes #11751  …
> fix(core, apple): remove usage of deprecated options trackingID and androidClientID

- packages/firebase_messaging/firebase_messaging_web/lib/src/interop/messaging.dart
I’ve checked with different simpler examples but even by calling the interop directly, I’m not able to fix this issue any other way. There must be an interaction between Flutter and the Service Worker.
fixes #11954  …
> fix(messaging): fix an issue where Service Worker would not register in time

- packages/firebase_core/firebase_core/windows/CMakeLists.txt
add packages for release path process in firebase_core/CMakeLists.txt
https://github.com/firebase/flutterfire/issues/11919
> fix(core, windows): make auth, firestore and storage can build in release mode.

- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_document_snapshot.dart
Adds the name of a non-existent field to the error message.
> fix(firestore): output non-existent field in error message.

- packages/cloud_firestore/cloud_firestore/example/pubspec.yaml
- packages/cloud_firestore_odm/cloud_firestore_odm/example/pubspec.yaml
- packages/firebase_auth/firebase_auth/example/pubspec.yaml
- packages/firebase_messaging/firebase_messaging/example/pubspec.yaml
- packages/firebase_performance/firebase_performance/example/pubspec.yaml
- packages/firebase_performance/firebase_performance/pubspec.yaml
- packages/firebase_storage/firebase_storage/pubspec.yaml
- tests/pubspec.yaml
only affects examples, tools, and dev_dependencies
> chore(deps): bump pkg:http version

- packages/firebase_crashlytics/firebase_crashlytics/lib/firebase_crashlytics.dart
- packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart
Reason is no longer `thrown Instance of Errordescription`.
fixes https://github.com/firebase/flutterfire/issues/10552
> fix(crashlytics): update exception `reason` to ensure it does not produce incorrect value in Firebase console

- packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
- packages/firebase_auth/firebase_auth/lib/src/user.dart
- packages/firebase_auth/firebase_auth/test/firebase_auth_test.dart
- packages/firebase_auth/firebase_auth/test/user_test.dart
- tests/integration_test/firebase_auth/firebase_auth_instance_e2e_test.dart
- tests/integration_test/firebase_auth/firebase_auth_user_e2e_test.dart
iOS, android and web have updated to deprecate `updateEmail()` & `fetchSignInMethodsForEmail()` API.
Web: https://firebase.google.com/docs/reference/js/auth.md#fetchsigninmethodsforemail
android: https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth#fetchSignInMethodsForEmail(java.lang.String)
iOS: https://firebase.google.com/support/release-notes/ios#version_10190_-_dec_5_2023 
closes https://github.com/firebase/flutterfire/issues/12121 …
> fix(auth): deprecate `updateEmail()` & `fetchSignInMethodsForEmail()`

- packages/firebase_core/firebase_core/ios/Classes/FLTFirebaseCorePlugin.m
PR #11925 added support for custom auth domains on mobile.  
Custom auto domains are stored in a static `NSMutableDictionary`  called `customAuthDomains` in the `FLTFirebaseCorePlugin` class, keyed by the app name.
Unfortunately, this static dictionary is never initialized, so custom domains do not take effect.
This PR adds a static initializer to the `FLTFirebaseCorePlugin` class to initialize this dictionary
Does your PR require plugin users to manually update …
> fix(auth, ios): Initialise static dictionary for custom auth domains

- packages/firebase_messaging/firebase_messaging_web/lib/firebase_messaging_web.dart
- packages/firebase_messaging/firebase_messaging_web/lib/src/interop/messaging.dart
- packages/firebase_messaging/firebase_messaging_web/lib/src/interop/messaging_interop.dart
- packages/firebase_messaging/firebase_messaging_web/pubspec.yaml
https://github.com/firebase/flutterfire/issues/12027 …
> feat(messaging, web): migrate web to js_interop to be compatible with WASM

- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart
- packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
API Reference: https://firebase.google.com/docs/reference/js/auth.oauthcredential
closes #12252 
> fix(auth, web): fix null safety issue in typing JS Interop for OAuthCredential

- packages/cloud_firestore/cloud_firestore/example/integration_test/field_value_e2e.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/utils/utils.dart
> fix(firestore, web): fix an issue where nested object could be incorrectly decoded from JSObjects

- packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart
As per documentation:
The representation type of all JavaScript objects for extension types.
This is the supertype of all JS objects, but not other JS types, like primitives. See [https://dart.dev/web/js-interop](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) for more details on how to use JS interop.
closes #12242 …
> fix(core, web): fix an incompatibility with Flutter Beta that would occur when calling method on TrustedScriptURL

- packages/cloud_firestore/cloud_firestore/lib/src/query.dart
- packages/cloud_firestore/cloud_firestore/test/query_test.dart
Stop incorrect filters from reaching underlying Firebase SDKs.
fixes https://github.com/firebase/flutterfire/issues/12211
> fix(firestore): cannot use `not-in` & `in` filters in the same query

- packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
- tests/integration_test/firebase_auth/firebase_auth_user_e2e_test.dart
fixes https://github.com/firebase/flutterfire/issues/12309 …
> fix(auth, web): `signInWithEmailAndPassword()` throwing with incorrect exception code

- .github/workflows/e2e_tests.yaml
- packages/_flutterfire_internals/lib/_flutterfire_internals.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/document_reference_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/load_bundle_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/second_app_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/second_database.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/write_batch_e2e.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart
- Fixed the `NativeError` that should be `FirebaseException`. Also - unskipped tests for web testing `FirebaseException`.
- Fixed bug where we need to Jsify an array with `toJS` rather than `toJSBox`.
- Fixed bug where `bytesLoaded` can be a number or string depending on the circumstances. Not sure if bug with JS SDK or interop.
- Updated some tests were things were not possible on web which now are.
- Improved logic checking `FirebaseException`.
fixes https://github.com/firebase/flutterfire/issues/12314
Does your PR require plugin users to manually update …
> fix(firestore, web): Propagate `FirebaseException` properly, fix `mergeFields` bug, fix `bytesLoaded` different type under different conditions

- .github/workflows/all_plugins.yaml
- .github/workflows/e2e_tests.yaml
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart
- packages/firebase_auth/firebase_auth_web/pubspec.yaml
Latest flutter SDK `3.19.0` broke our use of `jsify()` function here: https://github.com/firebase/flutterfire/pull/12338/files#diff-073c6ae89d1947a587a79d2020e2cd9478a0d218a4aeb8dd6bce4b37344b92e1R24-R40
Used the latest guidance to create a JS object literal: https://dart.dev/interop/js-interop/usage
fixes https://github.com/firebase/flutterfire/issues/12291 …
> fix(auth, web): flutter `3.19.0` interop broke auth persistence setting. Updated the way we initialise JS Map inline with latest interop.

- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart
- packages/firebase_auth/firebase_auth_web/pubspec.yaml
- packages/firebase_core/firebase_core_web/lib/src/interop/utils/utils.dart
Revert changes to auth web SDK minimum constraint back to "3.2.0" from this PR: https://github.com/firebase/flutterfire/pull/12338/files
fixes: https://github.com/firebase/flutterfire/issues/12354 …
> fix(auth, web): lower SDK minimum version constraint to "3.2.0"

- packages/firebase_core/firebase_core/example/web/index.html
- packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart
- packages/firebase_core/firebase_core_web/lib/src/interop/package_web_tweaks.dart
> fix(core, web): fix compatibility with TrustedTypes

- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
- tests/integration_test/firebase_auth/firebase_auth_multi_factor_e2e_test.dart
When signing out we weren't removing the old multifactor objects.
closes #12486 
> fix(auth, android): fixing an issue that could cause `getEnrolledFactors` to return an empty list if signing out in the same app session

- packages/firebase_app_check/firebase_app_check/lib/src/firebase_app_check.dart
In
```
static FirebaseAppCheck instanceFor({required FirebaseApp app}) {
return _firebaseAppCheckInstances.putIfAbsent(app.name, () {
return FirebaseAppCheck._(app: app);
});
}
```
We already cache the result. No need to have 2 different caching mechanism. This is matching what we are doing on FirebaseAuth
#12452
[Flutter …
> refactor(app_check, web): small refactor around initialisation of FirebaseAppCheckWeb

- packages/firebase_auth/firebase_auth/windows/firebase_auth_plugin.cpp
Fix crash caused when trying to use firebase auth `signInWithCredential` on windows 
```dart
await FirebaseAuth.instance.signInWithCredential(
OAuthProvider('oidc.provider').credential(
idToken: idToken,
accessToken: accessToken,
)
);
```
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutte …
> feat(auth, windows): add support for oAuth with credentials on Windows

- packages/firebase_app_check/firebase_app_check_web/lib/src/interop/app_check.dart
`getToken` test is currently being skipped on Web and doesn't test success in e2e test.
closes #12500 
> fix(app_check, web): fix typing inference for `getToken` on web

- .github/ISSUE_TEMPLATE/bug_report.yml
YAML will give better formatting for the Flutter dependencies. Also hiding it under an expand.
Based on this: https://github.com/firebase/firebase-ios-sdk/blob/main/.github/ISSUE_TEMPLATE/BUG_REPORT.yml?plain=1#L126C1-L132C1
Does your PR require plugin users to manually update their apps …
> chore: small fix to template snippet sharing

- packages/cloud_firestore/cloud_firestore/example/integration_test/second_database.dart
See failing e2e tests because it now provides a link for an index rather than throwing an exception
https://github.com/firebase/flutterfire/actions/runs/8371322167/job/22930126154?pr=12218#step:14:464 …
> ci: remove query test combining `arrayContainsAny` and `notEqualTo` that is now valid.

- packages/cloud_firestore/cloud_firestore/example/integration_test/second_database.dart
> ci: update tests for `arrayContainsAny` & `isNotEqualTo` which now result in a "failed-precondition" exception.

- packages/cloud_firestore/cloud_firestore/android/build.gradle
- packages/cloud_functions/cloud_functions/android/build.gradle
- packages/cloud_functions/cloud_functions/example/android/app/build.gradle
- packages/firebase_analytics/firebase_analytics/android/build.gradle
- packages/firebase_analytics/firebase_analytics/example/android/app/build.gradle
- packages/firebase_app_check/firebase_app_check/android/build.gradle
- packages/firebase_app_check/firebase_app_check/example/android/app/build.gradle
- packages/firebase_app_installations/firebase_app_installations/android/build.gradle
- packages/firebase_app_installations/firebase_app_installations/example/android/app/build.gradle
- packages/firebase_auth/firebase_auth/android/build.gradle
- packages/firebase_core/firebase_core/android/build.gradle
- packages/firebase_crashlytics/firebase_crashlytics/android/build.gradle
- packages/firebase_crashlytics/firebase_crashlytics/example/android/app/build.gradle
- packages/firebase_database/firebase_database/android/build.gradle
- packages/firebase_database/firebase_database/example/android/app/build.gradle
- packages/firebase_dynamic_links/firebase_dynamic_links/android/build.gradle
- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/app/build.gradle
- packages/firebase_in_app_messaging/firebase_in_app_messaging/android/build.gradle
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/android/app/build.gradle
- packages/firebase_messaging/firebase_messaging/android/build.gradle
- packages/firebase_messaging/firebase_messaging/example/android/app/build.gradle
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/android/build.gradle
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/android/app/build.gradle
- packages/firebase_performance/firebase_performance/android/build.gradle
- packages/firebase_performance/firebase_performance/example/android/app/build.gradle
- packages/firebase_remote_config/firebase_remote_config/android/build.gradle
- packages/firebase_remote_config/firebase_remote_config/example/android/app/build.gradle
- packages/firebase_storage/firebase_storage/android/build.gradle
- packages/firebase_storage/firebase_storage/example/android/app/build.gradle
Compile against SDK 34 which is the current latest version (and matching the version in e2e tests 😅).
closes #12555
> feat(android): Bump `compileSdk` version of Android plugins to latest stable (34)

- packages/firebase_messaging/firebase_messaging_web/lib/src/interop/messaging.dart
> fix(messaging, web): Fix incorrect type casting.

- packages/cloud_firestore/cloud_firestore/windows/cloud_firestore_plugin.cpp
- packages/cloud_firestore/cloud_firestore/windows/cloud_firestore_plugin.h
- packages/cloud_firestore/cloud_firestore/windows/firestore_codec.cpp
Improve memory management by using unique_ptr and release events properly when storing it an object. …
> fix(firestore, windows): improve memory management

- packages/firebase_app_check/firebase_app_check/android/src/main/java/io/flutter/plugins/firebase/appcheck/FlutterFirebaseAppCheckPlugin.java
- Replaced specific import to wildcard import to stop deprecation warning, no name clashes and tiny package so no issues with compilation.
- Add note to remove suppression once SafetyNet is completely removed.
part of: https://github.com/firebase/flutterfire/issues/8073 …
> fix(app-check, android): fix unnecessary deprecation warning

- packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java
- packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
- packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/utils/PigeonParser.java
- packages/cloud_firestore/cloud_firestore/example/integration_test/instance_e2e.dart
- packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
- Suppressed deprecated API on android and annotated on user facing Dart API.
- Suppressed unchecked cast warnings on safe casts.
part of: https://github.com/firebase/flutterfire/issues/8073 …
> fix(firestore, android): lint warnings and deprecated API

- packages/cloud_firestore/cloud_firestore/example/integration_test/second_database.dart
- packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
- packages/cloud_firestore/cloud_firestore/test/cloud_firestore_test.dart
- packages/cloud_firestore/cloud_firestore/test/test_firestore_message_codec.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_firestore.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_transaction.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/utils/firestore_message_codec.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_firestore.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/test/utils/test_firestore_message_codec.dart
- packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
- Updated user facing code to allow both `databaseURL` &  `databaseId`. `databaseId` takes precedence over `databaseURL`  if both are input. Otherwise, they have the same value (if one or the other are selected).
- Refactored method channel, platform and web implementations to use `databaseId` naming.
- Wrote unit test.
- We can update pigeon and native code to use `databaseId` naming in a future PR, perhaps when `databaseURL` is removed.
Before you create this PR confirm that it meets all requirements listed below by …
> fix(firestore): deprecate `databaseURL` in favor of `databaseId`

- .github/workflows/all_plugins.yaml
- CONTRIBUTING.md
- melos.yaml
- pubspec.yaml
This bumps the version of Melos used to be at least 5.3.0
> chore: Bump Melos to ^5.3.0

- packages/firebase_messaging/firebase_messaging/android/build.gradle
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundExecutor.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundService.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingReceiver.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingUtils.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/JobIntentService.java
I tested messages received in open/background/quit and also when opening app with message. Working as intended.
Part of: https://github.com/firebase/flutterfire/issues/8073 …
> fix(messaging, android): Replace deprecated AsyncTask API and other deprecated API

- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
In dart2wasm, JS functions and dart functions cannot be cast directly between each other. Similarly, JS promises and dart futures cannot be cast directly between each other either. Instead, we should use `callAsFunction` and use `toDart` to convert the JSPromise to a Future.
> fix(auth, web): invocation of unsubscribe callback for dart2wasm compatibility.

- docs/cloud-messaging/receive.md
- packages/firebase_messaging/firebase_messaging/example/web/index.html
- tests/web/index.html
> fixes: #12638
Add scope for '**firebase-messaging-sw.js**' on registration itself. The scope remains unchanged from the existing scope of the Firebase messaging service worker, only the definition is now at registration as compared to earlier behaviour which happens after initialization. …
> fix(firebase_messaging, web): Define scope for 'firebase-messaging-sw.js' on registration

- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_recaptcha_verifier_factory.dart
Taking values from JSON and directly casting them to int or double makes them incompatible with dart2wasm, since in wasm they are two distinct types (as opposed to JavaScript where they are actually the same under the hood).
Does your PR require plugin users to manually update their apps …
> fix(web): fixing some uncorrect type casting for Web

- packages/_flutterfire_internals/lib/_flutterfire_internals.dart
- packages/_flutterfire_internals/lib/src/interop_shimmer.dart
> fix(web): fix type casting for JSString in error parsing

- packages/firebase_database/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/FlutterFirebaseDatabaseException.java
- packages/firebase_database/firebase_database_web/lib/src/database_reference_web.dart
- packages/firebase_database/firebase_database_web/lib/src/interop/database.dart
- packages/firebase_database/firebase_database_web/lib/src/query_web.dart
- tests/integration_test/firebase_database/database_reference_e2e.dart
1. Removed transaction handler from [throwing twice](https://github.com/firebase/flutterfire/compare/database-12675?expand=1#diff-8b979c4a2c5988c0951c38b09314bdcf73dc73d973e8a09c7a606e3adfc17f32L98). This is the main fix in the PR because we were using two exception handlers so when the second exception was passed into `convertFirebaseDatabaseException()`, it would pass in an already formed `FirebaseException` and cause the users issue.
2. [Moved exception stream](https://github.com/firebase/flutterfire/compare/database-12675?expand=1#diff-19abf2f5278bb16502160289df7e12535d5ab9c7a2e62ff6870537db777406dcR391) handling to the source so we can properly propagate exception without [unhandled exception](https://github.com/firebase/flutterfire/compare/database-12675?expand=1#diff-9da21a4056be815 …
> fix(database, web): Stop transaction & stream handling exceptions from throwing twice

- packages/firebase_core/firebase_core/windows/firebase_core_plugin.cpp
- packages/firebase_storage/firebase_storage/windows/firebase_storage_plugin.cpp
- packages/firebase_storage/firebase_storage/windows/firebase_storage_plugin.h
- packages/firebase_storage/firebase_storage_platform_interface/lib/src/method_channel/method_channel_task.dart
- tests/integration_test/e2e_test.dart
- tests/integration_test/firebase_storage/firebase_storage_e2e_test.dart
- tests/integration_test/firebase_storage/instance_e2e.dart
- tests/integration_test/firebase_storage/reference_e2e.dart
- tests/integration_test/firebase_storage/second_bucket.dart
- tests/integration_test/firebase_storage/task_e2e.dart
- tests/integration_test/firebase_storage/test_utils.dart
1. `putData()` is now writing the data as intended.
2. `putString()` is now decoding from base64 and base64Url before writing string (previously writing string as base64).
3. `putFile()` metadata was not working correctly.
4.  `putFile()` we have also had to do a [hack to pass metadata](https://github.com/firebase/flutterfire/pull/12723/files#diff-5be57535e40bc3dc68ed0a4706153ddc03710b570c24066b9178441e7ea591ccR260-R264) as `null` on windows, it was throwing exception in pigeon even though it is [allowable as a nullable value](https://github.com/firebase/flutterfire/blob/master/packages/firebase_storage/firebase_storage/windows/messages.g.cpp#L1256-L1259). Not [ideal, but it works](https://github.com/firebase/flutterfire/pull/12723/files#diff-cd14e729c2a123769d24deb04c095c7e5c520143b9fa450 …
> fix(storage, windows): putFile(), putString(), putData() & Task streaming event fixes

- packages/firebase_database/firebase_database/lib/ui/firebase_sorted_list.dart
Quick fix because when giving a sort/compare to FirebaseAnimatedList(), the sort/compare don't apply when editing a Database child. It used to only apply on build. So I've added the missing `_snapshots.sort(comparator);` method to the `_onChildChanged()` function.
closes https://github.com/firebase/flutterfire/issues/12657 …
> fix(database): sorting was not applied when database child changed.

- packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
` String? get languageCode {
if (_delegate.languageCode != null) {
return _delegate.languageCode;
}
return null;
}`
This code has a redundant check. Getter languageCode will always return String? for _delegate.languageCode. It is more easier to understand the simple and straight logic if is done as:
`String? get languageCode {
return _delegate.languageCode;
}`
- [x ] No, this is *not* a breaking change.
> chore(auth): Removed redundant `languageCode` null-check.

- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart
- packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
I tested this with user's example and it worked as intended. The JS error is correctly parsed and instantiated as a Dart credential if it exists. If not, `null` is passed as `credential` which is a nullable argument on FirebaseAuthException:
```dart
final AuthCredential? credential;
```
fixes https://github.com/firebase/flutterfire/issues/12771 …
> fix(auth, web): get auth credential from exception and pass to user if one is available

- packages/firebase_dynamic_links/firebase_dynamic_links/example/lib/main.dart
- packages/firebase_dynamic_links/firebase_dynamic_links/lib/src/firebase_dynamic_links.dart
- packages/firebase_dynamic_links/firebase_dynamic_links/test/firebase_dynamic_links_test.dart
- tests/integration_test/firebase_dynamic_links/firebase_dynamic_links_e2e_test.dart
Mark dynamic link APIs as deprecated ahead of August 25, 2025 removal of service.
closes https://github.com/firebase/flutterfire/issues/12803
[CLA]: …
> chore(dynamic-links): mark all relevant APIs as deprecated

- packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
closes https://github.com/firebase/flutterfire/issues/12806 …
> fix(messaging): ensure default app is available before checking auth notification

- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/PigeonParser.java
OAuthProvider can have a null access token, this makes behaviour consistent across web, apple and android.
fixes https://github.com/firebase/flutterfire/issues/12791 …
> fix(auth, android): allow nullable `accessToken` when creating `OAuthProvider`

- packages/firebase_storage/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FlutterFirebaseStoragePlugin.java
- packages/firebase_storage/firebase_storage/ios/Classes/FLTFirebaseStoragePlugin.m
- packages/firebase_storage/firebase_storage_web/lib/src/interop/storage.dart
- tests/android/app/build.gradle
- tests/integration_test/firebase_storage/reference_e2e.dart
This fixes a bug where if we set one property on `SettableMetadata` (e.g. `customMetadata`), it would also set every other metadata property to `null`. This was stopping `contentType` from being inferred for android at least.
Unfortunately, the emulator doesn't infer `contentType`, so I tested on a live project and it is now inferring type if SettableMetadata is used without setting `contentType`.
fixes https://github.com/firebase/flutterfire/issues/12801
[issue …
> fix(storage): do not set metadata property unless it has a value

- packages/firebase_vertexai/firebase_vertexai/lib/firebase_vertexai.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/firebase_vertexai.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_api.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_chat.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_content.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_function_calling.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_model.dart
The current approach uses `part` files which cannot be imported
separately. One drawback of this approach is that any members which need
to be referenced by test code must be public to the library. Using
`src/` libraries, as opposed to `src/` part files, allows making APIs
that are "package private" by convention - they are public to the
library, but only exported through the `src/` import.
One potential downside (alternatively seen as a benefit) of using
separate libraries is that private members are truly private to their
library, and we cannot make a member of a class private to the package.
The convention for package imports only allows top level declarations to
be considered non-public implementation details.
- Remove imports from the top level library. Replace `part` lines with …
> refactor(vertexai): Split into separate libraries

- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_model.dart
- packages/firebase_vertexai/firebase_vertexai/pubspec.yaml
> feat(vertexai): Add a few more params to model request

- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundExecutor.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingReceiver.java
This crash occurs because the `DartCallback` is `null` in some instances when retrieving.
Other notification plugins appear to check if the `DartCallback` instance is `null` or not:
See [awesome notifications](https://github.com/rafaelsetragni/awesome_notifications/blob/0f484c73bf76665049df46767170c563d5842a61/android/src/main/java/me/carda/awesome_notifications/DartBackgroundExecutor.java#L160-L171)
See [flutter local notifications](https://github.com/MaikuB/flutter_local_notifications/blob/5375645b01c845998606b58a3d97b278c5b2cefa/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/ActionBroadcastReceiver.java#L82-L88)
[This fixes this issue](https://github.com/firebase/flutterfire/compare/messaging-fix-crashes?expand=1#diff-8744f314855e43edf01113d287 …
> fix(messaging, android): stop app from crashing when `DartCallback` or `Context` is `null`

- docs/cloud-messaging/receive.md
closes https://github.com/firebase/flutterfire/issues/12839 …
> docs(messaging, android): update authorization state limitation for notification permission

- .github/workflows/e2e_tests.yaml
- packages/cloud_firestore/cloud_firestore/example/integration_test/second_database.dart
- I've changed to `fail-fast: false` to stop flakey tests on either firestore e2e or tests e2e from cancelling the other test job in the matrix which ultimately has led to a lot more test runs.
- Updated firestore tests that are now permissible queries.
Does your PR require plugin users …
> ci: improve e2e workflows & fix failing tests

- packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
- packages/firebase_auth/firebase_auth/lib/src/user.dart
Removed `useEmulator()` API. [Deprecated over 3 years ago](https://github.com/firebase/flutterfire/commit/747f1b61bb66067c8528555cef125a11cfedb3d6).
Removed `signInWithAuthProvider()` API. [Deprecated over a year ago](https://github.com/firebase/flutterfire/commit/ca340ea19c8dbb340f083e48cf1b0de36f7d64c4)
Removed deprecated annotation from `updateProfile()` API as it is not deprecated on Firebase native SDKs. [Example](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser?_gl=1*i1z2u3*_up*MQ..*_ga*MTY3Nzg0NjUzOS4xNzE3MTYwNTEx*_ga_CW55HF8NVT*MTcxNzE2MDUxMC4xLjAuMTcxNzE2MDUxMC4wLjAuMA..#updateProfile(com.google.firebase.auth.UserProfileChangeRequest))
*Replace this paragraph with a list of issues related to this PR from the [issue …
> refactor(auth)!: remove deprecated API ahead of breaking change release

- packages/firebase_storage/firebase_storage/lib/src/firebase_storage.dart
Removed `useEmulator()` API. [Deprecated](https://github.com/firebase/flutterfire/commit/747f1b61bb66067c8528555cef125a11cfedb3d6#diff-eb1d5f7023d5b3aafdee60e56c19b2f594c1cebc44b9cfeed149fce706322750R158) 3 years ago. …
> refactor(storage)!: remove deprecated API ahead of breaking change

- packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
- tests/integration_test/firebase_auth/firebase_auth_instance_e2e_test.dart
I was going to fix [this issue](https://github.com/firebase/flutterfire/issues/7064), but realised web never properly cleans up the event listeners in the interop layer. i.e the `onDispose()` function was never called for [onAuthStateChanged](https://github.com/firebase/flutterfire/pull/12903/files#diff-073c6ae89d1947a587a79d2020e2cd9478a0d218a4aeb8dd6bce4b37344b92e1R417) & [onIdTokenChanged](https://github.com/firebase/flutterfire/pull/12903/files#diff-073c6ae89d1947a587a79d2020e2cd9478a0d218a4aeb8dd6bce4b37344b92e1R460-R466).
Ideally, I would've mocked to see the stream handlers created/removed in FirebaseAuthWeb, but mocking the interop layer with staticInterop was extremely difficult and I opted to create an integration test.
Also `userStateChanges` isn't a real API so it can't be …
> fix(auth, web): stream handlers are properly cleaned up and recreated

- packages/cloud_firestore/cloud_firestore/example/web/wasm_index.html
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
- packages/firebase_core/firebase_core_web/lib/src/interop/utils/utils.dart
- packages/firebase_core/firebase_core_web/pubspec.yaml
- moved reusable functions to core web.
- Used `hashCode` for queries to ensure we target the correct `unsubscribe()` function. See example key: `flutterfire-[DEFAULT]_10335377_querySnapshot`.
- Tested on Firestore example, queries now only fire once after "hot restart".
Related to: #7064  …
> fix(firestore, web): ensure streams are removed on "hot restart"

- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
The issue reported in the ticket is in fact an error that is not properly parsed. The Credential contained in the Map is causing the MethodChannel to fail.
closes #12554  …
> fix(auth, ios): fix the parsing of an error that could specifically happen when using MicrosoftProvider

- packages/firebase_database/firebase_database_web/lib/firebase_database_web.dart
- packages/firebase_database/firebase_database_web/lib/src/interop/database.dart
- packages/firebase_database/firebase_database_web/lib/src/interop/database_interop.dart
- packages/firebase_database/firebase_database_web/lib/src/query_web.dart
- packages/firebase_database/firebase_database_web/pubspec.yaml
- Created a hash so each stream has a unique key, wrapped it in `kDebugMode` so it is only used in this mode, `hashCode` isn't used otherwise.
- Updated type returns in database interop layer as the stream handlers return an unsubscribe function and it is the recommended way to close event handlers.
- Now able to hot restart and streams will not throw exception and they will also only fire once.
related to: https://github.com/firebase/flutterfire/issues/7064
[issue …
> fix(database, web): clean up stream handlers on "hot restart"

- packages/firebase_storage/firebase_storage_web/lib/src/interop/storage.dart
- packages/firebase_storage/firebase_storage_web/lib/src/task_web.dart
1. [This commit](https://github.com/firebase/flutterfire/pull/12927/commits/12afd28616f47259fc01349497b8049843687e82) fixed an issue where stream was being recreated again (on `task.pause()` it was calling `snapshotEvents` again). Also fixed `task.pause()` so it paused when paused state came through. Also throwing exception.
2. Usual clean up on "hot restart" of stream handlers.
closes: https://github.com/firebase/flutterfire/issues/7064 …
> fix(storage, web): clean up stream handlers on "hot restart"

- packages/firebase_app_check/firebase_app_check/example/web/index.html
- packages/firebase_app_check/firebase_app_check_web/lib/firebase_app_check_web.dart
- packages/firebase_app_check/firebase_app_check_web/lib/src/interop/app_check.dart
1. app check web `onTokenChanged` was broken. The stream was never listened ([it was just mapped](https://github.com/firebase/flutterfire/compare/app-check-7064?expand=1#diff-ced897c7c86bb9b2236d8676e1d80e16f3627802ef58545c1344676bdea434d8L128)) to which was [changed here to listen()](https://github.com/firebase/flutterfire/compare/app-check-7064?expand=1#diff-ced897c7c86bb9b2236d8676e1d80e16f3627802ef58545c1344676bdea434d8R135).
2. Properly cleaned up and initialised streams made [on this commit](https://github.com/firebase/flutterfire/commit/b485792c3e933078377c4ae0728515046ad01c3c).
3. Cleaned up streams on "hot restart" on [this commit](https://github.com/firebase/flutterfire/commit/8dd9ff516a5453966d88e42fa0490cbed77562dc).
4. Also [reinserted the debug …
> fix(app-check, web): fixed broken `onTokenChanged` and ensured it is properly cleaned up. Streams are also cleaned up on "hot restart"

- packages/firebase_auth/firebase_auth/windows/messages.g.cpp
- packages/firebase_core/firebase_core/example/windows/flutter/CMakeLists.txt
> fix(auth, windows): fix a crash that could happen when using `sendEmailVerification` or `sendPasswordResetEmail`

- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
- packages/firebase_auth/firebase_auth/ios/Classes/PigeonParser.m
- packages/firebase_auth/firebase_auth/ios/Classes/Private/PigeonParser.h
Invoking this `@([authCredential hash])` produce two different hash keys which meant we were unable to retrieve from cache if the user `linkWithCredential()` threw exception "credential-already-in-use" containing a credential to sign-in with. 
This change ensures the same hash key is used to retrieve the exception in native code to allow `signInWithCredential()`.
Both users confirmed it is working.
fixes https://github.com/firebase/flutterfire/issues/12931
fixes: https://github.com/firebase/flutterfire/issues/12944 …
> fix(auth, apple): bug with cached `AuthCredential`, hash key was producing different value

- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundExecutor.java
This class isn't used anymore and the documentation is outdated. Removing.
closes #12936
> chore(messaging, android): fix native documentation

- packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
This pull request updates the documentation for the `auth/user-not-found` exception in the `firebase_auth.dart` file. The update reflects the recent change where email enumeration protection is enabled by default as of September 15, 2023. With this protection, the `auth/user-not-found` exception is no longer thrown if the account with the specified email does not exist.
**Changes made:**
- Updated the documentation to include a note about the email enumeration protection.
- Clarified the conditions under which the `auth/user-not-found` exception is thrown.
This change ensures that developers are aware of the new behavior and can handle authentication flows accordingly.
> docs: Update documentation for auth/user-not-found exception to reflect email enumeration protection

- packages/cloud_firestore/cloud_firestore/windows/cloud_firestore_plugin.cpp
See docs for instantiating 2nd database: https://firebase.google.com/docs/reference/cpp/class/firebase/firestore/firestore?_gl=1*wpl56g*_up*MQ..*_ga*ODM3Nzk3MTY5LjE3MTkzMTg2ODc.*_ga_CW55HF8NVT*MTcxOTMxODY4Ny4xLjAuMTcxOTMxODY4Ny4wLjAuMA..
closes https://github.com/firebase/flutterfire/issues/12996 …
> feat(firestore, windows): support multiple databases

- packages/firebase_database/firebase_database_web/lib/src/interop/database.dart
- packages/firebase_database/firebase_database_web/lib/src/query_web.dart
If exact same stream is created (i.e same hashCode generated from parameters), it will unsubscribe in debug mode.
I've created a map used in debug mode to track the count of the exact same stream and appended the count to the hashCode to ensure they are subscribed/unsubscribed separately.
Here is the user's code I used in example app:
```dart
ref.onValue.listen((data) {
print('got them 1');
}, onError: (e) => print('error: ${e}'), onDone: () => print('done'));
ref.onValue.listen((data) {
print('got them 2');
}, onError: (e) => print('error ${e}'), onDone: () => print('done'));
ref.onValue.listen((data) {
print('got them 3');
}, onError: (e) => print('error ${e}'), onDone: () => print('done'));
```
Here are console logs showing they all get the event as it was previously.
Here is a …
> fix(database, web): ensure exact same streams are not unsubscribed in debug mode

- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
I created a button to attach three listeners to a document ref:
```dart
ElevatedButton(
onPressed: () async {
final collection = FirebaseFirestore.instance
.collection('flutter-tests')
.doc('blah');
collection.snapshots().listen((data) {
print('Data: ${data.data()}');
});
collection.snapshots().listen((data) {
print('Data: ${data.data()}');
});
collection.snapshots().listen((data) {
print('Data: ${data.data()}');
});
},
child: const Text('Create Listeners'),
),
```
Here are the logs. The following proves the fix: 
- On initial start up, I created listeners which correctly printed the data 3 times.
- "hot restart" 3 times and created listeners again. Correctly printed the data 3 times.
- "hot restart" 1 more time and created listeners again. Correctly printed the data 3 times.
- Updated …
> fix(firestore, web): ensure exact same streams are not unsubscribed

- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
> fix(auth, web): ensure exact same streams are not unsubscribed

- docs/auth/federated-auth.md
> docs(auth, apple): show how to use `credentialWithIDToken()`

- packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart
- packages/firebase_core/firebase_core_platform_interface/test/firebase_options_test.dart
I need to change the `authDomain` and a `copyWith` method makes this a lot easier
Tangentially related: https://github.com/firebase/flutterfire/issues/12819
> feat(firebase_core_platform_interface): Add copyWith to FirebaseOptions

- packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart
- packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/platform_interface/platform_interface_messaging.dart
I don't think there is any way around this problem. The intent passed on notification has no data to tie it to the message received.
closes https://github.com/firebase/flutterfire/issues/12885 …
> docs(messaging, android): update inline documentation on behavior

- packages/firebase_auth/firebase_auth/example/lib/auth.dart
- packages/firebase_auth/firebase_auth/example/pubspec.yaml
Updates the flutter_facebook_auth to 7.0.1 for the firebase_auth example.
`token` had to be changed to `tokenString` in order to compile auth.dart for this update, otherwise you'll get the error below when building the example app.
```bash
Failed to build iOS app
Error (Xcode): lib/auth.dart:576:53: Error: The getter 'token' isn't defined for the class 'AccessToken'.
Encountered error while building for device.
``` …
> chore: update flutter_facebook_auth to 7.0.1

- docs/auth/email-link-auth.md
Documentation Error regarding the location of the Authorized Domains.
Sign-in method tab (Authentication -> Sign-in method). 
but the right location is
Settings tab (Authentication -> Settings -> Authorized Domains).
*This PR addresses a documentation error regarding the location of the Authorized Domains settings in the Firebase Console. The previous documentation incorrectly stated the navigation path as "Sign-in method tab (Authentication -> Sign-in method)". The correct path is "Settings tab (Authentication -> Settings -> Authorized Domains)".*
*It does not relate to any reported issues.*
> docs(auth): Correct  documentation for Authorized Domains location in Firebase Console

- AUTHORS
- packages/firebase_auth/firebase_auth/test/firebase_auth_test.dart
- packages/firebase_auth/firebase_auth/windows/firebase_auth_plugin.cpp
Added support for the rawNonce field in credential builder on the Windows platform.
Since there is no implementation of AppleAuthProvider on Windows platform, I am trying to use OAuthProvider. This works on MacOS, but on Windows I couldn't pass an idToken with a rawNonce and no accessToken to the credential builder. And signInWithCredentials threw an exception.
With this PR if rawNonce is provided then will be used overloaded credential builder firebase::auth::OAuthProvider::GetCredential that accept rawNonce argument.
Example of use:
```dart
final credential = OAuthProvider("apple.com").credential(idToken: webAuthRes.idToken, rawNonce: webAuthRes.nonce);
FirebaseAuth.instance.signInWithCredential(credential);
```
No existing issues found ((
Before you create this PR confirm that it meets …
> fix(firebase_auth): added supporting rawNonce for OAuth credential on Windows platform

- CONTRIBUTING.md
- README.md
- docs/setup/_setup_prereq_android.md
- docs/setup/_setup_prereq_ios.md
- docs/setup/_setup_prereq_web.md
- packages/cloud_firestore/cloud_firestore/example/README.md
- packages/cloud_firestore/cloud_firestore/example/lib/main.dart
- packages/cloud_functions/cloud_functions/example/README.md
- packages/firebase_analytics/firebase_analytics/example/README.md
- packages/firebase_app_check/firebase_app_check/example/README.md
- packages/firebase_auth/firebase_auth/example/README.md
- packages/firebase_auth/firebase_auth/example/lib/main.dart
- packages/firebase_auth/firebase_auth_web/README.md
- packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_core_exceptions.dart
- packages/firebase_core/firebase_core_web/README.md
- packages/firebase_crashlytics/firebase_crashlytics/example/README.md
- packages/firebase_database/firebase_database/example/README.md
- packages/firebase_dynamic_links/firebase_dynamic_links/example/README.md
- packages/firebase_messaging/firebase_messaging/example/README.md
- packages/firebase_performance/firebase_performance/example/README.md
- packages/firebase_performance/firebase_performance_platform_interface/pubspec.yaml
- packages/firebase_remote_config/firebase_remote_config/example/README.md
- packages/firebase_storage/firebase_storage/example/README.md
- tests/integration_test/firebase_dynamic_links/firebase_dynamic_links_e2e_test.dart
> docs: remove reference to flutter.io and firebase.flutter.dev

- packages/cloud_firestore/cloud_firestore/example/integration_test/document_reference_e2e.dart
- packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart
- packages/cloud_firestore/cloud_firestore/lib/src/query.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_document_reference.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_query.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_document_reference.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_query.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/document_reference_web.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
Cleaned up the platform channel code so we don't give default value everywhere but only on the user-facing interface.
closes #13174
[CLA]: …
> fix(firestore): not passing correctly the ListenSource when listening to as single `DocumentReference`

- packages/firebase_database/firebase_database_web/lib/src/query_web.dart
Cannot be tested since it only happens when hot reloading.
closes #13182 
> fix(database,web): fix an issue that would remove duplicate streams in Debug mode

- packages/firebase_app_installations/firebase_app_installations/ios/Classes/FirebaseInstallationsPlugin.swift
- packages/firebase_app_installations/firebase_app_installations/ios/Classes/IdChangedStreamHandler.swift
- tests/integration_test/firebase_app_installations/firebase_app_installations_e2e_test.dart
Currently, each call would assign `arguments` and `result` to a global context. If 2 calls were done at the same time, the result only 1 result would be sent back.
closes #13240  …
> fix(installations, apple): update the plugin to support parallels method calling

- packages/cloud_firestore/cloud_firestore/example/integration_test/e2e_test.dart
- packages/cloud_firestore/cloud_firestore/lib/src/utils/codec_utility.dart
- packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
- Only set `webExperimentalLongPollingOptions` if there is a value set by the user. 
- This ought to fix our web firestore e2e tests. The tests were failing because [we wrap in try/catch here](https://github.com/firebase/flutterfire/blob/fix-firestore-web/packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart#L34-L44). When we tried to initialise, it would throw an exception because `webExperimentalLongPollingOptions` was null. Then the firestore instance would be reinitialised without settings and that means we wouldn't have cache option set.
- e2e tests now work which is proof of fix as previously getting doc from cache was failing because initialising firestore without settings wasn't occurring properly. See example test failure that is now fixed from this PR: …
> fix(firestore, web): only set long polling options if it has a value

- packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
When running on wasm web, a TypeError was being thrown as the dart string/boolean parameters of ActionCodeSettings were not being 'jsified' before passing through to the javascript sdk.
[issue …
> fix(auth): TypeError when converting ActionCodeSettings to JS

- CHANGELOG.md
- packages/firebase_vertexai/firebase_vertexai/CHANGELOG.md
- packages/firebase_vertexai/firebase_vertexai/README.md
- packages/firebase_vertexai/firebase_vertexai/example/README.md
- packages/firebase_vertexai/firebase_vertexai/lib/firebase_vertexai.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/utils/mutex.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_api.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_chat.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_client.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_content.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_error.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_function_calling.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_model.dart
- packages/firebase_vertexai/firebase_vertexai/pubspec.yaml
- packages/firebase_vertexai/firebase_vertexai/test/firebase_vertexai_test.dart
- packages/firebase_vertexai/firebase_vertexai/test/vertex_content_test.dart
Fork Vertex AI sdk from dependent from generative ai sdk.
This PR contains breaking changes and will be merged into the GA preparation branch. …
> chore(vertexai): fork vertexai sdk away from generative ai sdk.

- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_api.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_content.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_model.dart
- packages/firebase_vertexai/firebase_vertexai/pubspec.yaml
- packages/firebase_vertexai/firebase_vertexai/test/utils/matchers.dart
- packages/firebase_vertexai/firebase_vertexai/test/utils/stub_client.dart
- packages/firebase_vertexai/firebase_vertexai/test/vertex_chat_test.dart
- packages/firebase_vertexai/firebase_vertexai/test/vertex_content_test.dart
- packages/firebase_vertexai/firebase_vertexai/test/vertex_model_test.dart
- packages/firebase_vertexai/firebase_vertexai/test/vertex_response_parsing_test.dart
> chore(vertexai): Add corresponding unit test for the fork

- packages/firebase_data_connect/firebase_data_connect/example/dataconnect/connector/mutations.gql
- packages/firebase_data_connect/firebase_data_connect/lib/src/network/grpc_transport.dart
- packages/firebase_data_connect/firebase_data_connect/lib/src/network/rest_transport.dart
- packages/firebase_data_connect/firebase_data_connect/test/src/network/rest_transport_test.dart
Fixed issue where if the server responds with an error, then the Data Connect library wouldn't throw an error.
> fix(fdc): Handled errors

- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
- packages/cloud_firestore/cloud_firestore/lib/src/query.dart
Remove single whereIn filter assertion
Closes https://github.com/firebase/flutterfire/issues/13407 …
> fix(cloud_firestore): remove single whereIn filter assertion

- packages/firebase_data_connect/firebase_data_connect/lib/src/core/ref.dart
- packages/firebase_data_connect/firebase_data_connect/lib/src/optional.dart
- packages/firebase_data_connect/firebase_data_connect/test/src/optional_test.dart
* Fix issue where on GRPC, since protobuf doesn't distinguish between double and int, all numbers were being parsed as doubles.
* Fix issue where `execute.ignore` was called, causing errors not being thrown.
> fix(fdc): Fix serializing errors

- packages/firebase_storage/firebase_storage/example/lib/main.dart
- packages/firebase_storage/firebase_storage/example/pubspec.yaml
- packages/firebase_storage/firebase_storage_web/lib/src/interop/storage.dart
- packages/firebase_storage/firebase_storage_web/lib/src/reference_web.dart
- tests/integration_test/firebase_storage/reference_e2e.dart
Some tests were skipped for web. Added them back.
closes #13464 
closes #13458
> fix(storage, web): fix putData when using UInt8List

- packages/firebase_vertexai/firebase_vertexai/example/lib/main.dart
Reflow comments and break long strings into adjacent string literals.
> style: shorten lines over 80 characters

- packages/firebase_storage/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FlutterFirebaseStoragePlugin.java
- packages/firebase_storage/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FlutterFirebaseStorageTask.java
- packages/firebase_storage/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/TaskStateChannelStreamHandler.java
The stream handler and event channel were never cleaned up once the StorageTask had finished, causing memory leak and ultimately an out-of-memory exception.
Using the following setup, I continued to create Storage Tasks.
```dart
ElevatedButton(
onPressed: () async {
Uint8List buffer = Uint8List(5000000);
Reference ref =  FirebaseStorage.instance.ref();
await ref.child('flutter-tests/putdata').putData(buffer);
},
child: const Text('Storage test'),
),
```
I profiled the app to see the memory footprint. 
Here is the baseline memory footprint starting the app, it starts with 269.1mb ( to the right of image, half way up):
I pressed the button 10 times which creates 10 Storage tasks, here is the lastest memory footprint which has now risen to 317mb:
Finally, you can see that `eventChannels` and …
> fix(storage, android): stream handler & event channel clean up on completion

- CHANGELOG.md
- packages/firebase_vertexai/firebase_vertexai/CHANGELOG.md
- packages/firebase_vertexai/firebase_vertexai/example/pubspec.yaml
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_version.dart
- packages/firebase_vertexai/firebase_vertexai/pubspec.yaml
- firebase_vertexai@1.0.1
Does your PR require plugin users to manually update their apps …
> chore(release): publish packages

- Package.swift
- Sources/firebase_core_shared/FLTFirebasePlugin.m
- Sources/firebase_core_shared/FLTFirebasePluginRegistry.m
- Sources/firebase_core_shared/include/FLTFirebasePlugin.h
- Sources/firebase_core_shared/include/FLTFirebasePluginRegistry.h
- melos.yaml
- scripts/generate_tag_spm_firebase_core.dart
- created a firebase core shared package in the root of FlutterFire repo for source code that is shared between all plugins. this will be pulled in by all plugins including firebase core. Symlinked code that is shared into Sources/ directory in the root of repo.
- created a script that tags `${firebase-core-version}-firebase-core-swift` so we can keep it up-to-date. 
I've tested this with my own FlutterFire fork so I think once I tag main branch by running the `[generate_tag_spm_firebase_core.dart` manually, I should be able to use it in the SPM firestore PR, and get that ready for review. 
*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. …
> chore(firebase_core): create a swift package of shared iOS source code for all plugins

- Package.swift
- packages/firebase_core/firebase_core/ios/firebase_core/Sources/firebase_core/FLTFirebasePlugin.m
- packages/firebase_core/firebase_core/ios/firebase_core/Sources/firebase_core/FLTFirebasePluginRegistry.m
- Cannot find a way to get firebase-ios-sdk version from remote repo, in the future, we can make a script for updating sdk version in preCommit hook of `melos version`.
- Updated headers to make firebase core source file compatible with cocoapods and Swift.
Does your PR require plugin …
> fix(core, ios): update Package.swift and header imports for backwards compatibility

- packages/firebase_remote_config/firebase_remote_config/android/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfig/FirebaseRemoteConfigPlugin.java
*Fixes incorrect key type usage in Android Remote Config teardown by removing an ineffective listenersMap.remove() call, addressing lint warnings.*
fixes https://github.com/firebase/flutterfire/issues/13417 …
> fix(remote_config, android): remove invalid map key from Remote Config tear down

- tests/integration_test/firebase_analytics/firebase_analytics_e2e_test.dart
- tests/integration_test/firebase_messaging/firebase_messaging_e2e_test.dart
- Tests consistently fail on iOS because [APNS token isn't received](https://github.com/firebase/flutterfire/blob/main/packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m#L404) before `subscribeToTopic()` is called. Skipped on CI.
- analytics getSessionId() is flakey as well. Skipped on CI. …
> test: skip flakey subscribe to topic tests + sessionId() for iOS on CI

- packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
- tests/integration_test/firebase_messaging/firebase_messaging_e2e_test.dart
It seems an APNS token is already received/set for iOS simulator and we no longer need to set a dummy APNS token.
Tested on iOS 17 and 18.
fixes https://github.com/firebase/flutterfire/issues/13558 …
> fix(messaging, ios): remove dummy APNS token for simulator

- packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
fixes https://github.com/firebase/flutterfire/issues/13366 …
> fix(messaging, ios): foreground notification appears twice on iOS 18

- .github/workflows/all_plugins.yaml
- packages/firebase_core/firebase_core/ios/firebase_core/Package.swift
- Increased swift integration test timeout which was the reason why it was failing. It also matches the timeout set in Firestore PR: https://github.com/firebase/flutterfire/pull/13329/files#diff-61a085d0578afbe6a13da0c8926054ea59e83ce30bd655a6349e78afe7940351R127
- I was able to reproduce the bug on a throwaway Flutter app outside of Flutterfire. I tested by pointing to firebase_core on path with the fix and I was able to build successfully:
fixes https://github.com/firebase/flutterfire/issues/13726
Does your PR require plugin users to manually update their …
> fix(core, ios): ensure iOS SDK version can be found from Package.swift

- .github/workflows/spam-removal/index.js
Closes out new batch of spam not captured with previous implementation: …
> chore: tweak spam words

- .github/workflows/ios.yaml
- packages/cloud_firestore/cloud_firestore/example/integration_test/collection_reference_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/document_change_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/document_reference_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/e2e_test.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/field_value_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/geo_point_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/instance_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/load_bundle_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/second_database.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/settings_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/snapshot_metadata_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/timestamp_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/transaction_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/web_snapshot_listeners.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/write_batch_e2e.dart
> test(firestore): switch `testWidgets()` to `test()` for e2e tests

- packages/firebase_data_connect/firebase_data_connect/lib/src/core/ref.dart
- packages/firebase_data_connect/firebase_data_connect/test/src/core/ref_test.dart
* Fix issue where if `getIdToken` threw an error, so did `executeQuery` and `executeMutation`
* Fix issue where if `stream.cancel` is called, the stream is automatically closed for all consumers
> fix(fdc): Don't throw when FirebaseAuth is unable to get an ID Token

- .github/workflows/android.yaml
- .github/workflows/ios.yaml
- .github/workflows/macos.yaml
- .github/workflows/web.yaml
- .github/workflows/windows.yaml
- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
closes: https://github.com/firebase/flutterfire/issues/13289 …
> test(firestore): additional coverage for `startAfterDocument()`

- packages/firebase_crashlytics/firebase_crashlytics/android/src/main/java/com/google/firebase/crashlytics/FlutterFirebaseCrashlyticsInternal.java
- packages/firebase_crashlytics/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/Constants.java
- packages/firebase_crashlytics/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/FlutterFirebaseCrashlyticsPlugin.java
- packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart
- packages/firebase_crashlytics/firebase_crashlytics/lib/src/utils.dart
- packages/firebase_crashlytics/firebase_crashlytics/test/firebase_crashlytics_test.dart
- packages/firebase_crashlytics/firebase_crashlytics_platform_interface/lib/src/method_channel/method_channel_crashlytics.dart
- packages/firebase_crashlytics/firebase_crashlytics_platform_interface/lib/src/platform_interface/platform_interface_crashlytics.dart
- packages/firebase_crashlytics/firebase_crashlytics_platform_interface/test/method_channel_tests/method_channel_crashlytics_test.dart
Add loading unit data to Crashlytics reports as internal keys. This is needed to symbolicate Dart stack traces in Flutter apps built with Deferred Components on Android, as Android Dynamic Modules.
Tested by unit tests, and manual end-to-end tests with the plugin built locally.
Doc: [go/crashlytics-deferred-components](http://go/crashlytics-deferred-components)
> feat(crashlytics, android): Support deferred component crash stack trace

- packages/firebase_auth/firebase_auth/windows/firebase_auth_plugin.cpp
Fixes #16536. (I hope - see below.)
Flutter's `EncodableValue` derives from this `std::variant`:
https://github.com/flutter/engine/blob/cea11063ae318691f0ede4ef12f2978ad01aff70/shell/platform/common/client_wrapper/include/flutter/encodable_value.h#L94-L95
https://github.com/flutter/engine/blob/cea11063ae318691f0ede4ef12f2978ad01aff70/shell/platform/common/client_wrapper/include/flutter/encodable_value.h#L103-L116
https://github.com/flutter/engine/blob/cea11063ae318691f0ede4ef12f2978ad01aff70/shell/platform/common/client_wrapper/include/flutter/encodable_value.h#L165
```cpp
class EncodableValue : public internal::EncodableValueVariant {
```
```cpp
using EncodableValueVariant = std::variant<std::monostate,
bool,
int32_t,
int64_t,
double,
std::string,
std::vector<uint8_t>, …
```
> fix(firebase_auth): Fix `std::variant` compiler errors with VS 2022 17.12

- packages/firebase_vertexai/firebase_vertexai/lib/src/api.dart
- Removed trailing whitespaces in 'HARM_SEVERITY_UNSPECIFIED ' and 'HARM_SEVERITY_HIGH '.
This issue needs to be fixed to ensure proper handling and avoid unexpected behavior
Nothing …
> fix(firebase_vertexai): Remove unnecessary trailing whitespace

- packages/firebase_storage/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FlutterFirebaseStoragePlugin.java
> fix(storage, android): fix an issue that could crash the app when concurrent calls to removeEventListeners were happening

- packages/firebase_remote_config/firebase_remote_config/android/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfig/FirebaseRemoteConfigPlugin.java
- packages/firebase_remote_config/firebase_remote_config/example/android/settings.gradle
- packages/firebase_remote_config/firebase_remote_config/ios/firebase_remote_config/Sources/firebase_remote_config/FLTFirebaseRemoteConfigPlugin.m
- packages/firebase_remote_config/firebase_remote_config/lib/src/firebase_remote_config.dart
- packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/method_channel/method_channel_firebase_remote_config.dart
- packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/platform_interface/platform_interface_firebase_remote_config.dart
- packages/firebase_remote_config/firebase_remote_config_web/lib/firebase_remote_config_web.dart
- packages/firebase_remote_config/firebase_remote_config_web/lib/src/internals.dart
- packages/firebase_remote_config/firebase_remote_config_web/lib/src/interop/firebase_remote_config.dart
- packages/firebase_remote_config/firebase_remote_config_web/lib/src/interop/firebase_remote_config_interop.dart
- packages/firebase_remote_config/firebase_remote_config_web/pubspec.yaml
- tests/integration_test/firebase_remote_config/firebase_remote_config_e2e_test.dart
> feat(remote-config): custom signals support

- packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart
Added an additional condition to check the stackTrace message for `TypeError: Cannot read properties of undefined (reading 'getApps')`. I observed that this error appears in the `exception` output in debug mode but is not present in `exception` for release mode, instead appearing only in the `stackTrace`.
fixes https://github.com/firebase/flutterfire/issues/17111 …
> fix(core, web): resolve type error in release mode

- packages/firebase_vertexai/firebase_vertexai/lib/src/imagen_api.dart
Added a warning log message if a value outside the range [0, 100] is specified for the JPEG compression quality in ImagenImageFormat.jpeg(compressionQuality:). Values outside this range seem to be treated as 0 or 100 by the backend and were likely set by accident. See [b/395693541](https://b.corp.google.com/issues/395693541) (Google internal) for more details.
This will ensure a smooth and quick …
> fix(vertexai): Imagen JPEG compression quality out of range warning

- packages/firebase_vertexai/firebase_vertexai/example/lib/pages/bidi_page.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/error.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/live_api.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/live_session.dart
- packages/firebase_vertexai/firebase_vertexai/test/error_test.dart
- packages/firebase_vertexai/firebase_vertexai/test/live_test.dart
> fix(vertexai): follow up changes for LiveModel

- packages/cloud_firestore/cloud_firestore/example/integration_test/timestamp_e2e.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/timestamp.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/test/timestamp_test.dart
Fixes https://github.com/firebase/flutterfire/issues/17189
> fix(cloud_firestore): correct nanoseconds calculation for pre-1970 dates

- packages/cloud_firestore/cloud_firestore/lib/src/collection_reference.dart
- packages/cloud_firestore/cloud_firestore/lib/src/document_reference.dart
- packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
- packages/cloud_firestore/cloud_firestore/test/cloud_firestore_test.dart
- packages/cloud_firestore/cloud_firestore/test/collection_reference_test.dart
Assertions are not used in release builds of Flutter applications resulting in these checks not throwing and passing to native where some errors are unhandled and cause a crash. (https://docs.flutter.dev/testing/build-modes#release)
Fixes some of: https://github.com/firebase/flutterfire/issues/17196
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is …
> fix(firestore): Change asserts to throw argumentError

- .github/workflows/all_plugins.yaml
Fixes swift inegration CI issue as native ios-sdk upgraded to XCode 16.3 from 16.2 which is not supported by macos-latest using version 14. …
> ci(swift-integration): bump macos-14 to macos-15

- packages/firebase_vertexai/firebase_vertexai/example/.gitignore
- packages/firebase_vertexai/firebase_vertexai/example/android/settings.gradle
- packages/firebase_vertexai/firebase_vertexai/example/lib/main.dart
- packages/firebase_vertexai/firebase_vertexai/example/lib/pages/function_calling_page.dart
- packages/firebase_vertexai/firebase_vertexai/example/lib/pages/imagen_page.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/firebase_vertexai.dart
> chore(vertexai): update sample for developer api and fix the instance key for FirebaseVertexAI 

- packages/firebase_vertexai/firebase_vertexai/example/lib/main.dart
- packages/firebase_vertexai/firebase_vertexai/example/lib/pages/imagen_page.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/firebase_vertexai.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/imagen_model.dart
> chore(vertexai): add imagen developer api support

- packages/firebase_auth/firebase_auth/ios/firebase_auth/Sources/firebase_auth/FLTFirebaseAuthPlugin.m
Fixes a crash where Firebase Auth's Apple Sign-In handler crashes with `EXC_BAD_ACCESS` on iOS/macOS when the completion handler is deallocated during async operations.
Specifically:
- Captures `appleCompletion` locally within `handleSignInWithApple` to prevent deallocation
- Adds nil check before calling the completion handler
- Creates strong references for callbacks in async operations
Affects both iOS and macOS platforms through the shared implementation.
Closes #17216.
> fix(auth,apple): prevent EXC_BAD_ACCESS crash in Apple Sign-In completion handler

- docs/cloud-messaging/receive.md
closes https://github.com/firebase/flutterfire/issues/13346 …
> chore(docs): Update Extension Helper Docs

- packages/firebase_vertexai/firebase_vertexai/lib/src/api.dart
- packages/firebase_vertexai/firebase_vertexai/test/api_test.dart
Also add the unit test for api.dart file.
[Flutter …
> feat(vertexai): Add HarmBlockThreshold.OFF

- packages/firebase_vertexai/firebase_vertexai/lib/src/schema.dart
- packages/firebase_vertexai/firebase_vertexai/test/schema_test.dart
https://github.com/firebase/flutterfire/issues/16745 …
> feat(firebaseai): Add new attributes for schema

- packages/firebase_vertexai/firebase_vertexai/lib/src/firebase_vertexai.dart
> chore(firebaseai): add the deprecation document

- docs/auth/multi-factor.md
Warn users in documentation that sms it not considered 'secure'. Not mentioned in Native Docs.
Noted here:
- https://www.cisa.gov/sites/default/files/2024-12/guidance-mobile-communications-best-practices.pdf
- https://cloud.google.com/solutions/modern-password-security-for-system-designers.pdf
closes https://github.com/firebase/flutterfire/issues/17202 …
> docs(auth): warn users about sms usage

- docs/app-check/default-providers.md
> docs(app_check): add additional steps to ensure App Check works on specific devices

- docs/auth/multi-factor.md
closes https://github.com/firebase/flutterfire/issues/13500 …
> docs(auth): windows platform does not support multi-factor auth

- packages/firebase_data_connect/firebase_data_connect/lib/src/any_value.dart
- packages/firebase_data_connect/firebase_data_connect/test/src/any_test.dart
Fixes https://github.com/firebase/flutterfire/issues/17348 …
> fix(data_connect): avoid calling toJson on raw JSON map or null object

- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/GeneratedAndroidFirebaseAuth.java
- packages/firebase_auth/firebase_auth/ios/firebase_auth/Sources/firebase_auth/FLTFirebaseAuthPlugin.m
- packages/firebase_auth/firebase_auth/ios/firebase_auth/Sources/firebase_auth/firebase_auth_messages.g.m
- packages/firebase_auth/firebase_auth/ios/firebase_auth/Sources/firebase_auth/include/Public/firebase_auth_messages.g.h
- packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/pigeon/messages.pigeon.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart
- packages/firebase_auth/firebase_auth_platform_interface/pigeons/messages.dart
- packages/firebase_auth/firebase_auth_platform_interface/test/pigeon/test_api.dart
- packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart
- tests/integration_test/firebase_auth/firebase_auth_instance_e2e_test.dart
This PR adds support for `initializeRecaptchaConfig`
Closes https://github.com/firebase/flutterfire/issues/17354
> feat(auth): add support for initializeRecaptchaConfig

- .github/workflows/all_plugins.yaml
- .github/workflows/scripts/swift-integration.dart
- Using version isn't a good idea particularly if there is an update to the code without a version. Preferable to test against any changes in the pull request. …
> ci(swift): use PR branch to test swift integration rather than version 

- packages/firebase_storage/firebase_storage/lib/src/utils.dart
- packages/firebase_storage/firebase_storage/test/utils_test.dart
*Add unit tests to ensure that `partsFromHttpUrl` does not return null for localhost URLs on all platforms.*
The PR #7003 fixed an issue where `refFromUrl` returns null when the URL is localhost, which is required when connecting to the Firebase emulator of the machine. While that fix works on all platforms that use the standard `localhost`, it does not work on Android emulators, where the only way to connect to the machine of the emulator is by using the `127.0.0.1` address, so #12047 patched it to work on Android as well.
The PR #12047 was sent by me, and I just came across this code. I improved it a bit by:
* Adding unit tests to handle both `localhost` and `127.0.0.1`, so adding these two unit tests while removing these two PRs will cause the tests to fail as expected.
* Refactoring …
> test(storage): ensure both standard localhost and Android localhost are handled

- packages/firebase_data_connect/firebase_data_connect/README.md
Old link pointed towards schema page that required an ACL. This updates to the public link.
> fix(fdc): Fixed readme link

- packages/firebase_app_check/firebase_app_check/android/build.gradle
- packages/firebase_app_check/firebase_app_check/android/src/main/java/io/flutter/plugins/firebase/appcheck/FlutterFirebaseAppCheckPlugin.java
- packages/firebase_app_check/firebase_app_check_platform_interface/lib/src/android_provider.dart
- packages/firebase_app_check/firebase_app_check_platform_interface/lib/src/method_channel/utils/provider_to_string.dart
> feat(app-check)!: remove deprecated functions

- packages/cloud_firestore/cloud_firestore/example/integration_test/instance_e2e.dart
- packages/cloud_firestore/cloud_firestore/lib/cloud_firestore.dart
- packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
- packages/cloud_firestore/cloud_firestore/test/cloud_firestore_test.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_firestore.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_firestore.dart
- packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
Removes all deprecated methods from the cloud_firestore package's front-facing API in preparation for a breaking change release.
- `databaseURL` parameter/property → Use `databaseId` instead
- `enablePersistence()` method → Use `Settings.persistenceEnabled` instead  
- `setIndexConfiguration()` method → Use `PersistentCacheIndexManager` instead
- `enableIndexedDbPersistence()` function → Use `FirestoreSettings.localCache` instead
- `cacheSizeBytes` setter → Use `FirestoreSettings.localCache` instead
```dart
// Before
FirebaseFirestore.instanceFor(app: app, databaseURL: 'db');
await firestore.enablePersistence();
await firestore.setIndexConfiguration(indexes: [...]);
// After  
FirebaseFirestore.instanceFor(app: app, databaseId: 'db');
firestore.settings = const …
```
> feat(firestore)!: remove deprecated functions

- packages/firebase_remote_config/firebase_remote_config/android/src/main/kotlin/io/flutter/plugins/firebase/firebaseremoteconfig/FirebaseRemoteConfigPlugin.kt
Fixes https://github.com/firebase/flutterfire/issues/17566
> fix(remote_config, android): make `onCancel` accept nullable arguments to avoid crash on hot restart

- packages/firebase_ai/firebase_ai/lib/src/developer/api.dart
- packages/firebase_ai/firebase_ai/test/developer_api_test.dart
The Developer API was missing support for `inlineData` parts, which was already implemented in the Vertex AI API.
This change copies the `inlineData` parsing logic from the Vertex AI `parsePart` function to the `_parsePart` function in the Developer API.
The existing test file, `developer_api_test.dart`, has been updated to include a test case for parsing `inlineData` parts, ensuring the functionality is working as expected.
Tested in the iOS simulator with a manual change to the sample (not included, since it likely warrants further example changes)
Fixes https://github.com/firebase/flutterfire/issues/17449
There was a previous attempt at this but it was closed: https://github.com/firebase/flutterfire/pull/17451
Before you create this PR confirm that it meets all requirements listed …
> feat(firebase-ai): add inlineData support to Developer API

- packages/firebase_auth/firebase_auth/ios/firebase_auth/Sources/firebase_auth/FLTPhoneNumberVerificationStreamHandler.m
- packages/firebase_auth/firebase_auth/ios/firebase_auth/Sources/firebase_auth/include/Private/FLTAuthStateChannelStreamHandler.h
- packages/firebase_auth/firebase_auth/ios/firebase_auth/Sources/firebase_auth/include/Private/FLTIdTokenChannelStreamHandler.h
- packages/firebase_auth/firebase_auth/ios/firebase_auth/Sources/firebase_auth/include/Private/FLTPhoneNumberVerificationStreamHandler.h
- packages/firebase_auth/firebase_auth/ios/firebase_auth/Sources/firebase_auth/include/Private/PigeonParser.h
Changed are non-public headers that import the firebase-ios-sdk's FirebaseAuth module (a Swift module). Importing Swift modules into an Objective-C header is not really supported (e.g. https://forums.swift.org/t/swift-cant-see-objc-methods-that-include-package-symbols/65732). 
* fixes https://github.com/firebase/flutterfire/issues/17552 …
> fix(auth, apple): Move FirebaseAuth imports to implementation files

- CHANGELOG.md
hiding a feature to wait for the service to be ready …
> chore(docs): Update CHANGELOG.md

- packages/firebase_ai/firebase_ai/example/lib/pages/token_count_page.dart
This isn't clear in the sample UI why this is happening, and ends up using more tokens than necessary.
Internal bug report.
> chore(firebaseai): remove `generateContent` call from count tokens page

- packages/firebase_ai/firebase_ai/example/lib/main.dart
- packages/firebase_ai/firebase_ai/example/lib/pages/json_schema_page.dart
- packages/firebase_ai/firebase_ai/lib/src/api.dart
- packages/firebase_ai/firebase_ai/test/api_test.dart
This adds the `responseJsonSchema` field to the GenerationConfig class, which enables more JSON schema features like `$def` and `$ref` along with other advanced JSON schema features that Gemini 2.5 supports.
See [the Gemini docs](https://ai.google.dev/gemini-api/docs/structured-output#json-schema) for more information about what is supported.
- Fixes https://github.com/firebase/flutterfire/issues/17551 …
> feat(firebaseai): add `responseJsonSchema` to `GenerationConfig`

- packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart
This updates the `FirebaseOptions.androidClientId` documentation.
- Fixes a copy/paste mistake that said “This value is used by iOS only”.
- Clarifies it as the Android OAuth client ID and notes “This value is used on Android only”.
This aligns `androidClientId` with `iosClientId` and avoids confusion for developers following the API docs on pub.dev.
Fixes #13519.
> docs(firebase_core): correct androidClientId docs (iOS-only → Android-only)

- packages/firebase_app_check/firebase_app_check/example/lib/main.dart
- packages/firebase_app_check/firebase_app_check/lib/src/firebase_app_check.dart
- packages/firebase_app_check/firebase_app_check_platform_interface/lib/src/method_channel/utils/provider_to_string.dart
- packages/firebase_app_check/firebase_app_check_platform_interface/test/method_channel_tests/utils/provider_to_string_test.dart
- packages/firebase_data_connect/firebase_data_connect/example/lib/main.dart
- tests/integration_test/firebase_app_check/firebase_app_check_e2e_test.dart
Fixes https://github.com/firebase/flutterfire/issues/17738 …
> fix(app_check): Deprecate androidProvider and appleProvider parameters in activate method
