- docs/database/lists-of-data.md
> docs(database): Correct orderByChild() snippet

- docs/analytics/_events.md
- docs/analytics/_user-properties.md
> docs(analytics): Sync changes from firebase.google.com

- tests/integration_test/e2e_test.dart
- tests/integration_test/firebase_auth/firebase_auth_e2e_test.dart
- tests/integration_test/firebase_auth/firebase_auth_instance_e2e.dart
- tests/integration_test/firebase_auth/firebase_auth_user_e2e.dart
- tests/integration_test/firebase_auth/test_utils.dart
> test(firebase_auth): migrate tests to `integration_test` package

- packages/firebase_crashlytics/firebase_crashlytics/example/ios/Flutter/AppFrameworkInfo.plist
- packages/firebase_crashlytics/firebase_crashlytics/example/ios/Podfile
- packages/firebase_crashlytics/firebase_crashlytics/example/ios/Runner.xcodeproj/project.pbxproj
- packages/firebase_crashlytics/firebase_crashlytics/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- packages/firebase_crashlytics/firebase_crashlytics/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/firebase_crashlytics/firebase_crashlytics/example/ios/Runner/Info.plist
- packages/firebase_crashlytics/firebase_crashlytics/example/lib/firebase_options.dart
As described in #8988 I was not able to run the example app because a `[core/duplicate-app]` is instantly thrown. I found that the reason for this was the [`GoogleServices.json`](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/example/ios/GoogleService-Info.plist) had a different configuration than the Dart only config in [`firebase_options.dart`](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/example/lib/firebase_options.dart). I pasted the configuration from the `GoogleServices.json` because in this file was the bundle id correct (this was not the case in the `firebase_options.dart`).
Additionally, I also added all the files that changed when just building the app for iOS with …
> fix(firebase_crashlytics): `[core/duplicate-app]` exception when running the example

- packages/cloud_firestore_odm/cloud_firestore_odm/example/build.yaml
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/integration.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/integration.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/movie.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/pubspec.yaml
- packages/cloud_firestore_odm/cloud_firestore_odm/example/test_driver/collection_reference_test.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/build.yaml
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/build.yaml
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/model.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/simple.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/pubspec.yaml
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/collection_generator.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/templates/collection_reference.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/validator_generator.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/pubspec.yaml
fixes https://github.com/firebase/flutterfire/issues/8296
> feat(cloud_firestore_odm): add support for json_serializable's field rename/property ignore

- tests/integration_test/e2e_test.dart
- tests/integration_test/firebase_dynamic_links/firebase_dynamic_links_e2e_test.dart
> test(firebase_dynamic_links): migrate to `integration_test` package

- packages/cloud_firestore/cloud_firestore/example/ios/Podfile
- packages/cloud_firestore/cloud_firestore/example/macos/Podfile
- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
- tests/ios/Podfile
- tests/macos/Podfile
> feat: Bump Firebase iOS SDK to 9.3.0

- docs/auth/manage-users.md
I corrected a typo in the documentation.
- [ x] No, this is *not* a breaking change. …
> docs(firebase_auth): "apple.com" provider name typo in docs

- packages/firebase_core/firebase_core/android/gradle.properties
> feat: bump Firebase Android SDK to 30.3.0

- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
- packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
Add other providers to MFA
[Flutter Style …
> feat(auth): add all providers available to MFA

- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
Error on the interop for Firestore TransactionOptions
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTIN …
> fix(firestore, web): fix interop on TransactionOptions

- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/validator_generator.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/pubspec.yaml
> chore: Bump analyzer version to ^4.3.0 to remove the usage of deprecated feature

- packages/firebase_storage/firebase_storage_web/lib/src/interop/storage.dart
- packages/firebase_storage/firebase_storage_web/lib/src/interop/storage_interop.dart
see title
fixes https://github.com/firebase/flutterfire/issues/9203
> fix(storage, web): fix UploadTask by fixing TaskEvent Web Interop

- packages/cloud_firestore_odm/doc/defining-models.md
> docs: Mention the need for createFieldMap

- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
See title 
Fixes https://github.com/firebase/flutterfire/issues/9210
> fix(auth, android): fix crash on Android where detaching from engine was not properly resetting the Pigeon handler

- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/integration/query.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/lib/cloud_firestore_odm.dart
Also add missing `FirestoreDocumentReferenceConverter` to `firestoreJsonConverters`
fixes #9232 …
> fix: Correctly type `firestoreJsonConverters` as `List<JsonConverter>`  instead of `List<Object>`

- packages/firebase_auth/firebase_auth/lib/src/user.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_user.dart
See title.
fixes https://github.com/firebase/flutterfire/issues/8349
> docs(firebase_auth): update `getIdTokenResult` inline documentation to be explicit about token behaviour

- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/collection_generator.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/templates/query_reference.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/validator_generator.dart
> fix(odm): replace deprecated elements from analyzer

- packages/firebase_core/firebase_core/android/gradle.properties
> feat: Bump Firebase android SDK to 30.3.2

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: Bump Firebase iOS SDK to 9.4.0

- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/validator_generator.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/pubspec.yaml
- tests/integration_test/firebase_dynamic_links/firebase_dynamic_links_e2e_test.dart
- tests/integration_test/firebase_messaging/firebase_messaging_e2e_test.dart
- tests/pubspec.yaml
7ba3141ecde739eef94eb677abd9b0a1f905aa1c has broken the CI. This PR should fix it.
ToDo: …
> ci: fix CI for branch `migrate-to-integration-tests`

- packages/firebase_crashlytics/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/FlutterFirebaseCrashlyticsPlugin.java
- packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart
- packages/firebase_crashlytics/firebase_crashlytics/lib/src/utils.dart
- packages/firebase_crashlytics/firebase_crashlytics/test/firebase_crashlytics_test.dart
- packages/firebase_crashlytics/firebase_crashlytics_platform_interface/lib/src/method_channel/method_channel_crashlytics.dart
- packages/firebase_crashlytics/firebase_crashlytics_platform_interface/lib/src/platform_interface/platform_interface_crashlytics.dart
- packages/firebase_crashlytics/firebase_crashlytics_platform_interface/test/method_channel_tests/method_channel_crashlytics_test.dart
> feat(crashlytics, android): Send Flutter Build Id to Crashlytics to get --split-debug-info working 

- packages/firebase_app_check/firebase_app_check/example/lib/main.dart
> feat(app_check, web): update the example app with webRecaptcha in activate button

- docs/app-check/default-providers.md
- docs/auth/federated-auth.md
- docs/cloud-messaging/client.md
- docs/cloud-messaging/first-message.md
- docs/cloud-messaging/receive.md
- docs/cloud-messaging/topic-messaging.md
- docs/database/lists-of-data.md
- docs/database/offline-capabilities.md
- docs/database/read-and-write.md
- docs/database/start.md
- docs/database/structure-data.md
- docs/dynamic-links/create.md
- docs/dynamic-links/receive.md
- docs/perf-mon/get-started.md
- docs/storage/create-reference.md
- docs/storage/delete-files.md
- docs/storage/download-files.md
- docs/storage/file-metadata.md
- docs/storage/handle-errors.md
- docs/storage/list-files.md
- docs/storage/start.md
- docs/storage/upload-files.md
Syncing with Google repo. Just housekeeping, nothing of substance except some reorganization of App Check …
> docs: Sync docs with Google repo

- packages/firebase_auth/firebase_auth/example/lib/main.dart
I think it should be "constraints" instead of "constraines". …
> chore(firebase_auth): fix typo "constraines" in example

- packages/cloud_firestore/cloud_firestore/example/ios/Podfile
- packages/cloud_firestore/cloud_firestore/lib/cloud_firestore.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_firestore.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_load_bundle_task.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/utils/firestore_message_codec.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_firestore.dart
- packages/cloud_functions/cloud_functions/lib/cloud_functions.dart
- packages/firebase_auth/firebase_auth/example/test_driver/instance_e2e.dart
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/lib/main.dart
- packages/firebase_storage/firebase_storage/lib/firebase_storage.dart
- packages/firebase_storage/firebase_storage/test/mock.dart
- tests/ios/Flutter/AppFrameworkInfo.plist
- tests/ios/Podfile
- tests/test_driver/cloud_functions/cloud_functions_e2e.dart
- tests/test_driver/firebase_auth/firebase_auth_instance_e2e.dart
- tests/test_driver/firebase_storage/reference_e2e.dart
see title 
fix https://github.com/firebase/flutterfire/issues/9473
> ci: fix CI issues related to Flutter 3.3 release

- docs/auth/federated-auth.md
- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
- packages/firebase_auth/firebase_auth/example/ios/Runner.xcodeproj/project.pbxproj
- packages/firebase_auth/firebase_auth/example/lib/auth.dart
- packages/firebase_auth/firebase_auth/lib/firebase_auth.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/firebase_auth_platform_interface.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/providers/yahoo_auth.dart
- packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
> feat(auth): add Yahoo as provider for iOS, Android and Web

- docs/auth/federated-auth.md
- packages/firebase_auth/firebase_auth/example/ios/Runner.xcodeproj/project.pbxproj
- packages/firebase_auth/firebase_auth/example/ios/Runner/Info.plist
- packages/firebase_auth/firebase_auth/example/lib/auth.dart
- packages/firebase_auth/firebase_auth/example/pubspec.yaml
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/utils/convert_auth_provider.dart
The recommended way of sign in with Twitter was unsafe (since it was exposing secrets to the front) …
> feat(auth): add Twitter login for Android, iOS and Web

- packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_multi_factor.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_multi_factor.dart
Currently trying to parse a number instead of the ISO String  …
> fix(auth, web): fix enrollementTimestamp parsing on Web

- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebasePermissionManager.java
See title.
fixes https://github.com/firebase/flutterfire/issues/9429
fixes https://github.com/firebase/flutterfire/issues/9430
[CLA]: …
> fix(firebase_messaging, android): ensure only messaging permission request is processed

- packages/cloud_firestore_odm/cloud_firestore_odm_generator/pubspec.yaml
Some changes were made recently to fix a deprecated warning, but the pubspec.yaml didn't follow.
fixes https://github.com/firebase/flutterfire/issues/9390
[CLA]: …
> fix: bump minimum analyzer version

- packages/firebase_auth/firebase_auth/lib/src/recaptcha_verifier.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_firebase_auth.dart
I think it should be "appearance" instead of "apperance". …
> docs(firebase_auth): fix typo "apperance" in `platform_interface_firebase_auth.dart`

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
- packages/firebase_performance/firebase_performance/example/ios/Podfile
> feat: Bump Firebase iOS SDK to 9.5.0

- packages/firebase_performance/firebase_performance/example/android/app/src/main/AndroidManifest.xml
> chore(performance): fix android launch for Firebase Performance

- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/app/src/main/AndroidManifest.xml
> chore(dynamic-links): fix android launch for Dynamic Links example app

- docs/auth/federated-auth.md
> feat(auth): add documentation for Play Game Sign-In

- packages/firebase_analytics/firebase_analytics/android/src/main/java/io/flutter/plugins/firebase/analytics/FlutterFirebaseAnalyticsPlugin.java
Unchecked casts have sufficient conditional checks to allow suppression of warnings.
closes #8575
> fix(firebase_analytics, android): suppress unchecked warnings that aren't necessary

- packages/firebase_core/firebase_core/lib/src/firebase.dart
see title.
closes https://github.com/firebase/flutterfire/issues/9400
> docs(firebase_core): update inline documentation on `initializeApp()` behaviour

- docs/auth/federated-auth.md
- packages/firebase_auth/firebase_auth/lib/src/user.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_user.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_user.dart
> feat(auth): add `linkWithRedirect` to the web

- docs/cloud-messaging/receive.md
> docs(fcm): add documentation for localized strings in notifications

- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/integration.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/integration/freezed.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/integration/query.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/movie.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/test_driver/document_reference_test.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/lib/src/firestore_reference.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/freezed.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/simple.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/templates/document_reference.dart
> feat(odm): Add transaction utilities to the ODM

- packages/cloud_firestore/cloud_firestore/example/test_driver/load_bundle_e2e.dart
- packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
Necessary for the ODM bundle support
> feat: Add namedQueryWithConverterGet

- packages/firebase_core/firebase_core_web/README.md
see title 
closes https://github.com/firebase/flutterfire/issues/9082
> chore(core,web): fix broken link to documentation

- packages/firebase_core/firebase_core/android/gradle.properties
- packages/firebase_messaging/firebase_messaging/android/build.gradle
> feat!: Firebase android SDK BOM `31.0.0`

- packages/firebase_ui_auth/example/test_driver/firebase_ui_auth_e2e.dart
- packages/firebase_ui_auth/example/test_driver/layout_test.dart
- packages/firebase_ui_auth/lib/src/widgets/reauthenticate_dialog.dart
Fixes overflow on smaller screens when keyboard is visible
Closes #9198
> fix(ui_auth): fix reauthenticate dialog overflow

- packages/firebase_ui_auth/doc/migration.md
> chore(ui): add migration guide

- packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
> feat: Firebase JS web SDK version: `9.11.0`

- packages/firebase_analytics/firebase_analytics_web/pubspec.yaml
> chore: bump analytics web flutter version minimum to `1.20.0`

- packages/firebase_auth/firebase_auth_web/pubspec.yaml
> chore: bump auth web flutter minimum version

- packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
- packages/cloud_functions/cloud_functions_web/pubspec.yaml
- packages/firebase_core/firebase_core_web/pubspec.yaml
- packages/firebase_messaging/firebase_messaging_web/pubspec.yaml
> chore: bump flutter minimum version for web packages

- packages/firebase_ui_auth/example/pubspec.yaml
- packages/firebase_ui_auth/pubspec.yaml
- packages/firebase_ui_database/example/pubspec.yaml
- packages/firebase_ui_database/pubspec.yaml
- packages/firebase_ui_firestore/example/pubspec.yaml
- packages/firebase_ui_localizations/example/pubspec.yaml
- packages/firebase_ui_oauth/example/pubspec.yaml
> fix(ui): bump dependencies

- packages/flutterfire_ui/README.md
Puts a deprecation warning and migration guide on `flutterfire_ui` readme.
> docs(ui): add deprecation warning and migration guide for flutterfire_ui

- packages/firebase_ui_auth/README.md
> docs(ui_auth): update platform support matrix

- packages/firebase_core/firebase_core/android/gradle.properties
> feat: Firebase android SDK BOM - `31.0.1`

- CONTRIBUTING.md
- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
- packages/cloud_firestore/cloud_firestore/lib/src/aggregate_query.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_aggregate_query.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
closes https://github.com/firebase/flutterfire/issues/9812 …
> fix(firestore, web): fix aggregated count to use the current query and not only the collection on Web

- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_user.dart
```javascript
// On firebase-admin (server)
console.log(user.metadata.creationTime); // Mon, 25 Oct 2022 10:17:31 GMT
```
```dart
// As currently implemented
print('${DateFormat('EEE, d MMM yyyy HH:mm:ss', 'en_US').parse(_webUser.metadata.creationTime!)}'); // 2022-10-25 09:17:31.699
// Fix
print('${DateFormat('EEE, d MMM yyyy HH:mm:ss', 'en_US').parse(_webUser.metadata.creationTime!, true)}'); // 2022-10-25 10:17:31.699Z
```
WEB support to complement PR #9248 
Fixes #9162 in WEB …
> fix(firebase_auth): use correct UTC time from server for `_webUser.metadata.creationTime` & `_webUser.metadata.lastSignInTime`

- packages/cloud_firestore_odm/cloud_firestore_odm_generator/pubspec.yaml
> fix: Upgrade analyzer version.

- packages/cloud_firestore_odm/cloud_firestore_odm/example/pubspec.yaml
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/collection_data.dart
> fix: Improve error handling if a collection and the associated model are defined in separate files.

- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundExecutor.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundService.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java
Moving to FlutterEngineGroup is more performant and allows for a shared heap
#9816
> feat(messaging): use FlutterEngineGroup to improve performance of background handlers

- packages/firebase_crashlytics/firebase_crashlytics/example/macos/Podfile
- packages/firebase_crashlytics/firebase_crashlytics/example/macos/Runner.xcodeproj/project.pbxproj
> chore(crashlytics): update Crashlytics example app to run with the latest SDK version

- docs/cloud-messaging/first-message.md
- docs/crashlytics/_get-started.md
- docs/in-app-messaging/_get-started.md
> docs: sync docs from Google repo

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
see title.
closes https://github.com/firebase/flutterfire/issues/9787
> feat: Firebase iOS SDK version `10.1.0`

- .github/workflows/all_plugins.yaml
- .github/workflows/e2e_tests.yaml
- .github/workflows/firebase_firestore.yaml
- .github/workflows/firebase_firestore_odm.yaml
- .github/workflows/firebase_performance.yaml
- .github/workflows/publish_old_docs.yaml
- .github/workflows/scripts/install-flutter.sh
- .github/workflows/scripts/install-tools.sh
- packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m
Updating the CI to remove custom scripts and use GitHub Actions for Flutter and Melos instead 
Also updating clang format to 14 to fix an issue with a difference between local and ci formatting  …
> chore: Update CI to use GitHub Actions

- packages/firebase_dynamic_links/firebase_dynamic_links/example/lib/main.dart
> chore(dynamic-link): update Dynamic link for example app, the previous is now used for test app

- .github/workflows/e2e_tests.yaml
- .github/workflows/firebase_firestore.yaml
- .github/workflows/firebase_firestore_odm.yaml
- .github/workflows/firebase_performance.yaml
https://github.com/actions/runner-images/issues/6384
https://github.com/firebase/flutterfire/actions/runs/3435741886 …
> ci: update to latest version of setup-java and macos

- packages/firebase_database/firebase_database/lib/src/database_event.dart
fixes https://github.com/firebase/flutterfire/issues/7100 https://github.com/firebase/flutterfire/issues/9837
[Flutter …
> fix(database): cache the result of event.snapshot to be able to compare the value

- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
Fixes https://github.com/firebase/flutterfire/issues/9877 …
> fix(auth, ios): fix `reauthenticateWithProvider` on iOS with Sign In With Apple that would throw a linked exception

- docs/dynamic-links/receive.md
See title.
closes https://github.com/firebase/flutterfire/issues/9465
> docs(dynamic-links): SHA-256 key requirement for android

- packages/firebase_ui_auth/doc/migration.md
- packages/firebase_ui_auth/doc/navigation.md
- packages/firebase_ui_auth/doc/theming.md
- packages/firebase_ui_auth/lib/src/auth_state.dart
Additional docs fix for EmailAuthProvider.
https://github.com/firebase/flutterfire/issues/9923
https://github.com/firebase/flutterfire/pull/9925
[CLA]: …
> fix(ui_auth): fix docs typo for EmailAuthProvider.

- packages/firebase_ui_auth/pubspec.yaml
- packages/firebase_ui_oauth/pubspec.yaml
`desktop_viewbview_auth: 0.0.10` has stub implementations for ios, android and web, so this should make pub be able to figure out that `firebase_ui_auth` supports all platforms. …
> fix(ui_auth): upgrade dependency to fix platform support for firebase_ui_auth

- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundExecutor.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundService.java
- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java
Reverts firebase/flutterfire#9867
closes https://github.com/firebase/flutterfire/issues/9932 https://github.com/firebase/flutterfire/issues/9912
> fix(messaging): Revert "feat(messaging): use FlutterEngineGroup to improve performance of background handlers"

- packages/firebase_dynamic_links/firebase_dynamic_links/pubspec.yaml
- packages/firebase_performance/firebase_performance_platform_interface/pubspec.yaml
> chore: update plugin_platform_interface dependencies

- packages/firebase_core/firebase_core/android/gradle.properties
Hello!
References
- https://firebase.google.com/support/release-notes/android#bom_v31-0-3 …
> feat: bump Firebase Android SDK to `31.0.3`

- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/ios/Flutter/AppFrameworkInfo.plist
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/ios/Podfile
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/ios/Runner.xcodeproj/project.pbxproj
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/ios/Runner/Info.plist
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/macos/Podfile
- packages/firebase_in_app_messaging/firebase_in_app_messaging/ios/Classes/FirebaseInAppMessagingPlugin.m
Prevent suppress variable from being converted to true or YES.
This change grabs the object key for "suppress" and assigns it to the boolean value that is was passed in as.
In App Messages on iOS were continually being suppressed even after turning off suppression await firebaseIam.setMessagesSuppressed(true);.
#9957 …
> fix(in_app_messaging): in app messages were suppressed on iOS

- packages/cloud_firestore_odm/cloud_firestore_odm/example/integration_test/freezed_test.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/integration.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/integration/freezed.freezed.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/integration/freezed.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/integration/named_query.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/integration/query.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/movie.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/freezed.freezed.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/freezed.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test/lib/simple.g.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/templates/document_reference.dart
> fix: a bug where the ODM does not respect JSON case renaming

- melos.yaml
> chore(firebase_ui): add aggregate changelog config

- packages/firebase_ui_auth/example/ios/Flutter/AppFrameworkInfo.plist
- packages/firebase_ui_auth/example/ios/Podfile
- packages/firebase_ui_auth/example/ios/Runner.xcodeproj/project.pbxproj
- packages/firebase_ui_auth/example/ios/Runner.xcworkspace/contents.xcworkspacedata
> chore: update firebase_ui_auth example

- packages/firebase_ui_auth/lib/src/providers/auth_provider.dart
> fix(ui_auth): fix OAuth providers on RegisterScreen

- melos.yaml
> chore: update melos yaml

- packages/firebase_ui_auth/lib/src/screens/register_screen.dart
> fix(ui_auth): allow to pass actions to the RegisterScreen

- packages/firebase_messaging/firebase_messaging/example/android/app/google-services.json
- packages/firebase_messaging/firebase_messaging/example/ios/Runner.xcodeproj/project.pbxproj
- packages/firebase_messaging/firebase_messaging/example/ios/Runner/GoogleService-Info.plist
- packages/firebase_messaging/firebase_messaging/example/ios/firebase_app_id_file.json
- packages/firebase_messaging/firebase_messaging/example/lib/firebase_options.dart
- packages/firebase_messaging/firebase_messaging/example/macos/firebase_app_id_file.json
part of https://github.com/firebase/flutterfire/issues/9643 …
> chore(messaging): move example app to "flutterfire-e2e-tests" Firebase project

- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
> feat(auth): improve error message when user cancels a sign in with a provider

- docs/dynamic-links/receive.md
> docs(dynamic_link): improve documentation regarding custom domains

- packages/firebase_storage/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FlutterFirebaseStorageTask.java
> fix(storage, android): fix concurrency issue

- packages/firebase_storage/firebase_storage/ios/Classes/FLTFirebaseStoragePlugin.m
> fix(storage, ios): fix usage of storage plugin with an isolate

- packages/firebase_dynamic_links/firebase_dynamic_links/ios/Classes/FLTFirebaseDynamicLinksPlugin.m
> fix(dynamic_links, iOS): fix an issue where the status of the dynamic link was not properly reported

- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart
My team detected the following error logs while using this plugin.
```
_TypeError
type 'Null' is not a subtype of type 'String'
method_channel_firebase_auth.dart in MethodChannelFirebaseAuth.verifyPhoneNumber.<fn> at line 660 within firebase_auth_platform_interface
```
↓
https://github.com/firebase/flutterfire/blob/master/packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart#L660
Apparently, ```details['code']``` is sometimes null, and ```code``` is a non-null definition, so we need to do a good null check.
*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to …
> fix(firebase_auth_platform_interface): ```details['code']``` null check

- packages/firebase_database/firebase_database/lib/ui/firebase_list.dart
> refactor(database): remove a deprecated FallThroughError

- packages/firebase_ui_firestore/test/table_builder_test.dart
> chore(ui_firestore): mock Collection#snapshots()

- packages/_flutterfire_internals/lib/src/exception.dart
- packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestoreUtils.m
> fix(cloud_firestore): propagate COLLECTION_GROUP_ASC index error message

- packages/firebase_auth/firebase_auth_web/pubspec.yaml
- packages/firebase_ui_localizations/pubspec.yaml
See https://github.com/dart-lang/intl/issues/522.
Rev the version of `package:intl`, see attached issue.
https://github.com/dart-lang/intl/issues/522
[CLA]: …
> chore(firebase_auth): Rev intl version

- packages/cloud_firestore_odm/cloud_firestore_odm/README.md
> docs: Update ODM doc link

- packages/firebase_auth/firebase_auth_web/pubspec.yaml
- packages/firebase_ui_localizations/pubspec.yaml
Reverts firebase/flutterfire#10157
> chore: Revert "chore(firebase_auth): Rev intl version"

- packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
> feat: bump Firebase JS SDK to 9.15

- packages/_flutterfire_internals/pubspec.yaml
> fix(core): remove unused libs from _flutterfire_internals

- packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestorePlugin.m
> fix(firestore, ios): fix crash that could occur when using transactions

- packages/firebase_ui_auth/lib/src/views/login_view.dart
*I noticed this issue when attempting to utilize the SignInScreen on my personal app. When passing in the oauthButtonVariant of icon, the oauth buttons would return in a row including their text causing an overflow. The ideal behavior is to return the buttons in a row without their text. In order to fix this issue, we need to fully pass in the users variable down through each widget; in this case, we only missed passing the parameter in the LoginView.*
*I did not find any related issue for this bug.*
There were a few unrelated failures when running the …
> fix(firebase_ui_auth): Fixed icon only oauth variant such that the oauth buttons are displayed in a row without text

- packages/firebase_ui_auth/doc/providers/phone.md
I corrected the title on `phone.md`. The docs incorrectly referred to the provider as "Firebase UI _Email_ provider" rather than "Firebase UI _Phone_ provider"
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes ([x]).
This will ensure a smooth and quick review process. Updating the pubspec.yaml and changelogs is not required.
> docs(firebase_ui): Corrected title on phone.md

- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
> fix(auth, android): fix a null pointer exception that could occur when removing an event listener

- packages/cloud_firestore/cloud_firestore/example/integration_test/second_app_e2e.dart
closes https://github.com/firebase/flutterfire/issues/9360
> test(firestore): reintegrate failing test

- packages/firebase_ui_auth/lib/src/screens/phone_input_screen.dart
- packages/firebase_ui_auth/lib/src/widgets/phone_input.dart
> fix(ui_auth): fix PhoneInputScreen layout

- packages/firebase_ui_auth/README.md
Fixed a typo in the Firebase UI Auth readme.
I didn't make an issue for this.
> docs(ui_auth): fix typo in "platform"

- docs/auth/passing-state-in-email-actions.md
> docs: Fix typo in passing-state-in-email-actions

- docs/analytics/_events.md
see title.
closes https://github.com/firebase/flutterfire/issues/10270
> docs(analytics): document supported values for `logEvent()` & `setDefaultEventParameters()`

- packages/firebase_ui_auth/doc/README.md
*Fixed the syntax error in readme code snippet*
> docs(firebase_ui_auth): fix return type of example main function

- packages/firebase_auth/firebase_auth/example/lib/auth.dart
- packages/firebase_auth/firebase_auth/example/pubspec.yaml
- packages/firebase_auth/firebase_auth/example/web/index.html
> chore(auth): fix client id in auth example app

- packages/firebase_crashlytics/firebase_crashlytics/example/ios/Podfile
- packages/firebase_crashlytics/firebase_crashlytics/example/ios/Runner.xcodeproj/project.pbxproj
> chore(crashlytics, ios): update `Podfile` & duplicate service file path so example runs

- packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestoreWriter.m
> fix(firestore, ios): fix an issue when removing a value that didn't exist in ServerTimestampBehavior map

- packages/firebase_core/firebase_core/android/gradle.properties
> feat: bump Firebase Android SDK to `31.2.0`

- packages/firebase_performance/firebase_performance/android/src/main/java/io/flutter/plugins/firebase/performance/FlutterFirebasePerformancePlugin.java
See title.
Part of https://github.com/firebase/flutterfire/issues/8073
> refactor(performance, android): replace deprecated API: `Tasks.call()`

- .github/dependabot.yml
- .github/workflows/all_plugins.yaml
- .github/workflows/e2e_tests.yaml
- .github/workflows/firebase_firestore.yaml
- .github/workflows/firebase_firestore_odm.yaml
- .github/workflows/firebase_performance.yaml
- .github/workflows/pr_title.yaml
- .github/workflows/publish_old_docs.yaml
And add dependabot configuration
> chore: update CI references to use SHA versions

- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
> test(firestore): add tests for startAfter without converter

- packages/firebase_storage/firebase_storage/pubspec.yaml
Adds `/` in homepage url in `pubspec.yaml` to get response status `200`
fixes #10439
> fix(firebase_storage): broken homepage link in pubspec.yaml

- docs/database/lists-of-data.md
According to Flutter, support for special unicode character `\u{0000}` will not be supported.
closes #9587 
> docs(database): add documentation about special unicode characters

- packages/firebase_core/firebase_core/pubspec.yaml
> chore(firebase_core): updated homepage link in pubspec.yaml to new docs page

- docs/cloud-messaging/receive.md
see title.
closes https://github.com/firebase/flutterfire/issues/10318
> docs(messaging): note on pragma annotation - `@pragma('vm:entry-point')` for tree shaking

- packages/firebase_messaging/firebase_messaging/example/lib/token_monitor.dart
- packages/firebase_messaging/firebase_messaging/example/web/index.html
See title.
closes https://github.com/firebase/flutterfire/issues/9335
> chore(messaging): update firebase_messaging example app. No more exceptions in console.

- packages/cloud_firestore/cloud_firestore/example/integration_test/cloud_firestore_e2e_test.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/collection_reference_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/document_change_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/document_reference_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/field_value_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/geo_point_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/instance_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/load_bundle_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/second_app_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/snapshot_metadata_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/timestamp_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/transaction_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/write_batch_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/pubspec.yaml
> ci(firestore, web): fix firestore CI

- packages/cloud_firestore/cloud_firestore_web/lib/src/utils/encode_utility.dart
Should only review https://github.com/firebase/flutterfire/pull/10466/commits/321aec8cc4f08668100f24fb8ce11cf43b5a64a7
Follow up on https://github.com/firebase/flutterfire/pull/10461 …
> fix(firestore,web): fix a codec issue with Iterable

- docs/setup/_setup_main.md
- packages/firebase_core/firebase_core/example/web/index.html
- packages/firebase_core/firebase_core_web/lib/firebase_core_web.dart
- packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart
- packages/firebase_core/firebase_core_web/lib/src/interop/js.dart
- packages/firebase_core/firebase_core_web/test/firebase_core_tt_test.dart
- packages/firebase_core/firebase_core_web/test/firebase_core_web_test.dart
- packages/firebase_core/firebase_core_web/test/tools.dart
> feat(core): support TrustedType

- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
Even with https://github.com/firebase/flutterfire/pull/10461 some tests do not run on [CI](https://github.com/firebase/flutterfire/actions/runs/4192055245/jobs/7267157551).
The test testing this behavior was only failing locally.
closes #10475  #10478 …
> fix(firestore, web): fix an issue in the update method using `FieldValue.arrayUnion` or `Map`

- packages/firebase_core/firebase_core/android/gradle.properties
See title 
Could help with #10490
> feat: bump Firebase Android SDK to 31.2.2

- .github/workflows/all_plugins.yaml
@Lyokone and I have decided to make this a manual step for now. There's no way of getting it to run on the CI successfully. If you lower the Flutter version used (3.3.0), it will fail due to a failed version constraint. See https://github.com/firebase/flutterfire/actions/runs/4223880879/jobs/7334133477
If you run on the latest stable Flutter version (>3.7.x), it will fail because the `flutter publish --dry-run` ignores the pubspec overrides. I've separated the action and made a note to explain what to do when this test fails. It will only fail I believe, when there's a change to platform interface code so it won't happen for each PR.
*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of …
> ci: separate pub dry run command, left a note explaining what to do in the event it fails

- docs/dynamic-links/receive.md
See title.
https://github.com/firebase/flutterfire/issues/9469
> docs(dynamic-links): warn users about enabling deep linking in their Flutter app

- .github/workflows/e2e_tests.yaml
> ci: fixed android e2e CI. Emulator failing to boot.

- packages/firebase_auth/firebase_auth/example/ios/Runner.xcodeproj/project.pbxproj
- packages/firebase_auth/firebase_auth/example/ios/Runner/Info.plist
- packages/firebase_auth/firebase_auth/example/ios/Runner/Runner.entitlements
- packages/firebase_auth/firebase_auth/example/lib/auth.dart
- packages/firebase_auth/firebase_auth/example/pubspec.yaml
More information here: https://firebase.google.com/docs/auth/ios/multi-factor#using_silent_notifications …
> chore(auth): update the example to offer the choice of using silent verification instead of Recaptcha

- .github/workflows/all_plugins.yaml
- .github/workflows/e2e_tests.yaml
- .github/workflows/firebase_firestore.yaml
- .github/workflows/firebase_firestore_odm.yaml
- .github/workflows/firebase_performance.yaml
- melos.yaml
> ci: update melos to v3 for Firestore and ODM

- packages/firebase_performance/firebase_performance/android/src/main/java/io/flutter/plugins/firebase/performance/FlutterFirebasePerformancePlugin.java
> fix(performance, android): fix NullPointerException errors and remove suppressed warnings

- packages/firebase_storage/firebase_storage/example/lib/main.dart
Now is the "+" button visible :)
Demo:
| Before | After |
|-|-|
| ![image](https://user-images.githubusercontent.com/24459435/223838405-8a3d1567-1354-49f2-aaba-6de48aa68f23.png) | ![image](https://user-images.githubusercontent.com/24459435/223840103-7772ac2a-92e7-49bf-ad29-9197f3ca860f.png) |
https://zapp.run/edit/firebasestorage-11015-z4ba06bq4bb0?entry=lib/main.dart&file=lib/main.dart
Closes #10574  …
> chore(firebase_storage): disable "debug" banner for example to make the "+" button more visible

- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/utils/exception.dart
Currently cannot be tested since we cannot activate this feature on the emulator.
The error code is properly returned on Web. But is not correctly parsed on iOS (it's hidden in a details object), and is not returned on Android (only available in a String).
fix #10589  …
> feat(auth): improve error handling when using beforeSignIn functions blocks sign in

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump Firebase iOS SDK `10.6.0`

- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_firestore.dart
> docs(firestore): fix a typo in Stream

- packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
> feat: bump Firebase JS SDK to `9.18.0`

- packages/cloud_functions/cloud_functions/lib/src/firebase_functions.dart
> docs(functions): fix an error in the documentation of Cloud Functions

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump Firebase iOS SDK to `10.7.0`

- packages/firebase_core/firebase_core/android/gradle.properties
> feat: bump Firebase Android SDK to 31.2.3

- packages/firebase_core/firebase_core/android/gradle.properties
> feat: bump Firebase Android SDK to 31.3.0

- docs/remote-config/_get-started.md
- packages/firebase_remote_config/firebase_remote_config/android/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfig/FirebaseRemoteConfigPlugin.java
- packages/firebase_remote_config/firebase_remote_config/example/ios/Runner.xcodeproj/project.pbxproj
- packages/firebase_remote_config/firebase_remote_config/example/ios/Runner/Info.plist
- packages/firebase_remote_config/firebase_remote_config/example/lib/home_page.dart
- packages/firebase_remote_config/firebase_remote_config/example/lib/main.dart
- packages/firebase_remote_config/firebase_remote_config/ios/Classes/FLTFirebaseRemoteConfigPlugin.h
- packages/firebase_remote_config/firebase_remote_config/ios/Classes/FLTFirebaseRemoteConfigPlugin.m
- packages/firebase_remote_config/firebase_remote_config/lib/firebase_remote_config.dart
- packages/firebase_remote_config/firebase_remote_config/lib/src/firebase_remote_config.dart
- packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/firebase_remote_config_platform_interface.dart
- packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/method_channel/method_channel_firebase_remote_config.dart
- packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/platform_interface/platform_interface_firebase_remote_config.dart
- packages/firebase_remote_config/firebase_remote_config_platform_interface/lib/src/remote_config_update.dart
- packages/firebase_remote_config/firebase_remote_config_web/lib/firebase_remote_config_web.dart
- tests/integration_test/firebase_remote_config/firebase_remote_config_e2e_test.dart
This PR is a breaking change for Remote Config since we're removing that FirebaseRemoteConfig came with the with the ChangeNotifier mixin. 
We also add support for onConfigUpdated, web support is not ready yet on native.
Documentation has been directly copied and adapted from https://firebase.google.com/docs/remote-config/get-started?platform=android#add-real-time-listener
This will ensure a smooth …
> feat(remote-config)!: add support for `onConfigUpdated`

- README.md
Report on latest test run of security best practices
https://github.com/ossf/scorecard#what-is-scorecard
https://github.com/firebase/flutterfire/pull/10680
> chore: add OpenSSF scorecard to README

- packages/firebase_core/firebase_core/android/gradle.properties
> feat: bump Firebase Android SDK to 31.4.0

- packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java
- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/lib/main.dart
- packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestoreReader.m
- packages/cloud_firestore/cloud_firestore/lib/cloud_firestore.dart
- packages/cloud_firestore/cloud_firestore/lib/src/query.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/cloud_firestore_platform_interface.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/field_path.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/filters.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_query.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_query.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
This PR adds support for Filter as a new argument of `where()`. …
> feat(firestore): add the `Filter` class and support for the OR query

- packages/firebase_ui_localizations/README.md
- packages/firebase_ui_localizations/bin/gen_l10n.dart
- packages/firebase_ui_localizations/lib/l10n/firebase_ui_he.arb
- packages/firebase_ui_localizations/lib/src/all_languages.dart
- packages/firebase_ui_localizations/lib/src/lang/ar.dart
- packages/firebase_ui_localizations/lib/src/lang/de.dart
- packages/firebase_ui_localizations/lib/src/lang/en.dart
- packages/firebase_ui_localizations/lib/src/lang/es.dart
- packages/firebase_ui_localizations/lib/src/lang/es_419.dart
- packages/firebase_ui_localizations/lib/src/lang/fr.dart
- packages/firebase_ui_localizations/lib/src/lang/he.dart
- packages/firebase_ui_localizations/lib/src/lang/hi.dart
- packages/firebase_ui_localizations/lib/src/lang/hu.dart
- packages/firebase_ui_localizations/lib/src/lang/id.dart
- packages/firebase_ui_localizations/lib/src/lang/it.dart
- packages/firebase_ui_localizations/lib/src/lang/ja.dart
- packages/firebase_ui_localizations/lib/src/lang/ko.dart
- packages/firebase_ui_localizations/lib/src/lang/nl.dart
- packages/firebase_ui_localizations/lib/src/lang/pl.dart
- packages/firebase_ui_localizations/lib/src/lang/pt.dart
- packages/firebase_ui_localizations/lib/src/lang/ru.dart
- packages/firebase_ui_localizations/lib/src/lang/th.dart
- packages/firebase_ui_localizations/lib/src/lang/tr.dart
- packages/firebase_ui_localizations/lib/src/lang/uk.dart
- packages/firebase_ui_localizations/lib/src/lang/zh.dart
- packages/firebase_ui_localizations/lib/src/lang/zh_tw.dart
- added contributing instructions (add .arb instead of a raw dart class)
- add header_template.txt to the labels generator
- create .arb for Hebrew
none
[CLA]: …
> chore(ui_localizations): add license header and create Hebrew .arb

- docs/setup/_setup_main.md
See title.
closes https://github.com/firebase/flutterfire/issues/7365
> docs: how to ignore and load your own version of Firebase JS SDK web script

- packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
This is the output in the console:
closes #10763 
> fix(auth, web): fix support for hot reload with multiple named instances when using an emulator on Web

- packages/firebase_core/firebase_core/android/gradle.properties
> feat: bump Firebase Android SDK to 31.5.0

- packages/firebase_ui_storage/pubspec.yaml
Fixes CI: https://github.com/firebase/flutterfire/actions/runs/4700243574/jobs/8335070363 …
> chore(ui_storage): add false_secrets rule

- docs/cloud-messaging/receive.md
> docs(auth, ios): add more details to the iOS documentation on how to use ImageNotification service with Auth

- packages/firebase_ui_auth/README.md
> fix: const error

- packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
fixed the spelling of synchronized in a firestore.dart comment …
> chore(firestore): fixed comment typo in firestore.dart

- CONTRIBUTING.md
- melos.yaml
> docs: update documentation for running tests within `CONTRIBUTING.md`

- packages/firebase_ui_localizations/pubspec.yaml
- packages/firebase_ui_localizations/pubspec_overrides.yaml
This fixes compatibility with flutter beta channel
none
> fix(ui_localizations): drop intl dependency as it is not used

- packages/firebase_app_check/firebase_app_check_web/pubspec.yaml
- packages/firebase_auth/firebase_auth_web/pubspec.yaml
- packages/firebase_core/firebase_core_web/pubspec.yaml
- packages/firebase_core/firebase_core_web/test/firebase_core_web_exceptions_test.dart
- packages/firebase_core/firebase_core_web/test/firebase_core_web_test.dart
- packages/firebase_ui_auth/pubspec.yaml
- packages/firebase_ui_oauth/pubspec.yaml
- packages/firebase_ui_oauth/pubspec_overrides.yaml
- packages/firebase_ui_oauth/test/flutterfire_ui_oauth_test.dart
- packages/firebase_ui_oauth_google/pubspec.yaml
Remove cyclic dependencies in FF
[Flutter Style …
> chore: fix cyclic dependencies in the project

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump Firebase iOS SDK to 10.9.0

- packages/cloud_firestore/cloud_firestore/example/lib/main.dart
- packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
> fix(firestore): fix emulator reload on Flutter 3.10

- packages/cloud_firestore_odm/analysis_options.yaml
- packages/cloud_firestore_odm/cloud_firestore_odm/example/pubspec.yaml
- packages/cloud_firestore_odm/cloud_firestore_odm/lib/src/firestore_builder.dart
- packages/cloud_firestore_odm/cloud_firestore_odm/lib/src/firestore_reference.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/build.yaml
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/collection_generator.dart
> fix: typo in build.yaml

- .github/workflows/e2e_tests.yaml
- packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
- packages/cloud_firestore/cloud_firestore/example/integration_test/instance_e2e.dart
- packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestorePlugin.m
- packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_firestore.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_firestore.dart
- packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
Adding a static function to enable debug logging.
closes https://github.com/firebase/flutterfire/issues/10995
> feat(firestore): add the ability to enable debug logging

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump Firebase iOS SDK to `10.10.0`. Requires Xcode version >= `14.1`.

- .github/workflows/e2e_tests.yaml
- packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
> feat: bump Firebase JS SDK to `9.22.1`

- packages/cloud_firestore/cloud_firestore/example/.fvm/fvm_config.json
- packages/firebase_core/firebase_core/example/ios/Flutter/AppFrameworkInfo.plist
- packages/firebase_core/firebase_core/example/ios/Podfile
- packages/firebase_core/firebase_core/example/ios/Runner.xcodeproj/project.pbxproj
- packages/firebase_core/firebase_core/example/macos/Runner.xcodeproj/project.pbxproj
- packages/firebase_core/firebase_core/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/firebase_core/firebase_core/ios/Classes/FLTFirebaseCorePlugin.m
- tests/integration_test/firebase_core/firebase_core_e2e_test.dart
See title
closes https://github.com/firebase/flutterfire/issues/10505
> fix(core, apple): pass boolean value instead of int to `setDataCollectionDefaultEnabled()`

- packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java
- packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestoreReader.m
- packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_firestore.dart
- packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
Updated android and apple. 
See Firestore documentation for persistence: https://firebase.google.com/docs/firestore/manage-data/enable-offline#configure_offline_persistence …
> fix(firestore): update deprecated persistence API

- .github/ISSUE_TEMPLATE/---bug-report.md
The bug issue template was like:
```
1.
2.
4.
```
...
> chore: fix numbering in bug issue template

- packages/cloud_firestore_odm/README.md
This adds documentation about needing to enable of `create_field_map`
Related to 10844
> docs: Mention create_field_map installation

- docs/remote-config/_get-started.md
As you can see in #11109 you get the following error, when you following the current docs to set up `firebase_remote_config`:
```
flutter: [firebase_remote_config/internal] Failed to get installations token. Error : Error Domain=com.firebase.installations Code=0 "Underlying error: The operation couldn’t be completed. SecItemAdd (-34018)" UserInfo={NSLocalizedFailureReason=Underlying error: The operation couldn’t be completed. SecItemAdd (-34018), NSUnderlyingError=0x60000312d4a0 {Error Domain=com.gul.keychain.ErrorDomain Code=0 "SecItemAdd (-34018)" UserInfo={NSLocalizedFailureReason=SecItemAdd (-34018)}}}.
```
To fix this, you need to add the [Keychain Sharing](https://developer.apple.com/documentation/xcode/configuring-keychain-sharing) capability in XCode. This PR adds this step to the …
> docs(firebase_remote_config): add note "Keychain Sharing" capability for macOS

- packages/firebase_ui_auth/lib/src/screens/internal/multi_provider_screen.dart
> fix(ui_auth): fix ProfileScreen ignoring parent rebuilds

- packages/firebase_ui_auth/lib/src/screens/profile_screen.dart
> feat(ui_auth): allow passing custom user avatar widget

- packages/firebase_ui_auth/lib/src/widgets/internal/universal_text_form_field.dart
Fix material misspelling
@lesnitsky
> fix(ui_auth): documentation - fix material misspelling in universal_text_form_field.dart

- AUTHORS
- packages/firebase_storage/firebase_storage_web/pubspec.yaml
Updated the [http](https://pub.dev/packages/http) package to `v1.0.0`. This will make the plugin compatible with all the packages that use the latest `v1.0.0` of the http package.
Fixes #11073 …
> fix(firebase_storage): updated `firebase_storage_web` to allow  `http` package dependency range '>=0.13.0 <2.0.0'. Fixes dependency resolution.

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
Bump to latest Firebase iOS SDK. Flaky android CI needs investigating. …
> feat: bump Firebase iOS SDK to 10.11.0

- packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
> fix(auth, web): add guarding to error casting in useEmulator

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump Firebase iOS SDK to `10.12.0`

- packages/firebase_ui_oauth/lib/src/platform_oauth_sign_in_web.dart
> fix(ui_auth): fix linking OAuthProvider from ProfileScreen

- packages/firebase_core/firebase_core/android/gradle.properties
> feat: bump Firebase android SDK to `32.2.0`

- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
- packages/firebase_auth/firebase_auth/ios/Classes/Public/FLTFirebaseAuthPlugin.h
> chore: fix formatting for CI

- packages/firebase_auth/firebase_auth/example/android/build.gradle
- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/utils/exception.dart
> fix(auth): fix MFA issue where the error wouldn't be properly catched

- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/collection_data.dart
- packages/cloud_firestore_odm/cloud_firestore_odm_generator/lib/src/templates/collection_reference.dart
- packages/firebase_ui_oauth_google/lib/src/provider.dart
- packages/firebase_ui_storage/README.md
- packages/firebase_ui_storage/lib/src/lib.dart
> chore: fix some typos in docs and named arg underlying implementation for ODM.

- packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
Fixes an issue with count when using 2nd database.
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.m …
> feat: bump Firebase web JS SDK `10.1.0`

- packages/cloud_functions/cloud_functions/android/build.gradle
- packages/cloud_functions/cloud_functions/android/src/main/java/io/flutter/plugins/firebase/functions/FlutterFirebaseFunctionsPlugin.java
- packages/cloud_functions/cloud_functions/example/android/app/build.gradle
- packages/cloud_functions/cloud_functions/ios/Classes/FLTFirebaseFunctionsPlugin.m
- packages/cloud_functions/cloud_functions_platform_interface/lib/src/https_callable_options.dart
- packages/cloud_functions/cloud_functions_platform_interface/lib/src/method_channel/method_channel_https_callable.dart
- packages/cloud_functions/cloud_functions_platform_interface/test/method_channel/method_channel_https_callable_test.dart
- packages/cloud_functions/cloud_functions_web/lib/https_callable_web.dart
- packages/cloud_functions/cloud_functions_web/lib/interop/functions_interop.dart
- tests/integration_test/cloud_functions/cloud_functions_e2e_test.dart
See title.
closes https://github.com/firebase/flutterfire/issues/11388
> feat(functions): pass `limitedUseAppCheckToken` option to Cloud Function

- packages/firebase_app_installations/firebase_app_installations/ios/Classes/FirebaseInstallationsPlugin.swift
- packages/firebase_app_installations/firebase_app_installations/ios/Classes/IdChangedStreamHandler.swift
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/ios/Classes/FirebaseModelDownloaderPlugin.swift
- packages/firebase_remote_config/firebase_remote_config/example/macos/RunnerTests/RunnerTests.swift
`swiftformat` tool has updated, this PR simply runs the latest version and has formatted 4 different swift files. …
> chore: format swift files

- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
Looks like this got missed with the migration to pigeon
> fix(auth): set the tenant id on iOS `FIRAuth` instance

- .github/ISSUE_TEMPLATE/---feature-request.md
- .github/ISSUE_TEMPLATE/config.yml
As discussed, move feature requests from discussions to issues. …
> chore: move feature requests to issues

- packages/firebase_remote_config/firebase_remote_config/README.md
Removing the link to https://firebase.flutter.dev/, since it is archived.
Since the "Usage" section ended up pretty much identical to the "Getting started" section, the "Usage" section was removed. …
> docs(firebase_remote_config): Remove link with archived content from readme

- packages/firebase_dynamic_links/firebase_dynamic_links/README.md
I think it's helpful to show also the note about the deprecation in the README.md of the firebase_dynamic_links package.
...
[CLA]: …
> docs(firebase_dynamic_links): add deprecation note to README.md

- packages/firebase_auth/firebase_auth/pubspec.yaml
Updating the firebase_auth description.
Firebase Auth now also supports web and will probably support more in the future. As a result the Android and IOS mention in the description is out of date. …
> docs: firebase_auth description

- packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
> feat: bump Firebase web JS SDK `10.3.1`

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump Firebase iOS SDK `10.15.0`

- docs/cloud-messaging/receive.md
see title.
closes https://github.com/firebase/flutterfire/issues/11487
> docs(messaging, android): update requesting permissions documentation

- packages/firebase_crashlytics/firebase_crashlytics/ios/crashlytics_add_upload_symbols
related change: https://github.com/firebase/firebase-ios-sdk/pull/11867
> fix(firebase_crashlytics): update upload symbols input file

- docs/auth/email-link-auth.md
Email enumeration protection may be enabled on your Firebase project. See this [thread](https://github.com/firebase/firebase-ios-sdk/issues/11810) and this [comment](https://github.com/firebase/firebase-ios-sdk/issues/11810#issuecomment-1750523485) in particular for more details.
closes https://github.com/firebase/flutterfire/issues/11508 …
> docs(auth): email enumeration protection warning for `fetchSignInMethodsForEmail()`

- packages/firebase_app_check/firebase_app_check/README.md
*Update the documentation link for the [firebase_app_check](https://pub.dev/packages/firebase_app_check) package*
*closes #11690*
[CLA]: …
> docs: Updated documentation link in firebase_app_check README.md

- packages/cloud_firestore/cloud_firestore/windows/cloud_firestore_plugin.cpp
- packages/firebase_core/firebase_core/windows/CMakeLists.txt
Updating to 11.6.0 to get access to Filters …
> feat(firestore, windows): add Filters to windows

- packages/firebase_storage/firebase_storage_platform_interface/pubspec.yaml
> feat(storage)!: migrating to Pigeon is a breaking for firebase_storage_platform_interface

- packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
> fix(firestore, android): fix hot reload freezing the app on Android

- packages/firebase_core/firebase_core/android/gradle.properties
See title.
fixes https://github.com/firebase/flutterfire/issues/10759
> feat: bump Firebase android SDK BoM `32.5.0`

- packages/firebase_storage/firebase_storage_platform_interface/pigeons/messages.dart
> fix(storage, windows): add missing c++ generated files into pigeon template

- docs/app-check/default-providers.md
- docs/auth/email-link-auth.md
- docs/auth/federated-auth.md
- docs/cloud-messaging/client.md
- docs/cloud-messaging/receive.md
- docs/cloud-messaging/topic-messaging.md
> docs: Merge from internal repo

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: update iOS SDK to version 10.17.0

- packages/cloud_firestore_odm/cloud_firestore_odm_generator/pubspec.yaml
Bumped max allowed analyzer version to support other packages that now depend on analyzer v6.
Before I made any changes I ran `flutter test` and it's producing errors in the `cloud_firestore_odm_generator` package. I'm not sure if they are related to my dev setup or something else.
<details>
<summary>Flutter Test Error</summary>
> /Users/removed/projects/open-source/flutterfire/packages/cloud_firestore_odm/cloud_firestore_odm_generator/test/query_reference_test.dart: query does not generate utilities for getters [E]
Unsupported operation: Isolate.resolvePackageUri
dart:isolate                                                      Isolate.resolvePackageUri
package:build_resolvers/src/build_asset_uri_resolver.dart 247:31  packagePath
package:build_resolvers/src/sdk_summary.dart 53:22 …
> chore(cloud_firestore_odm_generator): bumps max analyzer support to v6

- packages/firebase_auth/firebase_auth/lib/firebase_auth.dart
- packages/firebase_auth/firebase_auth/lib/src/user.dart
> fix(auth): add proper error message when trying to access the `multifactor` object on an unsupported platform

- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart
> fix(firestore, web): fix being able to use normal Where conditions and Filter.OR together

- packages/firebase_storage/firebase_storage_platform_interface/lib/src/method_channel/method_channel_firebase_storage.dart
> feat: update code to remove warnings using Flutter 3.16

- packages/firebase_remote_config/firebase_remote_config/android/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfig/FirebaseRemoteConfigPlugin.java
> fix(remote_config, android): fix an issue that could cause a non responsive app when hot restarting an app

- docs/setup/_setup_main.md
> docs(core, web): update the instructions on how to manually import Firebase SDKS now that we are using the modular Web SDKs

- packages/firebase_crashlytics/firebase_crashlytics/example/android/app/build.gradle
- packages/firebase_crashlytics/firebase_crashlytics/example/android/build.gradle
- packages/firebase_crashlytics/firebase_crashlytics/example/ios/Flutter/AppFrameworkInfo.plist
- packages/firebase_crashlytics/firebase_crashlytics/example/ios/Runner.xcodeproj/project.pbxproj
- packages/firebase_crashlytics/firebase_crashlytics/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/firebase_crashlytics/firebase_crashlytics/example/ios/Runner/Info.plist
> chore(crashlytics): update example app so it can run without extra configuration

- packages/firebase_core/firebase_core/android/gradle.properties
> feat: bump firebase android SDK BOM to `32.6.0`

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump iOS SDK to version 10.18.0

- packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
> feat: bump JS SDK to version 10.6.0

- packages/firebase_messaging/firebase_messaging/example/macos/Runner.xcodeproj/project.pbxproj
- packages/firebase_messaging/firebase_messaging/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/firebase_messaging/firebase_messaging/example/pubspec.yaml
> chore(messaging): update example app

- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java
- packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m
- packages/firebase_core/firebase_core/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseCorePlugin.java
- packages/firebase_core/firebase_core/ios/Classes/FLTFirebaseCorePlugin.h
- packages/firebase_core/firebase_core/ios/Classes/FLTFirebaseCorePlugin.m
> feat(auth): add support for custom domains on mobile

- packages/firebase_analytics/firebase_analytics/test/firebase_analytics_test.dart
- packages/firebase_analytics/firebase_analytics_platform_interface/lib/src/analytics_event_item.dart
- packages/firebase_database/firebase_database/lib/firebase_database.dart
> fix(analytics): fix the toString method on AnalyticsEventItem to print out its content

- packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
> feat: bump JS SDK to version 10.7.0

- packages/firebase_messaging/firebase_messaging/lib/firebase_messaging.dart
- packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_notification.dart
> fix(messaging): expose the missing WebNotification object

- .github/workflows/e2e_tests.yaml
- .github/workflows/firebase_firestore_odm.yaml
- .github/workflows/scripts/functions/package-lock.json
- .github/workflows/scripts/functions/package.json
- .github/workflows/scripts/functions/tsconfig.json
- packages/firebase_messaging/firebase_messaging/example/scripts/package.json
- tests/integration_test/e2e_test.dart
> ci: update Node.JS version to 20 to be compatible with the new `firebase-tools` version

- packages/firebase_storage/firebase_storage/windows/firebase_storage_plugin.cpp
> fix(storage, windows): fix an issue where `getData` function would statically allocate memory

- AUTHORS
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_multi_factor.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/multi_factor.dart
- packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
Fix unmarshal of MultiFactorInfo for `user.multiFactor.enrolledFactors` in web plugin. Sharing the same unmarshalling logic as resolver.
[CLA]: …
> fix(auth): Fix unmarshal of MultiFactorInfo through web plugin

- packages/cloud_firestore/cloud_firestore/example/integration_test/load_bundle_e2e.dart
- packages/cloud_firestore/cloud_firestore/lib/cloud_firestore.dart
see title.
fixes https://github.com/firebase/flutterfire/issues/7722
> fix(firestore): export `LoadBundleTaskState` in `cloud_firestore`

- packages/cloud_firestore/cloud_firestore/example/integration_test/transaction_e2e.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_transaction.dart
fixes https://github.com/firebase/flutterfire/issues/12007 …
> fix(firestore): `transaction.get()` should throw `FirebaseException` on exception.

- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingBackgroundExecutor.java
possible fix for: https://github.com/firebase/flutterfire/issues/9345 …
> fix(messaging, android): possible fix to a crash occurring on android background executor

- packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
- packages/cloud_functions/cloud_functions/lib/src/firebase_functions.dart
- packages/firebase_auth/firebase_auth/lib/src/firebase_auth.dart
- packages/firebase_storage/firebase_storage/lib/src/firebase_storage.dart
closes https://github.com/firebase/flutterfire/issues/11907 …
> feat: allow users to disable automatic host mapping

- packages/firebase_auth/firebase_auth/windows/messages.g.cpp
> fix(auth, windows): fix a parsing issue of the Pigeon message on Windows for sendPasswordResetEmail

- packages/firebase_analytics/firebase_analytics/example/lib/main.dart
> chore(analytics): add a button to the example app for analytics

- packages/firebase_auth/firebase_auth/windows/firebase_auth_plugin.cpp
> feat(auth, windows): add support for creationTime and lastSignInTime

- packages/firebase_analytics/firebase_analytics/example/lib/main.dart
- packages/firebase_analytics/firebase_analytics/example/lib/tabs_page.dart
- packages/firebase_analytics/firebase_analytics/lib/observer.dart
- packages/firebase_analytics/firebase_analytics/lib/src/firebase_analytics.dart
- packages/firebase_analytics/firebase_analytics/test/firebase_analytics_test.dart
- tests/integration_test/firebase_analytics/firebase_analytics_e2e_test.dart
Fix #11035
https://github.com/firebase/flutterfire/pull/9397
#11035 
> fix(analytics): `setCurrentScreen()` was deprecated, using `logScreenView()` instead

- packages/firebase_storage/firebase_storage/lib/src/utils.dart
*Fix bug when using firebase storage emulator on Android*
* Fix #12046 
- [ x I read and followed the [Flutter Style Guide].
The current code
```dart
if (decodedUrl.contains(_firebaseStorageHost) ||
decodedUrl.contains('localhost')) {
String origin;
if (decodedUrl.contains('localhost')) {
Uri uri = Uri.parse(url);
origin = '^http?://${uri.host}:${uri.port}';
} else {
```
check for the host by using the `contains` which might be not the most efficient, instead, it …
> fix(storage, android): fix `refFromUrl()` when using firebase storage emulator. Essentially, check `10.0.2.2` domain as well.

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump firebase iOS SDK to `10.19.0`

- tests/integration_test/firebase_analytics/firebase_analytics_e2e_test.dart
> test(analytics): `getSessionId()` returns a type `int?`, allow this response in e2e test.

- packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
- packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
> fix(firestore, web): update `setSettings` to allow usage of a up-to-date persistence on web

- docs/cloud-messaging/receive.md
see title.
closes https://github.com/firebase/flutterfire/issues/11914
> docs(messaging): update firebase web messaging implementation

- packages/firebase_storage/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/FlutterFirebaseStoragePlugin.java
- packages/firebase_storage/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/TaskStateChannelStreamHandler.java
- packages/firebase_storage/firebase_storage/ios/Classes/FLTFirebaseStoragePlugin.h
- packages/firebase_storage/firebase_storage/ios/Classes/FLTFirebaseStoragePlugin.m
- packages/firebase_storage/firebase_storage/ios/Classes/FLTTaskStateChannelStreamHandler.m
- packages/firebase_storage/firebase_storage_platform_interface/lib/src/method_channel/method_channel_task.dart
- tests/integration_test/firebase_storage/task_e2e.dart
fixes https://github.com/firebase/flutterfire/issues/12008
fixes https://github.com/firebase/flutterfire/issues/11545
> fix(storage): ensure Task listeners correctly propagate exceptions and close properly.

- packages/firebase_storage/firebase_storage/windows/firebase_storage_plugin.cpp
Two fixes:
1. Use the max size passed in from user instead of artifically created `max_size`: https://github.com/firebase/flutterfire/compare/storage-12134?expand=1#diff-cd14e729c2a123769d24deb04c095c7e5c520143b9fa4508a63797ebe890fd85R406
2. Check that no error exists, and send result back to the user: https://github.com/firebase/flutterfire/compare/storage-12134?expand=1#diff-cd14e729c2a123769d24deb04c095c7e5c520143b9fa4508a63797ebe890fd85R414
fixes https://github.com/firebase/flutterfire/issues/12134
Does your PR require plugin users to manually update …
> fix(storage, windows): `getData()` crash has been fixed

- packages/cloud_firestore/cloud_firestore/example/integration_test/load_bundle_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/lib/main.dart
- packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/field_value_factory_web.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/utils/utils.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/utils/decode_utility.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/utils/encode_utility.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart
- packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
- packages/cloud_firestore/cloud_firestore_web/test/test_common.dart
- packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
- packages/firebase_core/firebase_core_web/lib/firebase_core_web.dart
- packages/firebase_core/firebase_core_web/lib/src/interop/utils/es6_interop.dart
- packages/firebase_core/firebase_core_web/lib/src/interop/utils/utils.dart
https://github.com/firebase/flutterfire/issues/12027 …
> feat(firestore, web): migrate web to js_interop to be compatible with WASM

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump iOS SDK to version `10.20.0`

- packages/firebase_core/firebase_core/android/gradle.properties
> feat: bump Android SDK to version `32.7.1`

- packages/_flutterfire_internals/lib/_flutterfire_internals.dart
- packages/_flutterfire_internals/lib/src/interop_shimmer.dart
- packages/_flutterfire_internals/pubspec.yaml
- packages/_flutterfire_internals/test/guard_test.dart
- packages/firebase_core/firebase_core_web/lib/firebase_core_web.dart
- packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart
- packages/firebase_core/firebase_core_web/lib/src/interop/app.dart
- packages/firebase_core/firebase_core_web/lib/src/interop/app_interop.dart
- packages/firebase_core/firebase_core_web/lib/src/interop/core.dart
- packages/firebase_core/firebase_core_web/lib/src/interop/core_interop.dart
> fix(core, web): fix some JS interop that were incorrectly migrated

- packages/firebase_auth/firebase_auth/example/.gitignore
- packages/firebase_auth/firebase_auth/example/lib/main.dart
- packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart
- packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
- packages/firebase_core/firebase_core/example/.gitignore
- packages/firebase_core/firebase_core_web/lib/src/interop/utils/es6_interop.dart
fixes #12237
fixes #12248
fixes #12235
fixes #12238 …
> fix(auth, web): fix null safety issue in typing JS Interop

- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_recaptcha_verifier_factory.dart
> fix(core, web): fix Recaptcha instantiation error

- packages/firebase_core/firebase_core_web/lib/firebase_core_web.dart
- packages/firebase_core/firebase_core_web/lib/src/firebase_core_web.dart
- packages/firebase_core/firebase_core_web/lib/src/interop/core_interop.dart
Reference API: https://firebase.google.com/docs/reference/js/app.firebaseoptions
fixes #12253 
> fix(core, web): fix null safety issue in typing JS Interop

- packages/cloud_firestore/cloud_firestore/example/integration_test/field_value_e2e.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/utils/utils.dart
> fix(firestore, web): fix an issue where nested object could be incorrectly decoded from JSObjects

- .github/workflows/e2e_tests.yaml
> ci: update android to ubuntu-latest runner

- .github/workflows/e2e_tests.yaml
Removing a step helps to save 1 minute per run …
> ci: update AVD to API 34

- packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
- packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/GeneratedAndroidFirebaseFirestore.java
- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
- packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestorePlugin.m
- packages/cloud_firestore/cloud_firestore/ios/Classes/FirestoreMessages.g.m
- packages/cloud_firestore/cloud_firestore/ios/Classes/Public/FirestoreMessages.g.h
- packages/cloud_firestore/cloud_firestore/windows/messages.g.cpp
- packages/cloud_firestore/cloud_firestore/windows/messages.g.h
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_aggregate_query.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/pigeon/messages.pigeon.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/pigeons/messages.dart
- packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore.dart
fixes https://github.com/firebase/flutterfire/issues/12229 …
> fix(firestore): aggregate query `average()` is `null` when collection is empty or collection doesn't exist or the property doesn't exist on docs

- packages/cloud_firestore/cloud_firestore/lib/cloud_firestore.dart
fix https://github.com/firebase/flutterfire/issues/12225 …
> fix(firestore): expose `AggregateField` type to users

- tests/integration_test/firebase_auth/firebase_auth_instance_e2e_test.dart
> test(auth): skip `setLanguageCode` as it now returns device language instead of `null`

- packages/cloud_firestore/cloud_firestore/example/integration_test/document_reference_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/second_database.dart
> test(firestore): fix broken stream e2e tests that require tear down

- packages/firebase_analytics/firebase_analytics_web/lib/firebase_analytics_web.dart
> test(analytics): fix broken `getSessionId()` test that requires async API

- tests/integration_test/firebase_messaging/firebase_messaging_e2e_test.dart
- tests/web/firebase-messaging-sw.js
- tests/web/index.html
> test(messaging): update tests app for messaging web

- packages/firebase_storage/firebase_storage_platform_interface/lib/src/full_metadata.dart
> chore: fix analyse issue

- .github/workflows/all_plugins.yaml
- packages/cloud_firestore/cloud_firestore/example/integration_test/second_database.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/transaction_e2e.dart
> ci: updates to improve e2e tests

- packages/cloud_firestore/cloud_firestore/example/integration_test/query_e2e.dart
> ci: fix firestore e2e tests

- packages/firebase_messaging/firebase_messaging/example/scripts/send-message.js
closes https://github.com/firebase/flutterfire/issues/12172 …
> chore(messaging): update JS script for testing notifications removing deprecated `sendToDevice()` admin SDK API

- .github/workflows/e2e_tests.yaml
> ci: roll back `firebase-tools` to version `13.3.0` for web integration tests

- packages/cloud_firestore/cloud_firestore/windows/cloud_firestore_plugin.cpp
> fix(firestore, windows): fix compilation issue on Windows

- packages/cloud_firestore/cloud_firestore/example/integration_test/second_database.dart
The entire file has been formatted but this is the actual change: [`web-e2e-second-db?expand=1`#diff-6918694697](https://github.com/firebase/flutterfire/compare/web-e2e-second-db?expand=1#diff-69186946971119c262bbc33818abecdc9ae077adb87cdfd1c0a489787d6a7d44R3019) …
> ci(firestore, web): skip live 2nd database tests on CI runs

- packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_confirmation_result.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_multi_factor.dart
- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_user.dart
- packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
This updates all API that return a Future of some type. At a later date, we can think about updating Stream exception handling as well.
closes https://github.com/firebase/flutterfire/issues/9889 …
> refactor(auth, web): update error handling to ensure stack traces are preserved.

- packages/firebase_core/firebase_core/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseCorePlugin.java
> fix(core, android): fix a null issue when initializing `fromResource()`

- packages/cloud_firestore/cloud_firestore/example/android/app/build.gradle
- packages/cloud_firestore/cloud_firestore/example/android/build.gradle
- packages/cloud_firestore/cloud_firestore/example/android/settings.gradle
> chore: migrate cloud_firestore android example app

- packages/firebase_core/firebase_core/example/android/app/build.gradle
- packages/firebase_core/firebase_core/example/android/build.gradle
- packages/firebase_core/firebase_core/example/android/settings.gradle
> chore: migrate firebase_core android example app

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump iOS SDK to version 10.22.0

- packages/cloud_firestore/cloud_firestore/example/integration_test/field_value_e2e.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/utils/firestore_message_codec.dart
> fix(firestore): fix an issue that would cause `FieldValue.increment` to not work for big int

- packages/cloud_firestore/cloud_firestore/example/integration_test/field_value_e2e.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/utils/firestore_message_codec.dart
> fix(firestore): fix an issue that would cause FieldValue.increment to be interpreted as double

- packages/cloud_functions/cloud_functions_web/pubspec.yaml
- packages/firebase_app_check/firebase_app_check_web/pubspec.yaml
- packages/firebase_auth/firebase_auth_web/pubspec.yaml
- packages/firebase_core/firebase_core_web/pubspec.yaml
- packages/firebase_messaging/firebase_messaging_web/lib/firebase_messaging_web.dart
- packages/firebase_messaging/firebase_messaging_web/pubspec.yaml
- packages/firebase_storage/firebase_storage_web/pubspec.yaml
Matching official packages dependencies: https://github.com/flutter/packages/blob/main/packages/google_identity_services_web/pubspec.yaml
closes #12387
closes #12467
closes #12353 …
> feat: update `web` package to 0.5.1

- packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
> feat: bump JS SDK to version 10.8.1

- packages/firebase_analytics/firebase_analytics_web/pubspec.yaml
> feat(analytics, web): update web version to 0.5.1

- packages/firebase_core/firebase_core/android/gradle.properties
closes https://github.com/firebase/flutterfire/issues/12495 …
> fix: bump Android SDK to version `32.7.4`

- .github/workflows/e2e_tests.yaml
Should be fixed in the latest firebase-tools version: https://github.com/firebase/firebase-tools/issues/6808#issuecomment-1988598646
It should be released at some point this week, refresh e2e tests towards end of week to see issue resolved.
Does your PR require plugin users to manually …
> ci: use latest `firebase-tools` for web e2e tests

- .github/ISSUE_TEMPLATE/bug_report.yml
> chore: issue template fix indentation

- tests/ios/Flutter/AppFrameworkInfo.plist
- tests/ios/Podfile
- tests/ios/Runner.xcodeproj/project.pbxproj
- tests/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Currently, each CI run updates the setup when compiling the app …
> ci(ios): upgrading necessary files so we don't need to do it in CI

- docs/setup/_setup_main.md
*Update docs to reflect Windows Support.*
Does your PR require plugin users to manually …
> docs: note about windows support

- .github/workflows/e2e_tests.yaml
- melos.yaml
- website/firebase.json
> chore: remove unused odm scripts and references

- packages/firebase_remote_config/firebase_remote_config/android/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfig/FirebaseRemoteConfigPlugin.java
- packages/firebase_remote_config/firebase_remote_config/example/ios/Flutter/AppFrameworkInfo.plist
- packages/firebase_remote_config/firebase_remote_config/example/ios/Podfile
- packages/firebase_remote_config/firebase_remote_config/example/ios/Runner.xcodeproj/project.pbxproj
- packages/firebase_remote_config/firebase_remote_config/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/firebase_remote_config/firebase_remote_config/ios/Classes/FLTFirebaseRemoteConfigPlugin.m
> fix(remote_config): fixing an issue that could cause duplicate listeners on hot restart

- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/settings.dart
See implementation here: https://github.com/firebase/flutterfire/blob/feat/allow-multiple-inequalities/packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart#L132
closes #12553 …
> fix(firestore): fix documentation since `persistenceEnabled` has been enabled on Web

- packages/firebase_analytics/firebase_analytics/android/build.gradle
- packages/firebase_analytics/firebase_analytics/example/android/app/build.gradle
- packages/firebase_analytics/firebase_analytics/example/android/build.gradle
- packages/firebase_analytics/firebase_analytics/example/android/settings.gradle
> chore(analytics, android): migrate analytics android example app

- packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/method_channel/method_channel_messaging.dart
- packages/firebase_messaging/firebase_messaging_platform_interface/test/method_channel_tests/method_channel_messaging_test.dart
> test(messaging): Refactor usage of `Platform.isXxx` to `defaultTargetPlatform == TargetPlatform.xxx`

- packages/firebase_auth/firebase_auth_web/lib/src/firebase_auth_web_recaptcha_verifier_factory.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart
Confirmed working locally. We cannot run in e2e tests since Recaptcha would fail since it's automatised 😓 
closes #12587 
> fix(auth, web): fix an issue that could prevent Recaptcha from being properly initialized

- packages/firebase_app_installations/firebase_app_installations/android/src/main/java/io/flutter/plugins/firebase/installations/firebase_app_installations/FirebaseInstallationsPlugin.java
part of: https://github.com/firebase/flutterfire/issues/8073 …
> fix(app-installations, android): update deprecated API to latest Task implementation

- packages/firebase_storage/firebase_storage/example/lib/save_as/save_as_html.dart
> chore(storage, web): update example app save on web

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump Firebase iOS SDK to `10.24.0`

- packages/cloud_firestore/cloud_firestore/ios/cloud_firestore.podspec
- packages/cloud_firestore/cloud_firestore/macos/cloud_firestore.podspec
Remove version constraint from this PR: https://github.com/firebase/flutterfire/pull/9708
closes https://github.com/firebase/flutterfire/issues/12630 …
> fix(firestore): remove `nanopb` version constraints from podspec

- .github/workflows/all_plugins.yaml
> ci: change environment to `macos-latest` for formatting run

- CONTRIBUTING.md
> chore: update instructions for the release process

- packages/firebase_database/firebase_database_web/lib/src/utils/exception.dart
- tests/integration_test/firebase_database/exception.dart
- tests/integration_test/firebase_database/firebase_database_e2e_test.dart
- tests/integration_test/firebase_database/web_only.dart
- tests/integration_test/firebase_database/web_only_stub.dart
Addresses an issue with a previous PR #12647 
---- …
> fix(database, web): Fix exceptions being converted into lowercase

- packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
Please Check release notes, Thanks.
https://firebase.google.com/support/release-notes/js …
> feat: bump JS SDK to version 10.11.0

- packages/firebase_messaging/firebase_messaging/android/build.gradle
See comment: https://github.com/firebase/firebase-android-sdk/issues/5867#issuecomment-2059478952
closes https://github.com/firebase/flutterfire/issues/12700
[CLA]: …
> fix(messaging, android): remove deprecated instance ID (iid) dependency

- packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
> feat: bump Firebase JS SDK to version 10.11.1

- packages/cloud_firestore/cloud_firestore/ios/Classes/FLTQuerySnapshotStreamHandler.m
> fix(firestore, ios): fix query stream handler options.

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump firebase iOS SDK to `10.25.0`

- packages/firebase_vertexai/firebase_vertexai/CHANGELOG.md
- packages/firebase_vertexai/firebase_vertexai/README.md
- packages/firebase_vertexai/firebase_vertexai/example/README.md
- packages/firebase_vertexai/firebase_vertexai/example/lib/main.dart
- packages/firebase_vertexai/firebase_vertexai/lib/firebase_vertexai.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_api.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_content.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_model.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_version.dart
- packages/firebase_vertexai/firebase_vertexai/pubspec.yaml
- packages/firebase_vertexai/firebase_vertexai/test/vertex_content_test.dart
- bump google_generative_ai to 0.4.0
- Add Firebase Storage url support
- Add responseMimeType
> feat(vertexai): Add support for Storage prompt and responseMimeType

- packages/cloud_firestore/cloud_firestore/ios/Classes/FLTDocumentSnapshotStreamHandler.m
> fix(firestore, ios): fix document stream handler options.

- packages/cloud_firestore/cloud_firestore/example/integration_test/document_reference_e2e.dart
- packages/cloud_firestore/cloud_firestore/example/integration_test/second_database.dart
- packages/cloud_functions/cloud_functions/test/https_callable_test.dart
- packages/firebase_vertexai/firebase_vertexai/example/lib/main.dart
- tests/integration_test/cloud_functions/cloud_functions_e2e_test.dart
- tests/integration_test/firebase_auth/firebase_auth_instance_e2e_test.dart
> chore: update analyse issues surfaced from latest Flutter SDK

- packages/firebase_vertexai/firebase_vertexai/example/lib/main.dart
- packages/firebase_vertexai/firebase_vertexai/lib/firebase_vertexai.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/firebase_vertexai.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_model.dart
- packages/firebase_vertexai/firebase_vertexai/pubspec.yaml
Add the support for auth token in vertex request
> feat(vertex): Add auth support in the vertexai

- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPluginException.java
> fix(auth, android): remove unecessary error type guarding

- tests/.metadata
- tests/android/app/build.gradle
- tests/android/app/src/debug/AndroidManifest.xml
- tests/android/app/src/main/AndroidManifest.xml
- tests/android/app/src/main/kotlin/io/flutter/plugins/firebase/tests/MainActivity.kt
- tests/android/app/src/main/res/values-night/styles.xml
- tests/android/app/src/main/res/values/styles.xml
- tests/android/app/src/profile/AndroidManifest.xml
- tests/android/build.gradle
- tests/android/gradle.properties
- tests/android/gradle/wrapper/gradle-wrapper.properties
- tests/android/settings.gradle
- tests/web/index.html
Regenerate the `android` folder with the latest flutter version 3.22. …
> chore(tests): update tests example app

- packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart
- packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/platform_interface/platform_interface_firestore.dart
Copy from official documentation
https://firebase.google.com/docs/reference/js/firestore_
https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore#clearPersistence() …
> docs(firestore): update documentation for `clearPersistence`

- .github/workflows/scripts/database.rules.json
- tests/integration_test/firebase_database/data_snapshot_e2e.dart
- tests/integration_test/firebase_database/query_e2e.dart
fixes these: 
https://github.com/firebase/flutterfire/actions/runs/9301454054/job/25599623476#step:11:229
https://github.com/firebase/flutterfire/actions/runs/9316667666/job/25645391244?pr=12859#step:11:221
It sometimes works and sometimes fails. They seem to clash with other tests and it's hard to discern why but I think it might be down to the Flutter web testing framework. There seems to be some concurrency occurring which borks the tests.
Before you create this PR confirm that it meets all requirements listed below …
> test(database): fix tests that were failing frequently on web e2e test run

- packages/firebase_core/firebase_core/windows/CMakeLists.txt
> feat!: bump CPP SDK to version 12.0.0

- CHANGELOG.md
- VERSIONS.md
- scripts/generate_bom.dart
Also removed the comments on the MD file for `flutterfire install` …
> chore: update BoM script to automatically modify the changelog file

- packages/firebase_admob/README.md
- packages/firebase_ml_custom/README.md
- packages/firebase_ml_vision/README.md
Since we're doing a breaking release soon, I'm removing folders linking to deprecated packages. …
> chore: remove old folder linking to discontinued packages

- CODEOWNERS
> chore: updating CODEOWNERS file

- packages/firebase_database/firebase_database/lib/src/firebase_database.dart
Removed `factory FirebaseDatabase({FirebaseApp? app, String? databaseURL})` & `DatabaseReference reference() => ref();` which were [deprecated over 3 years ago](https://github.com/firebase/flutterfire/commit/8f750f82eecd9dfada4fe667f4acbed304821728#diff-6b29b1e1f00a5570407806217d77c5a147a3154f193aab0be14f1521a118d7b2).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` …
> refactor(database)!: remove deprecated API ahead of breaking change release

- packages/firebase_analytics/firebase_analytics/lib/src/firebase_analytics.dart
Removed user facing API that are have been deprecated for over 3 years now. 
I also added a deprecated annotation to `logSetCheckoutOption()` which should've had one from 3 years ago.
[Here is the PR](https://github.com/firebase/flutterfire/commit/2c5a8b91366f41d064646fb107043ef1fb70d8cb) when these APIs were made deprecated. …
> refactor(analytics)!: remove deprecated API ahead of breaking change release

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump Firebase iOS SDK to `10.27.0`

- packages/cloud_firestore/cloud_firestore/android/build.gradle
- packages/cloud_functions/cloud_functions/android/build.gradle
- packages/firebase_analytics/firebase_analytics/android/build.gradle
- packages/firebase_app_check/firebase_app_check/android/build.gradle
- packages/firebase_app_installations/firebase_app_installations/android/build.gradle
- packages/firebase_auth/firebase_auth/android/build.gradle
- packages/firebase_core/firebase_core/android/build.gradle
- packages/firebase_crashlytics/firebase_crashlytics/android/build.gradle
- packages/firebase_database/firebase_database/android/build.gradle
- packages/firebase_database/firebase_database/example/android/app/build.gradle
- packages/firebase_dynamic_links/firebase_dynamic_links/android/build.gradle
- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/app/build.gradle
- packages/firebase_in_app_messaging/firebase_in_app_messaging/android/build.gradle
- packages/firebase_messaging/firebase_messaging/android/build.gradle
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/android/build.gradle
- packages/firebase_performance/firebase_performance/android/build.gradle
- packages/firebase_remote_config/firebase_remote_config/android/build.gradle
- packages/firebase_storage/firebase_storage/android/build.gradle
- tests/android/app/build.gradle
> refactor!: android plugins require `minSdk 21`, auth requires `minSdk 23` ahead of android BOM `>=33.0.0`

- scripts/generate_bom.dart
> chore: automatically the modified changelog to the commit

- packages/firebase_app_check/firebase_app_check/example/.metadata
- packages/firebase_app_check/firebase_app_check/example/android/.gitignore
- packages/firebase_app_check/firebase_app_check/example/android/app/build.gradle
- packages/firebase_app_check/firebase_app_check/example/android/app/google-services.json
- packages/firebase_app_check/firebase_app_check/example/android/app/src/debug/AndroidManifest.xml
- packages/firebase_app_check/firebase_app_check/example/android/app/src/main/AndroidManifest.xml
- packages/firebase_app_check/firebase_app_check/example/android/app/src/main/kotlin/io/flutter/plugins/firebase/appcheck/example/MainActivity.kt
- packages/firebase_app_check/firebase_app_check/example/android/app/src/main/res/values-night/styles.xml
- packages/firebase_app_check/firebase_app_check/example/android/app/src/main/res/values/styles.xml
- packages/firebase_app_check/firebase_app_check/example/android/app/src/profile/AndroidManifest.xml
- packages/firebase_app_check/firebase_app_check/example/android/build.gradle
- packages/firebase_app_check/firebase_app_check/example/android/gradle.properties
- packages/firebase_app_check/firebase_app_check/example/android/settings.gradle
> chore(app_check): upgrade gradle

- packages/firebase_app_installations/firebase_app_installations/example/.metadata
- packages/firebase_app_installations/firebase_app_installations/example/android/app/build.gradle
- packages/firebase_app_installations/firebase_app_installations/example/android/app/google-services.json
- packages/firebase_app_installations/firebase_app_installations/example/android/app/src/debug/AndroidManifest.xml
- packages/firebase_app_installations/firebase_app_installations/example/android/app/src/main/AndroidManifest.xml
- packages/firebase_app_installations/firebase_app_installations/example/android/app/src/main/kotlin/io/flutter/plugins/firebase/installations/example/MainActivity.kt
- packages/firebase_app_installations/firebase_app_installations/example/android/app/src/main/res/values-night/styles.xml
- packages/firebase_app_installations/firebase_app_installations/example/android/app/src/main/res/values/styles.xml
- packages/firebase_app_installations/firebase_app_installations/example/android/app/src/profile/AndroidManifest.xml
- packages/firebase_app_installations/firebase_app_installations/example/android/build.gradle
- packages/firebase_app_installations/firebase_app_installations/example/android/gradle.properties
- packages/firebase_app_installations/firebase_app_installations/example/android/settings.gradle
> chore(app_installations): upgrade gradle

- packages/firebase_crashlytics/firebase_crashlytics/example/.metadata
- packages/firebase_crashlytics/firebase_crashlytics/example/android/.gitignore
- packages/firebase_crashlytics/firebase_crashlytics/example/android/app/build.gradle
- packages/firebase_crashlytics/firebase_crashlytics/example/android/app/google-services.json
- packages/firebase_crashlytics/firebase_crashlytics/example/android/app/src/debug/AndroidManifest.xml
- packages/firebase_crashlytics/firebase_crashlytics/example/android/app/src/main/AndroidManifest.xml
- packages/firebase_crashlytics/firebase_crashlytics/example/android/app/src/main/kotlin/io/flutter/plugins/firebasecrashlyticsexample/MainActivity.kt
- packages/firebase_crashlytics/firebase_crashlytics/example/android/app/src/main/res/drawable-v21/launch_background.xml
- packages/firebase_crashlytics/firebase_crashlytics/example/android/app/src/main/res/values-night/styles.xml
- packages/firebase_crashlytics/firebase_crashlytics/example/android/app/src/profile/AndroidManifest.xml
- packages/firebase_crashlytics/firebase_crashlytics/example/android/build.gradle
- packages/firebase_crashlytics/firebase_crashlytics/example/android/gradle.properties
- packages/firebase_crashlytics/firebase_crashlytics/example/android/settings.gradle
> chore(crashlytics): upgrade example gradle

- packages/firebase_dynamic_links/firebase_dynamic_links/example/.gitignore
- packages/firebase_dynamic_links/firebase_dynamic_links/example/.metadata
- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/.gitignore
- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/app/build.gradle
- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/app/google-services.json
- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/app/src/debug/AndroidManifest.xml
- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/app/src/main/AndroidManifest.xml
- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/app/src/main/kotlin/io/flutter/plugins/firebase/dynamiclinksexample/MainActivity.kt
- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/app/src/main/res/drawable-v21/launch_background.xml
- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/app/src/main/res/values-night/styles.xml
- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/app/src/profile/AndroidManifest.xml
- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/build.gradle
- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/gradle.properties
- packages/firebase_dynamic_links/firebase_dynamic_links/example/android/settings.gradle
> chore(dynamic_links): upgrade example gradle

- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/.metadata
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/android/.gitignore
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/android/app/build.gradle
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/android/app/google-services.json
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/android/app/src/debug/AndroidManifest.xml
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/android/app/src/main/AndroidManifest.xml
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/android/app/src/main/kotlin/io/flutter/plugins/firebase/tests/MainActivity.kt
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/android/app/src/main/res/drawable-v21/launch_background.xml
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/android/app/src/main/res/values-night/styles.xml
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/android/app/src/profile/AndroidManifest.xml
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/android/build.gradle
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/android/gradle.properties
- packages/firebase_in_app_messaging/firebase_in_app_messaging/example/android/settings.gradle
> chore(in_app_messaging): upgrade example gradle

- packages/firebase_messaging/firebase_messaging/example/.metadata
- packages/firebase_messaging/firebase_messaging/example/android/.gitignore
- packages/firebase_messaging/firebase_messaging/example/android/app/build.gradle
- packages/firebase_messaging/firebase_messaging/example/android/app/google-services.json
- packages/firebase_messaging/firebase_messaging/example/android/app/src/debug/AndroidManifest.xml
- packages/firebase_messaging/firebase_messaging/example/android/app/src/main/AndroidManifest.xml
- packages/firebase_messaging/firebase_messaging/example/android/app/src/main/kotlin/io/flutter/plugins/firebase/messaging/example/MainActivity.kt
- packages/firebase_messaging/firebase_messaging/example/android/app/src/main/res/drawable-v21/launch_background.xml
- packages/firebase_messaging/firebase_messaging/example/android/app/src/main/res/values-night/styles.xml
- packages/firebase_messaging/firebase_messaging/example/android/app/src/profile/AndroidManifest.xml
- packages/firebase_messaging/firebase_messaging/example/android/build.gradle
- packages/firebase_messaging/firebase_messaging/example/android/gradle.properties
- packages/firebase_messaging/firebase_messaging/example/android/settings.gradle
> chore(messaging): upgrade example gradle

- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/.metadata
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/android/app/build.gradle
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/android/app/google-services.json
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/android/app/src/debug/AndroidManifest.xml
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/android/app/src/main/AndroidManifest.xml
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/android/app/src/main/java/io/flutter/plugins/firebase/firebase_ml_model_downloader_example/MainActivity.java
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/android/app/src/main/kotlin/io/flutter/plugins/firebase/tests/MainActivity.kt
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/android/app/src/main/res/values-night/styles.xml
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/android/app/src/main/res/values/styles.xml
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/android/app/src/profile/AndroidManifest.xml
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/android/build.gradle
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/android/gradle.properties
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/android/settings.gradle
> chore(ml_model_downloader): upgrade example gradle

- packages/firebase_performance/firebase_performance/example/.metadata
- packages/firebase_performance/firebase_performance/example/android/.gitignore
- packages/firebase_performance/firebase_performance/example/android/app/build.gradle
- packages/firebase_performance/firebase_performance/example/android/app/google-services.json
- packages/firebase_performance/firebase_performance/example/android/app/gradle/wrapper/gradle-wrapper.properties
- packages/firebase_performance/firebase_performance/example/android/app/src/debug/AndroidManifest.xml
- packages/firebase_performance/firebase_performance/example/android/app/src/main/AndroidManifest.xml
- packages/firebase_performance/firebase_performance/example/android/app/src/main/kotlin/io/flutter/plugins/firebase/tests/MainActivity.kt
- packages/firebase_performance/firebase_performance/example/android/app/src/main/res/drawable-v21/launch_background.xml
- packages/firebase_performance/firebase_performance/example/android/app/src/main/res/values-night/styles.xml
- packages/firebase_performance/firebase_performance/example/android/app/src/profile/AndroidManifest.xml
- packages/firebase_performance/firebase_performance/example/android/build.gradle
- packages/firebase_performance/firebase_performance/example/android/gradle.properties
- packages/firebase_performance/firebase_performance/example/android/settings.gradle
> chore(performance): upgrade example gradle

- packages/firebase_remote_config/firebase_remote_config/example/.gitignore
- packages/firebase_remote_config/firebase_remote_config/example/.metadata
- packages/firebase_remote_config/firebase_remote_config/example/android/.gitignore
- packages/firebase_remote_config/firebase_remote_config/example/android/app/build.gradle
- packages/firebase_remote_config/firebase_remote_config/example/android/app/google-services.json
- packages/firebase_remote_config/firebase_remote_config/example/android/app/src/debug/AndroidManifest.xml
- packages/firebase_remote_config/firebase_remote_config/example/android/app/src/main/AndroidManifest.xml
- packages/firebase_remote_config/firebase_remote_config/example/android/app/src/main/kotlin/io/flutter/plugins/firebase/remoteconfig/example/MainActivity.kt
- packages/firebase_remote_config/firebase_remote_config/example/android/app/src/main/res/drawable-v21/launch_background.xml
- packages/firebase_remote_config/firebase_remote_config/example/android/app/src/main/res/values-night/styles.xml
- packages/firebase_remote_config/firebase_remote_config/example/android/app/src/profile/AndroidManifest.xml
- packages/firebase_remote_config/firebase_remote_config/example/android/build.gradle
- packages/firebase_remote_config/firebase_remote_config/example/android/gradle.properties
- packages/firebase_remote_config/firebase_remote_config/example/android/settings.gradle
> chore(remote_config): upgrade example gradle

- melos.yaml
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_version.dart
- pubspec.yaml
- scripts/generate_vertexai_version.dart
generate version using melos `preCommit` hook. 
I also ran the script manually which correctly [updated the version](https://github.com/firebase/flutterfire/pull/12904/files#diff-c8558e899c587dfa1f90da2d351c6b5b667a85f0ac6957b13c1033063a8d2feeR16). …
> chore(vertex_ai): ensure generated vertex version is auto updated when versioning 

- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_model.dart
- packages/firebase_vertexai/firebase_vertexai/pubspec.yaml
Related PR in generative ai sdk: https://github.com/google-gemini/generative-ai-dart/pull/180 …
> fix(vertexai): fix the countTokens brokage

- packages/firebase_app_check/firebase_app_check/ios/firebase_app_check.podspec
closes https://github.com/firebase/flutterfire/issues/12910 …
> fix(app-check, ios): update app check to stable release

- packages/firebase_storage/firebase_storage/example/windows/flutter/CMakeLists.txt
- packages/firebase_storage/firebase_storage/windows/firebase_storage_plugin.cpp
> feat(storage, windows): add support for creationTime and updateTime

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump Firebase iOS SDK to `10.28.0`

- packages/firebase_app_installations/firebase_app_installations/example/lib/main.dart
- packages/firebase_app_installations/firebase_app_installations/example/pubspec.yaml
- packages/firebase_app_installations/firebase_app_installations_platform_interface/pubspec.yaml
- packages/firebase_app_installations/firebase_app_installations_web/lib/firebase_app_installations_web.dart
- packages/firebase_app_installations/firebase_app_installations_web/lib/src/interop/installations.dart
- packages/firebase_app_installations/firebase_app_installations_web/pubspec.yaml
- packages/firebase_database/firebase_database_web/lib/firebase_database_web.dart
- packages/firebase_database/firebase_database_web/lib/src/data_snapshot_web.dart
- packages/firebase_database/firebase_database_web/lib/src/database_event_web.dart
- packages/firebase_database/firebase_database_web/lib/src/database_reference_web.dart
- packages/firebase_database/firebase_database_web/lib/src/interop/data_snapshot_interop.dart
- packages/firebase_database/firebase_database_web/lib/src/interop/database.dart
- packages/firebase_database/firebase_database_web/lib/src/interop/database_interop.dart
- packages/firebase_database/firebase_database_web/lib/src/interop/query_interop.dart
- packages/firebase_database/firebase_database_web/lib/src/interop/reference_interop.dart
- packages/firebase_database/firebase_database_web/lib/src/ondisconnect_web.dart
- packages/firebase_database/firebase_database_web/lib/src/query_web.dart
- packages/firebase_database/firebase_database_web/lib/src/transaction_result_web.dart
- packages/firebase_database/firebase_database_web/lib/src/utils/exception.dart
- packages/firebase_database/firebase_database_web/lib/src/utils/snapshot_utils.dart
- packages/firebase_database/firebase_database_web/pubspec.yaml
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/lib/main.dart
- packages/firebase_ml_model_downloader/firebase_ml_model_downloader/example/pubspec.yaml
- packages/firebase_vertexai/firebase_vertexai/example/pubspec.yaml
- packages/firebase_vertexai/firebase_vertexai/pubspec.yaml
Update lints across all packages to be consistent
> chore: update lints across packages

- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/utils/convert_auth_provider.dart
> fix(auth): fixing scopes and parameters that would not be taken into account for GoogleAuthProvider

- packages/firebase_analytics/firebase_analytics/example/macos/Podfile
- packages/firebase_analytics/firebase_analytics/example/macos/Runner.xcodeproj/project.pbxproj
- packages/firebase_analytics/firebase_analytics/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
> chore(analytics, macos): update the example app

- packages/firebase_auth/firebase_auth/lib/src/user.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/platform_interface/platform_interface_user.dart
Taken from https://firebase.google.com/docs/reference/js/v8/firebase.User#verifybeforeupdateemail
closes #11801 
> docs(auth): add information about error codes for `verifyBeforeUpdateEmail`

- packages/firebase_storage/firebase_storage_web/lib/src/interop/storage.dart
> fix(storage, web): ensure exact same streams are not unsubscribed

- packages/firebase_app_check/firebase_app_check_web/lib/src/interop/app_check.dart
> fix(app-check, web): ensure exact same streams are not unsubscribed

- docs/setup/_setup_prereq_ios.md
Copied note from iOS setup to Flutter: https://firebase.google.com/docs/ios/setup
closes: https://github.com/firebase/flutterfire/issues/11186
[CLA]: …
> docs(macos): make note that keysharing capability should be enabled

- packages/firebase_analytics/firebase_analytics_web/lib/interop/analytics.dart
> fix(analytics, web): Default to empty object for intializeAnalytics

- docs/cloud-messaging/receive.md
Refrences:
https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages
https://developer.apple.com/documentation/usernotifications/generating-a-remote-notification#Localize-your-alert-messages
Closes #12691 
[pub …
> docs(messaging): Fix documentation for localized messages

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump iOS SDK to version 10.29.0

- packages/cloud_firestore/cloud_firestore/example/ios/Runner.xcodeproj/project.pbxproj
> chore(firestore, ios): updating project files

- packages/firebase_vertexai/firebase_vertexai/example/lib/main.dart
Making the required option more obvious to be able to run on web. …
> chore: update example app for VertexAI

- packages/firebase_storage/firebase_storage/lib/src/firebase_storage.dart
> fix(storage, windows): add log to explain that the Storage Emulator is not available on Windows

- CHANGELOG.md
- VERSIONS.md
- packages/cloud_firestore/cloud_firestore/CHANGELOG.md
- packages/cloud_firestore/cloud_firestore/example/pubspec.yaml
- packages/cloud_firestore/cloud_firestore/pubspec.yaml
- packages/cloud_firestore/cloud_firestore_platform_interface/CHANGELOG.md
- packages/cloud_firestore/cloud_firestore_platform_interface/pubspec.yaml
- packages/cloud_firestore/cloud_firestore_web/CHANGELOG.md
- packages/cloud_firestore/cloud_firestore_web/pubspec.yaml
- packages/firebase_app_check/firebase_app_check/example/pubspec.yaml
- packages/firebase_auth/firebase_auth/CHANGELOG.md
- packages/firebase_auth/firebase_auth/example/pubspec.yaml
- packages/firebase_auth/firebase_auth/pubspec.yaml
- packages/firebase_storage/firebase_storage/CHANGELOG.md
- packages/firebase_storage/firebase_storage/example/pubspec.yaml
- packages/firebase_storage/firebase_storage/pubspec.yaml
- packages/firebase_vertexai/firebase_vertexai/CHANGELOG.md
- packages/firebase_vertexai/firebase_vertexai/example/pubspec.yaml
- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_version.dart
- packages/firebase_vertexai/firebase_vertexai/pubspec.yaml
- scripts/versions.json
- tests/pubspec.yaml
> chore(release): publish packages 

- packages/firebase_data_connect/firebase_data_connect/example/.gitignore
- packages/firebase_data_connect/firebase_data_connect/example/lib/generated/create_movie.dart
- packages/firebase_data_connect/firebase_data_connect/example/lib/generated/list_movies.dart
- packages/firebase_data_connect/firebase_data_connect/example/lib/main.dart
- packages/firebase_data_connect/firebase_data_connect/example/web/index.html
- packages/firebase_data_connect/firebase_data_connect/lib/src/common/common_library.dart
- packages/firebase_data_connect/firebase_data_connect/lib/src/core/ref.dart
- packages/firebase_data_connect/firebase_data_connect/lib/src/firebase_data_connect.dart
- packages/firebase_data_connect/firebase_data_connect/lib/src/network/grpc_transport.dart
- packages/firebase_data_connect/firebase_data_connect/lib/src/network/rest_library.dart
- packages/firebase_data_connect/firebase_data_connect/lib/src/network/rest_transport.dart
* Added error handling and throwing
* Added ability to call execute when no cache is currently available
> Added error catching implementation

- .github/workflows/e2e_tests.yaml
- melos.yaml
- tests/integration_test/e2e_test.dart
- tests/integration_test/firebase_app_check/firebase_app_check_e2e_test.dart
- tests/web/index.html
- tests/web/wasm_index.html
> test(app-check, web): move  to its own job to stop throttling of other e2e tests

- .github/workflows/android.yaml
- .github/workflows/ios.yaml
- .github/workflows/macos.yaml
- .github/workflows/web.yaml
- .github/workflows/windows.yaml
- cached firebase emulator based on operating system.
- macOS and iOS have same key for Xcode which should be the same given they run on the same mac version and there is no difference.
- updated key naming so they are better defined and understood.
- Fixed flutter and pub cache to operating system as they were also overloading cache with unique keys.
This will ensure a smooth and quick review …
> test: update caching strategies for github actions

- .github/workflows/android.yaml
> ci(android): fix emulator failing to shutdown causes test failure

- .github/workflows/scripts/swift-integration.sh
> ci: add swift integration logging

- packages/firebase_auth/firebase_auth/example/android/settings.gradle
- packages/firebase_auth/firebase_auth/example/ios/Runner/AppDelegate.swift
> chore(auth): example app fixes

- packages/firebase_data_connect/firebase_data_connect/CHANGELOG.md
- packages/firebase_data_connect/firebase_data_connect/pubspec.yaml
> feat(fdc)!: commit as breaking change to bump `firebase_data_connect` to v0.1.0

- packages/firebase_core/firebase_core/android/gradle.properties
> feat: bump Firebase android BOM to `33.3.0`

- packages/firebase_data_connect/firebase_data_connect/README.md
> chore(fdc): Update README.md

- melos.yaml
- scripts/generate_dataconnect_version.dart
Update data connect version in src code before commit/publish package. …
> chore: update melos preCommit hook for data connect version

- packages/firebase_vertexai/firebase_vertexai/lib/src/vertex_error.dart
- packages/firebase_vertexai/firebase_vertexai/test/vertex_response_parsing_test.dart
> feat(vertexai): Error message for service api not enabled.

- packages/firebase_vertexai/firebase_vertexai/lib/src/api.dart
> fix(vertexai): fix safetyRating's newly added attributes might not in json

- docs/database/read-and-write.md
> docs: Documentation only changes

- packages/cloud_firestore/cloud_firestore/test/query_test.dart
Remove test that no longer applies
[Flutter Style …
> chore(cloud_firestore): remove test that no longer applies

- packages/firebase_vertexai/firebase_vertexai/example/lib/main.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/api.dart
> chore(vertexai): function calling sample update

- .gitignore
> chore: ignore SPM build files

- CHANGELOG.md
- packages/firebase_app_check/firebase_app_check_web/CHANGELOG.md
> chore(app-check, web): fix CHANGELOGs for app check web

- CHANGELOG.md
> chore(vertexai): Update CHANGELOG.md to add link

- packages/firebase_vertexai/firebase_vertexai/example/lib/main.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/model.dart
> fix(vertexai): hotfix for vertexai auth access to storage

- packages/firebase_vertexai/firebase_vertexai/lib/src/error.dart
https://github.com/firebase/flutterfire/issues/13542 …
> fix(vertexai): fix the url in the service not available error

- packages/firebase_database/firebase_database_web/lib/src/interop/database.dart
Remove sync on stream broadcast
fixes https://github.com/firebase/flutterfire/issues/13490
fixes https://github.com/firebase/flutterfire/issues/13482 …
> fix(database, web): remove sync on stream broadcast

- packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java
- packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
Remove a bit of duplicated code.
[Flutter Style …
> chore(firestore): clean up the code for checking if instance exists

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
fixes https://github.com/firebase/flutterfire/issues/13553
fixes https://github.com/firebase/flutterfire/issues/13451 …
> feat: bump firebase iOS SDK to `v11.4.0`

- packages/firebase_core/firebase_core/android/gradle.properties
> feat: update Android SDK to version 33.5.1

- packages/firebase_auth/firebase_auth/ios/Classes/PigeonParser.m
- packages/firebase_auth/firebase_auth/ios/Classes/Private/PigeonParser.h
closes https://github.com/firebase/flutterfire/issues/13567 …
> fix(auth, apple): set nullability on pigeon parser method

- .github/workflows/close-spam-issues.yaml
> chore: create cron to clean up spam issues

- .github/workflows/close-spam-issues.yaml
> chore: fix logic, `issue` object can be null in github context

- .github/workflows/close-spam-issues.yaml
> chore: list of spammers

- .github/workflows/close-spam-issues.yaml
> chore: pass github token to action

- .github/workflows/close-spam-issues.yaml
- .github/workflows/spam-removal/index.js
- .github/workflows/spam-removal/package.json
- .gitignore
> chore: node script that removes spam issues

- .github/workflows/spam-removal/index.js
> chore: update title and body

- packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java
fixes https://github.com/firebase/flutterfire/issues/16668 …
> fix(firestore, android): synchronize access to firestore instances

- packages/firebase_storage/firebase_storage/ios/Classes/FLTFirebaseStoragePlugin.h
- packages/firebase_storage/firebase_storage/ios/Classes/FLTFirebaseStoragePlugin.m
- packages/firebase_storage/firebase_storage/ios/Classes/FLTTaskStateChannelStreamHandler.h
- packages/firebase_storage/firebase_storage/ios/Classes/FLTTaskStateChannelStreamHandler.m
Same issue as https://github.com/firebase/flutterfire/pull/13508
fixes https://github.com/firebase/flutterfire/issues/13532
> fix(storage, apple): clean up event channel, stream handler and task on completion

- packages/firebase_core/firebase_core/example/macos/Flutter/Flutter-Debug.xcconfig
- packages/firebase_core/firebase_core/example/macos/Runner.xcodeproj/project.pbxproj
- packages/firebase_core/firebase_core/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/firebase_core/firebase_core/example/macos/Runner/AppDelegate.swift
- packages/firebase_core/firebase_core/macos/firebase_core/Package.swift
- packages/firebase_core/firebase_core/macos/firebase_core/Sources/firebase_core/dummy.m
- packages/firebase_core/firebase_core/macos/firebase_core/Sources/firebase_core/include/dummy.h
> fix(core, macos): exclude files pulled in from remote dependency. SPM integration

- packages/firebase_messaging/firebase_messaging/example/android/settings.gradle
- packages/firebase_messaging/firebase_messaging/example/pubspec.yaml
fixed. See successful example app build: 
```
➜  example git:(fix-messaging-example) ✗ flutter run -d emulator-5554
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...                             33.7s
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Installing build/app/outputs/flutter-apk/app-debug.apk...          614ms
Syncing files to device sdk gphone64 arm64...                       82ms
Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
```
fixes https://github.com/firebase/flutterfire/issues/16831
Before you create this PR confirm that it meets …
> chore(messaging, android): fix example app

- packages/firebase_storage/firebase_storage/lib/src/utils.dart
- packages/firebase_storage/firebase_storage/test/utils_test.dart
fixes https://github.com/firebase/flutterfire/issues/15799
> fix(storage): update regex for cloudStoragePath

- packages/firebase_core/firebase_core/android/gradle.properties
> feat: bump Firebase android BOM to `v33.7.0`

- packages/cloud_firestore/cloud_firestore/example/android/settings.gradle
- packages/firebase_data_connect/firebase_data_connect/example/android/settings.gradle
> ci(android): bump AGP to `8.1.0` for firestore and data-connect example apps

- packages/firebase_crashlytics/firebase_crashlytics/android/src/main/java/io/flutter/plugins/firebase/crashlytics/FlutterFirebaseCrashlyticsPlugin.java
fixes https://github.com/firebase/flutterfire/issues/16838
> fix(crashlytics, android): suppress unchecked cast warning

- packages/firebase_core/firebase_core/macos/firebase_core/Package.swift
fixes https://github.com/firebase/flutterfire/issues/16868 …
> fix(core, macos): update path to firebase sdk version for SPM

- packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
> feat: bump JS SDK to version 11.1.0

- docs/storage/download-files.md
fixes https://github.com/firebase/flutterfire/issues/16904
> docs(storage): remove mention of getStream function

- VERSIONS.md
- scripts/versions.json
> chore: BoM Version 3.5.0

- packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java
Fixes https://github.com/firebase/flutterfire/issues/16978
> fix(cloud_firestore, android): suppress unchecked warning

- packages/firebase_messaging/firebase_messaging/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingUtils.java
> fix(messaging, android): remove a deprecation message

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
- tests/integration_test/firebase_auth/firebase_auth_instance_e2e_test.dart
- tests/integration_test/firebase_auth/firebase_auth_user_e2e_test.dart
closes https://github.com/firebase/flutterfire/issues/17004 …
> feat: bump firebase iOS SDK to `v11.7.0`

- packages/firebase_vertexai/firebase_vertexai/example/.gitignore
- packages/firebase_vertexai/firebase_vertexai/example/lib/main.dart
- packages/firebase_vertexai/firebase_vertexai/example/lib/pages/chat_page.dart
- packages/firebase_vertexai/firebase_vertexai/example/lib/pages/function_calling_page.dart
- packages/firebase_vertexai/firebase_vertexai/example/lib/pages/image_prompt_page.dart
- packages/firebase_vertexai/firebase_vertexai/example/lib/pages/schema_page.dart
- packages/firebase_vertexai/firebase_vertexai/example/lib/pages/storage_uri_page.dart
- packages/firebase_vertexai/firebase_vertexai/example/lib/pages/token_count_page.dart
- packages/firebase_vertexai/firebase_vertexai/example/lib/widgets/message_widget.dart
- packages/firebase_vertexai/firebase_vertexai/example/macos/Runner/AppDelegate.swift
> feat(vertexai): organize example page and functions

- packages/firebase_vertexai/firebase_vertexai/lib/src/error.dart
fixes: https://github.com/firebase/flutterfire/issues/17030 …
> fix(firebase_vertexai): Corrected minor typo in VertexAISDKException

- packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
> feat: bump Firebase JS SDK to `11.2.0`

- packages/firebase_crashlytics/firebase_crashlytics/example/android/settings.gradle
closes https://github.com/firebase/flutterfire/issues/17063
> chore(crashlytics): update AGP for example app

- packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
> feat: bump Firebase JS SDK to `11.3.1`

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump Firebase iOS SDK to `11.8.0`

- packages/firebase_analytics/firebase_analytics/ios/firebase_analytics/Package.swift
- packages/firebase_analytics/firebase_analytics/macos/firebase_analytics/Package.swift
> fix(analytics, apple): use correct tag for library name

- .gitignore
- docs/auth/email-link-auth.md
- docs/auth/passing-state-in-email-actions.md
- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/GeneratedAndroidFirebaseAuth.java
- packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/PigeonParser.java
- packages/firebase_auth/firebase_auth/example/android/app/build.gradle
- packages/firebase_auth/firebase_auth/example/android/settings.gradle
- packages/firebase_auth/firebase_auth/ios/firebase_auth/Sources/firebase_auth/PigeonParser.m
- packages/firebase_auth/firebase_auth/ios/firebase_auth/Sources/firebase_auth/firebase_auth_messages.g.m
- packages/firebase_auth/firebase_auth/ios/firebase_auth/Sources/firebase_auth/include/Public/firebase_auth_messages.g.h
- packages/firebase_auth/firebase_auth/windows/messages.g.cpp
- packages/firebase_auth/firebase_auth/windows/messages.g.h
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/action_code_settings.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_user.dart
- packages/firebase_auth/firebase_auth_platform_interface/lib/src/pigeon/messages.pigeon.dart
- packages/firebase_auth/firebase_auth_platform_interface/pigeons/messages.dart
- packages/firebase_auth/firebase_auth_platform_interface/test/action_code_settings_test.dart
- packages/firebase_auth/firebase_auth_web/lib/src/interop/auth_interop.dart
- packages/firebase_auth/firebase_auth_web/lib/src/utils/web_utils.dart
> feat(auth): support for `linkDomain` in `ActionCodeSettings`

- packages/firebase_auth/firebase_auth_web/lib/firebase_auth_web.dart
- tests/integration_test/firebase_auth/firebase_auth_instance_e2e_test.dart
> fix(auth, web): fix an issue that could occur when deleting FirebaseApp

- packages/firebase_vertexai/firebase_vertexai/lib/src/firebase_vertexai.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/imagen_api.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/imagen_content.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/imagen_model.dart
> fix(vertexai): Add @experimental annotation for imagen apis

- packages/firebase_app_installations/firebase_app_installations_web/lib/src/interop/installations.dart
Fixes https://github.com/firebase/flutterfire/issues/17179 …
> fix(app_installations, web): resolve type cast error in `getId` and `getToken` for wasm

- docs/auth/federated-auth.md
Fixes https://github.com/firebase/flutterfire/issues/17175 …
> docs(auth): fix formatting

- .github/workflows/ios.yaml
- packages/firebase_vertexai/firebase_vertexai/pubspec.yaml
Add meta to the dependency list, this should fix the currently broken publisher tests.
> fix(vertexai): Add meta to the dependency list

- packages/firebase_core/firebase_core/android/gradle.properties
- tests/android/app/build.gradle
- tests/android/settings.gradle
> feat: bump Firebase android SDK to 33.11.0

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump Firebase iOS SDK to 11.10.0

- packages/firebase_core/firebase_core/windows/CMakeLists.txt
> feat(core,windows): update C++ SDK to 12.7.0

- packages/firebase_vertexai/firebase_vertexai/lib/src/imagen_content.dart
Fixes https://github.com/firebase/flutterfire/issues/17199
> fix(vertexai): handle null predictions

- AUTHORS
- packages/firebase_vertexai/firebase_vertexai/lib/firebase_vertexai.dart
- packages/firebase_vertexai/firebase_vertexai/test/chat_test.dart
- packages/firebase_vertexai/firebase_vertexai/test/model_test.dart
The HarmBlockThreshold added in version 1.5.0 of firebase_vertexai is missing from the exported APIs. This PR adds it to the list.
This PR fixes the following scenario in which, I want to use HarmBlockMethod.probability like this:
`SafetySetting(HarmCategory.hateSpeech, HarmBlockThreshold.high, HarmBlockMethod.probability),` 
and being unable to only with the following import:
`import 'package:firebase_vertexai/firebase_vertexai.dart';` and I would need to also add 
`import 'package:firebase_vertexai/src/api.dart';` which would be an anti-pattern.
TLDR: HarmCategory and HarmBlockThreshold were already present, HarmBlockMethod was missing and this PR adds it to the exports list.
Fixes https://github.com/firebase/flutterfire/issues/17253 …
> fix(firebase_vertexai): add missing HarmBlockThreshold to exported APIs

- packages/firebase_vertexai/firebase_vertexai/lib/src/base_model.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/generative_model.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/imagen_model.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/live_model.dart
- packages/firebase_vertexai/firebase_vertexai/test/base_model_test.dart
> feat(vertexai): Add appId in headers

- packages/firebase_data_connect/firebase_data_connect/lib/src/common/common_library.dart
- packages/firebase_data_connect/firebase_data_connect/test/src/common/common_library_test.dart
Started tracking platform detection for FDC.
> feat(fdc): Included platform detection changes

- packages/firebase_vertexai/firebase_vertexai/example/lib/main.dart
- packages/firebase_vertexai/firebase_vertexai/example/lib/pages/chat_page.dart
- packages/firebase_vertexai/firebase_vertexai/lib/firebase_vertexai.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/api.dart
- packages/firebase_vertexai/firebase_vertexai/lib/src/live_api.dart
- packages/firebase_vertexai/firebase_vertexai/test/live_test.dart
> feat(vertexai): Add responseModality

- packages/firebase_vertexai/firebase_vertexai/lib/src/api.dart
- packages/firebase_vertexai/firebase_vertexai/test/api_test.dart
> fix(vertexai): handle omit tokenCount nicely

- packages/firebase_ai/firebase_ai/example/lib/main.dart
- packages/firebase_ai/firebase_ai/lib/src/firebase_ai.dart
> chore(firebaseai): disable Live Model when the backend is not vertex ai

- packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
> feat: bump Firebase JS SDK to 11.7.0

- packages/cloud_firestore/cloud_firestore/android/build.gradle
- packages/cloud_firestore/cloud_firestore/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/cloud_firestore/cloud_firestore/example/android/settings.gradle
- packages/cloud_functions/cloud_functions/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/firebase_app_check/firebase_app_check/android/build.gradle
- packages/firebase_app_check/firebase_app_check/android/gradle/wrapper/gradle-wrapper.properties
- packages/firebase_app_check/firebase_app_check/example/android/settings.gradle
- packages/firebase_auth/firebase_auth/example/android/settings.gradle
- packages/firebase_data_connect/firebase_data_connect/example/android/settings.gradle
- tests/android/gradle/wrapper/gradle-wrapper.properties
- tests/android/settings.gradle
> chore: bump AGP versions

- packages/firebase_data_connect/firebase_data_connect/pubspec.yaml
Closes https://github.com/firebase/flutterfire/issues/17374 …
> fix(data_connect): upgrade intl package version

- packages/firebase_ai/firebase_ai/test/imagen_test.dart
Added some tests to Firebase AI 
[Flutter Style …
> test(ai): added tests to Firebase AI toJson method

- packages/firebase_core/firebase_core/ios/firebase_core/Sources/firebase_core/FLTFirebaseCorePlugin.m
fixes https://github.com/firebase/flutterfire/issues/17495 …
> fix(core): resolve iOS crash when enabling automatic data collection via `setAutomaticDataCollectionEnabled`

- packages/firebase_ai/firebase_ai/example/lib/pages/token_count_page.dart
- packages/firebase_ai/firebase_ai/lib/src/api.dart
- packages/firebase_ai/firebase_ai/test/api_test.dart
- packages/firebase_vertexai/firebase_vertexai/example/lib/pages/token_count_page.dart
- packages/firebase_vertexai/firebase_vertexai/test/api_test.dart
> feat(firebaseai): deprecate totalBillableCharacters

- packages/firebase_analytics/firebase_analytics/ios/firebase_analytics/Sources/firebase_analytics/FirebaseAnalyticsMessages.g.swift
- packages/firebase_app_installations/firebase_app_installations/ios/firebase_app_installations/Sources/firebase_app_installations/IdChangedStreamHandler.swift
- packages/firebase_auth/firebase_auth/example/macos/Runner/AppDelegate.swift
- packages/firebase_auth/firebase_auth/ios/firebase_auth/Sources/firebase_auth/FLTFirebaseAuthPlugin.m
Fixes https://github.com/firebase/flutterfire/issues/17516
> feat(auth,macos): add support for `publish` and `addApplicationDelegate` on macOS FlutterPluginRegistrar

- packages/firebase_remote_config/firebase_remote_config/ios/firebase_remote_config/Package.swift
- packages/firebase_remote_config/firebase_remote_config/macos/firebase_remote_config/Package.swift
This PR removes unnecessary `cSettings` from the `Package.swift` file for the `firebase_remote_config` package.
https://developer.apple.com/documentation/packagedescription/csetting
https://docs.flutter.dev/packages-and-plugins/swift-package-manager/for-plugin-authors
ref https://github.com/firebase/flutterfire/pull/17489 …
> chore(remote_config): Remove cSettings from Package.swift

- melos.yaml
The `check-license-header` script was failing with a `permission denied` error on `.gradle` files. This is because the `addlicense` tool was trying to process these files, which are build scripts and should not have license headers.
This commit fixes the issue by adding an ignore pattern for `.gradle` files to the `addlicense` command in both the `check-license-header` and `add-license-header` scripts in `melos.yaml`.
The root cause of the issue is addlicense tool has the latest release on Aug 13 that supports .gradle file
https://github.com/google/addlicense/releases
*Replace this paragraph …
> fix(ci): ignore .gradle files in license check

- packages/firebase_ai/firebase_ai/test/error_test.dart
- packages/firebase_vertexai/firebase_vertexai/test/error_test.dart
> chore(firebaseai): fix error message test failure

- packages/firebase_app_check/firebase_app_check/ios/firebase_app_check/Sources/firebase_app_check/FLTFirebaseAppCheckPlugin.m
fixes https://github.com/firebase/flutterfire/issues/17624 …
> fix(app_check, iOS): correctly parse `forceRefresh` argument using `boolValue`

- packages/firebase_ai/firebase_ai/lib/src/firebase_ai.dart
> fix(firebaseai): making sure vertex instance will differentiate with location

- packages/cloud_firestore/cloud_firestore/example/windows/runner/main.cpp
- packages/firebase_auth/firebase_auth/example/windows/runner/main.cpp
- packages/firebase_core/firebase_core/example/windows/runner/main.cpp
- packages/firebase_core/firebase_core/windows/firebase_core_plugin.cpp
- packages/firebase_core/firebase_core/windows/firebase_core_plugin.h
- packages/firebase_storage/firebase_storage/example/windows/runner/main.cpp
> chore: fix formatting issue for .cpp/.h files

- packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb
> feat: bump Firebase iOS SDK to 12.2.0

- packages/firebase_core/firebase_core_web/lib/src/firebase_sdk_version.dart
> feat: bump Firebase JS SDK to 12.2.1

- .github/ISSUE_TEMPLATE/bug_report.yml
> chore: add reminder to remove sensitive credentials from bug report

- packages/firebase_ai/firebase_ai/lib/src/live_api.dart
- packages/firebase_ai/firebase_ai/test/live_test.dart
Fixes https://github.com/firebase/flutterfire/issues/17702 …
> fix(firebaseai): fix the json parse for toolCallCancellation

- .gemini/config.yaml
https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github#config.yaml-schema …
> chore(ci): add gemini config for the repo

- packages/firebase_ai/firebase_ai/pubspec.yaml
Update topics to match current branding.
> fix(firebaseai): update topics in pubspec.yaml for firebase_ai
